### ISSUE TITLE
🐛 BUG: Deleting Account doesn't work

### ISSUE THREAD

**Issue by akshaybharwani** [dailydotdev/daily#1031]
### What went wrong? 🤔

Deleting account via the 'Delete Account' button in Security settings redirects back to home page and doesn't actually delete account.

### Expected Behavior

It should Delete my account and log me out.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Firefox 120

### Browsers

Firefox

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @akshaybharwani,

We'll look into it. Thanks for reporting.
In the meantime, you can email support at daily.dev and we will delete your account

**Comment by omBratteng** [comment]
This should now be resolved.

cc: @rebelchris @idoshamun
