### ISSUE TITLE
🧩 FEATURE REQUEST:  applying filters while searching for post

### ISSUE THREAD

**Issue by pacifiquem** [dailydotdev/daily#1033]
### Concise Description

Supporting filters while searching a post

### Description

While a user is searching a post with ``post finder`` allow them to apply filters like:
- uploaded time (time range)
- from a user
- engagement ...

### Solution Proposed

Add filter support while searching a post.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @pacifiquem,

This is a dup of https://github.com/dailydotdev/daily/discussions/294.
Let's focus the discussion there please 🙏

**Comment by pacifiquem** [comment]
Sure @idoshamun
