### ISSUE TITLE
🧩 FEATURE REQUEST:  Add RSS so users can access their content on their RSS reader of choice

### ISSUE THREAD

**Issue by NehGuk** [dailydotdev/daily#1037]
### Concise Description

Allowing users to access their feed in their RSS client of choice

### Description

Letting users access their Daily.dev feed in external RSS feed clients.

### Solution Proposed

Enabling users to create and copy an RSS feed that they can access outside Daily.dev.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @NehGuk,

Please see my response here: 
https://github.com/dailydotdev/daily/issues/996
