### ISSUE TITLE
🧩 FEATURE REQUEST:  Redirect users to full profile after editing their account details

### ISSUE THREAD

**Issue by regisrex** [dailydotdev/daily#1039]
### Concise Description

Redirect users to full profile after editing their account details

### Description

Keeping users on the edit profile page after they have saved changes is likely to result into a bad user experience. I'd like dailydev to push users to their profiles after editing them.

### Solution Proposed

![image](https://github.com/dailydotdev/daily/assets/94565752/dec63b91-5bd9-4d2a-b469-84a769a66925)
after updating my profile and saving changes, it would be better to redirect them to this page for avoiding multiple saves and also to enable users to preview what they have changed on their profile
![image](https://github.com/dailydotdev/daily/assets/94565752/0479ee5e-6a0a-405a-8534-e9d3e6eae8c1)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @regisrex,

Thanks for suggesting this idea. With that said, we disagree. Navigating the user to a different page is an unexpected experience and assumes the user wants to see their profile. Many users edit multiple times or navigate to a different page followed by their edit.
