### ISSUE TITLE
🐛 BUG: 404 all links in FAQ

### ISSUE THREAD

**Issue by YugandharrPatil** [dailydotdev/daily#1046]
### What went wrong? 🤔

I don't know if it's just me (shouldn't be) but all links in the FAQs.md lead to 404 pages.

### Expected Behavior

Redirect to the respective pages.

### Steps to Reproduce Issue

```bash
Fix the web app.
```

### Solution Proposed

Check the dev.to articles to make sure they exist and if they do, relay the correct URLs.
![Screenshot from 2023-12-18 13-42-50](https://github.com/dailydotdev/daily/assets/75467087/8a03c8dd-4019-48e7-9a59-0655d61ed5f3)

### Environment

Ubuntu 22.04 LTS

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @YugandharrPatil,

Good find! The FAQ is outdated, please refer to: https://docs.daily.dev/
