### ISSUE TITLE
🧩 FEATURE REQUEST:  bookmarks in google were hidden

### ISSUE THREAD

**Issue by tienle2003** [dailydotdev/daily#1048]
### Description

before this time, when I used Google Chrome bookmarks also showed on it, bookmarks were very convenient to help me easily choose and switch between different websites but today bookmarks are hidden when I use your service so very inconvenient for me. So can you recover it?

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Closed as dup of https://github.com/dailydotdev/daily/discussions/1047
