### ISSUE TITLE
🐛 BUG: Search History Pop-up Exceeds Screen Boundaries

### ISSUE THREAD

**Issue by sirajlekhak** [dailydotdev/daily#1064]
### Issue Description
![image](https://github.com/dailydotdev/daily/assets/107243265/90a6989e-9008-4da7-b69d-6d25fc013e45)

### Reproduction Steps
1. Navigate to daily.dev.
2. Click on the search bar.
3. Select "See Search History."

### Problem Details
The Search History pop-up extends beyond the screen boundaries, making it inaccessible and causing a user interface issue. This affects the overall user experience when accessing search history.

### Expected Behavior
The Search History pop-up should be contained within the visible screen area, ensuring that users can interact with it seamlessly without any part going out of view.

**Comment by idoshamun** [comment]
Hi @sirajlekhak,

Thanks for reporting this issue.
We'll look into it

**Comment by rebelchris** [comment]
We recently migrated this component into our [new search merge](https://app.daily.dev/posts/a-brand-new-search--b8om37unt) component which doesn't show them like this.
It should make this issue incompatible now.
