### ISSUE TITLE
🐛 BUG: I get the same Posts over and over again in "Popular" and "Most upvoted"

### ISSUE THREAD

**Issue by cytostatic** [dailydotdev/daily#1068]
### What went wrong? 🤔

On the "Popular" and "Most Upvoted" pages of the website, blog posts are repeated when scrolling.

![Bildschirmfoto 2024-02-01 um 09 43 55](https://github.com/dailydotdev/daily/assets/10391243/bbef0fb0-8d61-4b87-83b9-5943a28a451a)

### Expected Behavior

New blog posts should be loaded and displayed as the user scrolls down, ensuring a diverse and engaging browsing experience.

### Steps to Reproduce Issue

```bash
1. Navigate to the "Popular" or "Most Upvoted" section of the web app.
2. Scroll down to view additional blog posts.
```

### Environment

MacOS latest, iOS latest

### Browsers

Chrome, Safari

### OS

Mac, iOS

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @cytostatic,

This should have been fixed already. Can you confirm please?
