### ISSUE TITLE
Infinite loading on HomePage🐛 BUG: 

### ISSUE THREAD

**Issue by Tyronwilliam** [dailydotdev/daily#1070]
### What went wrong? 🤔

When you go on the homepage, you have infintite loading on button so you can't register or login 
The issue is on the web app and the extension

### Expected Behavior

Be able to register or log in 

### Steps to Reproduce Issue

```bash
1. Go to the homepage
2. See the error
```

### Screenshots

```bash
![DESCRIPTION]()
```

### Environment

Windows 11 

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Tyronwilliam,

Thanks for reporting it. Are you still experiencing this issue?
If so, where are you located?

**Comment by Tyronwilliam** [comment]
Hi, yep still facing the issue 

Im in Paris - France

**Comment by idoshamun** [comment]
@Tyronwilliam can you please clear your cookies and try again?

**Comment by idoshamun** [comment]
@gunAT9gunner please send an email to support at daily.dev so we can assist further. Make sure to attach a print screen of your network panel in the devtools. Sorry for the trouble 🙏

**Comment by Deeptanshu-sankhwar** [comment]
<img width="1240" alt="Screenshot 2024-03-22 at 10 29 06 AM" src="https://github.com/dailydotdev/daily/assets/31755863/2a37bc08-8fa9-4394-9d71-fc16177e8614">
It's because the browser API isn't able to verify its origin, which is required for registration

**Comment by sshanzel** [comment]
Hi @Deeptanshu-sankhwar, I see that you are trying to run the app locally. For that, we use [GitPod](https://gitpod.io/#https://github.com/dailydotdev/apps/) due to certain limitations.

**Comment by rebelchris** [comment]
We did several improvements to this process and this should no longer happen.
Feel free to open a new ticket if anything pops up.
