### ISSUE TITLE
🐛 BUG: Chrome automatically pops up a new blank tab, when turn off permision web extension

### ISSUE THREAD

**Issue by huyprowow** [dailydotdev/daily#1074]
### What went wrong? 🤔

after i installed chrome extension then i don't wan't open it in new tab. I go to the extension manager chrome and turn off permision switch. After a timeout period, Chrome automatically pops up a new blank tab even though I don't do anything it makes me extremely uncomfortable 
<img width="315" alt="Screenshot 2024-02-11 145509" src="https://github.com/dailydotdev/daily/assets/66174181/c9399e53-a8c9-4015-8ee5-4d11d0a5a75c">

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

3.29.4

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by huyprowow** [comment]
<img width="939" alt="Screenshot 2024-02-11 145919" src="https://github.com/dailydotdev/daily/assets/66174181/a12cd37a-e6ba-4053-b043-906cbf86cbf8">

**Comment by idoshamun** [comment]
Hi @huyprowow,

If you don't like the new tab functionality, I suggest using the webapp https://app.daily.dev

**Comment by huyprowow** [comment]
but this extension is the cause of my chrome error instead of fixing the error, why do you suggest using the web version???

**Comment by idoshamun** [comment]
we will investigate in the mean time I suggest an alternative 🙏

**Comment by huyprowow** [comment]
thank you 🥰
