### ISSUE TITLE
🐛 BUG: too many scroll to top buttons

### ISSUE THREAD

**Issue by BlankParticle** [dailydotdev/daily#1079]
### What went wrong? 🤔

For some reason daliy.dev homepage in the extension has 3 scroll to top buttons in the HTML, they are hidden with `opactiy: 0`, but I can still interact with them.

You can see their flex box outline in the screenshot.
![image](https://github.com/dailydotdev/daily/assets/130567419/5de01fae-fa8d-4fae-8490-67b53afb4aeb)

Also I removed opactiy and added `translate` to show and identify them.
![image](https://github.com/dailydotdev/daily/assets/130567419/dd2d827a-70f5-45dc-ab17-8b5733217f71)

Only the bottom one is used as far as I can see, It doesn't bug me that much but It's wired to hover over invisble elements.
[Screencast from 2024-02-19 18-24-09.webm](https://github.com/dailydotdev/daily/assets/130567419/530d97e6-4c86-4fb8-aa5a-b35474b61264)

### Expected Behavior

There should br one scroll to top button, also if you require them for some reason I shouldn't be able to interact with them

### Steps to Reproduce Issue

```bash
1. Go to app.daily.dev or extension homepage
2. Hover around the area under account info
3. Open devtools and select the invisible element to verify.
```

### Solution Proposed

Remove the extra buttons or use `display:none` instead of `opactiy:0`

### Screenshots

```bash
Added in the bug report
```

### Environment

Google Chrome 121.0.6167.184, Arch Linux, Gnome 45, Wayland

### Browsers

Chrome

### OS

Linux

### Version of daily.dev

Extension version 3.29.6

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
@BlankParticle thanks for the report! We will look into it

**Comment by BlankParticle** [comment]
Sure, Let me know If I can help.

**Comment by sshanzel** [comment]
Closing this one since it is now fixed from a recent PR. Thank you for reporting! 🙌
