### ISSUE TITLE
🐛 BUG: Firefox addon freeze the browser

### ISSUE THREAD

**Issue by flor-master** [dailydotdev/daily#1083]
### What went wrong? 🤔

Hi, I'm using the DailyDev addon for Firefox, and after the last update, sometimes, when I open a new tab with the DailyDev page - the browser freezes and stops reacting on any actions from my side :( 

### Steps to Reproduce Issue

```bash
- Install Firefox 123.0 (64-bit) Mac OS 14.2.1 (23C71) 
- Install DailyDev FF plugin v3.30.1
- Open new tab, sometimes it freeze browser
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Mac OS 14.2.1 (23C71)  Firefox 123.0 (64-bit) 

### Browsers

Firefox

### OS

Mac

### Version of daily.dev

3.30.1

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @flor-master,

Anything specific we can do to reproduce?
This sounds like high impact so anything you can share will be helpful

**Comment by flor-master** [comment]
Unfortunately, nothing specific :( 
It started after the latest update (end of the last week). Also, I don't have a step-by-step guide to reproduce it - just regular browser usage: Open a new tab, read/scroll an article from DailyDev, enter the URL, and go to the site. 

Sometimes it works fine for a few hours, sometimes Firefox freezes after 2-3 mins. But no freezes after disabling the DailyDev Add-on for FF. 
That's why I assume that it's related to the DeilyDev add-on.

**Comment by urienix** [comment]
If it helps, in Linux we have the same problem. I'm using Fedora 39 with Firefox 123.0 (64-bit). The browser works fine for a couple of minutes, but then it slows down. Many times it freezes, and after disabling the add-on, everything works normally again. When reactivating the add-on, the problem resurfaces. We're unsure of the exact cause, but we suspect that perhaps there's something in the latest features either of the browser or the extension causing the issue.

**Comment by Lukasss93** [comment]
same problem on Windows 11

**Comment by idoshamun** [comment]
We're investigating the issue and we'll do our best to resolve asap

**Comment by omBratteng** [comment]
Does it freeze when browsing the webapp version at app.daily.dev with/without the extension?

**Comment by omBratteng** [comment]
> If it helps, in Linux we have the same problem. I'm using Fedora 39 with Firefox 123.0 (64-bit).

Thanks, I can run a VM with fedora 39. How many cores and how much memory do you have on it?

**Comment by Lukasss93** [comment]
How to "reproduce":

https://github.com/dailydotdev/daily/assets/4071613/5863de6f-b20b-4e37-a8e1-05ad8c2303e3

**Comment by omBratteng** [comment]
I've been able to reproduce it. If you disable the companion app, does it still happen?

**Comment by Lukasss93** [comment]
> I've been able to reproduce it. If you disable the companion app, does it still happen?

Nope.

**Comment by omBratteng** [comment]
I fix has been merged, just waiting to publish a new release.

**Comment by rebelchris** [comment]
Hi @Lukasss93 @urienix @flor-master thanks again for logging this issue.
These reports help a lot 🙏

We managed to solve the issue and if you can update to V3.30.8 this should be fixed.
Please feel free to open any other issues if you may find so.
