### ISSUE TITLE
🐛 BUG: It is not possible to restore lost password

### ISSUE THREAD

**Issue by IAmWolkan** [dailydotdev/daily#1085]
### What went wrong? 🤔

When trying to verify the validation code during the Forgot password process nothing happens.
When I am checking the networks tab in dev tools I can se that the results is a 404 response on POST request on URL https://sso.daily.dev/self-service/verification?flow=, OPTION method works but not POST.

### Expected Behavior

Verification pass and it gives me the possibility to set new password or shows an error message about why the verification didn't pass. 

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/onboarding'
2. Click on 'Forgot password?'
3. Enter your email
4. Click on 'Send verification code'
5. Retrieve the verification code from your email
6. Enter your verification code in the code field
7. Click on 'Verify'
```

### Screenshots

```bash
![Response of request](https://github.com/dailydotdev/daily/assets/1618339/81864e9d-d8d8-4a2c-87c4-779cb9c8459e)
```

### Environment

Windows 11, Chrome 121.0.6167.189 and Firefox 123.0

### Browsers

Chrome, Firefox

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Thanks for logging this issue @IAmWolkan we'll look into this 🙏

**Comment by rebelchris** [comment]
Hi @IAmWolkan 

We discovered a small bug in our code, but managed to squash it.
You should be able to reset your password now.
