### ISSUE TITLE
🐛 BUG: Source suggestion notification not working

### ISSUE THREAD

**Issue by dusthijsvdh** [dailydotdev/daily#1097]
### What went wrong? 🤔

I recently submitted a few new sources. When they got approved, they notifaction only said that Stripe was added, which I haven't even submitted.

Screenshots:
(GitHub wasn't allowing me to drop my images in the screenshot section)

![msedge_7bCNFAVWnt](https://github.com/dailydotdev/daily/assets/25427808/c6b47e3d-fe7d-444c-be17-4f58f1cb2c02)
![image](https://github.com/dailydotdev/daily/assets/25427808/8be43019-71d2-4c66-917e-0a8a4adfac21)

### Expected Behavior

The correct source being referenced

### Steps to Reproduce Issue

```bash
1. Submit a few sources
2. Get them approved
```

### Environment

Windows 11 - Microsoft Edge for Business 122.0.2365.80 (Official build) (64-bit)

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

3.30.6

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @dusthijsvdh,

We revamped our source moderation panel and probably broke something in the process.
We'll fix it 😬

**Comment by idoshamun** [comment]
It should be fixed now for future submissions 😃
