### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by StellarSync** [dailydotdev/daily#1099]
### What went wrong? 🤔

Idk if this is a bug or not but I have to join the same squad everyday. There's a really cool squad and I really like it there. But everytime I reload or restart the browser, I am out of the squad. Please help and let me also help. I wish to be able to contribute to dailydev as well. Thank you for looking into my issue

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Arch Linux,  Brave browser

### Browsers

Brave

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @StellarSync,

Thanks for reporting. We're investigating the issue and hopefully fix it soon

**Comment by omBratteng** [comment]
I think we've fixed this in https://github.com/dailydotdev/daily-api/pull/1774

**Comment by sshanzel** [comment]
Yeah, this should have been fixed as well. Thank you for reporting, feel free to re-open the issue if it persists.
