### ISSUE TITLE
🐛 BUG: link marked as existing if submitted to private squad first 

### ISSUE THREAD

**Issue by palmiak** [dailydotdev/daily#1109]
### What went wrong? 🤔

If I submit a link to private squad and later I try to submit it to community picks I get info that this link already exists.

### Expected Behavior

I should be added normally - not treated as a duplicate.

### Steps to Reproduce Issue

```bash
1. Add a link that wasn't added before to a private squad
2. Click "submit new link" and try adding the same link - you should get info that it already exists.
```

### Solution Proposed

Links that were added in squads, shouldn't be saw as duplicates when submitting them into community picks.

### Screenshots

```bash
NA
```

### Environment

NA

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

NA

### Additional Context

```bash
NA
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
We're aware of this issue but due to technical challenges it's not prioritized for fix but may be fixed in the future. We're doing some architectural changes to help us address such edge cases better. I hope you understand 🙏

**Comment by palmiak** [comment]
So I must remember to first submit globally and later locally.

I can imagine that every link should have a flag is_global.

niedz., 7 kwi 2024, 09:25 użytkownik Ido Shamun ***@***.***>
napisał:

**Comment by idoshamun** [comment]
> So I must remember to first submit globally and later locally.

That should fix it indeed!

> I can imagine that every link should have a flag is_global.

A bit more complicated than this. Links that are added via squad are assigned to an `unknown` source and are not visible on their own, only via their squad post variation. Community picks are assigned with `community` source and it currently doesn't support adding an existing link. To support this use case we will need to change the source of the post which is currently immutable and changing it has a lot of side effects. Plenty of technical decisions that led us to this situation 🥵

**Comment by rebelchris** [comment]
Closing as non trivial anymore, we expose squads differently now and this is the way forward
