### ISSUE TITLE
🐛 BUG: Not Showing alert dialog to download again

### ISSUE THREAD

**Issue by DixitRam** [dailydotdev/daily#1110]
### What went wrong? 🤔

I am using daily.dev mobile app (Android), I downloaded my **DevCard** once , after some changes when i try to download it again it doesn't show pop up / alert of download agin ,so i can't download it.

What i have to do is :- 
1) every time i have to open default browser and download from that cuz it shows alert ,so i can download.

2) i have to delete / rename old image every time then download it from app

### Expected Behavior

It should show alert dialog or should be downloaded with different name for example :- `dixitram_7-4-24.png`

### Steps to Reproduce Issue

```bash
1. Go to 'Your Profile'
2. Click on 'Settings'
3. Click on 'Devcard'
3. Download 'Devcard' 
4. Try to download again
4. See the error 'not showing alert dialog '
```

### Solution Proposed

May be on every download file name should be comes with current date `username_dd-m-yy.png`

### Environment

Android 13 , Default Browser Brave

### Browsers

Brave

### OS

Android

### Version of daily.dev

Android 3

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @DixitRam,

Can you please share a screen recording so we can better understand your issue?

**Comment by DixitRam** [comment]
SORRY ,It was a problem in my browser, after changing default browser it's working perfectly. 
SOLUTION:-  Try to update browser  or chnage default browser
