### ISSUE TITLE
🧩 FEATURE REQUEST:  

### ISSUE THREAD

**Issue by Kenan-Kamel** [dailydotdev/daily#1111]
### Concise Description

Bookmarks classification/tags to organize the bookmarks by tags / categories 

### Description

I noticed that when I bookmark a post on my phone, I face the issue that I can't organize it in a way that allows me to return to it for reference. Even as the search feature is helpful, there is no way sometimes to remember what was article you're looking for, or you won't recall that you saved it in the first place. though

### Solution Proposed

A simple way to fix this is by adding either tags or organized bookmarks such as the one attached to browsers. Also, it could be designed so that the user should save it, but when the user goes back to the bookmark segment of the app, the user could set a tag there and look into the folder of older tags ordered by sections/tags as a menu. 

Hopefully, that makes sense! 

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Kenan-Kamel,

Thanks for the suggestion, we have an active discussion around that here: https://github.com/dailydotdev/daily/discussions/520
