### ISSUE TITLE
🐛 BUG: Bookmarks not available on New Tab in Brave

### ISSUE THREAD

**Issue by gurdittcancode** [dailydotdev/daily#1114]
### What went wrong? 🤔

When I set bookmarks to "Show only on new tab" in Brave, I couldn't see the bookmarks. Initially, I thought this was a bug in Brave, but then I noticed that when I disabled the browser extension from taking over my new tab page, the bookmarks tab was behaving as expected.
![Screenshot (43)](https://github.com/dailydotdev/daily/assets/93715659/3c1eb534-14ac-4ae5-815e-0d61d25f2312)
![Screenshot 2024-04-08 165254](https://github.com/dailydotdev/daily/assets/93715659/845dc804-de7d-44c2-8df7-dac9ccb0848f)

### Steps to Reproduce Issue

```bash
1. Go to brave://settings
2. Set show bookmarks to "show only on new tab"
3. Open a new tab. Bookmarks aren't visible on any window
```

### Browsers

Brave

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @gurdittcancode,

We're aware of this issue but unfortunately there's nothing we can do about it.
It's the browser that decides to hide them and ignore the settings. We have no API to control that 🥲
