### ISSUE TITLE
🐛 BUG: Not Showing Weekly goal in your profile page

### ISSUE THREAD

**Issue by DixitRam** [dailydotdev/daily#1115]
### What went wrong? 🤔

When i open my profile in non logged in browser it shows **Weekly goal** ,But not showing in my profile in  app/logged in browser.
Screen Recording:   Here in this Recording 1st page is my logged in page , and in another page i open my profile in incognito without signing. Same thing happens in Mobile 📱 
[Recording](https://github.com/dailydotdev/daily/assets/72870029/1cb57218-5a19-4077-bc1b-ed31ae3782d8)

### Expected Behavior

Expected weekly goal should be shown in logged in profile page also. 

### Steps to Reproduce Issue

```bash
1. Go to 'Profile and Check'
2. Go to 'Incognito / non logged in browser open your profile "app.daily.dev/UserName"'
3. See the error
```

### Browsers

Brave

### OS

Linux, Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sabdailydev** [comment]
@DixitRam Thanks for raising this issue. We are running an experiment to improve the experience of weekly goals (ideally you should be seeing just the streaks and not the weekly goals (irrespective of whether you are logged in or not)). We would need to prioritize this fix in the future.

**Comment by nensidosari** [comment]
This issue is now fixed, since you are part of the streaks experiment, the weekly goal is now hidden from your logged in/ non logged in profile.

Thank you for reporting!
