### ISSUE TITLE
🐛 BUG: Reputation was impacted after I deleted my own post

### ISSUE THREAD

**Issue by raymelon** [dailydotdev/daily#1116]
### What went wrong? 🤔

I was testing the squads feature, so I tried posting a link and deleting it right after.

My 210 reputation went down to 110 after the event.

Looking at the docs, https://docs.daily.dev/docs/your-profile/reputation

It is mentioned there that you can lose 100 points if your post gets removed by a moderator. I am a moderator of my squad, and I just deleted my post, hence me losing 100 reputation points.

### Expected Behavior

No change in reputation points.

### Steps to Reproduce Issue

```bash
1. Go to 'a private squad that you own'
2. Make a 'post there'
3. Delete 'the same post'
4. See your reputation drop 100 points
```

### Solution Proposed

No change in reputation points.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

version as of April 9, 2024

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@raymelon Yes, if it does happen again please let me know no worries, will just reset.
I'll keep you posted here once we solve it 🙏

**Comment by raymelon** [comment]
Okay! I'll wait for the fix!  Thank you @rebelchris! Cheers!

**Comment by rebelchris** [comment]
@raymelon Just pushed a fix to our system that solves this.
Thanks again for reporting the issue to us 🙏
