### ISSUE TITLE
🐛 BUG: Tab Comment highlight line is in incorrect position.

### ISSUE THREAD

**Issue by INTS-DucAnh** [dailydotdev/daily#1121]
### What went wrong? 🤔

The first time i click on Comment Button of a post in hub, it show me a box like this: 
![image](https://github.com/dailydotdev/daily/assets/161408884/4afc8fae-1615-4e60-ba24-b6cf0f7113ab)
You can see, the white line under the Write button. but when changed to Preview tab, it still on. 
![image](https://github.com/dailydotdev/daily/assets/161408884/2efcaef7-5ecc-47e3-9a69-809eefc7a733)
After that, i click to Write button again, it started to change to under Preview button. 
![image](https://github.com/dailydotdev/daily/assets/161408884/21a12083-da49-4ab2-b1b9-e2f0efe0ace8)
Currently, i use Brave and Window 10 with Daily.dev version 3.31.5 Updated 11 April 2024

### Steps to Reproduce Issue

```bash
1. Go to 'Home'
2. Click on 'Any post'
3. Click on 'Button Comment'
4. Click on 'Preview Comment'
5. Click on 'Write Comment'
6. See the error
```

### Solution Proposed

Might be flag initValue of underline is wrong at the firstime. 

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Window, Brave Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)

### Browsers

Brave

### OS

Windows

### Version of daily.dev

3.31.5

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @INTS-DucAnh thanks a lot for reporting, we'll look into this issue and report back.

**Comment by nensidosari** [comment]
This should now be fixed, thanks for reporting!
