### ISSUE TITLE
🐛 BUG: broken preview images

### ISSUE THREAD

**Issue by usulpro** [dailydotdev/daily#1122]
### What went wrong? 🤔

1 preview images in Webp format are broken 
2 preview images are taken from a blog hero image, not from `og:image` metatag

Example:
[this article](https://focusreactive.com/configure-cdn-caching-for-self-hosted-next-js-websites/?ref=dailydev) has a Hero image in [webp format](https://cdn.sanity.io/images/vftxng62/production/1f369439f55d01cc07f65901b8d1b3f898fa2b3b-1915x845.jpg?w=1920&auto=format) and social image in [jpeg format](https://cdn.sanity.io/images/vftxng62/production/1f369439f55d01cc07f65901b8d1b3f898fa2b3b-1915x845.jpg?w=1200&h=630) 

while in general WebP has a good browsers support and the article itself shows well, the post on Daily dev shows the broken image: https://app.daily.dev/posts/configure-cdn-caching-for-self-hosted-next-js-websites-vu2neyv3i

### Expected Behavior

Expected that preview images are correctly shown on post previews

### Steps to Reproduce Issue

```bash
1 open https://app.daily.dev/posts/configure-cdn-caching-for-self-hosted-next-js-websites-vu2neyv3i
2 note that the image isn't shown
3 compare with the https://focusreactive.com/configure-cdn-caching-for-self-hosted-next-js-websites/?ref=dailydev article
```

### Solution Proposed

there could be different ways to solve this:

Option 1: Fix the support for WebP - looks like this is the reason of why it's not shown

Option 2: Switch to social images to use as a preview. It's based on the idea that if the article already have `og:image` or `twitter:cart` metatags with social preview images - they are the best represented the article preview. So it might be the best option to use social images for preview when they set in the source

Option 3: (quick fix) - enable to manually specify a preview image for the picked articles

### Screenshots

```bash
![image](https://github.com/dailydotdev/daily/assets/14885189/e6ad7d32-804d-4a8e-aa99-2d91e0adb14c)
```

### Environment

Linux Mint

### Browsers

Chrome

### OS

Linux

### Version of daily.dev

browser

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @usulpro,

I see that the cover image in the linked post is properly set but I'll check further

**Comment by idoshamun** [comment]
I checked internally and we fixed this bug already following this post. Thanks for reporting!
