### ISSUE TITLE
🐛 BUG: daily.dev ai search not working correctly

### ISSUE THREAD

**Issue by 687edf53** [dailydotdev/daily#1123]
### What went wrong? 🤔

The daily.dev ai search is give me in a lot of question "Sorry, I cannot answer this question." although I ask him normal questions like 'apple company' or 'hotkey program' or 'csharp'
Thanks for this good extension

### Expected Behavior

I expected it to working normal like chatgpt but still it awesome extension

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

fix bug

### Environment

Windows 10

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @687edf53,

Our AI search (unlike our traditional search) expects a well formed question. It doesn't know how to handle vague terms like the ones you search on google

**Comment by 687edf53** [comment]
> Hi @687edf53,
> 
> Our AI search (unlike our traditional search) expects a well formed question. It doesn't know how to handle vague terms like the ones you search on google

g

**Comment by idoshamun** [comment]
yes it's very broad term. what are you trying to accomplish with your search? Please let me know and I can help with that maybe
