### ISSUE TITLE
🐛 BUG:  "read post" button/option is missing

### ISSUE THREAD

**Issue by faizan-kamili** [dailydotdev/daily#1126]
### What went wrong? 🤔

I checked todays post but some of them do not have "read post" button/option

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @faizan-kamili,

Not all posts lead to an article. These posts don't have a read post button.
