### ISSUE TITLE
🐛 BUG: Profile > Posts > New Posts returns to a generic 401 page.

### ISSUE THREAD

**Issue by mbvissers** [dailydotdev/daily#1127]
### What went wrong? 🤔

When going to the Posts tab in the Profile page and clicking on new Post, a generic access denied page shows up with the `Oops! This link leads to a private discussion` text. I have 60 rep.

### Expected Behavior

I expect to see either a page describing I don't have enough reputation to make a new post, or to have the 'new post' button disabled with a text explaining why it's disabled.

### Steps to Reproduce Issue

```bash
1. Go to 'Profile'
2. Click on the 'Posts' tab
3. Click on 'new post'
4. See the message
```

### Solution Proposed

Disable the 'new post' button and add text explaining why I cannot make a new post at this time. For example because of a lack of rep.

### Environment

Firefox 124.0.1, Ubuntu 23.10

### Browsers

Firefox

### OS

Linux

### Version of daily.dev

3.31.5

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @mbvissers,

Let me look into that

**Comment by idoshamun** [comment]
Hi @shachargiladi,

Sorry for the late reply. We gonna revamp this experience soon, so it's not open for contribution at the moment.
I hope we will have some issues to grab soon

**Comment by sshanzel** [comment]
@shachargiladi thank you for your interest in contributing! However, as mentioned, this is going to be fixed along the way in one of our upcoming initiatives. With that, feel free to check our unassigned issues with the label of [help-wanted](https://github.com/dailydotdev/daily/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

We also have a [recent issue](https://github.com/dailydotdev/daily/issues/1133) with regards to updating the user's own profile details. If you are up for the challenge, feel free to check it out 🙌

**Comment by idoshamun** [comment]
This should be fixed now
