### ISSUE TITLE
🐛 BUG: Community picks wrong title

### ISSUE THREAD

**Issue by arthurrio** [dailydotdev/daily#1129]
### What went wrong? 🤔

[I did this community pick](https://dly.to/DgZBnZbuTEj)
its a nice article from LinkedIn page but it came with a bad title.

The title that report: [Alex Xu on LinkedIn: #systemdesign #coding #interviewtips](https://api.daily.dev/r/L5yHAxyer)

### Expected Behavior

**Expected title:** Things Every Developer Should Know: Concurrency is 𝐍𝐎𝐓 parallelism.
**Or:**  Concurrency is 𝐍𝐎𝐓 parallelism.

### Steps to Reproduce Issue

```bash
1. Go to 'Comunity Pick'
2. Fill the Daily suggestions used input with some LinkedIn post 
3. Click on Submit button
4. See the error in the title
```

### Solution proposed
A button that could edit the title of a **community pick**

### Another reinforcement that could solve it too
I don't know if here's the best place to talk about [content guidelines](https://r.daily.dev/content-guidelines) 

but there is a rule to reject this kind of posts 
-  Content from sources that don't provide an RSS feed or Atom feed available for public use.

But other posts came from YouTube, a website [roadmap.sh](https://roadmap.sh/), or even a GitHub repo like [awesome repository](https://github.com/sindresorhus/awesome)

So, another point is just to know what to do in this case: 
- Report all content that doesn't follow the rules above
- How flexible is this rule? 
- Maybe change this rule could be a good idea? following the base idea of dailydev  

### Screenshots

![Comunity pick from LinkedIn article](https://github.com/dailydotdev/daily/assets/72942190/c5b6100f-8262-4eab-92fa-35d6c3e9e1ee)

### Additional Context

```bash
I was confuse about what is it: a bug, a feature or just need to clarify this rules.
So I bring this topic to a bug issue that I'm open to move to the right place
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @arthurrio,

Thanks for the report. We will look into it.

As for the your comment about the content guidelines, it applies only for source suggestions, not community picks
