### ISSUE TITLE
🐛 BUG: Tag overflow

### ISSUE THREAD

**Issue by kbaran1998** [dailydotdev/daily#1132]
### What went wrong? 🤔

For some of the posts, tags overflow on the large screen sizes. [example post](https://dly.to/wBi0TrA0zDx)

### Expected Behavior

They should fit inside the post's container.

### Steps to Reproduce Issue

```bash
Add multiple long tags like `#javascript` or `#data-structures` and view the collection with the  `xl` or `2xl` tailwind screen sizes.
```

### Solution Proposed

Limit the number of possible tags to display to 3 and/or sort them by length before rendering them.

### Screenshots

```bash
![Tags Overflow](https://github.com/dailydotdev/daily/assets/33691287/b37f543e-ba1c-4840-b6fc-ccaf642da8a1)
```

### Environment

Ubuntu 22.04, Chrome Version 124.0.6367.60

### Browsers

Chrome

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @kbaran1998,

Thanks for reporting. Can you confirm your extension version please?
We had this issue in older versions but it should be fixed by now

**Comment by rebelchris** [comment]
We did indeed make some adjustments to this.
The array of tags you gave as example sghould render as `+2 tags` in the latest version.

![image](https://github.com/dailydotdev/daily/assets/554874/2f18771b-18ac-4880-a5fd-7c7664662a12)

Closing as resolved for now.
Feel free to open another ticket if you see some other edge-case and thanks for logging the issue 🙏
