### ISSUE TITLE
🐛 BUG: Profile Social Links not saving

### ISSUE THREAD

**Issue by kenn7575** [dailydotdev/daily#1133]
### What went wrong? 🤔

When trying to update and submit "Profile Social Links" on account page, the content isn't being saved correctly.

### Expected Behavior

Being able to see the previous values types in the input fields when returning to the edit profile page.

### Steps to Reproduce Issue

```bash
1. Go to '/account/profile'
2. Type value into 'Profile Social Links github'
3. Scroll down to 'summit changes'
4. Not being able to see the changes when returning to "/account/profile"
```

### Solution Proposed

I don't if the data is being updated or if it's just a UX type of error, but it would make sense to see the values in their place as a confirmation that the data was saved.

### Environment

[MacBook, iPhone]

### Browsers

Chrome, Safari

### OS

Mac, iOS

### Version of daily.dev

commit e80f215

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
We may have validation issue there, but for that we will need more information.
Feel free to send screenshot to support at daily.dev. I don't want you to share personal information here :)

**Comment by kenn7575** [comment]
> We may have validation issue there, but for that we will need more information. Feel free to send screenshot to support at daily.dev. I don't want you to share personal information here :)

I think I uncovered what the issue is. It was just the GitHub input that caused the validation to fail. It expects [userName] and I types "https://github.com/[userName]".

Maybe the site shouldn't redirect users if a validation occurs. But instead, highlight the input with an error.

**Comment by idoshamun** [comment]
You're right. We'll try to fix it

**Comment by rebelchris** [comment]
We did a massive overhaul on the social links recently which should have fixed these issues as well.
please feel free to re-open if anything else pops up.
