### ISSUE TITLE
🐛 BUG: URL for source feed in Notifications tab is invalid.

### ISSUE THREAD

**Issue by ATOMICMAN007** [dailydotdev/daily#1135]
### What went wrong? 🤔

In the daily.dev new tab, when we try to visit a source like Hacker News in Notification tab by clicking the icon/logo of the source, the link actually leads to a 404 page since the URL generated for the source is: https://app.daily.dev/sources/undefined
So far, I have been able to reproduce this with Hacker News in my notifications tab.
![image](https://github.com/dailydotdev/daily/assets/71210312/7877986a-3a00-4056-9ba2-d1feea7c27c0)

### Expected Behavior

After clicking on the source icon, we should be taken to the page of that source.

### Steps to Reproduce Issue

```bash
1. Go to notifications tab in the new tab page of daily.dev
2. Click on Icon of a source you follow, Hacker News, for example.
3. Leads to the 404 page
```

### Environment

Windows 11, Brave Version 1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit)

### Browsers

Brave

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ATOMICMAN007,

Thanks for the report! We will look into it

**Comment by capJavert** [comment]
@ATOMICMAN007 we found an issue and after related PR is merged I will also retro fix the notifications affected.

**Comment by capJavert** [comment]
Existing notifications should now also point to correct source. Tnx for reporting this!
