### ISSUE TITLE
🐛 BUG: Same articles show up multiple times

### ISSUE THREAD

**Issue by piotrekkr** [dailydotdev/daily#1136]
### What went wrong? 🤔

Some articles are showing multiple times in feed. For example `Framework won’t be just a laptop company anymore` or `I Know the Secret to the Quiet Mind. I Wish I’d Never Learned It.`. 

### Expected Behavior

Each articlle is showed once 

### Steps to Reproduce Issue

```bash
Go to daily dev page.
```

### Screenshots

![image](https://github.com/dailydotdev/daily/assets/503782/048c5390-9799-4acc-8d28-0323c731b13a)

![image](https://github.com/dailydotdev/daily/assets/503782/a4c8558c-4fc2-42d3-a8ac-428ca2be9533)

### Environment

Linux, Firefox

### Browsers

Firefox

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @piotrekkr,

It's a pagination + caching issue we have on our side. We hope to fix it soon but it's challenging 😬

**Comment by rebelchris** [comment]
It should be fixed now :)
