### ISSUE TITLE
🐛 BUG: I turned off email notifications and you keep sending the weekly report

### ISSUE THREAD

**Issue by omerhertz** [dailydotdev/daily#1137]
### What went wrong? 🤔

see above

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @omerhertz,

Sorry for this inconvenience. Can you please send us your email to support at daily.dev so we can debug your case?

**Comment by rebelchris** [comment]
Closing as no follow up is given.
