### ISSUE TITLE
🐛 BUG: I received a "Your post is now on daily.dev" but I never submitted any

### ISSUE THREAD

**Issue by SlimDeluxe** [dailydotdev/daily#1140]
### What went wrong? 🤔

Today, after creating a daily.dev account a few days ago, I received an email with the subject "Congratulations! Your post is now on daily.dev!" but I am not sure what it is referring to. I never submitted a post, only commented on some of them.
The "Start a discussion" button is also not a link - I can't click on it.

I use the web version, not the extension.

### Expected Behavior

Not receive messages that are not true

### Steps to Reproduce Issue

```bash
1. Create a new acccount
2. Wait a few days
3. Receive a message and be confused
```

### Screenshots

[![2024-04-28-11-13.png](https://i.postimg.cc/m252PVqT/2024-04-28-11-13.png)](https://postimg.cc/vc5dj7bK)

### Browsers

Brave

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @SlimDeluxe,

Even though you didn't do anything, our bots or another community member found your post useful and added it to the feed. In this case, we also notify the author of the article.

I hope this makes sense.

**Comment by SlimDeluxe** [comment]
Hi @idoshamun , but which post is it referring to? The email message, as can be seen in my screenshot, appears to contain only a placeholder.
I also do not have a blog... Maybe only the company one at datalinx.io but it's not active and also it's not the same domain as my email, so I continue to be confused :confused:

**Comment by idoshamun** [comment]
I totally missed that. We'll take a look 😬

**Comment by rebelchris** [comment]
@SlimDeluxe Thank you so much for logging this issue.

It turns out we accidentally send you the wrong email this should have been the one that you unlocked your DevCard.
Just because you missed it, be sure to check out your DevCard:

https://app.daily.dev/devcard
