### ISSUE TITLE
🧩 FEATURE REQUEST:  Add a loader or a spinner for the comments

### ISSUE THREAD

**Issue by aneesh1024** [dailydotdev/daily#1142]
### Description

I was looking at the comments and I saw this

![image](https://github.com/dailydotdev/daily/assets/99677867/81efbfa3-6595-4521-97ea-bde823396686)

The number of comments here are being shown as 5 but there are no comments, I was actually going to report a bug but luckily the comments loaded after a while, so I thought that it would be better if there was a loader or spinner displaying comments loading status.

### Solution Proposed

Add a spinner displaying the status of the comments

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Closing as dup of https://github.com/dailydotdev/daily/discussions/1141
