### ISSUE TITLE
🧩 FEATURE REQUEST:  Middle click to open posts in new tab

### ISSUE THREAD

**Issue by Shobhit0109** [dailydotdev/daily#1147]
### Concise Description

Allow middle mouse click button on each post.

### Description

I have dev extension. Some posts don't allow middle click & in other posts i need to do middle click on "read posts"

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Shobhit0109,

The posts the allow middle click, indeed allow it only in the "read post". The rest don't lead to any external link so we just open a modal with more information. Does that make sense?

**Comment by Shobhit0109** [comment]
I am asking the card which shows more info open it in new tab if I do middle click so that I can open many posts and read them instead of opening reading and repeating on each post.
Also, some posts don't even show read posts.

**Comment by rebelchris** [comment]
To give some more context:
Some posts are not linking to any external website, they are discussions in the platform thus don't have middle-click enabled.
All those that have offer the middle click on the read button (as it's the only one opening in new tab/external site)

Hoping this clarifies the answer, closing for now.
But feel free to raise again if unclear/open new tickets.
