### ISSUE TITLE
🐛 BUG: when there is 3 tags with long text, the tags overflow the article card

### ISSUE THREAD

**Issue by ysabag** [dailydotdev/daily#1149]
### What went wrong? 🤔

the tags overflow the article card
![image](https://github.com/dailydotdev/daily/assets/98085226/6d5ff744-f95e-44b2-a6e6-c4dd1535b844)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Environment

Windows 10, Edge browser

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ysabag,

Can you confirm the version that you use please?
We fixed this bug in the past, so I need to know if it's an old version or we reintroduced it somehow

**Comment by rebelchris** [comment]
Closing as fixed.
