### ISSUE TITLE
🐛 BUG: why I can't refresh my feed on mobile 

### ISSUE THREAD

**Issue by Ahmad-Maartmesrini** [dailydotdev/daily#1157]
### What went wrong? 🤔

No matter mow much I refresh it's not showing me something new, announcing Svelte kit 2 have been in the feed for a while 

### Expected Behavior

It should fetch new articles 

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Ahmad-Maartmesrini,

Can you provide more context for how long you see the same articles and what feed are you looking at?

**Comment by Ahmad-Maartmesrini** [comment]
It's been over a month since I started reading about Svelte and I still seeing Announcing Svelte kit 2, and other web dev content that have around for a while that I have seen already!

________________________________

**Comment by idoshamun** [comment]
When you can please send me a screenshot (make sure to include the url bar).
Please also check your network panel for any failed requests. If you find any let me know

**Comment by Ahmad-Maartmesrini** [comment]
I'm talking about Firefox extension, thanks!
[cid:d3a9fe76-46d1-4cef-85b4-2ee09653774e]
________________________________

**Comment by idoshamun** [comment]
Can you please attach a screenshot of the network panel please? I'd like to see failing requests

**Comment by Ahmad-Maartmesrini** [comment]
There is no failed request, or let tell that I didn't see request at all


________________________________

**Comment by idoshamun** [comment]
Without any steps to reproduce or error logs it will be hard for us to fix the issue 🙈

**Comment by rebelchris** [comment]
Closing as no response for a while.

**Comment by Ahmad-Maartmesrini** [comment]
oh did I forgot to share that everything is fine, thanks!
