### ISSUE TITLE
🐛 BUG: Companion widget covers button that closes page overlay

### ISSUE THREAD

**Issue by GeorgeMD** [dailydotdev/daily#1160]
### What went wrong? 🤔

The companion widget covers an `x` button that closes a banner asking me to sign up.

### Steps to Reproduce Issue

```bash
1. Have a 1920x1080 resolution with 100% scale
1. Go to https://medium.com/snapp-mobile/whats-next-for-flutter-6eb32e5e78ee
2. Make sure you see the bottom banner asking you to sign up
3. When trying to close the banner, the widget is in the way
```

### Solution Proposed

Either allow users to drag the widget up or down or minimize it temporarily.

### Screenshots

```bash
![The widget doesn't fully cover the button, but it still cannot be clicked](https://github.com/dailydotdev/daily/assets/20901158/9ae33a63-c6be-4140-9e19-717dd90ef92c)
```

### Environment

Windows 10, Chrome Version 124.0.6367.201 (Official Build) (64-bit)

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

3.31.11

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @GeorgeMD,

Thanks for the report. It's a dup of https://github.com/dailydotdev/daily/issues/967
