### ISSUE TITLE
🐛 BUG: Companion widget placement issue on medium

### ISSUE THREAD

**Issue by harshadsatra** [dailydotdev/daily#1163]
### What went wrong? 🤔

When Companion widget is enabled, it overlaps the close button on medium.com, enable to close it and cant read the full article.

### Steps to Reproduce Issue

```bash
1. Sign out of medium, if you are already logged in
2. Go to any medium article in the feed
3. Click Read more.
4. See the error
```

### Solution Proposed

Enable dynamic flotting of companion widget

### Screenshots

```bash
![Cant close the medium popup](https://ibb.co/1QCMLFR)
```

### Browsers

Chrome

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @harshadsatra,

It's a dup of https://github.com/dailydotdev/daily/issues/967
