### ISSUE TITLE
🧩 FEATURE REQUEST: Weekend Reading Streaks customizable 

### ISSUE THREAD

**Issue by nottalha** [dailydotdev/daily#1165]
### Concise Description

Weekend days are Friday & Saturday, so if weekend freeze can be modified

### Description

Using daily.dev is absolutely amazing, (Thanks)
My weekends are Fri & Sat, and as for someone else it might be somewhere in weekdays (other then Saturday & Sunday. So if we can select the select off days it would be really good, to maintain streaks.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sabdailydev** [comment]
@nottalha Thanks for the suggestion. We now have this in our backlog and we will prioritize it when we can (unable to commit an ETA with several parallel priorities).

**Comment by rebelchris** [comment]
Closing this issue as you can now set your weekend days:
https://docs.daily.dev/docs/your-profile/weekly-goal#restore-streak

Hope that helps @nottalha
