### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by ajbrehm** [dailydotdev/daily#1166]
### What went wrong? 🤔

I have created two squads and I am "active" in them (have posted one post in each). But my profile doesn't list me as active in any squads and I cannot add the existing squads to the list (it asks me to create a new squad when I try):

![image](https://github.com/dailydotdev/daily/assets/48602082/a213b0cc-aa5a-4684-a266-00c0cea98279)

### Expected Behavior

I would assume the squads would show up or that I could add them.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ajbrehm,

We present only public squads in this list. Currently only system admins can set squads as public. Soon we will introduce a review process for that.
