### ISSUE TITLE
Cannot add my GitHub profile link in my profile.

### ISSUE THREAD

**Issue by addyxx-h4ck1** [dailydotdev/daily#1173]
### What went wrong? 🤔

https://github.com/addyxx-h4ck1
That is my GitHub account . I've been trying to add it in the socials on my profile but am getting an error saying ' invalid characters ' even though the link is correct.

### Expected Behavior

I expected everything to work fine because my username in GitHub is valid and I didn't get any issues when I was creating my account on github

### Steps to Reproduce Issue

```bash
1. Go to 'daily.dev'
2. Click on 'profile'
3. Scroll down to 'socials then under GitHub try this link (https://github.com/addyxx-h4ck1) it's my GitHub profile link, then click submit to save changes'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @addyxx-h4ck1,

Sorry for the confusion but you should add only your handle, not the full url.
We will try to make the UX better 🙏

**Comment by addyxx-h4ck1** [comment]
> Hi @addyxx-h4ck1,
> 
> Sorry for the confusion but you should add only your handle, not the full url.
> We will try to make the UX better 🙏 

Thank you very much it worked, but am sure there are others facing the same problem do something about it. I appreciate your help
