### ISSUE TITLE
🐛 BUG:  Reputation point didn't increased after my comment got upvoted

### ISSUE THREAD

**Issue by EligibleDev** [dailydotdev/daily#1177]
### What went wrong? 🤔

In the documentation, it says that when someone creates a profile, they receive 10 reputation points. And when their comment gets upvoted, they get 50 points. 

But when my comment got upvoted, the reputation point didn't increase. It's still 10.

### Expected Behavior

I expected my reputation point to be 60 right now.

### Steps to Reproduce Issue

```bash
I don't think it happened to everyone.
```

### Screenshots

```bash
![Screenshot of the upvote notification](https://i.ibb.co/KXq3tHy/Screenshot-1.png)
![My number of upvotes didn't increase either](https://i.ibb.co/VvFnry6/Screenshot-2.png)
```

### Browsers

Brave

### OS

Windows, Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nimrodkra** [comment]
If you read carefully you’ll also notice that it says in the documentation that only upvotes from users who have more than 250 reputation points will be counted. Does it explain why your reputation did not increase?
