### ISSUE TITLE
Admin-panel

### ISSUE THREAD

**Issue by Butonix** [dailydotdev/daily#1178]
Can you tell me how to log in to the admin panel?

**Comment by idoshamun** [comment]
Hi @Butonix,

Can you elaborate please?

**Comment by Butonix** [comment]
> Hi @Butonix,
> 
> Can you elaborate please?

does daily have its own admin panel? I mean globally. Where he can see all the users, perform various actions. See analytics for a day, a month, and so on. Let's say a user has sent a report, it must be displayed somewhere in order to process it

**Comment by idoshamun** [comment]
We have something like that, but it's not publicly available for obvious reasons
