### ISSUE TITLE
🐛 BUG: wrong url in promoted article

### ISSUE THREAD

**Issue by ViNoS-ab** [dailydotdev/daily#1180]
### What went wrong? 🤔

a promoted article has the wrong URL thus when I click on it, it takes me to an invalid url
![image](https://github.com/dailydotdev/daily/assets/61888585/d871453b-ea54-46b8-8595-821d478139cf)
![image](https://github.com/dailydotdev/daily/assets/61888585/62a3ebc5-b347-4204-9c0b-ba0ccf06372e)
hasthe

### Expected Behavior

i expected to open the right URL to the article

### Steps to Reproduce Issue

```bash
1. Go to home page
2. Click on a promoted card ( tested on "Carbon" posts)
4. a page with an invalid URL is shown
```

### Solution Proposed

i have no idea how these promoted posts are added however:
this is most probably a problem from the post promoter (Carbon)  where they added the wrong URL by adding the protocol in a wrong way
solution: 
- validate URL before allowing submission

OR
the platform already has some validation method that doesn't work properly and adding an additional `https` and caused the problem

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ViNoS-ab,

We get our ads from third party networks, so unfortunately we have no control over the links they send.
We will reach out to them and ask to fix it.
Thanks for the report!
