### ISSUE TITLE
🐛 BUG: carbon ad is not working

### ISSUE THREAD

**Issue by rafalnawojczyk** [dailydotdev/daily#1181]
### What went wrong? 🤔

![image](https://github.com/dailydotdev/daily/assets/102222064/472a8c97-300c-402a-a8c5-d5b8166a3be0)
Clicking on this ad results in `DNS_PROBE_FINISHED_NXDOMAIN`

### Expected Behavior

Redirecting us to a proper article/page?

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

win10

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @rafalnawojczyk,

Thanks for reporting please see: https://github.com/dailydotdev/daily/issues/1180
