### ISSUE TITLE
🐛 BUG: Back Home button not working 

### ISSUE THREAD

**Issue by Sochuks** [dailydotdev/daily#1182]
### What went wrong? 🤔

New User here, while exploring visit the PROFILE section.
![screen1](https://github.com/dailydotdev/daily/assets/86538460/ee3f1f83-a5f8-4d7f-80f2-df7d2ad70ba7)

Sees POST tab clicks on it with excitement hoping I can share a new post.
On POST tab I find a message "Hardest part of being a developer? Where do we start – it’s everything. Go on, share with us your best rant." with a NEW POST BUTTON below it 
![screen2](https://github.com/dailydotdev/daily/assets/86538460/c34ea97b-069e-4836-9759-eb9a68e1ddc8)

Click the NEW POST BUTTON however, I get redirected to a message that says "Oops! This link leads to a private discussion
You don't seem to have access to this page. Try to ask the person who shared this link with you for permissions."
Below this message a BACK HOME BUTTON (maybe because I'm new here)
![screen3](https://github.com/dailydotdev/daily/assets/86538460/54865ebe-3012-4f82-a667-cbef3f1830ab)

Click BACK HOME and nothing happens. (I just want to go BACK HOME)  

### Expected Behavior

I expect the system to redirect back to MY FEEDS when I click the BACK HOME BUTTON 

### Steps to Reproduce Issue

```bash
1. Go to PROFILE
2. Click on POSTS
3. Click on NEW POST
4. Click on BACK HOME
5. Error - NOTHING HAPPENS!
```

### Solution Proposed

add missing home page link to BACK HOME BUTTON

### Screenshots

```bash
![screen1](https://github.com/dailydotdev/daily/assets/86538460/ee3f1f83-a5f8-4d7f-80f2-df7d2ad70ba7)
![screen2](https://github.com/dailydotdev/daily/assets/86538460/c34ea97b-069e-4836-9759-eb9a68e1ddc8)
![screen3](https://github.com/dailydotdev/daily/assets/86538460/54865ebe-3012-4f82-a667-cbef3f1830ab)
```

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Sochuks,

Thanks for reporting! We'll look into that

**Comment by omBratteng** [comment]
@idoshamun we probably should also replace the `New post` button with "Join or create a squad to create a post", since you get denied access to `https://app.daily.dev/squads/create` if you're not part of any squads.

**Comment by Sochuks** [comment]
Awesome! I can post now and the UI looks good also. Keep up the good work.
