### ISSUE TITLE
🐛 BUG: Create a Squad link incorrect when using chrome extension

### ISSUE THREAD

**Issue by harshadsatra** [dailydotdev/daily#1184]
### What went wrong? 🤔

Create a Squad link incorrect when using chrome extension

<img width="1440" alt="Screenshot 2024-05-29 at 11 55 45 PM" src="https://github.com/dailydotdev/daily/assets/5407138/8811f2cb-1757-4fba-b980-290a8949b89e">

### Expected Behavior

Link should be diected to: https://app.daily.dev/squads/new

### Steps to Reproduce Issue

```bash
Steps:
1. Open new tab with daily.dev as new tab page
2. Click on Community picks in the sidebar
3. Community picks popup opens up
4. Check "Create a squad" link
```

### Solution Proposed

Update the link

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Mac OS, Chrome

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Thanks for reporting @harshadsatra.
We have a fix for this open and deploying it will be included in a new extension release 🙏
