### ISSUE TITLE
🐛 BUG: NEWSLETTER HEADLINES

### ISSUE THREAD

**Issue by keerthinannepamula1** [dailydotdev/daily#1188]
### What went wrong? 🤔

the newletter headlines are too big and underlined

### Solution Proposed

1. medium-sized headlines
2. hide underlines
3. some description about th

### Screenshots

![image](https://github.com/dailydotdev/daily/assets/160098716/30af677e-21bb-45a7-9d11-77c3219c1a83)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @keerthinannepamula1,

Thanks for the feedback, we're constantly experimenting with the design of the digest. We will consider changing the headlines
