### ISSUE TITLE
🐛 BUG: Streak counter doesn't work when third-party cookies are disabled

### ISSUE THREAD

**Issue by ffxsam** [dailydotdev/daily#1189]
### What went wrong? 🤔

Chrome will be ending support for third-party/cross-site cookies soon, and as a web developer, I've turned mine off in advance to make sure our own services work normally. Ever since I've done this, the streak counter seems to have broken.

### Expected Behavior

Streak counter should go up every day I visit.

### Steps to Reproduce Issue

1. Go to `chrome://flags` in Chrome.
1. Find "Test Third Party Cookie Phaseout" and enable it.
1. Restart Chrome.
1. Start using daily.dev daily. 😁

### Environment

macOS 14.2.1, Chrome 125

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ffxsam,

We will test that. Maybe it messes with our authentication cookie.

**Comment by ffxsam** [comment]
Turns out that it has nothing to do with the cookie-blocking. So, streaks is just not working for me in general. And I'm definitely logged in.
![CleanShot 2024-06-04 at 10 47 43](https://github.com/dailydotdev/daily/assets/12532733/18494d6b-5433-4dfc-a785-c7e6696ad06f)

**Comment by idoshamun** [comment]
When you click on "Read Post" the counter doesn't change in a follow up visit?

**Comment by ffxsam** [comment]
Oh, you mean simply opening and skimming the page isn't enough to increase the streak counter? Neeeever mind, closing issue!

<img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGR5eXJhY2R5amM5dnptZG1qMXVwbHV0dWF1ZDYxeHhmMGU2ZmR5cyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/a93jwI0wkWTQs/giphy.gif">
