### ISSUE TITLE
🐛 BUG: Client-side exception in [Invite Screen]

### ISSUE THREAD

**Issue by NihadZeidan** [dailydotdev/daily#1190]
### What went wrong? 🤔

I tried to check the invite a friend page but got this error "Application error: a client-side exception has occurred (see the browser console for more information)."

## Error on screen
![Error Appear](https://github.com/dailydotdev/daily/assets/77915170/85094008-8088-4e9c-a37d-6362303ce22f)

## Console 
![Console log](https://github.com/dailydotdev/daily/assets/77915170/7a21c95f-00c5-44b6-a3ec-abc4eabf61d9)

### Expected Behavior

Friend Invitation screen render normally.

### Steps to Reproduce Issue

```bash
1. Click on your avatar in the right top corner.
2. Click on "Invite Friends" tab.
```

### Solution Proposed

- Check time value sent from the server.
- Add extra checking before manipulating any time/date value.
- In case something went wrong in a specific section of the screen try to render UI Error for that section instead of blocking the whole screen.

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
It's fixed now. Thanks for reporting @NihadZeidan
