### ISSUE TITLE
🐛 BUG: The streak pop 

### ISSUE THREAD

**Issue by 238u** [dailydotdev/daily#1195]
### What went wrong? 🤔

the streak pop up is still showing after selecting never show me this again

### Expected Behavior

the streak pop up to never show again

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @238u,

Thanks for the report. We fixed the issue :)
