### ISSUE TITLE
🐛 BUG: There are ads on the app, but its links are not pointing correctly to a valid URL.

### ISSUE THREAD

**Issue by miltonlm** [dailydotdev/daily#1197]
### What went wrong? 🤔

I was interested on one of the ads shown on the feed, however after clicking the link it sent me to an invalid URL:

`https://https//srv.buysellads.com/ads/click/x/GTND427JCABIVK7ICVBLYKQUC6SDL53NCYYI4Z3JCAYIK5QUCKSDC2QKCYYD5KJUCYYD427YCTYD653YCA7IP23KC6SI427MCTAIKK3EHJNCLSIZ`

As you can see, there's an error in the link.

### Expected Behavior

I would expect it to open a link with this URL:

`https://srv.buysellads.com/ads/click/x/GTND427JCABIVK7ICVBLYKQUC6SDL53NCYYI4Z3JCAYIK5QUCKSDC2QKCYYD5KJUCYYD427YCTYD653YCA7IP23KC6SI427MCTAIKK3EHJNCLSIZ`

instead of:

`https://https//srv.buysellads.com/ads/click/x/GTND427JCABIVK7ICVBLYKQUC6SDL53NCYYI4Z3JCAYIK5QUCKSDC2QKCYYD5KJUCYYD427YCTYD653YCA7IP23KC6SI427MCTAIKK3EHJNCLSIZ`

### Steps to Reproduce Issue

```bash
1. Go to My Feed.
2. Click on VPS Redefined. Supercharged hosting. Lower price. Shop for £8.18
3. See the error.
```

### Solution Proposed

Fix the link that the ad points to.

### Environment

Ubuntu 24.04, Opera Browser, Latest Version.

### Browsers

Opera

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
@miltonlm this is fixed now! sorry about that
