### ISSUE TITLE
🐛 BUG: Application error when trying to join Squad

### ISSUE THREAD

**Issue by idris-aitmoulay** [dailydotdev/daily#1199]
### What went wrong? 🤔

Trying to join any squad through error

```Application error: a client-side exception has occurred (see the browser console for more information).```

Steps: 

![image](https://github.com/dailydotdev/daily/assets/34316683/7315a5ab-e73d-4f9f-9af6-614fc90c5192)
![image](https://github.com/dailydotdev/daily/assets/34316683/ce1f59e9-74c4-4c93-8ebe-7a2b9836ee9a)
`click on back`
![image](https://github.com/dailydotdev/daily/assets/34316683/760847a8-737c-4dd2-ac49-d0ce82659c8a)

### Expected Behavior

Success message that I joined the squad

### Steps to Reproduce Issue

```bash
1. Go to https://app.daily.dev/squads
2. Click on 'Join Squad'
3. See the 'Application error'
```

### Browsers

Chrome

### OS

Windows

### Additional Context

```bash
Chrome: Version 125.0.6422.142 (Build officiel) (64 bits)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @idris-aitmoulay,

This should be fixed now. Thanks for reporting!

**Comment by idris-aitmoulay** [comment]
> This should be fixed now. Thanks for reporting!

Cooooooooool
