### ISSUE TITLE
Hiring Badge showing below search bar (Android app)

### ISSUE THREAD

**Issue by mishrayush15** [dailydotdev/daily#1201]
### What went wrong? 🤔

The "Daily.dev is Hiring" badge is showing on all the pages/sections of the daily.dev android application. It doesn't look good in terms of design when the same badge is showing below the search bar.

### Expected Behavior

It would look really awesome if we could remove the hiring badge from the search bar page/section.

### Steps to Reproduce Issue

```bash
1. Open the Daily.Dev Android App
2. Go to search icon on the bottom navbar
3. You would see the hiring badge showing below the search bar in the search section.
```

### Solution Proposed

Either by removing or by showing the hiring badge on the bottom of the seach bar page would be a better solution.

### Environment

Android 11+

### OS

Android

### Version of daily.dev

3

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@mishrayush15 Thanks so much for reporting, this got recently fixed 🙏
