### ISSUE TITLE
🐛 BUG: "reading streak" popup shows up every day even though I've told it not to

### ISSUE THREAD

**Issue by ZaLiTHkA** [dailydotdev/daily#1202]
### What went wrong? 🤔

as per the screenshot attached further below, I have the "Never show this again" option checked, but every day I get the same popup on my first new tab.

I've tried deselecting and reselecting this option, but it comes up again the next day regardless.

### Expected Behavior

I expect the checkbox to do what the label says, and "never show this again"..

### Steps to Reproduce Issue

```bash
n/a
```

### Screenshots

![Screenshot from 2024-06-06 08-10-02](https://github.com/dailydotdev/daily/assets/2149312/a3b91de3-ba9f-4987-b5a2-fb2919acf37b)

### Environment

Zorin OS 17.1, Windows 10 Pro, Windows 11 Pro

### Browsers

Brave

### OS

Windows, Linux

### Version of daily.dev

3.31.17

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by ZaLiTHkA** [comment]
also, this is most definitely _not_ a "new milestone reached"... just saying.

**Comment by idoshamun** [comment]
Hi @ZaLiTHkA,

Thanks for reporting. We found the issue and fixed it. We hope to release new extension soon.
