### ISSUE TITLE
🐛 BUG: 404 Error When Attempting to Sign Up Using GitHub or Google on Firefox

### ISSUE THREAD

**Issue by bugenzi** [dailydotdev/daily#1203]
### What went wrong? 🤔

I encountered a "404 Not Found" error when trying to sign up on daily.dev using GitHub on Mozilla. The error message suggests that the route for the GET request is not found.

Error Message:
```Route GET:/v1/auth/authorize?provider=google&redirect_uri=moz-extension://uid/index.html&skip_authenticate=true&register_mode=default not found```

### Steps to Reproduce Issue

```bash
1. Go to the daily.dev
2. Click on Access all features button
3. Select GitHub option or google
4. Redirects to API response URL error 404
```

### Solution Proposed

It appears there might be a misconfiguration in the API route or a missing endpoint for handling the authorization request. Please check the API routing and endpoint configurations.

### Environment

Ubuntu 24.04 noble

### Browsers

Firefox

### OS

Linux

### Version of daily.dev

3.15.5

### Additional Context

```bash
I attempted to sign up on Jun 6 23:35 Central European Time (CET), and the same issue occurred multiple times.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @bugenzi 

Thanks for reporting, unfortunately our Firefox extension has been demoted to a old version.
Please see this thread for more info: https://x.com/dailydotdev/status/1798960336667893866

In the mean time you can still use Chrome extension or our [webapp](https://app.daily.dev/)
