### ISSUE TITLE
🐛 BUG: Cannot complete signup

### ISSUE THREAD

**Issue by Nix-C** [dailydotdev/daily#1204]
### What went wrong? 🤔

Just installed the chrome extension and I can't get past the signup screen after connecting GitHub.

### Expected Behavior

Adjust username, click sign-up, proceed to daily.dev dashboard.

### Steps to Reproduce Issue

```bash
1. Go to 'daily.dev'
2. Click on 'Sign Up With GitHub'
3. Connect GitHub account
4. Review user data and click "Sign Up"
4. Nothing Happens (Check js console for errors)
```

### Browsers

Chrome

### OS

Windows

### Additional Context

```bash
Loom Video: https://www.loom.com/share/4d56ce1d92fd4837ad5489da19f81ee6?sid=3e03a157-3109-4f79-97d0-13faa6169bb9
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@Nix-C Thanks for reporting and providing the loom (really helps)
I see our validation didn't kick in, we don't allow `-` characters in the username.

I'll log it for our team to look into and fix so you get better visual feedback.
Hope you can signup with a different username, let me know if it still won't work.

**Comment by Nix-C** [comment]
@rebelchris Just tried now and noticed the validation for existing usernames works! (Validation for the `-` still does not tho)
New bug, someone stole my username 🥲 (KIDDING)

**Comment by Nix-C** [comment]
@rebelchris in case it helps, closing this issue.

If anyone encounters the error before it's fixed:
`Your username cannot contain non-alphanumerical characters`
