### ISSUE TITLE
🐛 BUG: Layout issue

### ISSUE THREAD

**Issue by AbhinavAchha** [dailydotdev/daily#1208]
### What went wrong? 🤔

in layout of one post per line, the density is not working properly

### Screenshots

```bash
[Screencast_20240607_152402.webm](https://github.com/dailydotdev/daily/assets/68775533/d608d3f0-8598-487d-a5d9-4ad66dafded8)
```

### Environment

Fedora Linux Brave: Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)

### Browsers

Brave

### OS

Linux

### Version of daily.dev

3.31.17

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @AbhinavAchha,

You're right the density setting affects only the card view. It's not a bug it's a feature 😂

**Comment by rebelchris** [comment]
@AbhinavAchha 

Based on your feedback we modified the settings so the density becomes disabled with a reason if you hover once you are on list mode.
Thanks a lot for the feedback 

<img width="462" alt="Screenshot 2024-07-11 at 20 37 53" src="https://github.com/dailydotdev/daily/assets/554874/3c0f33bb-76f4-48c0-a35f-7c711298efc0">
