### ISSUE TITLE
🐛 BUG: Streak Popup shows again even after you click never show again on Brave

### ISSUE THREAD

**Issue by klendi** [dailydotdev/daily#1210]
### What went wrong? 🤔

Streak Popup shows again even after you click never show again on Brave.

### Expected Behavior

Never show streak popup after clicking never show again

### Steps to Reproduce Issue

```bash
1. Open a new tab
```

### Solution Proposed

Perhaps you guys are saving that into cache or something like that that Brave deleted or doesn't allow.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Macos

### Browsers

Brave

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @klendi,

Thanks for reporting. We found the issue and fixed it. We hope to release new extension soon.
