### ISSUE TITLE
🐛 BUG: Duplicate post suggestions in feed

### ISSUE THREAD

**Issue by shatandv** [dailydotdev/daily#1212]
### What went wrong? 🤔

Just signed up.
Selected a bunch of tags for my feed: backend, cloud, postgresql, ai, data-engineering, data-science, deep-learning, linux, devops, devsecops, infrastructure, architecture, mobile, python, venture-capital, startup, tech-news, testing, frontend, webdev.

I'm frequently seeing duplicate suggestions in my feed.
<img width="1064" alt="image" src="https://github.com/dailydotdev/daily/assets/19673037/8f80493a-2267-498d-b398-0fe95ac90808">
<img width="1067" alt="image" src="https://github.com/dailydotdev/daily/assets/19673037/233213a3-b838-41eb-bf69-720c54d8ad7f">

The duplicates seem to appear not on the same "page" of suggestions but after more suggestions are loaded with infinite scroll.
They seem to be duplicated only once, not any more than that.
Also, they are not necessarily in the same order as first seen.

When I've opened a new tab with my feed and I haven't seen any duplicates yet (tried this a couple times).

Maybe it's a first-time thing after sign up. It's not exactly a good "first look" at the product though, I imagine :)

### Expected Behavior

Given I'm browsing my feed for the first time, when I'm scrolling through the suggestions, then I don't see the same suggestion more than once.

### Steps to Reproduce Issue

```bash
1. Sign up.
2. Choose these tags for the personal feed on the onboarding page: backend, cloud, postgresql, ai, data-engineering, data-science, deep-learning, linux, devops, devsecops, infrastructure, architecture, mobile, python, venture-capital, startup, tech-news, testing, frontend, webdev.
3. Accept the tags and get sent to the feed page.
4. Scroll through the feed, while taking note of the suggested posts. You might notice the duplicates.
```

### Solution Proposed

No idea how the feed is formed and how the just-signed-up state might be affecting it.
Maybe some kind of frontend or backend state is not properly updated on sign up, so the "seen" commands for the suggestions are not processed appropriately.

### Screenshots

```bash
![First encounter of these suggestions](https://github.com/dailydotdev/daily/assets/19673037/8f80493a-2267-498d-b398-0fe95ac90808)
![Second encounter of the suggestions further down the page](https://github.com/dailydotdev/daily/assets/19673037/233213a3-b838-41eb-bf69-720c54d8ad7f)
```

### Environment

Windows 11, Chrome v.125.0.6422.142

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

Web app as of today

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @shatandv,

Thanks for reporting it, we recently received more reports about this issue and decided to reopen https://github.com/dailydotdev/daily/issues/97.
Let's keep the discussion there.
