### ISSUE TITLE
🐛 BUG: A lot of duplicates occurring

### ISSUE THREAD

**Issue by hinogi** [dailydotdev/daily#1213]
### What went wrong? 🤔

![image](https://github.com/dailydotdev/daily/assets/4602609/3941c9ce-f5b5-439a-8f4e-2510b0f4347e)

### Expected Behavior

distinct

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @hinogi,

Thanks for reporting it, we recently received more reports about this issue and decided to reopen https://github.com/dailydotdev/daily/issues/97.
Let's keep the discussion there.
