### ISSUE TITLE
🐛 BUG: Your feed filters are too specific.  

### ISSUE THREAD

**Issue by udpwz** [dailydotdev/daily#1215]
### What went wrong? 🤔

I can't see blogs, on extension site

I follow every single tag, In the extension view but still show me 
`
Your feed filters are too specific.
We couldn't fetch enough articles based on your selected tags. Try adding more tags using the feed settings.
`
,but everything is correct on  https://app.daily.dev/ site

`
Error: Cannot query field "featuredComments" on type "Post". Did you mean "numComments"?: {"response":{"errors":[{"message":"Cannot query field \"featuredComments\" on type \"Post\". Did you mean \"numComments\"?","locations":[{"line":54,"column":5}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"status":200,"headers":{"map":{"access-control-allow-credentials":"true","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","content-length":"201","content-security-policy":"default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests","content-type":"application/json; charset=utf-8","cross-origin-opener-policy":"same-origin","cross-origin-resource-policy":"same-origin","date":"Tue, 11 Jun 2024 19:30:14 GMT","origin-agent-cluster":"?1","referrer-policy":"no-referrer","strict-transport-security":"max-age=15552000; includeSubDomains","vary":"Origin","via":"1.1 google","x-content-type-options":"nosniff","x-dns-prefetch-control":"off","x-download-options":"noopen","x-firefox-spdy":"h2","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"0"}}},"request":{"query":"\n  query Feed(\n    $loggedIn: Boolean! = false\n    $first: Int\n    $after: String\n    $ranking: Ranking\n    $unreadOnly: Boolean\n    $version: Int\n  ) {\n    page: feed(\n      first: $first\n      after: $after\n      ranking: $ranking\n      unreadOnly: $unreadOnly\n      version: $version\n    ) {\n      ...FeedPostConnection\n    }\n  }\n  \n  fragment FeedPostConnection on PostConnection {\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n    edges {\n      node {\n        ...FeedPost\n        ...UserPost @include(if: $loggedIn)\n      }\n    }\n  }\n  \n  fragment FeedPost on Post {\n    id\n    title\n    createdAt\n    image\n    readTime\n    source {\n      id\n      name\n      image\n    }\n    permalink\n    numComments\n    numUpvotes\n    commentsPermalink\n    author {\n      name\n      image\n      username\n    }\n    featuredComments {\n      id\n      content\n      permalink\n      author {\n        name\n        image\n        username\n      }\n    }\n    trending\n    tags\n  }\n\n  \n  fragment UserPost on Post {\n    read\n    upvoted\n    commented\n    bookmarked\n  }\n\n\n","variables":{"version":1,"ranking":"POPULARITY","first":13,"loggedIn":true,"unreadOnly":false}}}
`

### Steps to Reproduce Issue

```bash
1. Go to New Tab with Extension
2. Click on '....'
3. Scroll down to '....'
4. See the error Open Console
```

### Screenshots

```bash
![image](https://github.com/dailydotdev/daily/assets/33403896/a7872e98-7349-4d98-8821-a9594b280efc)
![image](https://github.com/dailydotdev/daily/assets/33403896/e21e5716-c7fc-4e54-b7ef-f9be254cddbe)
![image](https://github.com/dailydotdev/daily/assets/33403896/9fedc3eb-1576-431b-b730-f32ba28b0343)
![image](https://github.com/dailydotdev/daily/assets/33403896/40ae8fe2-0f90-484a-92e7-00678e3e3712)
```

### Browsers

Firefox

### OS

Windows

### Version of daily.dev

3.15.5

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @udpwz,

You're using a 2 year old version of our extension which is no longer supported. This is due to an issue we currently have with FireFox review process. I suggest you to uninstall it and just our webapp.
I hope we can resolve this issue quickly
