### ISSUE TITLE
🐛 BUG: Every daily.dev link that goes to r.daily.dev is broken on Chrome at least.

### ISSUE THREAD

**Issue by hennysmafter** [dailydotdev/daily#1219]
### What went wrong? 🤔

Open the daily.dev site and click on feedback for instance. It will bring you to: https://r.daily.dev/feedback
Which gives you a nice Google greeting: This site can’t be reached r.daily.dev unexpectedly closed the connection.

### Expected Behavior

Remove the r. subdomain and boom you are there on the feedback page.

### Steps to Reproduce Issue

```bash
1. Go to 'daily.dev'
2. Click on 'feedback'
3. Watch the error happening in front of your eyes
```

### Solution Proposed

Dive into the code and see why all those links are made with the subdomain r. and either fix the redirects on this subdomain or remove the subdomain from the links.

So far every time I get this error I just remove the r. part and still get to the right page, so I don't think the r. part is necessary.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

Make it easily findable!!!!!!!

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @hennysmafter,

I think this was a temporary issue. Can you check again please?

**Comment by hennysmafter** [comment]
![image](https://github.com/dailydotdev/daily/assets/4426337/7f97a51d-e356-4d54-8b1f-11d20107cf47)

I don't think it is temporary.

1. I go to https://app.daily.dev/
2. I click on feedback at the bottom left and then the error in the image happens.

**Comment by idoshamun** [comment]
It works just fine on my end 😬
