### ISSUE TITLE
🐛 BUG: streak counter not working

### ISSUE THREAD

**Issue by maxmeneghini** [dailydotdev/daily#1221]
### What went wrong? 🤔

I've noticed 2 problems with the streak counter on the mobile app:
1. It always shows the day before as non-marked, even if I did. Eventually, it updates the day after, but sometimes it doesn't (which brings us to number 2).
2. Streak counter is not counting at least half the days I use the app to read. Is there any rules I'm missing? I spend at least 10-15 min per day browsing stuff in the app.

### Expected Behavior

Counter should mark the day as soon as criteria is matched.

### Steps to Reproduce Issue

```bash
1. Open the app.
2. Click on streak counter.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Android 13 One UI, Samasung Galaxy S20 FE

### OS

Android

### Version of daily.dev

7

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @maxmeneghini,

Did you set properly the timezone of your account? Also, streak counts only when you read an article

**Comment by maxmeneghini** [comment]
Yes, timezone is correct. And I read 2 or 3 articles a day, usually.

Em sex., 14 de jun. de 2024 04:24, Ido Shamun ***@***.***>
escreveu:

**Comment by idoshamun** [comment]
We weren't able to reproduce but we will try to look into your account specifically.
I'll keep you posted

**Comment by idoshamun** [comment]
We checked our records, and here's a snapshot of of your recent reading days. The table shows the date and number of articles read. It seems like you are not reading an article every day. Do you happen to have cookie blocker? Or maybe you don't click the "read article" button when it is presented?
<img width="189" alt="image" src="https://github.com/dailydotdev/daily/assets/1993245/838094c8-9959-40d5-b99b-5dd467b74df6">

**Comment by maxmeneghini** [comment]
I didn't even notice the "Read post" until now. I always clicked on the
image right after the description. Any chance that's not mapped correctly?

Em ter., 25 de jun. de 2024 às 10:11, Ido Shamun ***@***.***>
escreveu:

**Comment by maxmeneghini** [comment]
Well, I did a couple of screenshots last week, and I can assure you I had
clicked on a few articles just make sure (clicked on the image as well).

Did it on 2 consecutive days to make sure as well.







Em qua., 26 de jun. de 2024 10:11, Ido Shamun ***@***.***>
escreveu:

**Comment by idoshamun** [comment]
Can you confirm you have no cookie blockers and you are logged in?

**Comment by maxmeneghini** [comment]
Yes to both. Unless there's a built in blocker on Samsung android phones
I'm not aware of.

Em qua., 26 de jun. de 2024 às 10:21, Ido Shamun ***@***.***>
escreveu:

**Comment by idoshamun** [comment]
Interesting I'm not aware of any. Does it happen when you use daily.dev on desktop?

**Comment by maxmeneghini** [comment]
I've never tried that. Just had it on the phone. I usually read articles
when in transit, or waiting something.

Em qui., 27 de jun. de 2024 às 04:57, Ido Shamun ***@***.***>
escreveu:

**Comment by idoshamun** [comment]
I see. At this point I'm not sure how to proceed as we have no way to reproduce it and you're the only user who reported this issue. If you ever find a way to reproduce please let me know. Ok?

**Comment by rebelchris** [comment]
Closing as resolved for now.
