### ISSUE TITLE
🐛 BUG: Weekly/Daily email updates

### ISSUE THREAD

**Issue by rnboo** [dailydotdev/daily#1224]
### What went wrong? 🤔

When having the 'Weekly' option selected for setting personalized emails once a week and then setting a time to send the mail, the option is automatically set to 'Daily'. This can be byc confirmed by reloading the page/closing the app and going back to the notification settings, the time is correctly set, while option 'Daily' is selected.

Edit: I was able to recreate the same behaivior when changing the settings as mentioned [on desktop](https://app.daily.dev/account/notifications)

### Expected Behavior

It seems that the weekly option cant be configured together with the time setting under the 'Email Notifications' settings

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @rnboo,

Thanks for the report. We will look into that

**Comment by BharathSubu** [comment]
Hey , I looked into the codeBase and found a fix. I'm new to contributing in open-source projects , so pls take a look at the change  and comment for changes happy to do it 

![WhatsApp Image 2024-06-26 at 5 18 25 PM](https://github.com/dailydotdev/daily/assets/66304459/62b61c2b-874d-4c68-ac29-c33f9f870772)

**Comment by sshanzel** [comment]
Hi @BharathSubu! Thank you for your interest in fixing the issue. If you want to submit a PR, you will have to:
1. Fork the project: https://github.com/dailydotdev/apps/fork
2. Make a branch for the fix.
3. Make changes on that branch.
4. Raise the PR.

The steps above should help you to raise your first PR here in our repo. I would love it if you could follow through the steps so people can see that you were the one who actually fixed the issue and gain the `Contributor` badge ❤️

**Comment by BharathSubu** [comment]
Hey @sshanzel I have made the PR

**Comment by sshanzel** [comment]
@BharathSubu thank you so much for fixing the issue! ❤️ 🥳 🍻
