### ISSUE TITLE
Fix the unsubscribe button, I unsubscribed 4 times

### ISSUE THREAD

**Issue by Dzheky** [dailydotdev/daily#1227]
### What went wrong? 🤔

Fix the unsubscribe button, I unsubscribed 4 times in the span of 3 weeks. I still receive emails.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Dzheky,

I'm terribly sorry for this poor experience. In the last several weeks we migrated to a new mailing system which may have caused this issue. If you email your email address I'll make sure personally to unsubscribe you completely.
Our address is support at daily.dev
