### ISSUE TITLE
🐛 BUG: Deleted squad welcome post

### ISSUE THREAD

**Issue by frank-connolly** [dailydotdev/daily#1232]
### What went wrong? 🤔

When I was setting up a new squad called 'Just Java' (it is public), I deleted the 'welcome' post thinking it was just for me. However, I now realise it was important to the squad. I cannot seem to recreate it and its deletion means that:

- When I click any 'new member X has joined your squad' notification I get taken to a 404 page. 
- In the squad creation checklist I cannot complete the 'customise welcome' step.

I do not know what new members see when they join the squad and hope its not an off-putting 404. 

Thanks
Frank

### Expected Behavior

When clicking 'new member has joined your squad, welcome them' notification to be taken to the appropriate screen.

### Steps to Reproduce Issue

```bash
1. Go to 'Just Java' squad and join
2. See what greets you as a welcome to the squad (I don't know what it is - maybe a 404)
```

### Solution Proposed

Reinstate the welcome post with some kind of protection that it cannot be deleted or it should default to a generic one if deleted.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @frank-connolly,

we'll try to recreate this post for you. I'll let you know

**Comment by idoshamun** [comment]
Should be ok now! :)

**Comment by rebelchris** [comment]
Hi @frank-connolly Thanks for opening up the issue.
I reverted the deletion of the welcome post so you are now able to see it again.

Note you can arrange pinned posts differently by unpinning/repinning them

**Comment by frank-connolly** [comment]
Thanks @rebelchris!
