### ISSUE TITLE
🐛 BUG: Incorrect read time estimation

### ISSUE THREAD

**Issue by frank-connolly** [dailydotdev/daily#1235]
### What went wrong? 🤔

I [posted a link to a small article on GeeksForGeeks](https://dly.to/MJmgc3Cnbbx) which was labelled with a 45 minute read time. The TL;DR was correct but the read time was way off. The article title was also not auto populated when sharing the post.

### Expected Behavior

The article should be around 3 minute read time

### Steps to Reproduce Issue

```bash
1. Go to the post linked in 'What went wrong'
2. Click on the article
3. Scroll down to the end to see it is a quick read
4. See the incorrect reading time estimation in the post
```

### Solution Proposed

Whatever mechanism used to calculate read time does not work well with GeekForGeeks site it seems. It would need to be adjusted to give the reading time estimate for this article accurately

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @frank-connolly,

Thanks a lot for the report. We will look into that

**Comment by idoshamun** [comment]
It's fixed now!
