### ISSUE TITLE
🧩 FEATURE REQUEST:  Post title translation

### ISSUE THREAD

**Issue by Maaz-Ahmed007** [dailydotdev/daily#1237]
### Concise Description

App.daily.dev could use an auto post title translator

### Description

![Screenshot 2024-06-24 214438](https://github.com/dailydotdev/daily/assets/60651630/ed8decc0-6ea8-41f9-8231-a9faa47988cf)
![Screenshot 2024-06-24 214558](https://github.com/dailydotdev/daily/assets/60651630/5154cca0-172b-4a29-a6e4-699da3fefe63)

Some posts have titles in different languages, which could be hard to understand for English readers as in this example.

### Solution Proposed

If you add a feature that automatically translates the titles in English for most English reading users or add a text button that on clicks translates the title for user as in the Instagram post titles that would be really good.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Maaz-Ahmed007,

daily.dev supports currently only English, if you see non-English content on your feed you can report it and we will take action.
Thanks for reaching out!

**Comment by mathiasschopmans** [comment]
Is there a user setting to turn the translation off? I'm annoyed by the translations and don't like the titles to be translated in my native (german) language. Is there a way to read the orginal (english) titles=

**Comment by rebelchris** [comment]
@mathiasschopmans yes, under feed setting you can set it back to "Original language"

![Image](https://github.com/user-attachments/assets/c77b11c0-d254-44c9-b60a-3f4894a01e1c)
