### ISSUE TITLE
🐛 BUG: Duplicate links in the page

### ISSUE THREAD

**Issue by ysabag** [dailydotdev/daily#1238]
### What went wrong? 🤔

![image](https://github.com/dailydotdev/daily/assets/98085226/37ee580f-0d67-4cb5-9724-e739f9f4fd2a)

### Expected Behavior

no duplication

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![image](https://github.com/dailydotdev/daily/assets/98085226/37ee580f-0d67-4cb5-9724-e739f9f4fd2a)
```

### Browsers

Microsoft Edge

### Version of daily.dev

web

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
We reopened this issue https://github.com/dailydotdev/daily/issues/97 recently.
We're working to fix it
