### ISSUE TITLE
🐛 BUG: Incorrect 'More posts from X' widget

### ISSUE THREAD

**Issue by frank-connolly** [dailydotdev/daily#1239]
### What went wrong? 🤔

While looking at any post in the Just Java squad I see a 'More posts from Just Java' widget on the right. However, none of the articles listen in the widget have been posted in the squad. Most are unrelated to the topic of the squad.

### Expected Behavior

Only actual articles posted to the squad appear in the widget.

### Steps to Reproduce Issue

1. Go to [Just Java squad welcome post](https://app.daily.dev/posts/4lkF85AjX)
2. Scroll down until you see `More posts from Just Java` widget on the right
3. Confirm that articles listed are not posted to the squad

### Solution Proposed

Mechanism used to list articles in widget is updated to pull from squad articles only

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sabdailydev** [comment]
@frank-connolly thanks for reporting this. We will add it to our backlog. 

Also, I wanted to check if you might be open to a 1:1 discussion. We'd love to hear any other feedback you might have about operating Squads. You can book a slot that's convenient from my calendly link [here](https://calendly.com/sab-07/daily-dev-user-feedback-session. )

**Comment by frank-connolly** [comment]
@sabdailydev I'd be happy to

**Comment by frank-connolly** [comment]
![image](https://github.com/user-attachments/assets/1236b811-d186-4b98-a0de-a0f93f24a2f9)
Widget showing my profile repeated with dates (possibly dates for posts but clicking this brings the user to my profile)

**Comment by idoshamun** [comment]
The reason is that your posts don't have title, they're probably shared links. We need to fix it
