### ISSUE TITLE
🧩 FEATURE REQUEST:  

### ISSUE THREAD

**Issue by HakimAbdul12** [dailydotdev/daily#1240]
### Concise Description

Will like  a theme toggler button to the navbar and the footer

### Description

I would like to propose adding a theme toggler button to both the navbar and the footer. This feature will allow users to switch between light and dark themes easily, enhancing the overall user experience.

### Solution Proposed

Button Placement:

Navbar: The theme toggler button should be placed on the right side of the navbar.
Footer: The theme toggler button should be placed on the left side of the footer.
Button Design:

The button should be visually appealing and consistent with the current design of the application.
It should clearly indicate the current theme (light or dark) and change its appearance accordingly.
Functionality:

Clicking the button should toggle the theme between light and dark modes.
The selected theme should be applied instantly to the entire application.
The theme preference should be saved in the user’s browser (e.g., using localStorage) so that the chosen theme persists across sessions.
Accessibility:

Ensure that the theme toggler is accessible and usable by all users, including those who rely on keyboard navigation and screen readers.
Provide appropriate ARIA attributes and ensure sufficient contrast for the button in both themes.
Thank you for considering this suggestion. I believe this feature will greatly enhance the user experience by providing a more personalized and comfortable interface.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @HakimAbdul12,

We already have a theme toggle in the customize menu.
Click on your profile image and hit the customize button.
<img width="314" alt="image" src="https://github.com/dailydotdev/daily/assets/1993245/28b81538-7ecc-459d-8e89-e0f9934e9df6">
