### ISSUE TITLE
🐛 BUG: Squads cards don't show the `Read post` button

### ISSUE THREAD

**Issue by JCKodel** [dailydotdev/daily#1243]
### What went wrong? 🤔

For normal cards, hovering over the card shows a `Read post` button, which will open the link. The same is not true for squads card (I'm forced to click the card, then click the button to open it, then close the card).

This makes squads cards hard to use.

### Expected Behavior

Same behavior across all the UI.

### Steps to Reproduce Issue

```bash
1. Hover the mouse over a squad card
```

### Solution Proposed

Make the UI consistent

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @JCKodel,

Thanks for the report. We're now experimenting with a variation for squad posts to be exactly like any other article. You are probably still in the control group. Stay tuned for the experiment results

**Comment by rebelchris** [comment]
We ended up implementing the new design all-round which solves this reported issue.
Do note some content might not contain a link, therefor not render the button.
