### ISSUE TITLE
🐛 BUG: SIGN UP BUTTON NOT WORKING 

### ISSUE THREAD

**Issue by Dr-Bernard** [dailydotdev/daily#1244]
### What went wrong? 🤔

After adding daily.dev to my chrome extensions, I was prompted to sign up for the service. After clicking the button: 'sign up with Google mail' and selecting my email, another page appeared where I typed in my names and other details. Then I checked the box that reads "I don't want to receive updates and promotions via email" then I clicked the sign up button BUT NOTHING HAPPENED. After waiting for several minutes, I clicked it again nothing still happened. I then clicked it again multiple times, checked my internet connections, other tabs etc and confirmed that despite that I have good internet connection, THE SIGN UP BUTTON IS STILL NOT WORKING. See attached screenshot.
![Sign up button refused to work on daily dev sign up page Screenshot 2024-06-29 050532](https://github.com/dailydotdev/daily/assets/57553165/9010107a-1b9e-4326-a4a2-a92798d58049)

### Expected Behavior

I expected that when I click on the 'Sign up' button there will be a notification of successful sign up or reason for the failed sign up.

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/onboarding?ref=install'
2. Click on 'sign up with Google mail'
3. On the new page displayed type in all the required details. Check the box that reads "I don't want to receive updates and promotions via email" then click the sign up button
4. See the error: you will notice that the page will not react at all to the clicking of the sign up button
```

### Solution Proposed

The page should pop up a notification saying that the sign up was successful or if it was not successful the reason for the failure should be displayed accordingly.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
See screenshot of the page where I got stuck after clicking the Sign up button. ![Sign up button refused to work on daily dev sign up page Screenshot 2024-06-29 050532](https://github.com/dailydotdev/daily/assets/57553165/9010107a-1b9e-4326-a4a2-a92798d58049)
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @Dr-Bernard ,

Thanks for reporting and reaching out.
We dont allow hypens in username, it should have shown you a error message, I've logged it as a urgent bug to fix. 🙏

For the time being you should be able to change the username to something without any special characters.

**Comment by Dr-Bernard** [comment]
Thank you very much @rebelchris  for your intervention.

I have done as you advised, and I have now successfully signed up.

See screenshots of successful sign up below:
![Sign up has now worked for me Screenshot 2024-06-29 104936](https://github.com/dailydotdev/daily/assets/57553165/bcee92f8-0659-49ab-9bcd-23ddbfe092b8)
![Uploading I am now fully onboarded on daily.dev Screenshot 2024-06-29 110237.png…]()

**Comment by omBratteng** [comment]
> I am now fully onboarded on daily.dev

Awesome! Glad to have you here
