### ISSUE TITLE
🐛 BUG: Bio disapers when changing timezone.

### ISSUE THREAD

**Issue by feliarana** [dailydotdev/daily#1249]
### What went wrong? 🤔

![Peek 2024-07-01 11-23](https://github.com/dailydotdev/daily/assets/8558165/5d5a1b12-aeee-4a67-a585-95ac06daec8b)

### Expected Behavior

The gif should be enough, but it should not change or reset any other input.

### Steps to Reproduce Issue

```bash
1. Go to 'Profile'
2. Update any personal input except timezone dropdown.
3. Now, try clicking on any other timezone.
4. All other inputs are reset to original value.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @feliarana,

Thanks for reporting, it is indeed a bug on our side when a field fails to update.
We'll look into this and report back once it's solved.

**Comment by rebelchris** [comment]
Hi @feliarana 

We solved the issue and it got deployed.
Once again, thanks for reporting 🙏
