### ISSUE TITLE
🐛 BUG: Cannot log in with other google account

### ISSUE THREAD

**Issue by Bandiz** [dailydotdev/daily#1250]
### What went wrong? 🤔

I want to switch my google account, but when trying to logout and then login it force logs me in with the old account.

### Expected Behavior

I should be able to choose a different google account.

### Steps to Reproduce Issue

```bash
1. Log in with google account A
2. Click on profile
3. Click on 'Logout'
4. Click on 'Use another account'
5. Click on Google
6. Now you are logged back in with google account A
```

### Solution Proposed

Support for multiple accounts, or a logout should actually log me out completely so that I could choose an account that I actually want to use the extension with.

### Browsers

Brave

### OS

Windows

### Version of daily.dev

3.32.2

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @Bandiz ,

We technically support this, I think what happens here is more of a Google issue.
Can you make sure if you for instance visit https://myaccount.google.com/ that in the top right corner you are logged into more then one account?

If there is only one shown there/only one logged in at the moment it skips the step to pick another one.

**Comment by Bandiz** [comment]
The issue no longer happens. Not sure why though. And ofc, I did have multiple accounts connected at the time when I registered the Issue.
I'm closing this report as this no longer is an issue for me. 
Thank you for looking into it!
