### ISSUE TITLE
🐛 BUG: I get a 404 on an article that supossedly already exists

### ISSUE THREAD

**Issue by pavlospt** [dailydotdev/daily#1252]
### What went wrong? 🤔

https://app.daily.dev/posts/rustic-witcher-reimagining-data-anonymization-uhufs3hih This one says that it exists and I get a 404 when I click it! 

### Steps to Reproduce Issue

```bash
1. Submit this article: https://engineering.theblueground.com/rustic-witcher-reimagining-data-anonymization/
2. Get an error that it already exists
3. Click on the existing
4. 404
```

### Screenshots

https://github.com/dailydotdev/daily/assets/1070871/055ff4f1-d0ef-4c29-9946-d59e2971969e
https://github.com/dailydotdev/daily/assets/1070871/fac513bc-f5bd-412a-ac90-23f5e76866db

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @pavlospt,

When a link is shared to a private squad first and only then submitted to community picks this edge case can happen.
We should consider how to fix it, thanks for the report

**Comment by idoshamun** [comment]
Eventually we decided to fix the error but we have no plans to allow submitting a community picks if a link previously shared in a private squad. Fixing it requires a lot of changes and since it's a rare edge case, we're not willing to take the risk

**Comment by pavlospt** [comment]
@idoshamun TBH when I encounterted this bug, I had mistakenly shared it in a private squad, because the UI lead me to create the Squad as the only means to share the link, since I had no access to publicly share it, or something like that. So I am not so sure about the level of "rare edge case" this would be.

**Comment by idoshamun** [comment]
By default when you open a squad now it's public. The platform is gradually moving from community picks to squads as they provide a better experience and more feature rich
