### ISSUE TITLE
🐛 BUG: Password viewer icon issue 

### ISSUE THREAD

**Issue by sujadud** [dailydotdev/daily#1254]
### What went wrong? 🤔

While signing up on your site, I encountered an issue with the signup modal. When typing my password, two show password buttons appeared. I believe this needs to be fixed, kindly check it out.

![image](https://github.com/dailydotdev/daily/assets/43004887/70fb69a6-0254-4738-aa7f-6b98abd46494)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @sujadud,

We will look into it. Thanks for the report

**Comment by sujadud** [comment]
You are most welcome 😊

**Comment by nensidosari** [comment]
Hi @sujadud, thank you for reporting this issue. 

This seems to be an issue only on edge/internet explorer in specific versions (if that's the browser you're using) and we weren't able to replicate, but we have just pushed a possible fix for it. 

Do try again and see if it still happens to you. Hope it is resolved.

**Comment by sujadud** [comment]
Alhamdulillah, I can no longer see the problem. 
Thanks to Daily.dev Team for quickly providing a solution in my report. You are doing excellent work. Happy coding. 😊
