### ISSUE TITLE
🐛 BUG: Selecting user link from posts comments breaks routing on the users profile page

### ISSUE THREAD

**Issue by DLParkin** [dailydotdev/daily#1255]
### What went wrong? 🤔

Had a look but could not see an issue for it

Seems to affect all profiles selected from a modal posts comments for me using chrome

Clicked a post to view details (any but example given)
https://app.daily.dev/posts/squads-2-0-is-here--5jvjk9pbr

Scrolled to comments and selected the first comment user name to view profile 
![image](https://github.com/dailydotdev/daily/assets/22126206/547fcc1c-57f1-42d5-ac79-7eb4584f5d12)

When viewing the profile:
Could not longer click anything and had to reload

Example shows route updated but page has not 
![image](https://github.com/dailydotdev/daily/assets/22126206/7bb37fe2-6491-45a4-ba38-65db1f72fec2)

 

### Expected Behavior

Should be able to route to the expected page

### Steps to Reproduce Issue

```bash
Already provided
```

### Solution Proposed

I would take a gander but have to take the dog for a walk

### Screenshots

```bash
Already provided
```

### Environment

Chrome

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

Browser? 

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@DLParkin Thanks so much for raising this issue.
My colleague @sshanzel just pushed a urgent fix for this.

Could you verify it's back to working again?
(Closing for now, please feel free to open a new one if anything pops up)

**Comment by DLParkin** [comment]
@rebelchris it is working as expected now.
