### ISSUE TITLE
🐛 BUG: Member Squad welcome is 404

### ISSUE THREAD

**Issue by codercatdev** [dailydotdev/daily#1257]
### What went wrong? 🤔

<img width="705" alt="image" src="https://github.com/dailydotdev/daily/assets/3102249/033afaf9-88c9-4cc6-9975-2bd7091b3e1b">
This link is always 404

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @codercatdev this happens if you delete the squads welcome posts.
Is it something you want us to restore for you?

**Comment by codercatdev** [comment]
@rebelchris that would be great, thanks!

**Comment by rebelchris** [comment]
Hi @codercatdev,

I've returned the welcome post for you.
That should make it work again.

Thanks for reaching out, please feel free to open new tickets for other issues you might encounter.
