### ISSUE TITLE
🐛 BUG:  Most upvoted feed on source page doesn't include all posts

### ISSUE THREAD

**Issue by bennycode** [dailydotdev/daily#1259]
### What went wrong? 🤔

I visited this website and it shows a post with 17 votes as "most upvoted": https://app.daily.dev/sources/typescripttv

But there is a post with the title "Use TypeScript generators for cleaner programming" that has 134 (much higher) upvotes.

### Expected Behavior

The post "Use TypeScript generators for cleaner programming" being on top

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/sources/typescripttv'
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @bennycode,

The most upvoted feed on the source page checks the most upvoted posts in the last week.
We need to fix either the description or the criteria. Thanks for raising it! 🙏
