### ISSUE TITLE
🐛 BUG: unable to leave squad on android

### ISSUE THREAD

**Issue by altlv** [dailydotdev/daily#1260]
### What went wrong? 🤔

Observed that the 3 dots on squad page doesn't open the menu, thus doesn't provide means to leave a squad i wrongly joined.
I was able to do this in the web mode.

Unfortunately i have no mobile logs at hand for this.

3 dots button highlights, but menu does not open

### Expected Behavior

Menu under 3 dots open and allows to interact with the said menu

### Steps to Reproduce Issue

```bash
1. Go to 'Squads' 
2. Click on 'Your Squad X > option'
3. Open menu  '3 vertical dots' on the squad landing page
4. Observe
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

android app

### OS

Android

### Version of daily.dev

10

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @altlv,

Thanks for reporting, this seems to be a bug on mobile indeed.
We'll look into it and will try to solve it asap.

**Comment by ilasw** [comment]
Hi @altlv,
Thanks for opening the issue!

I've recently pushed a fix, and it should work as expected now. Let us know if any other issues come up!

**Comment by altlv** [comment]
Aye Sir. It works on production ^^

Menu opens now
![Screenshot_2024-07-08-21-40-57-720_com android chrome](https://github.com/dailydotdev/daily/assets/30120302/d2b5fcfc-3785-4423-a437-95923c8f47cb)
