### ISSUE TITLE
🐛 BUG: Firefox extensions always shows Your feed filters are too specific.

### ISSUE THREAD

**Issue by jaoord** [dailydotdev/daily#1262]
### What went wrong? 🤔

Your feed filters are too specific.

doesn't matter if i have one filter or 10

### Expected Behavior

show me the feed

### Steps to Reproduce Issue

```bash
install extension in firefox
go to new page tab
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

windows 11, firefox 127.0.2

### Browsers

Firefox

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @jaoord,

Can you please share your extension version?

**Comment by jaoord** [comment]
3.15.5

**Comment by jaoord** [comment]
I do see this in console though:

![image](https://github.com/dailydotdev/daily/assets/6464609/6515889e-730f-4c5e-96a2-1c33c2b659f6)

**Comment by rebelchris** [comment]
Hi @jaoord,

Unfortunately our Firefox extension got reverted to a old, unsupported version. 
For the mean time please use our web app instead: https://app.daily.dev/

We are urgently trying to resolve this with FF to get our version back up and running.

**Comment by jaoord** [comment]
Grand, let's hope they can sort it out. Thanks

**Comment by tejas-polakam** [comment]
Hi, I am still recieving this issue, any timeline for a update or fix?

**Comment by idoshamun** [comment]
Hi @tejas-polakam,

We submitted a version for review, and it's been waiting for quite a long time.
Hopefully FF team will review it soon
