### ISSUE TITLE
🐛 BUG: Comments missing 

### ISSUE THREAD

**Issue by closetgeekshow** [dailydotdev/daily#1264]
### What went wrong? 🤔

I seem to recall that yesterday there was a very active comment thread inside https://app.daily.dev/posts/Ko6RLKpLW but now there's only one comment. What gives? 

### Expected Behavior

I'm expecting to see about 10 comments on here, there is now only one. 

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @closetgeekshow,

I'm not sure how to proceed really. Do you have any such examples?

**Comment by rebelchris** [comment]
Closing as no reproducible steps are given.
