### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by Benjv380** [dailydotdev/daily#1265]
### What went wrong? 🤔

Al tratar de ingresar a algún apartado ejemplo algún grupo o comunidad da error "Error de aplicación: se ha producido una excepción del lado del cliente (consulte la consola del navegador para obtener más información) ".

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Android

### Browsers

Other

### OS

Android

### Version of daily.dev

10 desde playstore

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @Benjv380 , thank you for reporting the issue. 

Could you please give us a bit more information about the error? 🙏 
Any videos of the process with the error included, screenshot of your console errors, step by step actions so we can reproduce the issue and try to figure out what the error is.

Thank you!

**Comment by rebelchris** [comment]
Closing as no follow up is given
