### ISSUE TITLE
🐛 BUG: Shortcuts or most visited sites hidden at breakpoints

### ISSUE THREAD

**Issue by CuriousCoder00** [dailydotdev/daily#1266]
### What went wrong? 🤔

In full screen the shortcuts are visible but as the window size gets reduced the shortcuts are not completely visible.
Screenshot of shortcuts in full screen:
![image](https://github.com/dailydotdev/daily/assets/103230903/4e323a68-cafe-4de0-b9c9-544efabd8d91)
Screenshot of Shortcuts after reducing window/screen size
![image](https://github.com/dailydotdev/daily/assets/103230903/07c54f38-eac7-4cd3-8549-ae8e649c5482)
But after certain breakpoint the shortcuts are completely hidden
 
this is the screenshot where more option available but it takes to modify the shortcuts instead of making it visible
![image](https://github.com/dailydotdev/daily/assets/103230903/574f3c02-bdba-4ac9-8343-5f272c222ec0)
![image](https://github.com/dailydotdev/daily/assets/103230903/fc5ab20c-52a5-4692-8a04-ddb39fb852f0)

### Expected Behavior

all shortcuts should be visible on all screen sizes.. 
and like there's option available for modifying shortcuts.. there can be a other option to show hidden shortcuts or scrollbar..

### Steps to Reproduce Issue

```bash
1. Go to 'home page' or open new tab with daily.dev extension enabled
2. Observe shortcuts
3. Reduce window/screen size
4. See the error
```

### Solution Proposed

Instead of making it hidden.. optimize with different sizes and breakpoints
or can add scrollbar for shortcuts...

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

3.33.1

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @CuriousCoder00 ,

We show 8 shortcuts on desktop screens, and only 4 for that version on smaller screens (due to it only being available on extension)
The 3 dots menu is to open the settings, but it had a bug which has been fixed in version 3.33.2

Hope this answers you question, feel free to respond if anything unclear still.

**Comment by name-andy46** [comment]
I am not able to see the toggle to enable shortcuts in the Preferences section of the Customize modal. This is shown in the documentation.
![daily_dev_bug](https://github.com/user-attachments/assets/282c5483-e0bf-402f-acda-0ac0dc53429f)

**Comment by rebelchris** [comment]
@name-andy46 Can you make sure you are on our browser extension?
Shortcuts are not available in the webapp, therefor we don't show the option there.

**Comment by CuriousCoder00** [comment]
@rebelchris Thanks for providing detailed information.
I guess i should close this issue now..!!
