### ISSUE TITLE
🐛 BUG: Thumbnail showing random image in my post after post creation

### ISSUE THREAD

**Issue by vijaydeepak-tt** [dailydotdev/daily#1267]
### What went wrong? 🤔

I have pasted a medium blog link in my Squad, and posted it, initially it showed the correct thumbnail pulled from medium, but after sometime it changes to random image as thumbnail for one post, for another post it showing a image from that blog

### Steps to Reproduce Issue

```bash
1. Go to ['...'](https://app.daily.dev/squads/tarzzotech)
2. Check the Building micro frontend application with Next.js title blog
3. Check that posts thumbnail in app.dev squad
4. Then click the view post and check the actual blog, and compare both the thumbnails.
5. Both are different.
6. you will be seeing the same for some other blogs as well
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
Expected image is a thumbnail in the blog https://medium.com/stackademic/building-a-micro-frontend-application-with-next-js-14-2-and-tailwind-css-part-iii-a0217f2d3d61
```

### Environment

mac, chrome web browser, browser extension

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

v0.5.0

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @vijaydeepak-tt ,

Thanks for reporting, we have some image checks in our crawling system that determines which image has the best quality.
I've asked my colleague to look into why this one was picked and will revert back once I know more.

**Comment by rebelchris** [comment]
@vijaydeepak-tt We re-scraped this article and its showing the right one now.

Closing this ticket, but don't hesitate to open new ones if anything else pops up 🙏
