### ISSUE TITLE
🐛 BUG: I can't add shortcuts to sites I visit frequently

### ISSUE THREAD

**Issue by ricardo-cavalheiro** [dailydotdev/daily#1268]
### What went wrong? 🤔

After adding just one site as a shortcut, I can't add any other sites. Nothing happens when I click on the button that is supposed to open a modal to register the site. As if the button had no interactivity.

### Expected Behavior

The button that opens the modal for registering a new shortcut should work.

### Steps to Reproduce Issue

```bash
1. Install the extension and select the interests
3. Add the first custom shortcut
4. Click on the button to the right of the custom shortcut you added earlier. It shouldn't be working.
```

### Screenshots

```bash
![image](https://github.com/dailydotdev/daily/assets/81830062/e38f79fc-5389-4c45-9aac-d7d5d5a3d5f0)
```

### Environment

Windows 11 23H2, Microsoft Edge 126.0.2592.87 (Official build) (64-bit)

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

3.33.1

### Additional Context

The following error is shown in the browser console: "It seems that the menu you are trying to display is not renderer or you have a menu id mismatch. You used the menu id: shortcut-context"

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @ricardo-cavalheiro thanks for reporting.

We submitted the fix in version 3.33.2 please keep an eye out for that release and thanks for logging the issue.
