### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by momzzze** [dailydotdev/daily#1271]
### What went wrong? 🤔

Hello everyone I really like the new feature to set up my urls however I wanted to add another one and the button which is on the screenshot did not respond
![Screenshot 2024-07-12 144219](https://github.com/user-attachments/assets/4b9e3c60-a293-4a39-afdb-0213d016cff5)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @momzzze thanks for reporting.

We submitted the fix in version 3.33.2 please keep an eye out for that release and thanks for logging the issue.
