### ISSUE TITLE
🧩 FEATURE REQUEST:  Don't add videos

### ISSUE THREAD

**Issue by JCKodel** [dailydotdev/daily#1272]
### Concise Description

If I wanted to watch videos, I would go to YouTube

### Description

Now we have videos? Really?

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @JCKodel,

Adding video support was one of our most requested features. With that said, we understand it's not for everyone. You can head to your feed settings and remove them. Enjoy!
