### ISSUE TITLE
🐛 BUG: Add Shortcut button is not working

### ISSUE THREAD

**Issue by NNPhaniCharan** [dailydotdev/daily#1273]
### What went wrong? 🤔

I was trying to add shortcut. I clicked on button with 3 dots. it is not responsive.

### Expected Behavior

On clicking i was expecting a popup box to add new shortcut.

### Steps to Reproduce Issue

```bash
1. Click on Add Shortcut
2. Open Console
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Chrome 126.0.6478.127

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @NNPhaniCharan 

We submitted the fix in version 3.33.2 please keep an eye out for that release and thanks for logging the issue.

Could you ensure you are on this version and it that solves the issue for you?
