### ISSUE TITLE
🐛 BUG: "Most visited links" panel where all the shortcuts to my most frequent sites disappeared.

### ISSUE THREAD

**Issue by Noctumsempra** [dailydotdev/daily#1274]
### What went wrong? 🤔

"Most visited links" panel where all the shortcuts to the "most frequent sites" that you could configure disappeared from the screen, it's not in the settings either. Where did this go?

![image](https://github.com/user-attachments/assets/eac0d83b-bf92-4ebe-8e2e-222a5d54e790)

![image](https://github.com/user-attachments/assets/751f94c3-43b7-4215-a59f-e335081339a2)

### Expected Behavior

I expect that freq links panel to be PRESENT as it used to be.

### Steps to Reproduce Issue

```bash
1. Open a new tab o go to api.daily.dev

only cards, NO freq links
```

### Solution Proposed

I don't know how to solve this, I don't have any access to the code or anything. Just try to restore it please, otherwise this extension stops being useflul to me and will have to get rid of it. Can't live without the frequent links. Don't fuck with those things. We people use that shit a lot. Thanks

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 10, MS Edge

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @Noctumsempra 

Thanks for reaching out, the option to enable it again is under the "Customize" settings.

See the [docs](https://docs.daily.dev/docs/customize-your-feed/preferences) for reference.

You can find it in the sidebar 🙏

Please let me know if you can't find to solve it, or have other issues we can help with.

**Comment by Noctumsempra** [comment]
Could solve it, I don't know why it was disabled. Never touched such option... I revisited settings earlier but couldn't see that one before, my bad. Guess I got blind.

Thanks.
