### ISSUE TITLE
🐛 BUG or QoL upgrade : Daily.dev browser extension: Replace the page you see when opening a new tab.

### ISSUE THREAD

**Issue by P1r4t30fTh3Und3rW0rld** [dailydotdev/daily#1277]
### What went wrong? 🤔

While the Daily.dev browser extension is active. it automatically Replaces the page you see when opening a new tab. To disable it we can only stop the extension from the extension management settings, and will have to turn it back on to use it again.
which is rather inconvenient.

and even after quitting and restarting the browser, we still get the same issue.

screenshot: Page shown after restarting the browser. 
![startup](https://github.com/user-attachments/assets/ccd0c0f5-c35b-425d-a88f-2fe946a9c99b)

Screen Recording: 

https://github.com/user-attachments/assets/a93d986d-a814-4f33-85ad-cbfe97de1a96

Btw, I love Daily.dev :)

### Steps to Reproduce Issue

```bash
Step1: install the Daily.dev web extension from Daily.dev website or Windows web store.
Step2: click on Open.
Step3: register using your email.
Step4: Open a new tab in your browser pressing "ctrl+N" on your keyboard or clicking on the "+" icon on the tabs bar. 


refer to the screen recording attached in this report.
```

### Solution Proposed

modify the extension's permissions: 
![permissions](https://github.com/user-attachments/assets/62bdf146-0caa-4675-b4e2-b191748ebdae)

### Environment

Windows 11 Home

### Browsers

Brave

### OS

Windows

### Version of daily.dev

3.33.2

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @P1r4t30fTh3Und3rW0rld,

daily.dev is a new tab browser extension. This means that it is opened on every new tab like you presented.
If you don't like this behavior I suggest using our webapp at https://app.daily.dev.
Thanks for reaching out :)
