### ISSUE TITLE
🐛 BUG: Shortcut wont be edited

### ISSUE THREAD

**Issue by NohaAteff** [dailydotdev/daily#1279]
### What went wrong? 🤔

So i was added a few shortcuts to the new tab, the last one i added was not the right url so it wont open the intended website but when i try to edit it or manage the shortcuts the intended button doesnot work, it doesn't do anything like i keep pressing it but nothing happends, the last button the one with the three dots
![image](https://github.com/user-attachments/assets/8a952672-c481-4942-a9ef-1bc5c60f7e0f)

### Expected Behavior

i expected a menu to let me manage my short cuts

### Steps to Reproduce Issue

```bash
1. Go to 'new tab'
2. Click on 'three dots button for managing shortcuts'
3. See the error 'nothing happends'
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @NohaAteff  thanks for reporting.

We submitted the fix in version 3.33.2 please keep an eye out for that release and thanks for logging the issue.
Could you verify which version you are on?
