### ISSUE TITLE
🐛 BUG: Cannot post in my Public Squad

### ISSUE THREAD

**Issue by mark-at-pieces** [dailydotdev/daily#1280]
### What went wrong? 🤔

no option to post in my public squad anymore. I'm the admin of the squad, but the option to post in my sqaud is not gone.

### Expected Behavior

when i click new post, I expect that this defualt to a post in my squad. I hit the drop down and there is no option.

### Steps to Reproduce Issue

```bash
** Ensure you are an admin of the squad **
1. click on a squad you own
2. click the new post button
3. click the drop down to select the squad you want to post in
** notice the option for the squad you were in is no longer there
```

### Environment

sonoma 14.4.1

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

NA

### Additional Context

```bash
NA
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @mark-at-pieces, 

Thank you for reporting this issue. We'll try to fix as soon as possible and get back to you.

**Comment by nensidosari** [comment]
Thank you for reporting, we will take a look at this as well.

**Comment by rebelchris** [comment]
@mark-at-pieces Thanks for reporting, we fixed the issue and it should work as intended again 🙏

**Comment by nensidosari** [comment]
@mark-at-pieces as for the issue mentioned below, could you please check again if that is resolved as well by the above fix? We can't seem to replicate at the moment.

> Also noticed that if I include an image in the post and post it (to a private space) the image disappears, and i have to edit and re-include the image i want to include in my post.

If it ends up to still be an issue for you, please open a separate issue for it 🙏

**Comment by mark-at-pieces** [comment]
> @mark-at-pieces as for the issue mentioned below, could you please check again if that is resolved as well by the above fix? We can't seem to replicate at the moment.
> 
> > Also noticed that if I include an image in the post and post it (to a private space) the image disappears, and i have to edit and re-include the image i want to include in my post.
> 
> If it ends up to still be an issue for you, please open a separate issue for it 🙏

this resolved both it appears 🤷 thanks for the help!
