### ISSUE TITLE
🐛 BUG:  Pause button is not displayed.

### ISSUE THREAD

**Issue by koyablue** [dailydotdev/daily#1281]
### What went wrong? 🤔

The pause button is not displayed in the side nav.  

<img width="1382" alt="スクリーンショット 2024-07-16 午後12 22 27" src="https://github.com/user-attachments/assets/922aec8c-1b02-4448-8d21-6045abe4f44f">

### Steps to Reproduce Issue

```bash
1. Open a new tab
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @koyablue,

Thank you for reporting this issue. 

We've recently changed the placement of the pause button from the sidebar to the profile menu, so if you click on your profile icon, you should be able to find the pause option in the menu there. 

Hope this helps!
