### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by Vignesh-Jothi** [dailydotdev/daily#1282]
### What went wrong? 🤔

When I try to click on the link give in the post it redirected to daily.dev page.

### Expected Behavior

when I click the link, it has to go that link but instead of it going like example: daliy.dev/thatwebsite

### Steps to Reproduce Issue

```bash
1. Go to any post
2. Click on link given in the post description.
4. See the error. (Page not found)
```

### Screenshots

![Screenshot 2024-07-16 173533](https://github.com/user-attachments/assets/dc109f2c-d46e-4823-8528-ff93d52c7fc1)

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Vignesh-Jothi,

I'm not sure I understand the issue. Can you elaborate please?

**Comment by Vignesh-Jothi** [comment]
When I click the link in the post, it redirects me to the daily.dev page. This redirection issue might be due to an incorrect or misconfigured link. Could you please check and update the link to ensure it directs to the intended page?

**Comment by idoshamun** [comment]
I'm still not sure what you refer to. Can you please send an example?

**Comment by Vignesh-Jothi** [comment]
Sorry, this is my fault, "When I click the link in the post, it redirects me to the daily.dev page. It seems that the owner of the post did not provide the correct link."

**Comment by rebelchris** [comment]
@Vignesh-Jothi I do indeed think the owner posted a link without `http://` in front.
Do you mind sharing the post here that you saw this on?

Would love to see if we can somehow detect this early on.

**Comment by Vignesh-Jothi** [comment]
@rebelchris I think this post [feed](https://app.daily.dev/posts/r67clGWUF)
