### ISSUE TITLE
🐛 BUG:  Search option is not working

### ISSUE THREAD

**Issue by thushar-p** [dailydotdev/daily#1284]
### What went wrong? 🤔

I wanted to search for a topic and couldn't see the results.

### Expected Behavior

It should have responded with the result. But it was an empty page

### Steps to Reproduce Issue

```bash
1. Go to ' search tab on android app '
2. Click on ' search bar'
3. Search for any thing and click on any recommended topics. The results are not rendered.
```

### Solution Proposed

I have not debugged or did any kind of research.

### Screenshots

```bash
.
```

### Environment

Android smartphone

### Browsers

Other

### OS

Android

### Version of daily.dev

13

### Additional Context

```bash
.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Thanks for reporting!
Well look into it urgently

**Comment by rebelchris** [comment]
@thushar-p Thanks again for reporting.
We deployed a fix for this issue and it should work as intended now 🙏

**Comment by thushar-p** [comment]
Great @rebelchris. Thanks for the quick fix 👍
