### ISSUE TITLE
🐛 BUG: Streak keeps resetting

### ISSUE THREAD

**Issue by franz-see** [dailydotdev/daily#1287]
### What went wrong? 🤔

I use chrome extension. That means daily.dev opens everytime I open a new tab. I also click on articles at least once a day

### Expected Behavior

Streak not resetting

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

Streak not resetting

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Sonoma 14.5 + Chrome + Chrome Extension

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

No idea

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @franz-see, 

Thank you for reporting the issue! 

At the moment we weren't able to reproduce this, but it might be working as intended if you just click on the post and not actually read/watch the original content.

You can read more here about what qualifies as a reading day https://docs.daily.dev/docs/your-profile/reading-streak#what-counts-as-a-reading-day. If you comply with that and the issue still persists, please reach out again with a video or your daily dev handle/id so we can take a further look into your account in specific.
