### ISSUE TITLE
¹🐛 BUG: Opening the app showed a translucent overlay.

### ISSUE THREAD

**Issue by XDreamist** [dailydotdev/daily#1288]
### What went wrong? 🤔

Whenever I tried to open the mobile app. It just showed a translucent overlay instead of going directly to the app. The issue happened for 4 5 days. Because of that, I lost my streaks. It showed an overlay and nothing was responsive when I tried to click it

### Expected Behavior

It showed the app is opening but no inputs were taken or it was simply not responsive.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

Can you give my lost streaks backs :)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Samsung Galaxy F22

### Browsers

Chrome

### OS

Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@XDreamist Could you perhaps provide us with more details as in a screenshot or video of what's happening.
It makes it very hard to debug if we can't reproduce/see the issue at hand.

**Comment by XDreamist** [comment]
@rebelchris I can't give you the exact screenshot as the bug is fixed right now. Well before the logo shows up like this.
![Screenshot_20240720_180812_dailydev](https://github.com/user-attachments/assets/b676cd10-67ca-4199-b94b-535af275d85e)
The app goes to the browser and displays as an overlay right. But when the bug happened, the app was not showing the logo loading and there was a translucent overlay which doesn't let me interact with the screen. Hope this helps. If you're still finding this difficult to decode the bug. It is ok as the bug is fixed now.

**Comment by XDreamist** [comment]
@rebelchris this was the issue. Now the same issue is showing up again.

Uploading Bug_Daily.Dev.mp4…
