### ISSUE TITLE
🐛 BUG: Customize the Welcome post button doesn't work because the post is removed

### ISSUE THREAD

**Issue by plutov** [dailydotdev/daily#1292]
### What went wrong? 🤔

Customize the Welcome post button doesn't work because the post is removed. However I can't find a way to re-create the Welcome post.

### Expected Behavior

Clicking on this button should create a Welcome post if not found.

<img width="392" alt="Screenshot 2024-07-19 at 13 17 43" src="https://github.com/user-attachments/assets/9d8966e0-09f3-463f-98bc-c8b1387ad37d">

### Steps to Reproduce Issue

```bash
1. Go toy our Squad
2. Click on check mark
3. Step can't be completed
```

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @plutov unfortunately we don't support a way to return the welcome posts once removed.
If you want to I can put it back manually for you, in that case please do respond with your squad URL.

**Comment by rebelchris** [comment]
Closing as no reaction, please do respond back if you wish to have this solved.
