### ISSUE TITLE
🐛 BUG: cant open daily dev with my internet

### ISSUE THREAD

**Issue by minutak** [dailydotdev/daily#1294]
### What went wrong? 🤔

I cant open daily dev web version on firefox with my internet. I tested that its the internet 100%. When a switched to data on my mobile it worked but not with my internet either on mobile or pc.

### Expected Behavior

It should just load into the daily dev web

### Steps to Reproduce Issue

```bash
1. i go on daily dev
2. i click on web version
3. it wont load
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

### OS

Windows, Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @minutak ,

Thanks for reaching out.
Could you please verify which version of daily.dev extension you have on Firefox.

Firefox recently downgraded us to a 2 year old version, so if you are on 3.15.5 it won't work.
If this is the case please use our webapp so long: app.daily.dev

**Comment by minutak** [comment]
Hello, well i am using the web version. The problem is that either the app.daily.dev or api.daily.dev wont load, i send a screenshot what it says. I tried it on many different browser, but they didnt work either. Then i tried it on android too and it didnt work with my wifi only when i turned on my data.

![image](https://github.com/user-attachments/assets/bb466c8b-7cd1-4a23-b713-c27b781df62e)

**Comment by rebelchris** [comment]
Hi @minutak,

It's not a generic issue on our side, are you still experiencing this?
From where/vpn are you visiting from?

**Comment by minutak** [comment]
@rebelchris I still the same problem. I tried it on my mobile with mobile data and it worked, but when i switched on my wifi, then it didnt work. i didnt tried VPN yet, but i will try it. I am visiting from Czech Republic.

**Comment by minutak** [comment]
> Hi @minutak,
> 
> It's not a generic issue on our side, are you still experiencing this? From where/vpn are you visiting from?

Well now i tried to load the site and it worked. I recently switched on Brave browser, but i had the same problem. Now i tried it and it works. Idk if you made some update recently or something but i jsut want to let you know
