### ISSUE TITLE
🐛 BUG: All shortcuts are erased when adding "Most Visited Sites"

### ISSUE THREAD

**Issue by Boris-Picard** [dailydotdev/daily#1302]
### What went wrong? 🤔

When adding "Most Visited Sites," all previous shortcuts are erased upon switching.

### Expected Behavior

Expected: Previous shortcuts should be kept to allow switching between personal shortcuts and most visited sites.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Boris-Picard,

Thanks for reporting but it's not a bug, it's a feature 😉 
We'll log it of course.
