### ISSUE TITLE
Application error on client side - Realme Narzo

### ISSUE THREAD

**Issue by tsindel** [dailydotdev/daily#1303]
### What went wrong? 🤔

Few seconds after opening the app it crashes.
![Screenshot_2024-07-25-08-07-58-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/32cfa797-72b3-41fa-b3c3-5261cb2c974b)

### Expected Behavior

The app should continue working

### Steps to Reproduce Issue

```bash
No steps. Just opening the app.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Realme Narzo 30 5g - RMX3242

### OS

Android

### Version of daily.dev

Latest

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @tsindel,

Thanks for the report. We'll look into it in the meantime can you try our webapp https://app.daily.dev and let me know if it works

**Comment by tsindel** [comment]
Hello, the shared webapp works without issues!

**Comment by tsindel** [comment]
At first, the app worked well, but when I tried to unblock "Community Picks" from "Blocked" category, the app crashed again with the same error message.

**Comment by nensidosari** [comment]
@tsindel can you still replicate this behaviour? 

So far we're not able to replicate, but in order to understand more would you be able to take a video for us, or any logs that show more about the errors? 🙏

**Comment by rebelchris** [comment]
Hi @tsindel,

Tried to replicate today with the steps provider but wasn't able to get this.
Any chance you could perhaps check the console logs for any messages or as Nensi suggested a video for us?

**Comment by tsindel** [comment]
Hi,

sadly there was no way for me to get the console messages. Also there was
no unique error path, as it seems. The error seemed to trigger at random
times.

S pozdravem / Regards
Tomáš Šindel

**Comment by RatulMaharaj** [comment]
I’m having a similar issue as well in the PWA on iOS. 

Here’s what I found in the logs:

```sh
LOGOneSignal: SDK is not compatible with this browser. To support iOS please install as a Web App. See the OneSignal guide https://documentation.onesignal.com/docs/safari-web-push-for-ios
ERRORTypeError: null is not an object (evaluating 'n.author.name')
ERRORTypeError: null is not an object (evaluating 'n.author.name')
ERRORA client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

This makes the app completely unusable for me.

**Comment by rebelchris** [comment]
@RatulMaharaj thanks a lot for those logs that will help a lot.
Well investigate and come back to you asap.

**Comment by idoshamun** [comment]
Hi @RatulMaharaj,

Does it happen in a specific post or squad only? If so, please share the link

**Comment by RatulMaharaj** [comment]
> Hi @RatulMaharaj,
> 
> 
> 
> Does it happen in a specific post or squad only? If so, please share the link

Hi @idoshamun I'm assuming it is, but I'm not able to see which one is causing the issue as I can't get to the home page / main feed at all. 

Here's a screen recording:

https://github.com/user-attachments/assets/42b83305-b7b7-4184-a0c0-00a7e2ff3681

**Comment by idoshamun** [comment]
@RatulMaharaj can you check now please?

**Comment by RatulMaharaj** [comment]
It seems to be resolved for me. Thanks!

**Comment by idoshamun** [comment]
Awesome!
