### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by Jobox3000** [dailydotdev/daily#1306]
### What went wrong? 🤔

Sapendo che utilizzo l applicativo dall' Italia, riscontro problemi nella traduzione automatica di Google, e l alert che mistra per tradurre, mandando in errore l app.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Jobox3000,

Would you mind explaining in English please?
