### ISSUE TITLE
🐛 BUG: Action on posts in a feed from a squad where you dont have access

### ISSUE THREAD

**Issue by fsg-docux** [dailydotdev/daily#1310]
### What went wrong? 🤔

If admin removes your access from the squad. 

You can still see the posts from that squad on your feed.

But, if you try to comment or like it nothing happens.

### Expected Behavior

Option 1: Either the post should not be visible from that squad.

Option 2: If the Post is visible. All the actions related to the posts should be disabled like Upvote, Comment etc.

### Steps to Reproduce Issue

```bash
1. Join any squad.
2. Ask admin to remove you from the squad.
3. Check the feed for posts from that squad.
4. Upvote or Comment on that post.
```

### Solution Proposed

Option 1: Either the post should not be visible from that squad.

Option 2: If the Post is visible. All the actions related to the posts should be disabled like Upvote, Comment etc.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows, iOS

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @fsg-docux,

Are you referring to a public or private squad? Can you elaborate please?
