### ISSUE TITLE
🐛 BUG: Can not feed data

### ISSUE THREAD

**Issue by lnpquang** [dailydotdev/daily#1315]
### What went wrong? 🤔

Can not feed data in "My feed"
![Screenshot 2024-08-01 103755](https://github.com/user-attachments/assets/ce4c9d2c-b682-4a5d-a30e-2ebc4f8dfa07)

I tried to clear the cache, log out an login again but no luck.

### Steps to Reproduce Issue

```bash
1. Go to '+ New Feed', search for a tag, select the tag, and don't enter the feed name 
2. Click on the 'Save' button
3. Go back to My feed
4. Blank screen, no data at all
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Win 11 Pro

### Browsers

Chrome, Brave

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
It's fixed now
