### ISSUE TITLE
🧩 FEATURE REQUEST:  Group notifications by type and send allow custumization when the push notification / email should be send

### ISSUE THREAD

**Issue by KristianMariyanov** [dailydotdev/daily#1316]
### Concise Description

Group notifications by type and allow customization when they are send. so the notification page and push notification are less overwhelming

### Description

For people that has public squads the amount of push notifications/emails for newly joined members could be overwhelming.
I want to receive such notifications, but once in an hour, or once in a day. 

Additionally, the notification page lists each of the notifications as a new item. It will be great to group them if you have similar notifications. 

### Solution Proposed

Ideally, I'd be able to tell how often I want to receive notifications/emails for each of type of notification. 

Examples of grouping:

- John Smith and 12 others joined your Squad "Build with LLMs"
- John Smith and 2 others commented on your post...

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by KristianMariyanov** [comment]
Related: https://github.com/dailydotdev/daily/issues/1192

**Comment by idoshamun** [comment]
Hi @KristianMariyanov,

Thanks for the suggestion! In the meantime, can I suggest setting your notification settings per squad?
You can choose per squad what notifications you'd like to receive. This may help you clear the clutter.
