### ISSUE TITLE
🐛 BUG: Opening Chrome in desktop mode also launches the app in desktop mode.

### ISSUE THREAD

**Issue by AndersonCeci** [dailydotdev/daily#1318]
### What went wrong? 🤔

I'm not sure if this is a bug or expected behavior, but when I open Chrome in desktop mode, it also launches the app in desktop mode.

### Expected Behavior

I expected the app to open normally 

### Steps to Reproduce Issue

```bash
1. Go to Chrome or any web app 
2. Click on view as desktop mode
3. Close the chrome and open the app
4. In the application opens on desktop view just like chrome
```

### Browsers

Chrome, Firefox, Safari, Microsoft Edge, Opera, Brave

### OS

iOS, Android

### Version of daily.dev

The Latest Version

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @AndersonCeci,

I'm not sure I understand your issue. daily.dev is a new tab extension, meaning it opens every new tab. Is that what you experience?
