### ISSUE TITLE
🐛 BUG: Extension Removed from the Mozilla Firefox Add-On Store?

### ISSUE THREAD

**Issue by Thomashighbaugh** [dailydotdev/daily#1320]
### What went wrong? 🤔

Didn't see a bug report (didn't look too hard either, sorry if this is a duplicate) but following the link from your site and from DDG both lead to a 404 page that suggests the extension has been removed by the developer? 

Right when I was going to go back to using your platform too... 

Easy fix, just package up an .xpi since you should have all the tooling to sign it already. Just thought I would let you know if you didn't

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Thomashighbaugh,

Unfortunately, after weeks of back and forth with the Firefox review team we decided to temporarily remove the extension from the store. They asked us to change major things to comply with their policy. So until we fix it, you're welcome to use our webapp https://app.daily.dev

**Comment by dlastnoel** [comment]
Is there any roadmap or estimated time for the firefox add on to be back?

**Comment by idoshamun** [comment]
Hi @dlastnoel,

We decided to give it another go. So hopefully, in a few weeks, we can submit a newer version. But it's all up to the FF reviewers I guess

**Comment by dlastnoel** [comment]
@idoshamun  appreciate it man. Cheers foir more!

**Comment by hieulw** [comment]
Unfortunately, I move to Zen browser and lost this great extension, I don't know why in the setting there no way of customize url home for new tab but only in new window.

**Comment by dlastnoel** [comment]
Any updates regarding the adding of dailydev again to firefox?

**Comment by idoshamun** [comment]
Not at the moment, unfortunately, Firefox isn't being cooperative

**Comment by DonDebonair** [comment]
It sucks that Mozilla will not play ball, but this way you're pushing people back to Chrome, which is something that nobody should want to happen. The world is better off without a browser monopoly and as daily.dev is getting more popular (rightly so, because it's a great platform!), this creates yet another reason to keep using Chrome.

2 questions:

1. Is it possible to allow more technical inclined people to sideload the Firefox extension?
2. Can you elaborate what the "fight" with Mozilla is about? I think it would create more understanding within the community on why you choose not to publish a Firefox extension.

**Comment by idoshamun** [comment]
1. Let me think about it, as the primary issue here is keeping everyone updated with the latest version. By the way, have you considered using the web app as your home page on Firefox?
2. The review was long and tiresome, but it comes down to two primary issues currently:
     * Our ads should be opt-in. The Firefox team doesn't accept that we show ads because of the pixel tracking. Obviously this is our revenue stream so we can't do that
     * Analytics events should be opt-in. They are all stored in-house, it's an in-house development and these events are used to improve the feed so the product can't function properly without them. We could understand this behavior if we were talking about third party system but it's not the case.
Needless to say, everything is mentioned in our privacy policy, and any user has to accept it to sign up, but it's not enough for Firefox. So we took the extra step and showed a dedicated modal that says what data we collect, and if someone isn't happy about it, they can uninstall, but that's also not enough. They want the product to function properly if the user decides to opt out. One-sidedly they just removed any version we released for the past two year and set a broken version as the active one which hurt our reputation among new firefox users.

We have an idea how to approach it but it's just not as prioritized as other ideas as we're not sure the firefox team will even accept our idea

**Comment by DonDebonair** [comment]
Thanks for your thoughtful response!

Yes, I have set app.daily.dev as my homepage in FF, but sadly that will only show daily.dev in the first tab when you first open the browser. What I liked about the Chrome extension is that each new tab is also daily.dev.

It is possible to show ads without tracking right? I know that means that advertisers cannot see the effectiveness of their campaigns, but that is a worthwhile tradeoff to letting users keep their privacy.

Have you thought about other forms of monitization? I'd be willing to pay 5 euros a month for daily.dev if I can get a FF extension without ads.

**Comment by idoshamun** [comment]
Unfortunately our primary ads provider requires to implement the pixel tracking. And yes we're considering other forms of monetization. No plans at the moment though. Even if we fix the ads issue we still remain with the algorithmic feed which requires data. Let me see if there's anyway on FF to choose a site that opens every new tab

**Comment by DonDebonair** [comment]
One other thing that I miss without an extension is having the companion available when I read posts, so I can comment and vote directly.

**Comment by idoshamun** [comment]
Makes perfect sense. Thanks!

**Comment by dlastnoel** [comment]
As a FF enthusiast, I would love to see daily.dev rocking on the fox browser again. Thanks for the transparency. Cheers 🍻

**Comment by damienbutt** [comment]
Could you not just publish the extension on GitHub in a release for people to download and install manually until things get sorted with Firefox?

**Comment by idoshamun** [comment]
We will upload the next release and let everyone install it manually

**Comment by DonDebonair** [comment]
That's great! Thank you so much!

**Comment by idoshamun** [comment]
And here it is as promised, a brand new FF version available for all of you ❤️ 
https://drive.google.com/file/d/11lnzw9PQeV6GR_-xv15vjEhXTa0dmJHq/view?usp=sharing

Do let me know if you find some weird issues

**Comment by DonDebonair** [comment]
Thanks @idoshamun for providing this! Sadly, I cannot install the extension. It says the file is corrupt. Here are the steps:

1. Click on Extensions icon
2. Click _Manage extensions_
3. Click on the cogwheel
4. Choose _Install Add-on From File_
5. Choose firefox.xpi you uploaded to Drive
6. Error message that file is corrupt

Firefox version: 132.0.2

OS: MacOS Sequoia 15.0.1

**Comment by idoshamun** [comment]
@DonDebonair I edited my message with instructions 🙏

**Comment by dlastnoel** [comment]
@idoshamun installation went smoothly. Thanks!

**Comment by DonDebonair** [comment]
@idoshamun with your instructions it works like a charm! Happy to have the extension back :)

**Comment by valdoryu** [comment]
I have another suggestion inspired by press websites in the  EU: 
Either accept the ad policy and willingly pay a small monthly fee
It's 100% legal and I think Mozilla couldn't complain about it

**Comment by damienbutt** [comment]
> And here it is as promised, a brand new FF version available for all of you ❤️
> 
> Steps to install:
> 
>     * Download the file: [drive.google.com/file/d/11lnzw9PQeV6GR_-xv15vjEhXTa0dmJHq/view?usp=sharing](https://drive.google.com/file/d/11lnzw9PQeV6GR_-xv15vjEhXTa0dmJHq/view?usp=sharing)
> 
>     * Navigate Firefox to about:debugging#/runtime/this-firefox
> 
>     * Click "Load Temporary Add-on"
> 
>     * Choose the downloaded file
> 
>     * Enjoy!
> 
> 
> Do let me know if you find some weird issues

Is there any way to use this using the "Install Add-On from file", rather than the temporary way. I keep having to re-add it.

**Comment by idoshamun** [comment]
Unfortunately, we got another rejection and we decided to let it go.
We will try to automate our release process and host the artifact here.
I'll update you once that's done.
Thank you all for bearing this with us

**Comment by idoshamun** [comment]
We checked our ability to self-distribute the app, and unfortunately, Firefox still requires you to go through a review in order to sign the extension and let you install it permanently. This means that our hands are tied and we decided to give up on it.
It's a hard decision to make but we have no choice.
I hope to see you all using our [webapp](https://app.daily.dev) or the extension on other browsers.
Thanks a lot!

**Comment by SyedMuhammadAbis** [comment]
Said Loif

**Comment by Benexl** [comment]
just set app.daily.dev as your homepage then use this extension (https://addons.mozilla.org/en-US/firefox/addon/new-tab-homepage/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) to make the homepage load in new tabs

Almost thought that i would have to install chrome again 😂

**Comment by ihatem** [comment]
Just use this extension [https://addons.mozilla.org/firefox/addon/new-tab-override](https://addons.mozilla.org/firefox/addon/new-tab-override) to override the new tab address + the search bar will be focused by default
