### ISSUE TITLE
🐛 BUG: Time period filter not showing up

### ISSUE THREAD

**Issue by 0xtemcha** [dailydotdev/daily#1325]
### What went wrong? 🤔

Time period filter on the most upvoted feed not showing up
<img width="1435" alt="Screenshot 2024-08-06 at 18 03 51" src="https://github.com/user-attachments/assets/d5644460-e697-4869-8028-ae6b8fa915b0">

### Expected Behavior

Filter is visible and working

### Steps to Reproduce Issue

```bash
1. Go to 'Explore'
2. Click on 'By upvotes'
4. No time period filter
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @0xtemcha, 

Thank you for reporting this issue. It seems to be an issue only on extension.

We'll work to fix this and let you know, in the meantime if you want to be able to filter please visit https://app.daily.dev/posts/upvoted, you should be able to see the filter there.

**Comment by rebelchris** [comment]
@0xtemcha this has been resolved and active in our latest versions.

**Comment by 0xtemcha** [comment]
Thanks! 🥳

пн, 4 нояб. 2024 г. в 08:38, Chris Bongers ***@***.***>:
