### ISSUE TITLE
🐛 BUG: Reputation is not updating

### ISSUE THREAD

**Issue by andymouat84** [dailydotdev/daily#1329]
### What went wrong? 🤔

I have received upvotes on my comments on posts however my reputation is still at 10

### Expected Behavior

According to the reputation breakdown I should receive 50 points per upvote, I have received 4 upvotes in total so my reputation should now be 210

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nimrodkra** [comment]
@andymouat84 reputation point will go up only if the person who upvoted has more than 250 reputation points. Reference: https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points

![IMG_1013](https://github.com/user-attachments/assets/d153f4de-3762-430e-aa0d-8a932c20e30b)
