### ISSUE TITLE
🐛 BUG: Can't see the comment

### ISSUE THREAD

**Issue by sachins-zluck** [dailydotdev/daily#1330]
### What went wrong? 🤔

I was roaming around in one of my favourite squad watercooler.  Then I saw this post https://dly.to/kbWTI0CA979 where I can see comment count 1. but i can't see the comment. 
![Screenshot 2024-08-07 at 4 36 34 PM](https://github.com/user-attachments/assets/f06d6cf0-b520-4e2f-bd84-d25a079e416b)

### Expected Behavior

I should be able to see the comment. 

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

MacOS sonoma

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @sachins-zluck,

It's a bug with the counter. There's no comment there.
Thank you for reporting!
