### ISSUE TITLE
🧩 FEATURE REQUEST:  

### ISSUE THREAD

**Issue by IkiosX** [dailydotdev/daily#1331]
### Concise Description

Move-able menu Bar

### Description

Hi the Menu Bar is locked on the side which makes Medium payment window impossible to cancel because the cross section disappear
![df](https://github.com/user-attachments/assets/550361ac-b2bb-484c-a4a4-64cdf659410d)

### Additional Context

```bash
Could include any colour customization too.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sachigoyal** [comment]
Hi @IkiosX 
Could you please provide the steps to reproduce.

**Comment by idoshamun** [comment]
Hi @IkiosX,

Closing as it's a dup of https://github.com/dailydotdev/daily/issues/967. Thanks for reporting
