### ISSUE TITLE
🐛 BUG: Shortcuts Glitching

### ISSUE THREAD

**Issue by madhav-bhartia** [dailydotdev/daily#1335]
### What went wrong? 🤔

I was adding gmail.com as my shortcut. It gave me the error please enter a valid URL (or something like this), but it was glitching, appearing and disappearing really fast.

### Expected Behavior

I expect it to not appear and disappear really fast.

### Steps to Reproduce Issue

```bash
1. Go to 'daily.dev homepage'
2. Click on 'manage shortucts'
3. Add an invalid link.
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 11

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sachigoyal** [comment]
Hello @madhav-bhartia 
I can not see a screenshot of this bug issue would you provide me the link, so i can work for this issue.
Thankyou

**Comment by idoshamun** [comment]
Hi @madhav-bhartia,

Thanks for reporting.
Are you able to reproduce this issue?

**Comment by rebelchris** [comment]
@madhav-bhartia I guess it was similar to this?
https://github.com/dailydotdev/daily/issues/1357

Closing this one, as the other one provides more info.
