### ISSUE TITLE
🐛 BUG: Icons are not loaded properly

### ISSUE THREAD

**Issue by ezazulhaq** [dailydotdev/daily#1340]
### What went wrong? 🤔

Hi Team,

In web browser (Chrome Browser) the icons are not loaded properly.

![image](https://github.com/user-attachments/assets/386a19da-f9c1-40ae-a190-1d5c0b64e9b2)

It will be good to fix this issue as it is not giving a good feel to Web users.

Thanks.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 11

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ezazulhaq,

This seems like an edge case. Does it still happen? If so, where are you located?

**Comment by ezazulhaq** [comment]
> Hi @ezazulhaq,
> 
> This seems like an edge case. Does it still happen? If so, where are you located?
