### ISSUE TITLE
Button to delete account

### ISSUE THREAD

**Issue by kevinnayar** [dailydotdev/daily#1341]
### Concise Description

I cannot find a way to delete my account including all my information

### Description

I cannot find a way to delete my account including all my information. Ideally, this should just be a single click action. 

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nimrodkra** [comment]
Go to profile -> account details -> Security -> Delete account. Here’s a direct link: https://app.daily.dev/account/security

![IMG_1162](https://github.com/user-attachments/assets/33deac87-a29b-4fbb-9724-9ff9f0ed9c21)
