### ISSUE TITLE
🐛 BUG: Companion app is displayed on top off youtube videos in fullscreen

### ISSUE THREAD

**Issue by dustessavdh** [dailydotdev/daily#1354]
### What went wrong? 🤔

I opened a YouTube video from daily.dev and started watching it.
When going into full-screen mode, the companion app remains visible and is displayed on top of the video.

![msedge_jdbxiKHD8Q](https://github.com/user-attachments/assets/b2b90e7e-e6fe-46a6-9aba-33f4191d11f6)

### Expected Behavior

I would expect the companion app to be hidden when watching something in full-screen.

### Steps to Reproduce Issue

```bash
1. Go to https://app.daily.dev/posts/uuPr6wUya
2. Click on Watch 'Video'
3. Click on 'Full-screen'
4. See the companion app is still visible.
```

### Solution Proposed

I would propose that the companion app hides itself in full-screen mode.
This might be relevant for this: <https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide>

### Screenshots

```bash
See `What went wrong?`
```

### Environment

Windows 11, Edge Version 127.0.2651.105

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

 3.33.8

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@dustessavdh Good point, we tried to set it to a max top, but this is a good edge-case to consider.
