### ISSUE TITLE
🐛 BUG: Wrong number of total daily suggestions

### ISSUE THREAD

**Issue by bobbyiliev** [dailydotdev/daily#1356]
### What went wrong? 🤔

As of today I've noticed that the daily suggestions limit is now 5 instead of 3 which is awesome 🎉 

The bug that I noticed is that once you reach the max you get a message saying that you've reached the limit of 3 instead of the actual new limit:

<img width="532" alt="image" src="https://github.com/user-attachments/assets/3aaba77c-4219-483b-b992-f7da5999a92e">

### Expected Behavior

Show the correct limit in the message

### Steps to Reproduce Issue

```bash
1. Submit the maximum number of contributions
1. Get the incorrect message
```

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hey Bobby,

Thanks for reporting, probably a copy i missed somewhere while upgrading to 5.
Will look into it 👍

**Comment by rebelchris** [comment]
@bobbyiliev Merged, should be fixed for webapp already, we'll do a new extension soon as well 🙏
Thanks for reporting.

**Comment by bobbyiliev** [comment]
Awesome! Thanks @rebelchris!
