### ISSUE TITLE
🐛 BUG: Dancing shortcut popup

### ISSUE THREAD

**Issue by SuperSpiderMan** [dailydotdev/daily#1357]
### What went wrong? 🤔

When Adding a shorcut to my browser, as i type in the url the page vibrates up and down as it letts me know what type of link it is expecting. I have a video of the problem:

https://github.com/user-attachments/assets/fe016d88-b4e3-4ffe-90ab-0d51d2b2b610

### Expected Behavior

The popup should stay open or stay closed until i am done typing.

### Steps to Reproduce Issue

```bash
1. Go to 'Daily.dev extension default page'
2. Click on 'Add shortcut to favourite site'
3. Start typing your site URL but exclude "https" .
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

windows 11 

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@SuperSpiderMan Thanks for reporting and the video! (this helps a lot)
I can reproduce it and will log it to be fixed.

**Comment by SuperSpiderMan** [comment]
My absolute pleasure. I am new to daily.dev but want it to succeed! Have an
awesome day further.

**Comment by sshanzel** [comment]
Looking at the recording, it seems like there is an infinite loop happening by clearing the input's hint and then setting a new value at the same time.

**Comment by mrSandeepKr** [comment]
Hi I would like to take take up this bug

**Comment by sshanzel** [comment]
> Hi I would like to take take up this bug

Once our dev environment for local dev has been fixed, I will send a message for you to try 🙌

**Comment by sshanzel** [comment]
Hi @mrSandeepKr, the dev environment should now be up and running 🥳

**Comment by sshanzel** [comment]
The fix for this issue has been merged. Once we publish an extension and get yours updated, you should not see the issue anymore.

All thanks to @Abhi-Bohora for fixing the issue many have reported 🌟 🧙
