### ISSUE TITLE
🐛 BUG: My profile, readme tab, top tags link refers to content that doesn't exists

### ISSUE THREAD

**Issue by ingrqm** [dailydotdev/daily#1358]
### What went wrong? 🤔

Found 404 during exploration on my profile readme tab

### Expected Behavior

I see this content doesn't exist any more so I expect to change section `Top tags by reading days`

### Steps to Reproduce Issue

```bash
1. Go to my profile readme tab
2. Find section `Top tags by reading days`
3. Click [top tags](https://r.daily.dev/weekly-goal)
```

### Environment

MacOS Sonoma 14.6.1, Arc Based on Chromium version 127.0.6533.120 (Offical version) (arm64)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ingrqm,

We'll look into it. Thanks for reporting!
