### ISSUE TITLE
Todo list or checkboxes

### ISSUE THREAD

**Issue by AhmedTakeshy** [dailydotdev/daily#1361]
### What went wrong? 🤔

Some of the todo list or checkboxes have issue with the phone size and that's leading to a weird behavior which is the popup keeps moving up and down

### Expected Behavior

That it opens normally without doing that weird behavior

### Steps to Reproduce Issue

```bash
1. Go to any squad
2. Click on todo list that exist beside squad 's name
3. At that moment you should encounter the issue
```

### Screenshots

```bash
```

### Environment

Android version 9, daily dev mobile application

### Version of daily.dev

15

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by AhmedTakeshy** [comment]
Here is the video for screen record that shows the issue I encountered 
https://github.com/user-attachments/assets/9cf7fb2b-f62b-417d-9c93-32a592bd7ea4

**Comment by nensidosari** [comment]
Hi @AhmedTakeshy, 

Thank you for reporting the issue, we'll try our best to fix this soon.

**Comment by rebelchris** [comment]
@AhmedTakeshy We did a small overhaul on the fields recently it looks fixed on my side.
Could you please verify it's sorted?

Feel free to re-open if not the case.
