### ISSUE TITLE
🐛 BUG: Android app not working with Opera

### ISSUE THREAD

**Issue by negrimmer** [dailydotdev/daily#1364]
### What went wrong? 🤔

When installed from the Play Store, if you do not have Chrome installed/enabled, the daily.dev app is just a web shortcut and will open app.daily.dev in your defaulted browser, in my case Opera.

### Expected Behavior

The app should open regardless of the default browser just piggy backing off it, especially with Opera also being a Chromium browser.

### Steps to Reproduce Issue

```bash
1) Go to 'Play Store'
2) Download 'daily.dev'
3) Uninstall/Disable Chrome
4) Make sure default browser is set to Opera (not GX)
5) App will just redirect to 'app.daily.app' in browser
```

### Solution Proposed

Either support Opera or put a clear disclaimer in the description of the Play Store info that it **requires** Chrome to be installed/enabled also.

### Screenshots

```bash
[Walkthrough GIF](https://imgur.com/a/xBrUl01)
```

### Environment

Android 14 (AP2A.240805.005), Opera v84.1.4452.81169

### Browsers

Opera

### OS

Android

### Version of daily.dev

15

### Additional Context

```bash
If I install via a PWA from the site first, it will allow that to then open as a PWA. However, I would like to use the Play Store version for any updates of course, and as I will be transferring to a new phone soon, I would like to just resync all the apps from my Play Store account.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @negrimmer,

We will look into it. But since there are not so many Opera users, it may take time. I appreciate your patience 🙏

**Comment by negrimmer** [comment]
@idoshamun I appreciate the response. As I said just having Chrome enabled will allow the app to work fine, just thinking for others like myself that have moved away from Chrome due to the security issues it has now and the lack of trust for privacy. Look forward to an update!

**Comment by idoshamun** [comment]
Ah I understand now! We will add a note as suggested to enable Chrome. Thanks a lot!
