### ISSUE TITLE
🐛 BUG: Deleted welcome post and now I cannot complete the task of customizing the welcome post.

### ISSUE THREAD

**Issue by nikdra31** [dailydotdev/daily#1366]
### What went wrong? 🤔

Deleted welcome post and now I cannot complete the task of customizing the welcome post in order to make my squad public.
Squad is @infobipdevs

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @nikdra31 I've manually restored the welcome post for you for now.
We are working on a more stable way to overcome this issue.
