### ISSUE TITLE
🐛 BUG: Shortcuts missing

### ISSUE THREAD

**Issue by im4235** [dailydotdev/daily#1368]
### What went wrong? 🤔

My main new tab "my feed" page has begun only showing four shortcuts, regardless of window size / available space.
I can still see all 10 addresses if I go to customize but there is no way to use the last 6.

### Expected Behavior

I liked how it was before when I could click all the shortcuts and it was limited to 10, rather than 4.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

Revert to earlier version or amend to show more shortcuts

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @im4235 Which version of daily.dev extension are you using?
Also do you perhaps have a screenshot as 4 seems very low to show.

**Comment by ClemPalf** [comment]
Hi there, I have the same problem, depsite having several shortcuts, only 4 are available now. 
I am on the 3.34.6 version

**Comment by idoshamun** [comment]
Hi @ClemPalf, this maybe related to screen size. A screenshot would be helpful

**Comment by ClemPalf** [comment]
Hi @idoshamun,

Here is one
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/dffb2c44-49bf-42c6-b067-4d4512872a9a">

Note that ~ 2 weeks ago (I am really not sure about the date, sorry) everything was getting displayed properly on the same computer

**Comment by rebelchris** [comment]
We recently uniformed our shortcuts into one option thus fixing this issue.
