### ISSUE TITLE
feat: drag and drop files on input components

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1369]
### Discussed in https://github.com/dailydotdev/daily/discussions/1346

<div type='discussions-op-text'>

<sup>Originally posted by **Icestonks** August 19, 2024</sup>
It would be great if we could simply drag and drop or paste files directly into the thumbnail when creating a post.</div>

We have an `ImageInput` for uploading images (as the name implies), but it lacks drag-and-drop functionality.

It should be straightforward to introduce, by adding some event listener on drag over and on drop functions. There is a similar behavior from the `useMarkdownInput`, the function is named `onDrop`, on how we process image uploads.

**Comment by jagpreetrahi** [comment]
Hi @sshanzel  I hope you doing well , I am Jagpreet Singh  , am a developer . I am new here , I want to contribute on this issue . Can you elaborate me about it

**Comment by sshanzel** [comment]
Hey @jagpreetrahi, thank you for your interest. We have features that let you upload your user avatar/cover image. In doing so, we should allow the user to just drag over the file to the input component and automatically detect the file being uploaded.

**Comment by jagpreetrahi** [comment]
Hey @sshanzel , thanks for your patience! , Hope you're doing well. This feature sounds great, and I'm really interested in collaborating with you on it. Please feel free to connect with me, and let's discuss how we can move forward together. Looking forward to working on this.

**Comment by sshanzel** [comment]
Hi! Our GitPod environment is back and running again. Feel free to test it out 🥳

**Comment by sparshcodes** [comment]
Hey @sshanzel , Can you assign this issue. I have already worked on such input.
So i can provide a fix.

Thanks.

**Comment by jagpreetrahi** [comment]
Hii@sshanzel  yeh sure send some access for that

**Comment by sshanzel** [comment]
> Hey @sshanzel , Can you assign this issue. I have already worked on such input. So i can provide a fix.
> 
> Thanks.

Hey. Really appreciate the interest. While the issue is still open, @Abhi-Bohora actually opened a PR for the fix. Feel free if any of the other open issues pique your interest, and I shall help you with it 🙏

**Comment by sshanzel** [comment]
> Hii@sshanzel yeh sure send some access for that

Hi! There should be no need for any additional access, just head over to our README page, and a link to GitPod should be found.
