### ISSUE TITLE
🐛 BUG: the side border does not span to the bottom

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1370]
### What went wrong? 🤔

A minor UI issue where the border does not span from top to bottom.

![image](https://github.com/user-attachments/assets/fce3a21d-0ddb-4819-9690-13788f134eee)

### Expected Behavior

The border should react top to bottom

### Steps to Reproduce Issue

```bash
1. Login
2. Click the profile menu
3. Go to account details
4. See the screenshot above
```

### Solution Proposed

Probably a simple `flex-1` might fix it.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Any OS/browser

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

Web app

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Closing as solved
