### ISSUE TITLE
🐛 BUG: when reporting an article, after clicking the text field, "Others" should be selected

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1371]
### What went wrong? 🤔

Not an issue, but more of a QoL concern.

When you try to report an article, and tap on the “anything else you’d like to add” field - it would be nice to automatically set the reason to “other” if a different reason has not been previously selected

### Steps to Reproduce Issue

```bash
1. Login
2. Go to the feed
3. Click the options menu on any post -> select "Report"
4. Click the text field without selecting any of the options yet
```

### Solution Proposed

After step 4. we should automatically select the "Others" from the Radio input selections.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by GorkemEldeniz** [comment]
Would it be possible for me to work on this as a first-time contributor?

**Comment by Mohammadshahzaib007** [comment]
I have raised the pr for this issue
https://github.com/dailydotdev/apps/pull/3725 @sshanzel

**Comment by sshanzel** [comment]
@Mohammadshahzaib007 I've made some comments, but great work so far 🥳

**Comment by rebelchris** [comment]
Closed as completed
