### ISSUE TITLE
🐛 BUG: Daily Dev Widget comments don't play well with YouTube videos

### ISSUE THREAD

**Issue by bobbyiliev** [dailydotdev/daily#1377]
### What went wrong? 🤔

The Daily Dev widget does not play well if you were to try and type out a comment on a YouTube video. Mainly messes up the YT shortcuts like pressing space to start and stop the video.

### Expected Behavior

Don't trigger the YT shortcuts whenever typing out a comment.

### Steps to Reproduce Issue

```bash
1. Go to a YT video that is on Daily Dev
2. Click on the Daily Dev Widget
3. Start typing out a comment
4. Each time you press space the video will stop/start playing
```

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

3.34.0

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @bobbyiliev,

Just to understand exactly the situation, the issue is when you comment via our companion widget and it triggers YT shortcuts?

**Comment by bobbyiliev** [comment]
Hey @idoshamun 

Yea exactly, basically:

- Visit a video that is on Daily.Dev: https://www.youtube.com/watch?v=QMwNHaV5eMs
- Open the Daily Dev widget
- Start typing something and whenever you press space the video will start/stop
