### ISSUE TITLE
🐛 BUG: Feed doesn't refresh

### ISSUE THREAD

**Issue by dkuzmyk** [dailydotdev/daily#1379]
### What went wrong? 🤔

I have signed up today, have set up 3 different feeds and it has been working good for a few hours. I tried opening the website later this evening and my feeds are frozen. 

### Expected Behavior

just open the feed as it has done for the first few times

### Steps to Reproduce Issue

```bash
open my feed, refresh, open other custom feeds
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
![image](https://github.com/user-attachments/assets/19e442c9-379c-4d05-b002-7d69e6ec1cd6)
```

### Environment

Chrome Version 128.0.6613.114 (Official Build) (64-bit)

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

website

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by jegj** [comment]
I have the same issue and also found this in the console
![Screenshot from 2024-08-29 20-57-47](https://github.com/user-attachments/assets/87f48079-37e6-4498-bf92-da0747cf1df2)

**Comment by nimrodkra** [comment]
Thanks for reporting! We're looking into this now

**Comment by idoshamun** [comment]
It is fixed now, thanks!
