### ISSUE TITLE
🐛 BUG: "Recieve marketing by email" is checked by default in signup form

### ISSUE THREAD

**Issue by terrygonguet** [dailydotdev/daily#1380]
### What went wrong? 🤔

In the signup form there is a checkbox at the bottom that goes something like "don't send me updates by email" and it is unchecked by default.

This is illegal in the EU, this kind of marketing checkbox must be _opt in_ and not _opt out_.

Also it is a better user experience.

### Expected Behavior

This checkbox should be checked by default (or reversed so that checking it expresses agreement).

### Solution Proposed

Either check the box by default or reverse the logic so that checking it means consenting.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @terrygonguet,

Thanks for raising our awareness, we will check that
