### ISSUE TITLE
🐛 BUG: Unable to sign up

### ISSUE THREAD

**Issue by Morgy93** [dailydotdev/daily#1381]
### What went wrong? 🤔

After filling the form at https://app.daily.dev/onboarding and clicking on "Sign up" nothing happens.

<img width="463" alt="image" src="https://github.com/user-attachments/assets/8f59bfd2-e0ea-4495-9604-fae5d74c515c">

The browser console shows an error:

`POST https://sso.daily.dev/self-service/registration?flow=466-some-hash-not-sure-if-sensitive- 47fd83a 400 (Bad Request)`

### Expected Behavior

I'd expect to be signed up. Or at least get an error message for the user.

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/onboarding'
2. Fill out the form
3. Click on 'Sign up'
4. See the error in the browser console
```

### Solution Proposed

At least show an error message to the user upon bad fetch request.

But of course it would be great if I were able to sign up. =)

### Environment

macOS Sonoma 14.6.1, Microsoft Edge Version 129.0.2779.0 (Official build) Dev(arm64)

### Browsers

Microsoft Edge

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Morgy93,

Can you please send the personal details to our support email? (support at daily.dev)
In the meantime, if you can clear the cookies and try again this may help
