### ISSUE TITLE
🧩 FEATURE REQUEST:  Keep Page Position When Entering A Post (Squads)

### ISSUE THREAD

**Issue by parisosuch-dev** [dailydotdev/daily#1382]
### Concise Description

When clicking on a post in the web version and going back, it would be nice to hold page position.

### Description

When clicking on a post in the web version and going back, it would be nice to hold page position. There doesn't seem to be a back button on the web view. Clicking the back button for the browser, brings you to the top of the feed.

This occurs in squads but this feature works in the regular feed.

### Solution Proposed

Copy the behavior of the regular feeds.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @parisosuch-dev,

We'll look into that. Thank you!
