### ISSUE TITLE
🐛 BUG: 'github already exists' error when trying to add my github account on the social links to my profile

### ISSUE THREAD

**Issue by ricardogouveia3** [dailydotdev/daily#1384]
### What went wrong? 🤔

When I try to add my Github on my profile social links, it says 'github already exists'. Happens both when trying to add it via username or link

![image](https://github.com/user-attachments/assets/7acd816f-2816-413b-b025-ac485c97a95d)

### Expected Behavior

Maybe this is expected behavior (if another user has added the same GitHub link for example) but I think that at least the message could be more specific on how to solve it

### Steps to Reproduce Issue

```bash
1. Go to 'Profile'
3. Scroll down to 'Profile Social Links'
2. Try add 'ricardogouveia3' on the github input, for example (can't provide other username causing the same behavior)
4. See the error message
```

### Solution Proposed

I think this could be caused by another account I may have created using my github to login, but if this is the case so I think the message should be specific so I can login into that other account and delete it

### Screenshots

```bash
![error message](https://github.com/user-attachments/assets/7acd816f-2816-413b-b025-ac485c97a95d)
```

### Environment

Chrome, using the extension version of daily dev

### Browsers

Chrome

### OS

Windows, Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ricardogouveia3,

I see you have another account from 2022 that has this github assigned. Would you like me to reset it so you can assign it to the new account?

**Comment by ricardogouveia3** [comment]
> Hi @ricardogouveia3,
> 
> I see you have another account from 2022 that has this github assigned. Would you like me to reset it so you can assign it to the new account?

Sorry for the delayed response. Yes, please, that would be perfect! Thanks

**Comment by idoshamun** [comment]
Done. Try again please
