### ISSUE TITLE
🐛 BUG: Videos are being displayed even my feed is configured to not show then

### ISSUE THREAD

**Issue by JCKodel** [dailydotdev/daily#1389]
### What went wrong? 🤔

Videos are being displayed, even my feed is configured to not show then.

If I want to see youtube videos, I go to youtube.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

![image](https://github.com/user-attachments/assets/5da0f376-2e8d-48c6-9239-58cc7ff8cf89)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @JCKodel,

Thanks for reporting, we're aware of this issue. It happens only when someone shares a video to a squad. It happens because this post is flagged as shared post and not as video. It's has some technical challenges to fix but we'll look into it
