### ISSUE TITLE
🐛 BUG: Unable to see articles in the feed

### ISSUE THREAD

**Issue by kin-hero** [dailydotdev/daily#1392]
### What went wrong? 🤔

20240902
I am unable to see articles in my feed. It keeps on loading endlessly. I have added multiple topics that i am interested at like cloud, web dev, and career and so on.
![Screenshot 2024-09-02 at 11 17 36](https://github.com/user-attachments/assets/d25fd459-b897-4407-b01f-a8e3719a46ab)

I am also unable to create a new feed, when i choose the topics that i like and press `show feed preview`, it keeps on loading endlessly.
![Screenshot 2024-09-02 at 11 20 34](https://github.com/user-attachments/assets/050e34e9-47c4-435c-81e7-8d3223614e09)

### Expected Behavior

I am able to see the articles in my feed. 

### Steps to Reproduce Issue

```bash
It occurred immediately as i open my browser
```

### Environment

MacOs Sonoma 14.5 and Chrome Version 127.0.6533.122 (Official Build) (arm64)

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

3.34.0

### Additional Context

```bash
I open the chrome developer tool and i saw this API request

https://api.daily.dev/graphql. The response of this API request is this 
{"errors":[{"message":"Unknown query"}]}

This might be the reason why my feed is not loading with articles.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by kin-hero** [comment]
`https://api.daily.dev/graphql` -> 502 Bad Gateway
Access to XMLHttpRequest at 'https://api.daily.dev/graphql' from origin 'https://app.daily.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

POST https://api.daily.dev/graphql net::ERR_FAILED 502 (Bad Gateway)

After a while, it returns this 
![Screenshot 2024-09-02 at 11 34 06](https://github.com/user-attachments/assets/168f4965-1952-4f4a-8018-1d7a59f38847)
But i actually already added some topics in my feed
![Screenshot 2024-09-02 at 11 34 12](https://github.com/user-attachments/assets/7e704128-3021-4eac-ae0e-20680d4780be)

**Comment by simonced** [comment]
I have the same problem since today (2024-09-02)
I have a Next.JS error in the console:
![js console](https://github.com/user-attachments/assets/35bc0079-b910-4c04-a5cf-50223c6ceeb5)

**Comment by Shriansh2002** [comment]
It is happening same for me

[X Post](https://x.com/ShrianshAgarwal/status/1830458593381962093)


![image](https://github.com/user-attachments/assets/664a36eb-ef3f-4cfb-8e9d-65c2e6d93d67)
![image](https://github.com/user-attachments/assets/6b4b2602-03f6-491d-aa5f-54ae4644211e)

**Comment by rebelchris** [comment]
Hi all,

We are aware of this incident and resolving it at the moment 🙏

**Comment by rebelchris** [comment]
Hi,

We managed to resolve the issue and are back up and running 🚀

**Comment by kin-hero** [comment]
thank you, it is working now!
