### ISSUE TITLE
🐛 BUG: Feed is not displaying the current news

### ISSUE THREAD

**Issue by MUKTADIR-ALAM** [dailydotdev/daily#1393]
### What went wrong? 🤔

![Screenshot 2024-09-02 081603](https://github.com/user-attachments/assets/5923a5e2-3799-4820-a853-70b360e09a4d)
my feed is not opening please fix the bugs as soon as possible

### Expected Behavior

in feed should display the current news

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

my feed is not opening please fix the bugs as soon as possible

### Screenshots

```bash
![DESCRIPTION](LINK.png)
my feed is not opening please fix the bugs as soon as possible
```

### Environment

windows 11, google chrome Version 128.0.6613.114 (Official Build) (64-bit)

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

Version 3.34.0

### Additional Context

```bash
my feed is not opening please fix the bugs as soon as possible
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by jdmallen** [comment]
I'm seeing the same behavior in both Brave 1.69.160 and Firefox 129.0.2. Brave Shield and uBlock Origin are disabled.

![image](https://github.com/user-attachments/assets/cfc57eed-4964-4a9e-8a37-67d1f093b1d0)

![image](https://github.com/user-attachments/assets/70964260-cbfe-4b78-be65-69844aeb15ab)

**Comment by rebelchris** [comment]
Hi all,

We currently have a issue with our feed loading, should be resolved fairly soon 🙏

**Comment by rebelchris** [comment]
Closing this one to keep all discussion here: https://github.com/dailydotdev/daily/issues/1392

**Comment by MUKTADIR-ALAM** [comment]
> Hi all,
> 
> We currently have a issue with our feed loading, should be resolved fairly soon 🙏



> Hi all,
> 
> We currently have a issue with our feed loading, should be resolved fairly soon 🙏

thanks for fixing quickly
