### ISSUE TITLE
🐛 BUG: Newsfeed not charging on Firefox

### ISSUE THREAD

**Issue by aissat99** [dailydotdev/daily#1394]
### What went wrong? 🤔

When opening daily.dev on Firefox, the newsfeed is not charged and the article cards remain in "charging" mode. The situation remains the same even after refreshing the page.

### Expected Behavior

When I go to daily.dev, I should see a list of articles, then click on them and read.

### Steps to Reproduce Issue

```bash
1. Go to 'daily.dev'
2. See the error
```

### Screenshots

```bash
![Newsfeed not charging](https://github.com/user-attachments/assets/7def600d-ac11-4c01-8be7-46ce59bfc7cf)
```

### Environment

Ubuntu 24.04, Firefox 129.0.2 (64-bit)

### Browsers

Firefox

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi,

We are aware of this incident and resolving it at the moment 🙏

**Comment by rebelchris** [comment]
Closing this one to keep all discussion here:
https://github.com/dailydotdev/daily/issues/1392
