### ISSUE TITLE
🧩 FEATURE REQUEST:  Increase comment rate limit

### ISSUE THREAD

**Issue by KristianMariyanov** [dailydotdev/daily#1395]
### Description

I was welcoming people in my squad by answering their comments in the Welcome post. I answered around 10 comments and then I tried to comment on another post, but I got a rate limit error. 
![image](https://github.com/user-attachments/assets/0bab60e6-1376-4ad0-ab81-dc8b175980cb)
I didn't see any notification and had to check the network request to understand why is that. 

IMO 10 comments (assuming that's the exact number) is too small a limit for an hour. I reach it with my normal use. 

### Solution Proposed

Increase rate limit

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @KristianMariyanov,

Thanks for reporting. There's a thread for that already: https://github.com/dailydotdev/daily/issues/1236
Hopefully we can fix it soon
