### ISSUE TITLE
🐛 BUG: Sometimes a custom shortcut won't have a favicon

### ISSUE THREAD

**Issue by avi12** [dailydotdev/daily#1399]
### What went wrong? 🤔

![image](https://github.com/user-attachments/assets/7da81407-ee59-4468-a683-e24309ff6df3)

### Expected Behavior

Only if the website doesn't have a favicon, no favicon should be used

### Steps to Reproduce Issue

It's quite random and website-dependent
Some sites like ChatGPT don't have a favicon while others like Google News do have one

### Environment

Chrome extension on Edge

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

3.34.0

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @avi12 ,

We actually use a third-party service for it.
https://github.com/mat/besticon

Therefor we can't always predict the outcome of set icons.

**Comment by avi12** [comment]
https://www.google.com/s2/favicons?sz=64&domain=chatgpt.com

**Comment by rebelchris** [comment]
Hi,

Closing this issue as we now moved to the google favicon way.
thanks @avi12 for suggestion this.

**Comment by avi12** [comment]
Some of the icons fail to display for some reason

https://github.com/user-attachments/assets/1b65bb08-3fcd-4b8f-8cb0-c8d96ebf8b2c

**Comment by avi12** [comment]
Strangely, it changed to this
![image](https://github.com/user-attachments/assets/7c0eab98-aa4c-49df-83c6-11e814f04015)

Yet when I open a global favicon in a new tab, it redirects me to the correct Google URL

**Comment by rebelchris** [comment]
@avi12 Just published a fix for this :) 
It was mainly local cache because we didn't want to change the endpoint URLs.
