### ISSUE TITLE
🐛 BUG: Switching user on chrome opens blank page

### ISSUE THREAD

**Issue by ahmedash95** [dailydotdev/daily#140]
### What went wrong? 🤔
On chrome, when I switch to a different user the tab open became blank. every time I have to open a new tab in order to get the Daily view.

### Expected Behavior
Switching to a different user should display the page like what happens with a new tab

### Actual Behavior
Switching to a different user displays a blank page.

### Steps to Reproduce Issue
try to have 2 people as chrome users and switch between them.

### Solution
N/A

#### Operating System
Mac OS Catalina 10.15.2

#### Version of Daily
Daily 2.13.0

#### Browser
Google Chrome

Thanks

**Comment by idoshamun** [comment]
Hi @ahmedash95,

Thanks for reporting about this issue :)
To solve it, you need to install Daily on both users. This is how Chrome extensions work, it's not up to us. Please let me know how it goes once you try it.

**Comment by ahmedash95** [comment]
Hey @idoshamun, it's already installed on the account I'm switching to. as I said when opening a new tab after switching it works as expected.

Switching to another user opens a new chrome window.

**Comment by idoshamun** [comment]
Could you please send me a video of what's happening so I can better understand it? :pray:

**Comment by ahmedash95** [comment]
Thanks for waiting, here is a gif 
![dev-issue](https://user-images.githubusercontent.com/8272048/75550732-ce0c5200-5a32-11ea-9dca-5fa34793e182.gif)

notice the profile I'm switching to has the plugin

**Comment by idoshamun** [comment]
Thanks for sending the GIF, now it's much clearer. Unfortunately, I don't have any clue how to approach it, I believe it has something to do with Chrome default behavior.
If you have any hint or other information, it would be great.

**Comment by shoeyn** [comment]
![chrome-startup-settings](https://user-images.githubusercontent.com/793761/76248261-e7827a80-6238-11ea-885b-1b654bbff3ab.png)
Can you check your startup settings in Chrome on the particular user you're having issue with to make sure it's not set to open specific page on startup, and said specific page is about:blank.
That's the only way I can replicate the behaviour shown in the gif.
If you always want it to be Daily, set it to the open new tab page (which is controlled by daily).
Let me know if this helps or whether your setting is right and it's a deeper issue

**Comment by ahmedash95** [comment]
Hey @shoeyn, actually that solved the problem :).

Thanks a lot for the solution

**Comment by idoshamun** [comment]
Thank you @shoeyn for solving this issue! :grin:
