### ISSUE TITLE
🐛 BUG: Muting a thread doesnt work

### ISSUE THREAD

**Issue by itsjavi** [dailydotdev/daily#1401]
### What went wrong? 🤔

When I mute a thread I keep receiving notifications about new comments specially when they reply to mine, even if they don't mention me.

### Expected Behavior

When you mute a thread, no new notifications about that post comments are received, unless they mention you directly/explicitly, (or maybe not even that)

### Steps to Reproduce Issue

```bash
1. Go to your notifications
2. Click on the options icon of any notification
3. Click on "Mute this thread"
4. If the thread gets a new comment, you'll still receive a notification
```

### Screenshots

![image](https://github.com/user-attachments/assets/d995e91c-4cc1-4c38-bcf2-2bba514af823)

### Additional Context

My username there is: itsjavi

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @itsjavi ,

Thanks for reporting this we'll look into it and revert back.

**Comment by sshanzel** [comment]
Hi @itsjavi, can I get your user handle? Also, if handle, do you have a link to the comments relevant to the issue?

**Comment by rebelchris** [comment]
We did make several changes to comment muting and have seen no further response, so closing this as completed.
Do feel free to re-open new tickets.
