### ISSUE TITLE
🐛 BUG: Get started with squads, checklist can't be completed after deleting the welcome post

### ISSUE THREAD

**Issue by tomdevisser29** [dailydotdev/daily#1402]
### What went wrong? 🤔

I deleted the welcome post, and now I can't finish or complete the to-do list (because one of the items is editing the welcome post).

### Expected Behavior

Being able to create a new welcome post or just mark it complete.

### Steps to Reproduce Issue

```bash
1. Create a squad
2. Delete the welcome post
```

### Solution Proposed

Being able to create a new welcome post or just mark it complete.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by tomdevisser29** [comment]
<img width="400" alt="Screenshot 2024-09-04 at 15 09 28" src="https://github.com/user-attachments/assets/c1acbc39-0604-4202-9b97-a619420d9d86">

**Comment by rebelchris** [comment]
@tomdevisser29 Should be back :) 
Veel plezier met de Squad 🙏
