### ISSUE TITLE
🐛 BUG: Receiving notifications for unfollowed sources

### ISSUE THREAD

**Issue by JCKodel** [dailydotdev/daily#1404]
### What went wrong? 🤔

This guy only post content behind the fucking medium paywall (which I think should be forbidden).

I've unfollowed him, but my notifications feed still infested with this crappy paywall shit:

![image](https://github.com/user-attachments/assets/54881485-bbe4-4206-a634-e08ac42f3f78)

### Expected Behavior

If we block something, we BLOCK something >.<

### Steps to Reproduce Issue

```bash
1.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @JCKodel,

Paywall content is not allowed on the platform beside squads since they're opt-in.
Right now the block and notifications are separate from each other and we're working to fix it.
In the meantime, I suggest leaving the squad and it should fix the issue
