### ISSUE TITLE
🐛 BUG: Comment not found

### ISSUE THREAD

**Issue by frank-connolly** [dailydotdev/daily#1406]
### What went wrong? 🤔

![image](https://github.com/user-attachments/assets/07ec0c07-fb73-42cd-a491-c25f2c056bf2)
Despite the notification above I do not see the comment on this post. I believe this is happening with all similar notifications for the Welcome post in this squad. Clicking the notification simply brings me to the post, scrolling down to load comments does not reveal it. This is on desktop. 

### Expected Behavior

- The comment on the post should be visible
- Clicking the notification should take me to the comment.

### Steps to Reproduce Issue

```bash
1. Go to (Just Java squad welcome post)[https://app.daily.dev/posts/4lkF85AjX]
2. Search for the comment as described in the notification screenshot in 'What went wrong?' section
3. Unable to locate comment.
```

### Solution Proposed

This used to work. I suspect (if no recent changes in related code) the large number of comments for that post is causing some logic to not function as intended. Perhaps the design never factored in this number of comments.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Ubuntu

### Browsers

Chrome

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @frank-connolly,

I think we have an issue with very long discussions. We'll have to think how to address that.
Thanks for reporting

**Comment by rebelchris** [comment]
We recently bumped the comment list to load more, which should solve this issue.
We are internally looking at re-doing the comment section so will close this as resolved for now.
