### ISSUE TITLE
🧩 FEATURE REQUEST:  choose browser in mobile app

### ISSUE THREAD

**Issue by sitedialy** [dailydotdev/daily#1407]
### Description

Hello,

Could you please add (in setting) the possibility to choose which browser to use when open external links, instead of Google Chrome ?

Thank you.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @sitedialy,

Unfortunately, this is not possible with our current setup. I hope it will be possible in the future 🙏
