### ISSUE TITLE
🐛 BUG: fix alignment of the elements in the leaderboard

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1409]
### What went wrong? 🤔

![image](https://github.com/user-attachments/assets/320a7211-f244-4814-849a-fd2bee7e2003)

### Expected Behavior

The avatars should be aligned.

### Steps to Reproduce Issue

```bash
1. Go to the leaderboards page (https://app.daily.dev/users)
2. See the misalignment
```

### Solution Proposed

Fix the alignment of the avatars.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by Ahmad-Zahid** [comment]
@sshanzel Hi, can I take this up?

**Comment by sshanzel** [comment]
@Ahmad-Zahid feel free to try it! :shipit:
