### ISSUE TITLE
🐛 BUG: Pulling unrelated Wikiperia pages?

### ISSUE THREAD

**Issue by marik22312** [dailydotdev/daily#141]
### What went wrong? 🤔

The API is pulling unrelevant data from wikipedia
https://app.dailynow.co/r/e0fd169e2bd13c31146b6bbcce801b4f

### Expected Behavior

Didn't expect that at all...

### Solution

Need to take a look at the api first :)

#### Operating System
MacOS Mojave

#### Version of Daily
Daily 2.14.0

#### Browser
Google Chrome | 79.0.3945.130 (Official Build) (64-bit)
-- | --

**Comment by idoshamun** [comment]
Hi @marik22312,

Thanks for reporting this issue, I haven't noticed it before.
I see that this post comes from Hacker News. Have you seen any other wikipedia pages?

**Comment by marik22312** [comment]
@idoshamun nope, first time

**Comment by idoshamun** [comment]
I've deleted the aforementioned post, please open this issue if it happens again.
