### ISSUE TITLE
🧩 FEATURE REQUEST:  open links in external browser 

### ISSUE THREAD

**Issue by bigkrp** [dailydotdev/daily#1417]
### Concise Description

I want to have opportunity to open links that lead to some resource in my default browser 

### Description

The links that lead to resources like Medium or freeCodeCamp should have the option to be opened in the default browser. For example, I want to add them to my bookmarks in Firefox. I don't want to have to click on "Open in default browser" for each article; it's annoying.

### Solution Proposed

Add possibility in settings to set-up all external links in default browser 

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @bigkrp,

Please see my response here: https://github.com/dailydotdev/daily/issues/1407
