### ISSUE TITLE
🐛 BUG: Links to HumbleBundle have wrong TLDR contents (of a wrong bundle) and thus wrong tags.

### ISSUE THREAD

**Issue by p-kraszewski** [dailydotdev/daily#1418]
### What went wrong? 🤔

I added two links to valuable HumbleBundle book bundles:

* [Humble Tech Book Bundle: Machine Learning and AI by No Starch](https://api.daily.dev/r/N6SJygYQd) which has TLDR of some game bundle with #gaming tag
* [Humble Tech Book Bundle: Software Architecture 2024 by O'Reilly](https://api.daily.dev/r/03VswUmLp) which has TLDR of the above No Starch bundle with AI-related tags

### Expected Behavior

Have TLDR and tags related to the contents of the **actual** added link.

### Steps to Reproduce Issue

```bash
1. Add a HumbleBundle link
2. Wait for it to ba accepted (hopefully)
3. Observe the invalid TLDR and tags
```

### Solution Proposed

It might look like TLDR of **currently** added HumbleBundle is somehow taken from a **previously** added HumbleBundle (possibly even by some other user). Some caching issue?

### Environment

Vivaldi 6.9.3447.41 (Stable channel) stable (64-bit) 

### Browsers

Other

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @p-kraszewski,

We will look into it

**Comment by rebelchris** [comment]
@p-kraszewski since both paces are no longer live and our investigation didn't yield good results from changing crawling on the website provided we decided to not pursue this issue further.

I'm closing it, but if you ever have different examples feel free to open new tickets.
