### ISSUE TITLE
🐛 BUG: you sending emails and asking to reply to the address that doesn't accept messages

### ISSUE THREAD

**Issue by usulpro** [dailydotdev/daily#1419]
### What went wrong? 🤔

After submitting a source I've got a mail from you with the following message:

![image](https://github.com/user-attachments/assets/5f7b68ff-c9d3-442a-a651-a606631a58fd)

 I've written a response and sent it back. But I've got a message that this address isn't valid

![image](https://github.com/user-attachments/assets/9a571b6f-1b3f-42d6-8f3d-d0d1a7a3fdbd)

So I simply can't reply to your message

### Expected Behavior

It's expected that I can just reply to your message, or you provide another email address where I can send a reply

### Steps to Reproduce Issue

```bash
Well, to reproduce it, you have to submit a source that does not pass your validation first :)
Maybe you don't need to reproduce it from that point; just find such messages from your sending history and try to reply to it
```

### Solution Proposed

You might just need to check your email service settings. Or you could specify clear instructions on how to continue to communicate with you

### Browsers

Chrome

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @usulpro,

We will look into it 🙏

**Comment by usulpro** [comment]
@idoshamun thanks for fixing this :)
