### ISSUE TITLE
🧩 FEATURE REQUEST: Remove already read articles from the popular or recents list

### ISSUE THREAD

**Issue by prateek3255** [dailydotdev/daily#142]
### Description
I read articles from daily a lot, so I get a lot of already read articles in my feed whenever I open a new tab, which is not a good thing because that space could have been used for the articles that I haven't read.

### Solution
You can create a separate tab for the already read articles and remove it from the Recents/Popular list. An article can be considered as read if the user clicks on an article.

Also, if you think that not every user would want this, you can create an optional setting here -
![image](https://user-images.githubusercontent.com/21277179/75542060-0f0d6200-5a45-11ea-8d1c-93a0d6a4cdc2.png)
which will be false by default but when enabled would perform the above-mentioned action.

### Alternate Solutions
NA

I would love to work on it if you're moving forward with this feature.

**Comment by idoshamun** [comment]
Hi @prateek3255,

Thanks for the suggestion, it is actually a great idea.
I would love your contribution on this one, as you mentioned.
We will have to start first by changing the API and then move on to the app itself.
I will need some time to create a technical issue in https://github.com/dailydotdev/daily-api, describing the potential solution.

**Comment by prateek3255** [comment]
Thanks @idoshamun, let me know when I can start working on this.

**Comment by idoshamun** [comment]
@prateek3255 here you go https://github.com/dailydotdev/daily-api/issues/46
Let me know what you think and please comment there so I can assign you.
Thank you once more.

**Comment by prateek3255** [comment]
@idoshamun do let me know when I can start working on the extension part.

**Comment by idoshamun** [comment]
@prateek3255 I'm so very sorry, I was busy doing something else in this crazy time. I will create the new issue as soon as possible.

**Comment by idoshamun** [comment]
Here you go: https://github.com/dailydotdev/daily-apps/issues/99
Again sorry for the delay

**Comment by prateek3255** [comment]
> @prateek3255 I'm so very sorry, I was busy doing something else in this crazy time. I will create the new issue as soon as possible.

No worries @idoshamun
