### ISSUE TITLE
🐛 BUG: Company Badge announcement should not be shown if user has company badge already

### ISSUE THREAD

**Issue by thraizz** [dailydotdev/daily#1420]
### What went wrong? 🤔

Currently, there is a notification about the release of the company badge feature for users that have already set up the badge:
![image](https://github.com/user-attachments/assets/cdec3feb-dc08-4c12-bff7-10202b40ae41)

### Expected Behavior

The badge feature should not be displayed for users who have the company badge set up.

### Steps to Reproduce Issue

```bash
1. Set up the company badge
2. Refresh the home page
3. See the banner
```

### Solution Proposed

Check if user has badge, if yes, show badge, otherwise return 😄 

### Screenshots

```bash
![image](https://github.com/user-attachments/assets/cdec3feb-dc08-4c12-bff7-10202b40ae41)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @thraizz ,

This banner actually shows to everyone without any logic.
You can close it with the right side close button.
