### ISSUE TITLE
🐛 BUG: Auto-generated article by URL thumbnail mismatch

### ISSUE THREAD

**Issue by richardevcom** [dailydotdev/daily#1423]
### What went wrong? 🤔

I submitted this article: [https://medium.com/@itscarlosisaac/creating-a-saas-app-with-vue-and-nuxt-part-1-bee733b54713](https://medium.com/@itscarlosisaac/creating-a-saas-app-with-vue-and-nuxt-part-1-bee733b54713) to be added in [app.daily.dev](https://app.daily.dev/. Once the article was processed, it's thumbnail didn't match the article one: [https://dly.to/L7cnGP3VdLS](https://dly.to/L7cnGP3VdLS)

### Expected Behavior

app.daily.dev article thumbnail matches linked article thumbnail.

### Steps to Reproduce Issue

```bash
1. Go to '`Submit a link`'
2. Add URL '`https://medium.com/@itscarlosisaac/creating-a-saas-app-with-vue-and-nuxt-part-1-bee733b54713`'
3. Click '`Submit`'
4. Once article is published, see the error (thumbnail mismatch): `https://dly.to/L7cnGP3VdLS`
```

### Screenshots
![medium.com article](https://i.ibb.co/0FhSTxF/Screenshot-from-2024-09-11-04-42-49.png)
![app.daily.dev article](https://i.ibb.co/XDC9pbn/Screenshot-from-2024-09-11-04-43-11.png)

### Version of daily.dev

3.34.1

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @richardevcom I've asked our team to take a look what happened here.

**Comment by rebelchris** [comment]
Hi @richardevcom We now use the right image, thanks for notifying us.
