### ISSUE TITLE
🐛 BUG: Post deleted without my action

### ISSUE THREAD

**Issue by ronyquail** [dailydotdev/daily#1424]
### What went wrong? 🤔

I posted an article yesterday named Seperation of Concerns and woke up today to find it not there anymore and reputation points at zero. Very discouraging and feel I wouldn't;t want to share posts again if they get deleted.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @ronyquail,

Where did you share it to? 
Squad admin and mods can delete content they think isn't relevant to the platform. We will soon add admin approval for posting, so this review will happen before you publish rather than after

**Comment by ronyquail** [comment]
I shared it with Dart Developers. Should they at least say why they think it's not relevant? Cause I did get upvotes before it got deleted so some must have found the post useful. It seems like gate keeping by admin, to be honest and how can a community really grow if some posts are just deleted with no reason at all.

**Comment by idoshamun** [comment]
I understand this poor experience but unfortunately the platform doesn't provide many tools at the moment. We're working on it to allow better communication between admins and OPs.

I'm closing it for now as it's not an issue really but feel free to keep the discussion
