### ISSUE TITLE
🐛 BUG: Wrong company badge

### ISSUE THREAD

**Issue by dreamy32** [dailydotdev/daily#1427]
### What went wrong? 🤔

Earlier today, I entered my workplace email and the badge that I have been assigned is the one from another company of the same name. I suppose this is a human error, because my profile is very obvious about my current workplace.

### Expected Behavior

My workplace is: https://autocanadafinance.ca/
The company I have been assigned: https://www.autocan.ca/

**Comment by sabdailydev** [comment]
@dreamy32 Thanks for reporting this. Could you please share the actual logo?

**Comment by dreamy32** [comment]
Yes, here is the the logo and the alt logo. (I think the alt logo would better fit as a badge):

Logo: 
![AutoCanadaLogo](https://github.com/user-attachments/assets/d740fb6b-7aa3-4ec8-a190-ba06300e2fa5)
Alt Logo: 
![AutoCanadaFinance_Favicon](https://github.com/user-attachments/assets/09e551d1-6870-417f-99fe-28f8a5af788c)

**Comment by sabdailydev** [comment]
@dreamy32  Yes the alt logo would be a better fit. We have udpated it. Please check.

**Comment by dreamy32** [comment]
Thanks its good! 

_If I can give another comment, it might just me being picky, but it would be great if there were an inset padding in badge. It's hard to tell that it's an 'a'. _

**Comment by sabdailydev** [comment]
@dreamy32 We have noted your feedback, and we will try to update this when possible. Thanks.
