### ISSUE TITLE
🐛 BUG: A guy posted a 'Trojan horse' on feeds

### ISSUE THREAD

**Issue by phoenix-Mu** [dailydotdev/daily#1429]
### What went wrong? 🤔

![Screenshot 2024-09-12 091754](https://github.com/user-attachments/assets/498c346c-ca5e-4d56-9940-606b185cc65b)
![Screenshot 2024-09-12 104236](https://github.com/user-attachments/assets/b2b48dd9-6717-412f-b48a-e0df035789ba)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by dansholds** [comment]
Hey @phoenix-Mu "guy" here, can you tell me where exactly you downloaded this from? The download of the roadmaps PDF is clean?

**Comment by rebelchris** [comment]
Closing due to no follow up from reporter.
