### ISSUE TITLE
🐛 BUG: Exception when deleting custom feed, on Mobile App

### ISSUE THREAD

**Issue by mohamadalzhori** [dailydotdev/daily#1430]
### What went wrong? 🤔

When I try to delete a custom feed that i created I get a black screen with the following error:

"Application error: a client-side exception has occured (see the browser console for more information)"

### Expected Behavior

To delete the custom feed.

### Steps to Reproduce Issue

```bash
1. Go to Home
2. Click on the Plus Icon on top, alogside other feed titles
3. Enter feed name
4. Choose some tags
5. Save
6. Go to Settings in the top right corner
7. Select your custom feed
8. Click the recycle icon to delete the feed
9. BOOM!! Error
```

### Screenshots

```bash
![DESCRIPTION](https://imgur.com/bX3Ulfg)
```

### Environment

Android 12

### OS

Android

### Version of daily.dev

15

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @mohamadalzhori,

Thank you for reporting the issue!

We'll try to fix this as soon as possible.

**Comment by rebelchris** [comment]
I just published a fix for this, thanks for reporting it!
