### ISSUE TITLE
🐛 BUG: Feeds cant be sorted by date anymore

### ISSUE THREAD

**Issue by Manwe-777** [dailydotdev/daily#1433]
### What went wrong? 🤔

The docs suggest sorting feeds was possible before; [https://docs.daily.dev/docs/key-features/feeds#sorting-by-date](https://docs.daily.dev/docs/key-features/feeds#sorting-by-date), however things are now looking different in the feed settings, and sorting cant be found anymore.

### Expected Behavior

We should be able to set a sort by date or upvotes on feeds

### Browsers

Brave

### OS

Mac

### Version of daily.dev

3.34.1

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by omBratteng** [comment]
You can find the `Customize` under the profile dropdown
![image](https://github.com/user-attachments/assets/98e2ddbf-9680-4623-8b07-dc12cdf32bcc)

The other steps should be the same as before

**Comment by nensidosari** [comment]
Hi @Manwe-777,

Thank you for reporting this issue. 

Sorting feeds can now be found on user profile menu under "Customize". Please click on the user icon, click "Customize" and you should be able to toggle the "Show feed sorting menu" under Preferences section.
In the meantime we'll work to update the docs to reflect this change. 

Hope this helps. If you face any other difficulties, please feel free to report another issue. 

Best!
