### ISSUE TITLE
🐛 BUG: Expired Certificate on go.daily.dev

### ISSUE THREAD

**Issue by coder0107git** [dailydotdev/daily#1434]
### What went wrong? 🤔

The readme of this repo provides a link to a mobile version but when I went to it, Chrome complained about issues with the certificate. It seems that it expired in July.
![image](https://github.com/user-attachments/assets/9aa38600-32cf-43db-a2eb-35f9ce68f212)

### Expected Behavior

I expected it to not complain about the certificate.

### Steps to Reproduce Issue

```bash
1. Go to 'go.daily.dev'
2. See the error
```

### Solution Proposed

Renew the certificate with Lets Encrypt.

### Screenshots

NA

### Environment

`ChromeOS Fleex 120 LTS`, `Chrome 120.0.6099.331`

### Browsers

Chrome, Firefox, Microsoft Edge, Opera, Brave

### OS

Windows, Linux

### Code of Conduct

- [x] I follow the conditions of this project.

**Comment by idoshamun** [comment]
This domain is no longer maintained we should update the docs. Please use app.daily.dev

**Comment by coder0107git** [comment]
Okay. Thanks for the update!
