### ISSUE TITLE
🐛 BUG: Receiving lost streak notifications after disabling the streak system

### ISSUE THREAD

**Issue by duwejeferson** [dailydotdev/daily#1438]
### What went wrong? 🤔

I've received notifications and even an e-mail about a lost streak even after disabling the streak system. Also, i have e-mail notifications disabled.

### Expected Behavior

Didn't receive notifications or e-mails about a lost streak after disabling the system.

### Steps to Reproduce Issue

```bash
1. Disable streak system;
2. Break the streak;
```

#### Streak tracker disabled!
![streak tracker disabled](https://github.com/user-attachments/assets/2f094b2d-8b84-43ed-865b-140f2629eb47)
#### E-mail notifications disabled!
![e-mail notifications off](https://github.com/user-attachments/assets/8c1b2eed-d6fe-45b0-953a-e58a55fdea90)
#### Notification about the lost streak!
![notification lost streak](https://github.com/user-attachments/assets/673391eb-bdd3-4549-8eb6-c2004b85b22d)
#### E-mail about the lost streak!
![e-mail lost streak](https://github.com/user-attachments/assets/7f46d35a-f3bf-46d8-b5f8-1be88d244705)

### Environment

Windows 10, MS Edge 128.0.2739.79

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

Web

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @duwejeferson,

Thank you for reporting the issue!

We're investigating and will try to resolve the issue as soon as possible.

**Comment by sshanzel** [comment]
Should be fixed by now. Thank you for reporting! 🥳
