### ISSUE TITLE
🐛 BUG: Infinite Scroll Problem

### ISSUE THREAD

**Issue by konuralpt** [dailydotdev/daily#144]
### What went wrong? 🤔
 When i try to scroll down fast, its not loading the rest of articles. Also since its the infinite scroll, we may need to show a loading spinner there.

### Actual Behavior
it's not loading immediately even if i try to force scroll down a few times. But when i scroll up a bit at the end of the page, articles are coming.

#### Operating System
Mac OS Catalina 10.15.3 

#### Version of Daily
2.14.2

#### Browser
Google Chrome

![Untitled](https://user-images.githubusercontent.com/22154552/76563808-2d4d7600-64b9-11ea-8bb4-586e6c316fd6.gif)

**Comment by idoshamun** [comment]
Hi @konuralpt,

Thank you for taking the time and reporting this issue.
I would love your help on resolving this issue, would you mind contributing the fix?

**Comment by konuralpt** [comment]
@idoshamun Yeah sure, i would love to 👍
