### ISSUE TITLE
🛑 Help: Access to fetch at 'http://sso.local.com/self-service/registration/browser?' from origin 'http://localhost:5002' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Abhishek-Bohora** [dailydotdev/daily#1440]
Hello Everyone. I am trying to set up the daily.dev locally for development. My backend API `daily.api` is running successfully along with all the services of the docker. But I am getting this error on the console on the frontend side. you can take a look at the screenshot. I am trying to figure this out from morning but couldn't. Any help would be appreciated thanks.

OS: Window 11
.env file in frontend
```
NEXT_PUBLIC_API_URL=http://localhost:5000
#NEXT_PUBLIC_API_URL=https://api.daily.dev
NEXT_PUBLIC_SUBS_URL=ws://localhost:5000/graphql
NEXT_PUBLIC_DOMAIN=local.com

NEXT_PUBLIC_WEBAPP_URL=/
NEXT_PUBLIC_AUTH_URL=http://sso.local.com
NEXT_PUBLIC_HEIMDALL_URL=http://sso.local.com
#NEXT_PUBLIC_AUTH_URL=https://sso.daily.dev

NEXT_PUBLIC_ONESIGNAL_APP_ID=04cddacf-5920-47a6-b567-9ae334d26681
NEXT_PUBLIC_EXPERIMENTATION_KEY=6FA4C8D3DD2400B9D614BB7A229FD69B

NEXT_PUBLIC_GB_DEV_MODE=false

NEXT_PUBLIC_SLACK_CLIENT_ID=1137730955072.7361269413077
```
![Screenshot 2024-09-17 132849](https://github.com/user-attachments/assets/69679625-e021-4dfc-9af9-ab7ed3160e6b)

![net](https://github.com/user-attachments/assets/754e819e-385f-40c3-bb37-690cb2026d02)

For the note I have added this `127.0.0.1 sso.local.com` on my `C:\Windows\System32\drivers\etc` in `hosts` file if I don't add that than this different error will appear on console.

![ftc](https://github.com/user-attachments/assets/9e3455ef-19b2-4443-9990-e346104dc31c)

**Comment by sshanzel** [comment]
Hi. In order to run local development. It has to be [through GitPod](https://gitpod.io/#https://github.com/dailydotdev/apps/). Though we are investigating an issue with spooling it up, and we are hoping to fix it until next week.

**Comment by Abhishek-Bohora** [comment]
Hello @sshanzel  ohh yes, I noticed that there was a problem with running with gitpod. so I began to setup local development. Anyway Thanks
