### ISSUE TITLE
🐛 BUG: hydration error in /users endpoint

### ISSUE THREAD

**Issue by Abhishek-Bohora** [dailydotdev/daily#1441]
### What went wrong? 🤔

There is an next js hydration error when you visit `http://localhost:5002/users` endpoint. you can see in the screenshot.
![hyd-er](https://github.com/user-attachments/assets/f5bd3395-9fe3-480b-b5db-79af2bbb2409)

### Expected Behavior

 It should display the leaderboard

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome, Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment]
Hi, thank you for reporting. Like mentioned, local development has to go through GitPod. Nothing will work through local Docker, so we really won't consider anything related to that as an actual issue. Once the GitPod env is fixed, I will gladly let you know about it.
