### ISSUE TITLE
🐛 BUG: when i change the browser size part of the new tab is not shown

### ISSUE THREAD

**Issue by SujalMunikar** [dailydotdev/daily#1449]
### What went wrong? 🤔

when i change the size of the browser to half, the related shortcut bar suddenly disappears as it is in flex. if i minimize the browser zoom it can be again seen. when i need to open multiple browser and in different sizes, i want to be able to directly access the needed shortcut but it doesn't show there.

### Expected Behavior

just need to show shortcut bar even when size of the browser is changed or divided , when opening a new tab.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

just make the attribute properties to show shortcut bar even when size is changed

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by satvik2131** [comment]
I am not able to reproduce the issue , can you share a video recording .

**Comment by SujalMunikar** [comment]
Screen Recording 2024-09-29 145952.mp4
<https://drive.google.com/file/d/1pLESdq5SLCZfXLYJrus3FZOkbsOP-v6k/view?usp=drive_web>
here is the recording it shows that when i split the browser into multiple
section it just hides the shortcuts menu.

**Comment by idoshamun** [comment]
Hi @SujalMunikar,

Can you please share the window size once it's resized to half?

**Comment by rebelchris** [comment]
@SujalMunikar On the half screen you do first you enter the mobile view.
We only support the shortcuts on full size desktop view for spacing related issues.

It's not supported on the smaller versions. 
I hope that answers your question.
