### ISSUE TITLE
🐛 BUG: bug when adding a shortcut

### ISSUE THREAD

**Issue by clavelian** [dailydotdev/daily#1450]
### What went wrong? 🤔

![image](https://github.com/user-attachments/assets/68b75b57-9d70-426e-9d2b-1baa440671e5)

### Expected Behavior

even with valid link the bug still persists

### Steps to Reproduce Issue

```bash
1. Open tab
2. Add shortcut
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

updated win 11 chrome 

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Can you please add `https://` to the link?

**Comment by rebelchris** [comment]
It should be working when using fully qualified URLs as suggested.
Closing this issue.

Feel free to open any new ticket.
