### ISSUE TITLE
🐛 BUG: | Responsive problem on mobile application

### ISSUE THREAD

**Issue by NockIA** [dailydotdev/daily#1452]
### What went wrong? 🤔

I've downloaded your app on mobile and there's a responsive problem on the mobile app on the home page, the tags go beyond creating this problem.

### Expected Behavior

the fact that it doesn't exceed the screen size 

### Steps to Reproduce Issue

```bash
1. Go to 'home page'
2. Scroll down the page
3. ee the error on an article with a lot of tags
```

### Solution Proposed

Idk what technology you're using, but it's probably the equivalent of adding a flex-wrap to the box.

### Environment

Samsung s21 FE

### Browsers

Other

### OS

Android

### Version of daily.dev

16

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by maheswar-dileep** [comment]
@NockIA  Can you add a screenshot or a video of the issue.

**Comment by NockIA** [comment]
You can check to this link

https://ibb.co/xfZpX8V

**Comment by Atul-Shivnani** [comment]
Can't see any issue like this 
![dds2](https://github.com/user-attachments/assets/3d99832e-de11-4590-a844-97b80c0384b3)
![dds1](https://github.com/user-attachments/assets/05a22b98-bfc9-4906-8075-bc66774fd021)

**Comment by idoshamun** [comment]
Hi @NockIA,

It seems like you're translating the webapp. Is that right?

**Comment by NockIA** [comment]
Hi @idoshamun ,

Yes I translate it into French, maybe that's the cause of the problem?

**Comment by idoshamun** [comment]
Yes definitely
