### ISSUE TITLE
🐛 BUG:  Unable to Access Own Comment from a Notification on an Old Post

### ISSUE THREAD

**Issue by ms-solly** [dailydotdev/daily#1455]
### What went wrong? 🤔

I started using Daily.dev 4 days ago, and I received a notification about a 4-month-old post where someone tagged me. However, when I try to access the comment from the notification link, I'm unable to see the comment on the post.

Here's the post link from the notification:
https://app.daily.dev/posts/xit7FoDUw#c-qMFHSbJLj

Additionally, when I try to access my own comment on the same post (which I can view by going through my profile and replies), I still can't view it directly via the comment link:
https://app.daily.dev/posts/xit7FoDUw#c-poYA0RVS8

The issue might be related to multiple comments on the post, and it affects older posts specifically. The links to the comments don't display the corresponding content, even though I can see them through the profile and replies section.

### Expected Behavior

It is expected that when user clicked the link from the notification, it would take user directly to the specific comment where user  was tagged, allowing user to view the entire conversation without any issues.

### Steps to Reproduce Issue

```bash
1. Go to notifications section
2. Click on comment notification from an older post (e.g., a 4-month-old post).
3. Attempt to view the comment in the post using the provided link.
4. Observe that the comment is not visible, even though it should be.
```

### Solution Proposed

One potential solution is to verify the comment links for old posts to ensure that they direct users to the correct section of the post. The system should properly handle comment threads and load all associated comments regardless of the post's age.

Additionally, implementing sorting options like "Oldest" and "Latest" for comments may help users quickly locate specific comments. This could be an easier way to ensure the correct comment is found, even on older posts. Other possible solutions could involve refining how the system anchors to specific comments, though I’m unsure of the exact technical changes needed to make this work correctly when navigating to a particular comment.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Additional Context

```bash
I've only been using Daily.dev for few days, but this issue occurred when trying to access a comment from 4 months ago post . The comments can be seen through profiles and replies, but not through the direct link provided in the notifications.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by Atul-Shivnani** [comment]
Can't see such issue, is it only with old posts? 
(while going through the comments directly through the post)
![post link](https://github.com/user-attachments/assets/219e4239-3bba-4345-9420-11aaa02590d5)

from the notification you're directly navigated to that comment and the comment is highlighted by a purple border as well
![highlighted comment](https://github.com/user-attachments/assets/0a807687-0db1-4597-a2f2-eda2e2a47299)

**Comment by ms-solly** [comment]
yes I guess . 
The issue seems to occur specifically with older posts that have a large number of comments. For example, one post I tried to access has 1.4k comments, and they are organized from top to bottom, showing the oldest comments first. Even after scrolling to the very bottom to see the most recent comments, I only found comments from a month ago, not the one I received a notification for just a few days ago.

This indicates that the problem isn't just limited to old posts but also affects the visibility of recent comments on these posts.

**Comment by idoshamun** [comment]
@ms-solly you're right. we have issues supporting very long threads. we will look into it

**Comment by ms-solly** [comment]
@idoshamun Thanks for the update! I noticed that the sorting options (oldest/newest) have been added, and I can now access specific comments from old posts using the notification link. However, it’s taking quite a bit of time to load. Since the main issue seems to be resolved, I will be closing this issue soon.
