### ISSUE TITLE
🐛 BUG: Customize button is disabled

### ISSUE THREAD

**Issue by ozgrozer** [dailydotdev/daily#1456]
Created a new squad. Deleted the first (welcome) post. Now the Customize button is disabled and cannot complete this checklist.

Screenshot below
![Screenshot 2024-09-26 at 4 20 33 PM](https://github.com/user-attachments/assets/35c6dbe3-66bc-4f7a-9a25-948f60796044)

**Comment by idoshamun** [comment]
Hi @ozgrozer,

Please share here your squad handle so we can fix that

**Comment by ozgrozer** [comment]
It's thenextaitool

**Comment by derin-art** [comment]
Hi, I would to work on this

**Comment by idoshamun** [comment]
@ozgrozer that's fixed now :)

**Comment by ozgrozer** [comment]
@idoshamun Are you sure? Because customize button is still disabled.

**Comment by ozgrozer** [comment]
Customize button was disabled but I see that you guys bring back the welcome post so I've manually edited that post and the issue is resolved.
