### ISSUE TITLE
🐛 BUG: received email even though I disactivated email notifications

### ISSUE THREAD

**Issue by JosephChataignon** [dailydotdev/daily#1459]
### What went wrong? 🤔

I just received an email titled "Did you get your verified badge?", while I disactivated all email notifications. 
I double-checked the email settings and it looks like one category cannot be disactivated : "System alerts (security, privacy, etc.)", but this email should belong to  that category.

### Expected Behavior

I expect not to receive update emails when I disactivated all email notifications.
By the way, not allowing users to completely disactivate email notifications is probably illegal in many jurisdictions.

### Solution Proposed

Temporary solution: I blocked all emails from daily.dev

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @JosephChataignon,

This email is part of the "Product Tips" category. There should be an unsubscribe link in the email body.
Anyway, we're planning to simplify the categories as we got several complaints about that.
