### ISSUE TITLE
🐛 BUG: Mouse over animation loop

### ISSUE THREAD

**Issue by cynicaljoy** [dailydotdev/daily#146]
## 🐛 Bug Report

Mouseover effect looping endlessly

### What went wrong? 🤔

Animation loop causes poor user experience

### Steps to Reproduce Issue

If you place your cursor at the bottom edge of a tile it will cause the loop, see attached screen recording

#### Operating System

mac OS 10.15.4

#### Version of Daily

Chrome homepage

#### Browser

Chrome 80.0.3987.163
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

[daily-mouseover-screencap.zip](https://github.com/dailydotdev/daily/files/4457725/daily-mouseover-screencap.zip)

**Comment by idoshamun** [comment]
Hi @cynicaljoy,

Thanks for reporting this issue and dedicating the time.
Would you like to contribute a fix?
I will be happy to guide you through :)
