### ISSUE TITLE
🐛 BUG: When user share cross post from one squat to another squat -> will generate a 500 error

### ISSUE THREAD

**Issue by leamsigc** [dailydotdev/daily#1460]
### What went wrong? 🤔

Bug replication can be found in https://app.daily.dev/squads/nuxtandvue  { "statusCode": 500, "error": "Internal Server Error" }

![image](https://github.com/user-attachments/assets/b864a0cd-28b9-44cb-b348-98fabbe14842)

### Expected Behavior

Is that when the user hovers over the card and click on the link, the user will get redirected to the actual article

### Steps to Reproduce Issue

```bash
1. Go to https://app.daily.dev/squads/nuxtandvue
2. Hover on the card that have the article "Promises in Vue – how to do api requests correctly" 
3. Click on the "Read post" link
4. See the error
```

### Browsers

Firefox

### OS

Linux

### Version of daily.dev

Web version

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @leamsigc,

Thanks for the report. We will look into it

**Comment by nensidosari** [comment]
Hi @leamsigc, this issue is now fixed.
