### ISSUE TITLE
🐛 BUG: Change email when access lost?

### ISSUE THREAD

**Issue by edgyrich** [dailydotdev/daily#1461]
### What went wrong? 🤔

I cannot change my email/login because I’ve lost access to my old Google Workspace account. How can i change my email address from rich.tatum@edgylabs.com to rich.tatum@gmail.com?

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

I could update this account with my SMS and you could text me? Or we could use an authenticator app?

I can set up a new account, but I want to keep my id. (richtatum)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @edgyrich,

Please shoot us an email to support at daily.dev and we will take it from there.
