### ISSUE TITLE
🐛 BUG: lost streak after restoring it

### ISSUE THREAD

**Issue by jkinami** [dailydotdev/daily#1464]
### What went wrong? 🤔

I was able to restore my streak from the notification but after a few hours I lost my streak somehow. 

### Expected Behavior

It should have kept my streak for another day.

### Steps to Reproduce Issue

```bash
1. Go to 'Notifications'
2. Click on 'Oh no! Your 30 day streak has been broken - Click here if you wish to restore your streak'
3. Nothing happens
```

### Solution Proposed

Potentially a timezone issue. I live in Japan and I restored my streak right after 12 midnight when I lost my streak. I might have lost my streak again due to timezone issue.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 11 Home - Chrome Version 129.0.6668.60 (Official Build) (64-bit)

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

Latest Prod version

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by jkinami** [comment]
![image](https://github.com/user-attachments/assets/9ab122fb-9107-4ef6-a55b-5f7e4fac3575)

**Comment by idoshamun** [comment]
Hi @jkinami,

Few questions to help me investigate the issue:
* On the day you restored your streak, have you read a post?
* Please check that your timezone is set correctly here: https://app.daily.dev/account/notifications

**Comment by jkinami** [comment]
Hi Ido,

Thank you for looking into this.

Below are the steps I took to restore my streak.

I restored my streak between 12am-1am japan local time then went to bed. My
streak was restored and went to bed after waking up around 9am, I noticed
my streak reverted to zero. I read a post immediately and it became 1
streak.

I just checked my timezone and it is the correct time zone (UTC +9)

Thank you again,
Junichi

**Comment by idoshamun** [comment]
Thanks for the info. We will check it

**Comment by sshanzel** [comment]
Hi @jkinami, can you share your user handle? Just so I can check the right details. Thank you!

**Comment by jkinami** [comment]
Hi Lee,


Attaching a screenshot of my profile.

My handle is @jkinami

**Comment by sshanzel** [comment]
Hi @jkinami. After further investigation, you should have indeed kept your streak, all things considered. For that, I have manually fixed your streak to the around. Hope you like what you will see when you log back in.

As for the root cause, we are still investigating, and we've added some ways to help us further debug these cases.

**Comment by jkinami** [comment]
Thank you so much!
