### ISSUE TITLE
🐛 BUG: Unable to scroll in Search suggestions dropdown 

### ISSUE THREAD

**Issue by alphapuppey2** [dailydotdev/daily#1469]
### What went wrong? 🤔

the search dropdown exceeds my screen . tried to zoom out my browser because i got the feeling that there is more searched ,i just found out that it has more searched suggestions it did not show because my screen are too small for the dropdown to be displayed all the search suggestion 

default view
![image](https://github.com/user-attachments/assets/bc083968-40f2-4752-85b5-f3a2571a1dbd)
-- Zoom out 

![image](https://github.com/user-attachments/assets/dd9515f9-e3b3-4f60-bc95-2c9e128c4036)

### Expected Behavior

i expect that the search dropdown is scrollable 

### Steps to Reproduce Issue

```bash
1. Go to 'home'
2. Click on 'search bar'
3. Search Something
4. try to zoom out your browser you show all the search suggestions
```

### Solution Proposed

search suggestion to be Scrollable for all devices with small screens 

### Screenshots

```bash
default view
![image](https://github.com/user-attachments/assets/bc083968-40f2-4752-85b5-f3a2571a1dbd)
-- Zoom out 

![image](https://github.com/user-attachments/assets/dd9515f9-e3b3-4f60-bc95-2c9e128c4036)
```

### Browsers

Brave

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @alphapuppey2,

If you submit the search, you can scroll and do whatever you like.
Can you confirm please?

**Comment by KILLERTIAN** [comment]
![image](https://github.com/user-attachments/assets/e6f231aa-f3b0-4cda-b8b8-a36261e3241d)
I tried searching different things and it looked perfect, maybe the taskbar is the issue

**Comment by ashish-maurya531** [comment]
@alphapuppey2 @dailydotdev can I start the work on this issue

**Comment by sshanzel** [comment]
Hi @ashish-maurya531! I've assigned the issue to you now. Good luck! Let me know if you need any help.

For the fix, kindly set a `max-height` of the dropdown to 480px. Kindly use our GitPod environment for the development, it can be found in our repo's README 🙌

**Comment by PredictiveManish** [comment]
Is this issue is solved or pending??

**Comment by ashish-maurya531** [comment]
@PredictiveManish @sshanzel  done i have solved the issue. Plz merge it

**Comment by sshanzel** [comment]
> @PredictiveManish @sshanzel done i have solved the issue. Plz merge it

Hi. May I know where you tried to fix it? There is currently no PR related to this issue.

**Comment by sshanzel** [comment]
> Is this issue is solved or pending??

The issue is still open 🙏

**Comment by ashish-maurya531** [comment]
@sshanzel i have commited the changes on Gitpod, how can i raise the PR 
![image](https://github.com/user-attachments/assets/8db31078-33bc-4913-8829-67b791339957)

**Comment by ashish-maurya531** [comment]
@sshanzel  **look generated Pull request. New to GitPod that's way it takes time to understand**

**Comment by sshanzel** [comment]
> @sshanzel **look generated Pull request. New to GitPod that's way it takes time to understand**

All cool! No worries about it. Let me know if you need further help 🙏

**Comment by sshanzel** [comment]
This should have been [fixed](https://github.com/dailydotdev/apps/pull/3650) by now. Thank you so much for your work @ashish-maurya531 🙏 ❤️

**Comment by ashish-maurya531** [comment]
@sshanzel thanks 👍
