### ISSUE TITLE
🧩 FEATURE REQUEST: A ToDo Menu

### ISSUE THREAD

**Issue by aashutoshrathi** [dailydotdev/daily#147]
## Feature Request

A today menu like we used to have in Momentum.

### Description

This will help me keep track of todos and I won't have to keep track of the same things somewhere else.
Also, they can be synced with user account.

**Comment by idoshamun** [comment]
Hi @aashutoshrathi,

Thanks for the feature suggestion.
Unfortunately, this idea is out of our scope so we will not proceed with implementing it.

**Comment by dror-weiss** [comment]
Actually, I was looking for the same exact feature, rather than focusing on **Momentum's Notes**.
The fact that I open the new tab and see all the latest feed PLUS my notes helps a lot, in my opinion.

@idoshamun , please re-consider.

**Comment by idoshamun** [comment]
Hey @dror-weiss,

I will raise this issue in the next product planning meeting.
Bear in mind that we are a small team with a full backlog so I can't promise anything.
Thanks :)
