### ISSUE TITLE
🐛 BUG: Reputation decrease

### ISSUE THREAD

**Issue by roshanphuyal-dev** [dailydotdev/daily#1473]
### What went wrong? 🤔

I had my reputation above 220 yesterday but today when openning the app it was only in 120 reputation points.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @roshanphuyal-dev,

Please see here how you can lose reputation: https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points
