### ISSUE TITLE
🧩 FEATURE REQUEST:  Character limit for the post has to be increased to 8000 characters.

### ISSUE THREAD

**Issue by Balaji-Batchu** [dailydotdev/daily#1477]
### Concise Description

Character limit for the post has to be increased to 8000 characters

### Description

As a technical blog writer, I loved Daily.dev very much however keeping the post size limited to 4000 characters is too short which affects on post for example in my case I always want to explain any new topic with examples that make the reader or newbie understand the topic easily, but due to the limited (4000 characters) I am not able to explain the topic in detail. This may cause bloggers to approach different platforms like medium to write and then to post the link here which may reduce daily.dev blogger strength significantly. So I want to address the discomfort of having a very small post size. I am sure most of the users feel the same. On behalf of every blogger and daily.dev well wishes I hope my concern will be considered and make the changes in upcoming feature releases. 

Thank you team daily.dev 🤗

### Solution Proposed

I am proposing to make the post size double i.e, 8000 characters, which will help bloggers to explain the topic in depth to newbies.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Closing as it's dup of https://github.com/dailydotdev/daily/discussions/1476 which was opened by you 😅
