### ISSUE TITLE
🐛 BUG: Everything is daily.dev tab

### ISSUE THREAD

**Issue by codeokil** [dailydotdev/daily#1478]
### What went wrong? 🤔

Whenever I try to use a new normal tab it automatically becomes the daily—dev tab. I can't use the normal tab if I want to use one I have to turn off the extension.

### Expected Behavior

What I want is, when I click that extension it turns my feed into daily.dev feed otherwise I should be able to use my browser as I please.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

windows 11, chrome

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @codeokil,

Our browser extension is a new tab extension, meaning it opens daily.dev on every new tab. If you don't like it, you can use our webapp https://app.daily.dev. Enjoy!
