### ISSUE TITLE
🐛 BUG: Blogs Repeatation

### ISSUE THREAD

**Issue by Yuvadi29** [dailydotdev/daily#1479]
### What went wrong? 🤔

There are some blogs which are repeated more than once. I hope it can be fixed.

![image](https://github.com/user-attachments/assets/e6656858-d04b-418e-8f59-5d1f8237385d)
![image](https://github.com/user-attachments/assets/d2af27fc-8616-4e23-8fa0-e6519049ce4f)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Yuvadi29,

Thanks for reporting but I'm not sure exactly what I'm seeing. Can you elaborate please?

**Comment by Yuvadi29** [comment]
Hi @idoshamun , 
In the images i have shared above, you can see a blog with the name Building Production API services is repeated twice. The images shared are of 2 different rows containing the same blog.

**Comment by idoshamun** [comment]
Thanks a lot for the clarification. We will look into it

**Comment by rebelchris** [comment]
@allentv would you mind sending your dailydev userID either here or via email to `chris[at]daily.dev` 
You can find it via: https://api.daily.dev/id

**Comment by rebelchris** [comment]
Thanks for all the reports, we identified a issue on our caching layer and it should now be solved. 🙏
