### ISSUE TITLE
🧩 FEATURE REQUEST: Github trendings 

### ISSUE THREAD

**Issue by fparol4** [dailydotdev/daily#148]
### Description

We can add a guide to show trend repositories and github users with small filters, i think it's simple and will save time.

### Solution
Actually, i already know two extensions who do this, and i think its a good way:

#### 1 - Hackertab
![image](https://user-images.githubusercontent.com/47286899/79082108-aaa71900-7cf9-11ea-9e61-c94534c05ab4.png)
[Extension link](https://github.com/huchenme/hacker-tab-extension)
#### 2 - Devo
![image](https://user-images.githubusercontent.com/47286899/79082122-c3afca00-7cf9-11ea-987a-5e3a0f2bd0f4.png)
[Extension link](https://chrome.google.com/webstore/detail/devo/elkhalpmbmbaeoemecpcfdcoekmpgmdm/related?hl=en)

Thankxs, and sorry my bad english

**Comment by idoshamun** [comment]
Hi @fparol4,

Thanks for the feature suggestion and don't be sorry for your English :wink: 
Do you know what API those extensions use behind the scenes?

**Comment by fparol4** [comment]
Hi @idoshamun, thank you for be gentle 

Shure, these extensions consume this [API](https://github.com/huchenme/github-trending-api)
Basically, we have two main endpoints with some filters

**Repositories**
https://github-trending-api.now.sh/repositories?language=javascript&since=weekly
**Developers**
https://github-trending-api.now.sh/developers?language=javascript&since=weekly

**Comment by fparol4** [comment]
I think we can have some tab here, who show up the new layout for trending

![image](https://user-images.githubusercontent.com/47286899/79124784-72442100-7d73-11ea-8acf-f7bbcc6cb403.png)

Or more simple, following the existent structure, just adding more one resource

**Comment by idoshamun** [comment]
Thanks for sharing this awesome information!
Due to the current situation we are focused on other things, but I'll add it to our checklist.
I'll sure keep you posted :)
