### ISSUE TITLE
🐛 BUG: The mobile APP is not recording the streak, 

### ISSUE THREAD

**Issue by JenuelDev** [dailydotdev/daily#1481]
### What went wrong? 🤔

Im trying to stay on my streak but last friday, I thought my streak is good because I opened the android app multiple times but it did not record the streak last friday.

### Expected Behavior

When opening the android app and reading some articles on it should record my daily streak

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Streak is kept only when reading a post, it is not enough to just open the app.
Can you confirm that you read a post on Friday?

**Comment by JenuelDev** [comment]
yes, I always do read post. I think I always open daily dev everyday to read articles.

**Comment by idoshamun** [comment]
Do you perhaps have any cookie blockers or open the article link in different browser or anything that can mess our authentication?

**Comment by JenuelDev** [comment]
I am not sure.. oh, it seems its fixed now. Its working now.
