### ISSUE TITLE
🐛 BUG: Can't find the comment that someone replied to

### ISSUE THREAD

**Issue by AliYar-Khan** [dailydotdev/daily#1483]
### What went wrong? 🤔

  When I click a notification of a comment reply, it goes to that post but doesn't show the comment that was replied to

### Expected Behavior

When I click a notification of a comment reply, it should go to that post and show the comment that was replied to.

### Steps to Reproduce Issue

```bash
1. Go to Notifications.
2. Click on notification of post where someone replied to your comment
3. It doesn't show the comment
```

### Solution Proposed

Whenever someone reply to your comment it should be available on top or it should scroll down to that comment

### Environment

Windows 10, MicroSoft Edge

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

Latest

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @AliYar-Khan,

Can you please send here the relevant link?

**Comment by AliYar-Khan** [comment]
@idoshamun by link you means post link? here is the link https://app.daily.dev/posts/3xZ8I1PTS#c-mpYnYaVbc

**Comment by idoshamun** [comment]
@AliYar-Khan we currently have an issue directing to comments in a long thread 🙈

**Comment by AliYar-Khan** [comment]
Is it b_ing worked on? Can you mention the existing issue?

**Comment by AliYar-Khan** [comment]
I can try!! @idoshamun

**Comment by idoshamun** [comment]
@AliYar-Khan apparently @rebelchris already found the issue and proposed a fix (easier than we thought 😅 )
But maybe @sshanzel can point you to an issue available to pick
