### ISSUE TITLE
🐛 BUG:  difficulty of subscribing to a squad

### ISSUE THREAD

**Issue by Blaise5th** [dailydotdev/daily#1486]
### What went wrong? 🤔

Everytime I try to subscribe to a squad it  goes to a page asking "Didn't get a pop-up?" and I have tried nothing is clickable on it,
note is a mobile phone I am using 

### Expected Behavior

I was expecting it to subscribe to the squad 
![Screenshot_20241010-152856](https://github.com/user-attachments/assets/af3038e0-4873-486a-bdb2-eed3ad12d35b)

### Steps to Reproduce Issue

```bash
1. Go to squad at the bottom of my mobile device and click it, 
2. Then Click on view
3. Click on the ✓ checkmark that's inside a box
4. The error occurs when you click subscribe
```

### Environment

My mobile phone 

### Browsers

Other

### OS

Android

### Version of daily.dev

Current version 

### Additional Context

```bash
Sorry don't have anything else
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Blaise5th,

Thanks a lot for the report, we will look into it!

**Comment by sshanzel** [comment]
@Blaise5th are you still able to reproduce this? I think this was fixed with a recent change that Chris made in handling PNs. Feel free to reopen if it is still reproducible 🙏
