### ISSUE TITLE
🐛 BUG: null value on my notification screen

### ISSUE THREAD

**Issue by EdwardduPlesses** [dailydotdev/daily#1488]
### What went wrong? 🤔

On my Notification screen, I am getting a null value (This was with the new bookmark reminder feature)

### Steps to Reproduce Issue

```bash
1. Bookmark a post
2. Set a 24H reminder
3. Next day when viewing notifications see the null value (I don't know what this value is supposed to be)
```

### Screenshots

<img width="747" alt="image" src="https://github.com/user-attachments/assets/494942ec-3ab6-471b-abc9-f2557f3cacef">

### Browsers

Other

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@EdwardduPlesses Thanks for logging I can replicate it.
Will look into this issue.

**Comment by rebelchris** [comment]
![Screenshot 2024-10-14 at 12 37 18](https://github.com/user-attachments/assets/c2ba147e-e7b6-4ccf-aabc-2686f563858e)

Just to confirm I tried one that was broken before, and it now renders.
