### ISSUE TITLE
🧩 FEATURE REQUEST: Clearer date format in card footers

### ISSUE THREAD

**Issue by DamianoMagrini** [dailydotdev/daily#149]
### Description

Currently, in each article's footer, publication time/date is shown according to the following algorithm:
* if the post is less than 1 minute old, show "now";
* else, if less than 1 hour old, show "(number of minutes)m ago";
* else, if less than 48 hours old, show "(number of hours)h ago";
* else, show the date when it was published.

While this is not a terrible approach, it can lead to results such as "41 hours ago", which — at least to me, then tell me if I'm the only one who thinks this — sounds a bit weird.

The algorithm is located in the [mdyDateFilter.js](https://github.com/dailydotdev/daily-apps/blob/master/packages/components/src/common/mdyDateFilter.js) file. I can work on this and submit a PR, but I'm not quite sure about the algorithm to implement.

### Solution

Changes would need to be made to [mdyDateFilter.js](https://github.com/dailydotdev/daily-apps/blob/master/packages/components/src/common/mdyDateFilter.js). While I'm not certain about what could be a better implementation, I believe something roughly like this could work (the first couple of statements are the almost same as the current implementation):
* if less then 1 minute old, show "now";
* else, if less than 1 hour old, show "(number of minutes) minutes ago";
* else, if less than 1 day (not 2) old, show "(number of hours) hours ago";
* else, if less than 1 week old, show "(number of days) days ago"; **Edit:** or "Yesterday"
* else, if less than 1 month old, show "(number of weeks) weeks ago"; **Edit:** or "Last week"
* else, if less than 1 year old, show "(number of months) months ago"; **Edit:** (etc.)
* else, if less than 1 decade old, show "(number of years) years ago";
* else, show "(number of decades) decades ago".

The two main changes I made are:
1. for consistency, I didn't switch from relative to absolute but kept the relative format throughout;
2. I extended contractions (i.e. m → minutes).

I'm clearly open to improvements, this is just a first draft. Please let me know what you think.

**Edit:** I have just realized that this solution might be a bit tricky to implement. This is because, while hours and days are universal ("2 days ago" is "2 days ago" both in March and July), things get a bit more complicated with weeks, months, years, and decades (i.e. "11 months ago" can be both "11 months ago" or "Last year", based on the current month). Still, it shouldn't be *that* complicated to implement.

**Another edit:** [discussion on this topic from a UX standpoint](https://ux.stackexchange.com/questions/24017/relative-dates-times-rounding-and-how-accurate).

(Yet another edit, note to self: remember to update the [tests](https://github.com/dailydotdev/daily-apps/blob/master/packages/components/__tests__/mdyDateFilter.js))

### Alternat*iv*e Solutions

N/A

**Comment by idoshamun** [comment]
Hi @DamianoMagrini,

Thanks for this very thoughtful improvement suggestion.
After discussing this matter with @tsahimatsliah, we would love to proceed with the implementation of your suggestion with one slight change that after one year we will display the exact date.
We believe that the date is important for things like product releases and such.
What do you think?

**Comment by DamianoMagrini** [comment]
Thanks for your feedback! I completely agree: the year alone would be too generic. I was thinking, also, that "# months ago" could be replaced by "This (if same year)/Last (if last year) (name of month)". "Last September" sounds a bit more natural than "7 months ago", don't you agree? I'll start working on this within the next couple of days, please tell me what you think.

**Comment by idoshamun** [comment]
Totally agree with your last comment. I would use the short month representation, to shorten the text.

**Comment by DamianoMagrini** [comment]
Just two questions. First, for dates that start with a letter (e.g. last May), should it be capital (i.e. "last May" or "Last May")? And second, should the short month representation only be used for full dates (i.e. "Apr 22, 2020") or also for "This/Last (month)"? Thanks in advance for your time.

**Comment by idoshamun** [comment]
It should be lowercase, except for the first letter of the month. Yes, we should use short representation for both cases.
In regards to tests, feel free to change them if you find it better approach :)
I'm looking forward to see your contribution already, thanks for everything.

**Comment by DamianoMagrini** [comment]
One shortcoming of my proposed algorithm is that, in some countries, weeks start on Sunday rather than Monday (ISO standard). Should I keep to the standard? I don't think there's a way to detect the user's preferred starting day with JavaScript…

An alternative approach would be to just remove the "last" format for weeks and just say "# week(s) ago" just by dividing the number of days by 7.

How do you think I should proceed?

**Comment by idoshamun** [comment]
You "alternative approach" sounds great :)
Regarding the test, I think your first suggestion is better. I also tend to favor static tests.
No worries about the question, by the way, it's totally fine :grin:
