### ISSUE TITLE
🐛 BUG: Unable to Submit Post on daily.dev via Android Device

### ISSUE THREAD

**Issue by vishxly** [dailydotdev/daily#1490]
### What went wrong? 🤔

I am unable to submit a post when using daily.dev on my Android device. The issue occurs specifically when I try to submit a post on the daily.dev platform, and the submit button  doesn't respond.

### Expected Behavior

I expected to be able to submit the post without any issues by clicking the submit button, and the post should appear successfully on the platform.

### Steps to Reproduce Issue

```bash
1. Open daily.dev on an Android device.
2. Go to the "Submit a Post" section.
3. Fill in the post details(Mostly i tried for Sharing a link)
4. Click on the "Post" button.
5. Notice that the post submission does not proceed.
```

### Solution Proposed

It might help to check the submit button functionality for mobile devices, particularly for Android, to ensure that the form is correctly sending data when clicked. Also, verifying any responsive behavior or errors related to touch input would be helpful.

### Screenshots

```bash
![Post Button Issue](https://raw.githubusercontent.com/vishxly/Certification/refs/heads/main/Post%20Button%20Issue.jpg)
```

### Browsers

Chrome

### OS

Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@vishxly Thanks for reporting, seems to be an issue there.
Looking into it now.

**Comment by rebelchris** [comment]
@vishxly Thanks again for logging this, published a fix just now :)

**Comment by vishxly** [comment]
Great, Now it is working fine!
