### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by gvgvgvijayan** [dailydotdev/daily#1493]
### What went wrong? 🤔

![Screenshot from 2024-10-12 17-23-12](https://github.com/user-attachments/assets/95dbf448-78b4-405b-99f3-c4568d686df1)
![Screenshot from 2024-10-12 17-23-00](https://github.com/user-attachments/assets/0ba2d251-b360-4614-82a2-0805c90ae7a4)

Move a little further back from your screen and see both icons, 90% of the time I got confused is I'm in incognito?

### Expected Behavior

The icon should be able to differentiate by as many people as possible, including poor vision persons too.

### Steps to Reproduce Issue

```bash
1. Open Firefox in incognito mode
2. Open another instance of Firefox which have daily.dev as home page
3. Now compare the fav icon of the daily.dev tab in normal window of Firefox with the incognito window's fav icon
4. It will be difficult to differentiate which window right now because the clue to differentiate whether I'm incognito or not is by seeing the fav icon
5. Both daily.dev and Firefox incognito fav icon is nearly identical when we see in decent distance for example 2 feet away from the screen or more for 15.7 inch laptop with 1080p display resolution
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Ubuntu, but I assume this issue will be universal irrespective of any desktop OS.

### Browsers

Firefox 131.0.2

### OS

Ubuntu 24.10

### Version of daily.dev

3.32.0

#### Last Updated:
24 June 2024

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by dineshsutihar** [comment]
Hey @gvgvgvijayan   I'd like to work on it, but could you please tell me the steps to reproduce the issue first?

**Comment by gvgvgvijayan** [comment]
Hey @dineshsutihar thanks. I updated the issue comment. Please let me if anything else required.

**Comment by idoshamun** [comment]
Hi @gvgvgvijayan,

Thanks for the report but we have no plans of changing our logo colors.
This color is part of our design system and is used everywhere
