### ISSUE TITLE
🧩 FEATURE REQUEST:  Add LinkedIn provider to register using LinkedIn

### ISSUE THREAD

**Issue by Shaiq1217** [dailydotdev/daily#1495]
### Concise Description

Adding LinkedIn as a provider to daily.dev 

### Description

I would like to suggest adding LinkedIn as a provider besides Google and Github. Since, most people are interacting through various platforms including LinkedIn, I feel that implementing a registration with LinkedIn. 

### Aim
The eventual aim is to be able to allow connections to interact with my daily.dev and streamlining the interaction between the two platforms. This has the potential of making it easier to find more connections and to leverage my connections on LinkedIn

 

### Implementation
Since there are already providers that are being mapped to implement registration, to include LinkedIn would be fairly straight forward. The Login Flow already includes implementation for google so we can just leverage that to include LinkedIn.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Shaiq1217,

Thanks for the suggestion but currently it is out of scope for us.
Most users just login with Google, very few with GitHub and whoever wants to use email does that.
