### ISSUE TITLE
🐛 BUG: text overflow issue on the post side widget

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1496]
### What went wrong? 🤔

When a link is part of the Squad's description, it overflows like below.

Quick link: https://dly.to/Z36wbkFJyc8

![image](https://github.com/user-attachments/assets/f7118d61-bb1f-4727-bde8-f23107062516)

### Expected Behavior

It should just wrap the text to the next line.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by Abhi-Bohora** [comment]
Hello @sshanzel can you please assign this to me

**Comment by sshanzel** [comment]
@Abhi-Bohora why not. Feel free to take a peek 🚀

**Comment by Abhi-Bohora** [comment]
Hello @sshanzel I can see this in production but in development, I cannot figure out how to reproduce this as per my understanding it needs two accounts one to create a squad and write some overflowing URL in the squad description or some squad with a link in the description. is there a way to create two accounts in development or some ways to reproduce this so i can fix this ? also if I create squad or click on `Public squad`  in gitpod development environment it redirects me to localhost `http://localhost:5002/squads/testsquad` from gitpod environment and gives me `This site can’t be reached` in page

**Comment by sshanzel** [comment]
> Hello @sshanzel I can see this in production but in development, I cannot figure out how to reproduce this as per my understanding it needs two accounts one to create a squad and write some overflowing URL in the squad description or some squad with a link in the description. is there a way to create two accounts in development or some ways to reproduce this so i can fix this ? also if I create squad or click on `Public squad` in gitpod development environment it redirects me to localhost `http://localhost:5002/squads/testsquad` from gitpod environment and gives me `This site can’t be reached` in page

Creating the Squad went through, the issue is with the URL from the sidebar as it is an absolute path. With GitPod it should actually be different. To get past this, once you have created the Squad, manually type in the URL bar the hostname of the gitpod env +  `/squads/testsquad`.

**Comment by Abhi-Bohora** [comment]
@sshanzel I tried this but got this error please see the screenshot. my gitpod is running in `https://5002-dailydotdev-apps-vwf4wjsihxt.ws-us116.gitpod.io/` and I have just created the `testsquad` and when I enter `https://5002-dailydotdev-apps-vwf4wjsihxt.ws-us116.gitpod.io/squads/testsquad` in URL I get the error shown in the screenshot.
![1](https://github.com/user-attachments/assets/05d0fd16-8106-481b-82a8-a672f5f9fd71)
Error
![2](https://github.com/user-attachments/assets/06670ab5-5418-4389-b2f4-5708d5aefdf3)

**Comment by satvik2131** [comment]
Yes , I am facing the same issue while using gitpod and created a separate issue for that 
https://github.com/dailydotdev/daily/issues/1502

**Comment by omBratteng** [comment]
Leaving this here if anyone wants a quick fix, just [change this line](https://github.com/dailydotdev/apps/blob/5508daae5031637a6f779c6f6b22ca3fb5982bf9/packages/shared/src/components/post/SquadPostWidgets.tsx#L48) from

https://github.com/dailydotdev/apps/blob/5508daae5031637a6f779c6f6b22ca3fb5982bf9/packages/shared/src/components/post/SquadPostWidgets.tsx#L48

```html
<p className="mt-1 text-text-tertiary typo-callout">
```

to

```html
<p className="mt-1 overflow-hidden text-ellipsis text-text-tertiary typo-callout">
```

**Comment by rebelchris** [comment]
Closing this!

Thanks for the fix @Abhi-Bohora 🍻
