### ISSUE TITLE
Daily Dev Email Broken Link for Apple option "Add to Home Screen"

### ISSUE THREAD

**Issue by faraz-b** [dailydotdev/daily#1498]
The Apple option "Add to Home Screen" redirects to the Google play store daily dev app.

**Comment by nimrodkra** [comment]
Can you please share a screenshot of the UI you're currently looking at? I
couldn't reproduce it

**Comment by faraz-b** [comment]
Sure, attached a quick video below. As well as a snippet of the HTML source  of the email - sent on  Sun, Oct 13, 2024 at 12:32 AM. 

https://github.com/user-attachments/assets/b7d5b47e-038a-4be7-af86-cc8c35c1d1f9

```html
... removed for brevity 
iconGet it on Google Play ( https://play.google.com/store/apps/details?id=
=3Ddev.daily&hl=3Den_US )

iconAdd to Home Screen ( https://play.google.com/store/apps/details?id=3Dde=
v.daily&hl=3Den_US )

Explore ( https://app.daily.dev/posts ) =C2=A0 | =C2=A0 Discussions ( https=
://app.daily.dev/discussed ) =C2=A0 | =C2=A0 Tags ( https://app.daily.dev/t=
ags ) =C2=A0 | =C2=A0 Sources ( https://app.daily.dev/sources ) =C2=A0 | =
=C2=A0 Leaderboard ( https://app.daily.dev/users )
removed for brevity ...
```

**Comment by nimrodkra** [comment]
Wow what a great catch! Thank you for that. I've applied a fix and it
should be sorted going forward

**Comment by faraz-b** [comment]
You're a legend, thank you for the quick response and fix. Cheers!
