### ISSUE TITLE
🐛 BUG: ToolTip Floats Inaccurately

### ISSUE THREAD

**Issue by AlaguSelvan** [dailydotdev/daily#150]
### What went wrong? 🤔
tooltip component is shown inaccurately.

### Expected Behavior
Expecting Tooltip to be shown above its value.

### Steps to Reproduce Issue
![bugreportDaily](https://user-images.githubusercontent.com/34230909/79734124-d3d83280-8313-11ea-82bf-afdd7d50367c.gif)

### Environment
Windows 10 Pro
Chrome Version 80.0.3987.163 (Official Build) (64-bit)

#### Operating System
Windows 10 Pro
#### Browser
Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi @AlaguSelvan,

Thanks for catching this annoying bug :sweat: 
Would you like to help us resolve this issue or should I proceed?

**Comment by AlaguSelvan** [comment]
You can proceed with this, I haven't worked with vue😅.

**Comment by idoshamun** [comment]
Fix will be released as part of v2.14.6
