### ISSUE TITLE
🧩 FEATURE REQUEST:  More Shortcuts slots

### ISSUE THREAD

**Issue by Nasrallah-AL** [dailydotdev/daily#1500]
### Description

I used to save a lot of websites into my shortcuts, but you offer a very limited number of slots.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Nasrallah-AL,

Thanks for the suggestion. This is a dup of https://github.com/dailydotdev/daily/discussions/1387
