### ISSUE TITLE
🐛 BUG: can't mute thread

### ISSUE THREAD

**Issue by AlexandreGoldstein** [dailydotdev/daily#1504]
### What went wrong? 🤔

I did comment on a thread but never followed it or whatever, even since i get daily notification that someone replied to me, so i tried to mute this thread to stop those notification, mute is not working i'm still notified
![bugdaily](https://github.com/user-attachments/assets/f60fee58-011a-44e1-8ef4-f568541fa968)

### Expected Behavior

mute thread should mute thread ?

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](.png)
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @AlexandreGoldstein,

Thanks for reporting. We will look into it

**Comment by rebelchris** [comment]
Hi @AlexandreGoldstein,

Trying to look into the issue, but struggling to find which one your user is in this comment thread.
Could you point me to either your username on daily.dev or user id?
https://api.daily.dev/id

**Comment by AlexandreGoldstein** [comment]
Haohmaru444. Btw it seems fixed‚ or no one answered on this thread anymore but i don't get notifications anymoreAlexandre GoldsteinLe 5 nov. 2024 10:16, Chris Bongers ***@***.***> a écrit :
Hi @AlexandreGoldstein,
Trying to look into the issue, but struggling to find which one your user is in this comment thread.
Could you point me to either your username on daily.dev or user id?
https://api.daily.dev/id

**Comment by rebelchris** [comment]
@AlexandreGoldstein A major thanks to your report.
We identified some issues and resolved them now :)
