### ISSUE TITLE
🐛 BUG: Where did you hear from us appears everyday even if i fill it in

### ISSUE THREAD

**Issue by AoiRei** [dailydotdev/daily#1505]
### What went wrong? 🤔

"Where did you hear from us" box appears every day, even if i fill it in.

### Expected Behavior

After filling it in it will never appear again.

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev'
2. Click on 'The box "Where did you hear from us" select "Youtube" and submit'
3. Come back again next day and see the same box with the same question.
```

### Solution Proposed

After filling it in it should never appear again.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Other

### OS

Windows

### Version of daily.dev

latest

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @AoiRei,

This card gets set with a query param. Please make sure to remove it and you will never see it again :)

**Comment by AoiRei** [comment]
True, it was ?ua=true which i bookmarked.
