### ISSUE TITLE
🐛 BUG: Google is not available after one Search Request

### ISSUE THREAD

**Issue by marcelweikum** [dailydotdev/daily#1512]
### What went wrong? 🤔

When I search for something in the top bar, I also get Google as option.
![{B5663BC6-EE6B-4F59-BB86-AB691EB4BF69}](https://github.com/user-attachments/assets/76444e51-7578-4fbb-b5e3-e27b27989d02)

When I click on Search Post instead of Google and want to Google afterwards, Google is gone:
![{96E24712-4493-47A6-8499-7B29AF0D28A6}](https://github.com/user-attachments/assets/59b995c4-669e-4353-bb8a-dba6ab055f60)

Reloading the site doesn't help, I have to close the tab and reopen it.

### Expected Behavior

Google should always be available as search option

### Steps to Reproduce Issue

```bash
1. Go into Search bar
2. Search 'Test' and press enter
3. Go into Search bar again
4. Search 'Test' and see, there is no more Google
```

### Solution Proposed

I would like Google to always be available as search option

### Environment

Windows 11

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@marcelweikum We only offer the search with google option on our browser extension due to the native experience.
You won't see it if you hit our webapp (`https://app.daily.dev`) hope that explains the behaviour.

**Comment by marcelweikum** [comment]
@rebelchris Wow thank you for the quick answer.
That explains it!

#1513 is therefore related to the browser extension
