### ISSUE TITLE
🐛 BUG: md on share a link not displaying correctly

### ISSUE THREAD

**Issue by kris007iron** [dailydotdev/daily#1516]
### What went wrong? 🤔

When I shared a new link I used ** ** to bold one word and in the preview it was correct, but after posting it just showed asterisks around the word.

### Expected Behavior

Bolded words in the description of a shared link

### Steps to Reproduce Issue

```bash
1. Go to 'Share a link'
2. Use ** ** to bold a word
3. Post it on a squad
4. See the error - not correctly bolded word
```

### Solution Proposed

Apply same mechanism as to a preview mode where it displays md correctly
![Screenshot 2024-10-17 175651](https://github.com/user-attachments/assets/5118abd3-15a5-4d05-b016-84bae1c28fab)

### Screenshots

```bash
I cant paste it here so i added it in previous section
```

### Environment

Windows 10, Google Chrome

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [x] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @kris007iron,

Can you please share a link to the post?

**Comment by kris007iron** [comment]
https://app.daily.dev/posts/elasticsearch-mixed-with-kibana-can-provide-uncountable-ways-to-portray-logs-but-when-it-comes-to-sh-is90hdxxt

**Comment by sshanzel** [comment]
Hi @kris007iron, MD is not accepted on shared titles other than mentioning another user.
