### ISSUE TITLE
🧩 FEATURE REQUEST: Tooltip for Long Titles

### ISSUE THREAD

**Issue by cagdas001** [dailydotdev/daily#152]
### Description

I'm using the Chrome extension. Long titles have been cutting off by three dots in the card view. There is no way to display the full title within the extension tab, without opening the link. See the screenshot below, where you can see the title ends with three dots. Hovering on the card doesn't show any helpful info about the title nor the page itself. (tooltip etc.)

![2020-05-06_21-51-01](https://user-images.githubusercontent.com/28513447/81251453-fbc1d880-902b-11ea-9473-bd0b61d0eb0c.png)

### Solution

As a solution, the full text title could be shown upon hovering on the card, something similar to [tooltips](https://bootstrap-vue.org/docs/components/tooltip). The tooltip style could be customized as well, depending the selected theme/mode.

### Alternate Solutions

If tooltip doesn't look good, this can be solved by another solution too.

For e.g., one more possible solution that comes to my mind, we can also enlarge the card size a bit, then can show the full title on the larger card so that it fits.

* On Hover (for 2 seconds)
  (if displayed title is not the full title)
  1. User hovers on the card for 2 seconds
  2. Card size is enlarged
  3. The full title takes place in the enlarged card, instead of the shortened (with three dots) title. Since the size is now larger, it will fit
* On Leave (mouse cursor leaves the card area)
  1. User leaves the card
  2. Card size is returned back to its initial state
  3. The card title is returned back to its shortened state, ending with three dots

If someone from the maintaining team confirms, I can make a contribution for this

Thanks

**Comment by idoshamun** [comment]
Hi @cagdas001,

Thanks for informing us about this matter. I believe it's a major accessibility issue that has to be addressed and I would like to proceed with your suggestion of implementing a tooltip.
I would be happy to get your contribution as you suggest and guide you through the process.
Regarding the implementation, we would like to utilize the default browser tooltip using the `title` attribute. Please take into account that you have to apply for both card and list view

**Comment by cagdas001** [comment]
Hi @idoshamun, thanks for your reply.

If your main concern is the accessibility, I'd like to let you know that, I think the current implementation would handle this situation becuse `aria-label` attribute contains the full text, even though the displayed text is cut off by three dots.

For example:
```html
<span aria-label="Google launches ‘Read Along,’ a free app that helps young children practice reading">Google launches ‘Read Along,’ a free app that helps young children p...</span>
```

I guess screen readers will be able to read the `aria-label` attribute.

However, IMHO, it still needs to be addressed since there is no way to display the full title without opening the link.

**Comment by idoshamun** [comment]
I still think it's an accessibility issue because although screen readers may read the title completely, users cannot, maybe not a traditional accessibility issue. I agree with you that this should be addressed

**Comment by baaraak** [comment]
If you want quick fix you can add 'title' attribute to the span, this will add the browser default tooltip

**Comment by idoshamun** [comment]
@baaraak thank you! This is what I suggested as well.
@cagdas001 would love to get your contribution :)
