### ISSUE TITLE
🐛 BUG: Restore streak not working

### ISSUE THREAD

**Issue by ray73864** [dailydotdev/daily#1526]
### What went wrong? 🤔

I lost my streak, I have 310 reputation, I received the notification, I click on 'Click here if you wish to restore your streak' and nothing happens.

This is the 3rd time I have lost my streak, the very first time I was able to restore it, the last 2 times I haven't been able to restore it.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome, Firefox, Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment]
Hi @ray73864, after further investigation, you should've been able to restore your streak last October 19. I will manually fix your streak in the meantime while we work on improving the experience 🙏

**Comment by ahm3draslan** [comment]
Same happened to me today, can't restore my streak lost yesterday !

**Comment by ray73864** [comment]
Lost my streak, click on notification, streak isn't restoring.

**Comment by sshanzel** [comment]
> Lost my streak, click on notification, streak isn't restoring.

Was there no sort of popup or anything after clicking the notification yesterday?

**Comment by sshanzel** [comment]
> > > Lost my streak, click on notification, streak isn't restoring.
> > 
> > 
> > Was there no sort of popup or anything after clicking the notification yesterday?
> 
> There was not, it just said that I lost my streak.

Interesting. No worries, I will check it again, and if it was indeed a bug within the app, I will restore your streak manually 🙏 

@ahm3draslan may I get your user ID to check your case? Kindly paste the result when visiting this page https://api.daily.dev/id

**Comment by ray73864** [comment]
I saw it once, a long time ago, and when I clicked it, it used reputation to restore it.

Now when I click on the notification, it does nothing at all.

Admittedly by the time the toast message appears, I've already clicked on something to view it, which then gives me a streak of 1, but that's because the system doesn't tell me my streak is broken until after I've clicked on something to view it.

**Comment by ahm3draslan** [comment]
> > > > Lost my streak, click on notification, streak isn't restoring.
> > > 
> > > 
> > > Was there no sort of popup or anything after clicking the notification yesterday?
> > 
> > 
> > There was not, it just said that I lost my streak.
> 
> Interesting. No worries, I will check it again, and if it was indeed a bug within the app, I will restore your streak manually 🙏
> 
> [@ahm3draslan](https://github.com/ahm3draslan) may I get your user ID to check your case? Kindly paste the result when visiting this page https://api.daily.dev/id

wLzbXM1vgwWm7CwaCG6Nd

**Comment by ray73864** [comment]
I'm still getting hit by this.

Forgot to read some stuff on Monday (Yesterday Western Australian time for me), go to check stuff this morning (Tuesday), and I see a message in my notifications about restoring streak.

Click it, URL updates to 'https://app.daily.dev/notifications?streak_restore=41', but my streak doesn't restore.

I then go to read something today, and I get another notification bubble, I click it, it takes me to my notifications, click on the new notification, still nothing.

**Comment by idoshamun** [comment]
@ray73864 please confirm that your timezone is up to date here: https://app.daily.dev/account/notifications

**Comment by ray73864** [comment]
> [@ray73864](https://github.com/ray73864) please confirm that your timezone is up to date here: https://app.daily.dev/account/notifications

It is indeed, shows as '(UTC +8) Perth'
