### ISSUE TITLE
🐛 BUG: following the source go to next article

### ISSUE THREAD

**Issue by BicheT0rdue** [dailydotdev/daily#1527]
### What went wrong? 🤔

i was watching a youtube video in my feed page and when i clicked follow, it quit to go to the next article of my feed and also made it disappear from the feed.

### Expected Behavior

- follow activate without influencing anything else
- feed stay the same 

### Steps to Reproduce Issue

```bash
1. Go to 'app.daily.dev'
2. Click on 'article with video'
3. play the video, i could reproduce when the youtube video was halfway, but not when it just started, tried unfollow and refollow too be didn't seem to do anything so i think following an unknown source is part of it
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

windows 11 on chrome Version 129.0.6668.103 (Official Build) (64-bit)

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment]
Hi. I can't seem to reproduce the issue. However, the only way you get to the next article is through keyboard navigation, by hitting the left or right arrow keys.
