### ISSUE TITLE
My reputation was reduced by 100 points

### ISSUE THREAD

**Issue by vijaydeepak-tt** [dailydotdev/daily#1528]
My reputation was reduced by 100 points for any specific reason. earlier it was 1.7K now it is 1.6K.
My id: @vijay_deepak

**Comment by idoshamun** [comment]
You can read here https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points about reasons for reputation penalty.

**Comment by vijaydeepak-tt** [comment]
@idoshamun can u check is that, is my reputation is reduced because any of my post has been banned or removed. If I get the reason I will correct the mistake I made.

**Comment by idoshamun** [comment]
You repeatedly shared paywalled content, which got reported and eventually banned

**Comment by vijaydeepak-tt** [comment]
but those links are free to view, and there are no restrictions, even though they are all also an issue? should I not. share that

**Comment by idoshamun** [comment]
you're right. medium ui is very confusing with friend links. I'll fix that

**Comment by vijaydeepak-tt** [comment]
thank you

**Comment by vijaydeepak-tt** [comment]
HI @idoshamun need a help, my reputation is got reduced again, can u share which post got reported or any other reason, so I will remove that post form the portal

**Comment by idoshamun** [comment]
we don't provide this information so often unfortunately. i see you opened another issue, i'll reply there in more details
