### ISSUE TITLE
🐛 BUG: Add shortcuts modal UI glitch

### ISSUE THREAD

**Issue by RMRajesh1** [dailydotdev/daily#1530]
### What went wrong? 🤔

Add shortcuts field UI is glitching on typing. Attached the video for better understanding.

https://github.com/user-attachments/assets/9a699ec5-1e60-4aad-b667-7cbeca0b795a

### Expected Behavior

The field should not glitch at any time event if the user enters invalid values. The error message can be shown  below the field which is already handled

### Steps to Reproduce Issue

```bash
0. Install daily.dev in your browser
1. Go to new tab in the browser
2. Click on 'Add shortcut'
3. Type the shortcut and click another shortcut field (below)
4. We can see the entire modal is glitching
5. I have attached a video to reproduce the issue
```

### Solution Proposed

The error message is keeps adding and removing. This might cause the issue. We need to handle that part

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome, Other

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @RMRajesh1,

This is a dup of https://github.com/dailydotdev/daily/issues/1466
