### ISSUE TITLE
🧩 FEATURE REQUEST:  increase the limit when writing a post to 10,000 characters.

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1533]
### Description

There is a validation that happens on both the app and API side when it comes to the limit of characters. We should update both ends.

Reference: https://github.com/dailydotdev/daily/discussions/1531

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nevilparmar11** [comment]
Hey @sshanzel, I'd like to start working on this. Thanks!

**Comment by sshanzel** [comment]
@nevilparmar11 feel free to dig into the code! The value should be stored in a `const` variable that updates it across the project (both `apps` and `daily-api` must be updated).

**Comment by nevilparmar11** [comment]
@sshanzel I'm attempting to run this locally following the Gitpod steps, but I'm encountering errors when running `apps` with the `daily-api` Dockerized version and directly from the repository, both ways. Am I missing something? Could you please assist?

I tried it with `gitpod` and the behavior is the same. This occurs while attempting to crew a new squad/post and sometimes on some random pages.

<img width="1134" alt="Screenshot 2024-10-30 at 3 14 48 PM" src="https://github.com/user-attachments/assets/42419c3a-ac87-4f55-93c9-977bc5c62fbb">

<img width="817" alt="image" src="https://github.com/user-attachments/assets/5a5efd7f-e8ba-46c2-aaad-ec9e0c473319">

**Comment by Dhruv80576** [comment]
@sshanzel 
I would like to work on it.

**Comment by sshanzel** [comment]
Unfortunately, there is still an ongoing issue with the development env regarding these pages to test them out properly. I would recommend working on anything once that has been sorted out. Thank you for your interest in making dailydev a better community! 🙏

**Comment by rebelchris** [comment]
This has since been deployed and is now live:
![Screenshot 2024-12-03 at 08 23 12](https://github.com/user-attachments/assets/d913e73a-a6c6-47e5-acd6-037eaaa55da5)
