### ISSUE TITLE
🐛 BUG: Posts of my squad disappeared.

### ISSUE THREAD

**Issue by FrazzledTurtle** [dailydotdev/daily#1539]
### What went wrong? 🤔

The posts of my squad disappeared when I down-voted them. The squad still shows I have the same amount of posts I had, but none of them appear. 

### Expected Behavior

It should just keep them on the screen for me to edit if i want to.

### Steps to Reproduce Issue

```bash
1. Go to your squad page.
2. Click on down vote on one of your posts.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Pop OS, Zen Browser

### Browsers

Firefox

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @FrazzledTurtle,

Thanks for the report. We'll look into it
