### ISSUE TITLE
My daliy streak was broked

### ISSUE THREAD

**Issue by matterking1** [dailydotdev/daily#1540]
### What went wrong? 🤔

I am using daily dev since 2 months 
The bug is this that when I logged in and also read the articles and many things even I meke a posts but my streak was broked I don't know why 
Can you fix this bug to make my streak back 

### Expected Behavior

I do log in but my streak was broked this happening since 1 months 

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

Please fix this problem asap 
![Screenshot_2024-10-25-09-01-36-98_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/faf7eab4-8685-4db3-8f55-23ef2adf7af0)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
Screenshot_2024-10-25-09-01-36-98_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/faf7eab4-8685-4db3-8f55-23ef2adf7af0
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment]
Hi! Can you drop your handle here so I can check further?

**Comment by sshanzel** [comment]
It seems as though you have missed reading on weekdays, and when that happens, the streak is broken. Kindly check the docs page about streaks for more info 🙏  https://docs.daily.dev/docs/your-profile/weekly-goal
