### ISSUE TITLE
🐛 BUG: Squad drop down flickering

### ISSUE THREAD

**Issue by avi12** [dailydotdev/daily#1541]
### What went wrong? 🤔

https://github.com/user-attachments/assets/e191fc11-7b3f-4c49-bb7b-4f95ff8822da

### Environment

Website

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @avi12,

Thanks for the report!

**Comment by n-d-r-d-g** [comment]
I've been able to reproduce this bug in other dropdowns as well (at `/account/notifications`). The issue seems to come from the `Menu` component from `@dailydotdev/react-contexify`.

**Comment by rebelchris** [comment]
Duplicate of: https://github.com/dailydotdev/daily/issues/1466
It's a global issue, we're working on a fix.
