### ISSUE TITLE
Timezone desync between streak state & streak icon

### ISSUE THREAD

**Issue by valdoryu** [dailydotdev/daily#1543]
### What went wrong? 🤔

Hi,
I’ve noticed an issue with my streak counter
I am in Korea right now
At 2am, I have opened my app and saw that my streak icon was empty, meaning I had to read an article to continue my streak
However, despite doing so several times on different devices, the icon would not change
I went to sleep and after waking up, I opened an article and my streak icon filled up

I think there is a weird desync with timezones (and maybe weekend also ?)

### Expected Behavior

Opening an article at 2am should have continued my streak

### Steps to Reproduce Issue

```bash
Hard to reproduce I suppose as you have to have an empty streak at 2am on Korean timezone ?
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac, iOS

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by valdoryu** [comment]
If you are asking me, I don't have the permissions to do so

**Comment by rebelchris** [comment]
@valdoryu can you check your timezone is set correct here?
https://app.daily.dev/account/notifications

**Comment by valdoryu** [comment]
Ah ! It was incorrectly set
I assumed it was synced with my device
