### ISSUE TITLE
🐛 BUG: Add shortcuts URL input box is flickering

### ISSUE THREAD

**Issue by shreyashsrivastava** [dailydotdev/daily#1544]
### What went wrong? 🤔

When I added a URL for the first shortcut, and click on the next input to add the second. It starts flickering. It only flickers when the input url is not a valid link.
I edited and added the valid URL, still it was in flickering state.

https://github.com/user-attachments/assets/31c3745f-6306-41ca-b433-e9232e28df83

### Expected Behavior

It should not flicker.

### Steps to Reproduce Issue

```bash
1. From the homepage, Go to 'Add Shortcuts',
2. Click on the first input, add an invalid URL,
3. Click on the next input box,
4. See the error - The Flicker.
```

### Environment

MacOS Sonoma 14.6.1, Google Chrome Version 130.0.6723.69 (Official Build) (arm64)

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

3.34.6

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @shreyashsrivastava,

This is a dup of https://github.com/dailydotdev/daily/issues/1466
