### ISSUE TITLE
🐛 BUG: Incorrect Firefox add-on link

### ISSUE THREAD

**Issue by n-d-r-d-g** [dailydotdev/daily#1545]
### What went wrong? 🤔

The Firefox add-on link on the [README](https://github.com/dailydotdev/daily/blob/master/README.md#-get-dailydev) redirects to a Firefox add-ons page but the add-on can't be found.

I tried searching for it as well. No luck.

### Expected Behavior

The link should redirect to the add-on's page that details installation steps.

### Steps to Reproduce Issue

```bash
1. Go to https://addons.mozilla.org/en-US/firefox/addon/daily/
2. The following error is displayed: `Oops! We can’t find that page`
```

### Solution Proposed

I'm not sure whether the link is incorrect or the add-on was removed from the website itself. I hope it has simply moved to another page. In that case, we need to replace the add-on's link in the README. Otherwise, the add-on needs to be published again.

### Browsers

Chrome, Firefox, Safari, Microsoft Edge, Opera, Brave

### OS

Windows, Linux, Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @n-d-r-d-g,

Our FF addon is not available currently. It may changed in the future but for now we should remove this link.
Do you want to open a PR for that?

**Comment by rebelchris** [comment]
I removed the link from the readme for now :)

**Comment by idoshamun** [comment]
@n-d-r-d-g thanks a lot! currently it's not prioritized yet
