### ISSUE TITLE
🐛 BUG: app.daily.dev crashes on Safari iOS

### ISSUE THREAD

**Issue by mwkcoding** [dailydotdev/daily#1551]
### What went wrong? 🤔

When opening the "app" on my iPhone (allegedly after updating to iOS 18.1) the site just crashes upon loading and says a client error occurred and there's more info in the browser console. This is not possible on iPhone AFAIK. It does work on Chrome on iOS however.

### Expected Behavior

Site loading properly.

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev' on iPhone with iOS 18.1
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

iPhone 

### Browsers

Safari

### OS

iOS

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @mwkcoding,

Can you please try incognito see if it works?
Because we couldn't reproduce

**Comment by mwkcoding** [comment]
Welp. Can't even reproduce it now in general. Now it works fine 👀

**Comment by idoshamun** [comment]
Even better!
