### ISSUE TITLE
🐛 BUG: Unable to start the app

### ISSUE THREAD

**Issue by FlavioSantoro92** [dailydotdev/daily#1552]
### What went wrong? 🤔

Since today when I open the app or even directly from the browser I see the error "Application error: a client-side exception has occurred (see the browser console for more information)."
Unfortunately I have no PC with me at the moment and I can't see the actual error on console.
I've tried the app, Brave or Chrome but nothing changed. I'm on a Pixel 9 pro.

### Steps to Reproduce Issue

```bash
1. Open the app
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Android 15

### Browsers

Chrome, Brave

### OS

Android

### Version of daily.dev

16

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @FlavioSantoro92,

We will look into it. Can you please share your handle?

**Comment by FlavioSantoro92** [comment]
Hi, my username is @lamarohn if you mean that 😅

**Comment by idoshamun** [comment]
We're investigating the issue

**Comment by idoshamun** [comment]
If either of you can check the console on their pc it would be great

**Comment by MohamedAliMefteh** [comment]
I am a newbie but how do i check browser console on pc if i am using the app on android.

**Comment by idoshamun** [comment]
you can't easily, but you can go to https://app.daily.dev on your pc. log in to your account and see if the issue persists

**Comment by FlavioSantoro92** [comment]
> If either of you can check the console on their pc it would be great

I'm sorry but I am far away from my PC. At least there's a way to not lose my streak?

**Comment by idoshamun** [comment]
If the issue persists we will recover the streak for you. Don't worry

**Comment by rebelchris** [comment]
@MohamedAliMefteh Thanks that helped a ton! 
We managed to find the culprit and propose a solution that's been merged.

Please let us know if anything else pops up or stops working 🙏
Solved in: https://github.com/dailydotdev/apps/pull/3733

**Comment by rebelchris** [comment]
@FlavioSantoro92 we published a fix for this last night, could you confirm its working for you now?

**Comment by FlavioSantoro92** [comment]
> @FlavioSantoro92 we published a fix for this last night, could you confirm its working for you now?

Yes, It works!
