### ISSUE TITLE
🐛 BUG: Cannot access Squads

### ISSUE THREAD

**Issue by Anmol-Baranwal** [dailydotdev/daily#1553]
### What went wrong? 🤔

Hi team,

All squads are showing a 500 Internal Server Error whenever I visit their URLs.

I was trying to post something on my squad, then this happened. I've even tested it in incognito mode.

I tried accessing multiple squads and the same issue occurred with each one:

- https://app.daily.dev/squads/opensouls
- https://app.daily.dev/squads/dailydevworld

![image](https://github.com/user-attachments/assets/8233f2aa-5355-4ec4-9748-a952739305b0)

### Expected Behavior

It was a opening screen of the squad with info of admins, pinned posts and the description of the squad.

### Screenshots

```bash
![image](https://github.com/user-attachments/assets/da060c02-d171-48e4-9942-8dcb06f3c02d)
```

### Environment

Windows 10

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Thanks for reporting, immediately pushed a fix, it should be available now again.
