### ISSUE TITLE
🐛 BUG: Wrong number in the Squad Post count

### ISSUE THREAD

**Issue by vijaydeepak-tt** [dailydotdev/daily#1554]
### What went wrong? 🤔

In my squad (https://app.daily.dev/squads/tarzzotech), I have posted only 57 posts in total but it is showing 79 Posts. I have removed some of the posts from my squad and reposted the same post due to the link update. I think the numbers were not removed when I deleted the posts.
Is this an expected or a bug? Please check it.

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/squads/tarzzotech'
2. See the Squad Header
```

### Screenshots

![Screenshot 2024-10-30 at 6 17 11 PM](https://github.com/user-attachments/assets/8497ca5f-5723-4d9a-a0e1-f83b6327e713)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @vijaydeepak-tt,

We have an issue that deleted posts are not being reflected in the stats. We will fix it
