### ISSUE TITLE
🐛 BUG: Can't subscribe to squad

### ISSUE THREAD

**Issue by andradei** [dailydotdev/daily#1558]
### What went wrong? 🤔

Squads have a step (usually the last one) which is to Subscribe to get notified of new posts.
The Subscribe button doesn't work and the completion steps stay at 4/5.

### Expected Behavior

When I Subscribe to a Squad, mark that "onboarding" step as done.
Or, when I click Subscribe on the steps modal, do subscribe to the Squad and mark that "onboarding" step as done.

### Steps to Reproduce Issue

```bash
1. Join a Squad
2. Click on the steps to be onboarded
3. Read the (usually?) last step, which is to subscribe
4. Click on the subscribe button
```

### Solution Proposed

![dailydev](https://github.com/user-attachments/assets/d6de58cd-11d8-4613-9ed8-b71dd62ecc81)

### Screenshots

```bash
(Can't drag and drop a screenshot here, or paste it in this field for some reason. But I can do it on the "Solution Proposed" field above)
```

### Environment

Arch Linux, Brave v1.71.121 (Oct 30, 2024)

### Browsers

Brave

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @andradei,

Thanks for reporting this issue, we will look into it

**Comment by rebelchris** [comment]
@andradei thanks for reporting.
Could it be that you are already have notifications enabled?

You should be able to see this in the top part of your browser.
![Screenshot 2024-11-04 at 15 22 14](https://github.com/user-attachments/assets/7060a52b-ea07-483c-b81e-37ac4254da22)

This will help determine which part is buggy.

**Comment by rebelchris** [comment]
@andradei this has been completed, you should no longer see the option in Brave as they don't support notifications.

**Comment by andradei** [comment]
@rebelchris Thanks for working on this. I get notifications on the bell (top-right corner), I don't think I ever got any sort of live notifications so you are correct there.
