### ISSUE TITLE
🧩 FEATURE REQUEST:  Freeze can be made optional 

### ISSUE THREAD

**Issue by PredictiveManish** [dailydotdev/daily#1559]
### Description

When we see our reading streak we have a feature which says to freeze weekends in two pairs Friday and saturday or Saturday or Sunday. I think this should be made optional as if someone wants to freeze days or not as not everyone wants to use this feature and can freeze the days according to them which can make there reading flexible as per there own needs.
![Screenshot 2024-11-02 122243](https://github.com/user-attachments/assets/e476d9a2-34aa-43c9-ad71-e5b78019eef2)

### Solution Proposed

Just directly make the setting optional so that people can change or don't set any break in there reading habits.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @PredictiveManish,

Thanks for the suggestion. The weekend freeze is optional. If you read throughout the weekend, it will increase your streak but we don't force you to

**Comment by PredictiveManish** [comment]
> Hi @PredictiveManish,
> 
> Thanks for the suggestion. The weekend freeze is optional. If you read throughout the weekend, it will increase your streak but we don't force you to

Got it @idoshamun Thanks for answering
