### ISSUE TITLE
🐛 BUG: search at the home page got error

### ISSUE THREAD

**Issue by hoankhai811** [dailydotdev/daily#1560]
### What went wrong? 🤔

When i clicked the search input then type something it's got error 
![image](https://github.com/user-attachments/assets/8dfba58a-0aaa-41e0-90fe-e0aca6c643f6)

error desc bellow:
![image](https://github.com/user-attachments/assets/f3882f8c-ce8d-4847-9e76-1cc035bfac5b)

console tab:
![image](https://github.com/user-attachments/assets/6db4e16c-c9b3-45a7-bd36-8d03b5294858)

network tab:
![image](https://github.com/user-attachments/assets/84fd4fcc-d633-4891-90a6-15d47bd5470f)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

microsoft edge Version 130.0.2849.56 (Official build) (64-bit)

### Browsers

Microsoft Edge

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @hoankhai811 

Thanks for reporting,
Do you get it consistently and on different search terms or on a specific search term?

**Comment by omBratteng** [comment]
I was able to reproduce it, and have opened a fix here
https://github.com/dailydotdev/apps/pull/3750

**Comment by omBratteng** [comment]
The fix has been merged, and we’ll release the fix soon.

In the meantime, you can use the search in the [webapp](https://app.daily.dev), as it is working there.

**Comment by hoankhai811** [comment]
dear Christ Bongers,

I don't know the bug resolved been deployed to PROD or not but whenever i
type in the search input any chars it's will return the same error

Thanks & Best Regards,
HoanCK

Vào Th 7, 2 thg 11, 2024 vào lúc 17:00 Chris Bongers <
***@***.***> đã viết:
