### ISSUE TITLE
🐛 BUG: Unable to register to daily.dev | No feedback for password length

### ISSUE THREAD

**Issue by Varstahl** [dailydotdev/daily#1561]
### What went wrong? 🤔

I've tried registering many times with absolutely no feedback whatsoever. I've tried changing browsers, disabling extensions, until I decided to look into the console network, and scrolling down the response. Down the JSON, buried somewhere, was an error: "Maximum password length of 72, N received". There was no feedback whatsoever in the UI, and to make it worse it counts bytes and not characters, so I even needed to guess how many bytes was I using with extended ascii characters in my passwords.

### Expected Behavior

Visual feedback about password length.

### Steps to Reproduce Issue

```bash
1. Go to https://app.daily.dev/onboarding
2. Write down an e-Mail and click on `Sign up`
3. Write down information and use a password like `L?²]êÙ¨¹U÷b(ï½¥!_vTÌÒÓ2P{<¤.Ò!&MËÍrPÃâöææ2E¿hWEfrýÏÕûD£ïó<D¡Ïq'é7VÆÌ¥ufDyßäÍôÖ¼g<FR£Kc9±zÕ²ì$yÖô@À\íÿêK[ôp4dzQºv7³÷¤`
4. The registration doesn't proceed, no feedback about password length
```

### Solution Proposed

On top of giving feedback about the password quality, there should be an immediate error when the password length is greater than the supported bytes, also check the size in bytes via JS, instead of characters.

### Environment

Win10, Vivaldi

### Browsers

Chrome, Microsoft Edge, Other

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Varstahl,

Thanks for this report. We will look into it

**Comment by BharathSubu** [comment]
i can fix it but im not able to visit the onboarding route in gitpod environment and not able to logout as testuser

**Comment by satvik2131** [comment]
Hi @idoshamun , I am also facing the same issue , can't logout as test user

**Comment by idoshamun** [comment]
@sshanzel will help you with the contribution :)

**Comment by BharathSubu** [comment]
Hey , adding the property  maxLength={72} for the component  <PasswordField/> in RegistrationForm.tsx doesn't allow user to add password greater than length 72 - ( got to know the max length of password from backend response )

**Comment by Varstahl** [comment]
JFYI, since I've faced this issue before: max length will truncate whatever is inserted at 72 bytes, but that means that if we're at 71 bytes and we press a key that is UTF-8 multi-byte, the unicode character will be truncated in half, resulting in an invalid password and leaving the user unable to login. Been there, done that :D

**Comment by sshanzel** [comment]
Closing this now since the fix has been merged.

> JFYI, since I've faced this issue before: max length will truncate whatever is inserted at 72 bytes, but that means that if we're at 71 bytes and we press a key that is UTF-8 multi-byte, the unicode character will be truncated in half, resulting in an invalid password and leaving the user unable to login. Been there, done that :D

Thank you for your thoughts. Although that case might still exist, yes, I doubt that it is the case for most of our users 🙏
