### ISSUE TITLE
🐛 BUG: add to shortcut

### ISSUE THREAD

**Issue by clavelian** [dailydotdev/daily#1562]
### What went wrong? 🤔

It is hard to me to explain the error but I have video.

### Expected Behavior

bug when adding shortcut

https://github.com/user-attachments/assets/6a5b542d-e7f6-481c-a635-aaf5d2d01569

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by Abhi-Bohora** [comment]
Hello @clavelian this issue has already been fixed I think you need to update the extension ? this is the duplicate of this issue (https://github.com/dailydotdev/daily/issues/1357)

**Comment by idoshamun** [comment]
Hi @clavelian, @Abhi-Bohora is correct. The new version is still in review but it's fixed already. Stay tuned :)
