### ISSUE TITLE
🐛 BUG: Application error - a client-side exception has occurred

### ISSUE THREAD

**Issue by vulct174** [dailydotdev/daily#1563]
### What went wrong? 🤔

The error appears when you enter anything in the input search box

![image](https://github.com/user-attachments/assets/f067a47d-bd3c-4068-b704-fe27a148847e)

### Steps to Reproduce Issue

```bash
1. Go to new tab
2. Enter anything in the search box
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by vulct174** [comment]
![image](https://github.com/user-attachments/assets/890ea2cd-4536-4897-a8dd-a699b0b8dea3)

Error information is displayed in the console

**Comment by rebelchris** [comment]
Hi @vulct174 I think you are still on version 3.34.7 in that case?
We fixed the issue in 3.34.8 could you ensure you are on that version?

**Comment by vulct174** [comment]
> Hi @vulct174 I think you are still on version 3.34.7 in that case? We fixed the issue in 3.34.8 could you ensure you are on that version?

Thank you, I confirm that it is fixed on version 3.34.8

**Comment by Mr-DS-ML-85** [comment]
Same issue with me

**Comment by idoshamun** [comment]
@Mr-DS-ML-85 can you please share a screenshot of the issue?
