### ISSUE TITLE
Sometimes its unable fo fetch more posts ; have to relogin to fix 🐛 BUG: 

### ISSUE THREAD

**Issue by SahilLangoo** [dailydotdev/daily#157]
### What went wrong? 🤔

Sometimes its unable to fetch more posts ; have to login again to fix !
### Expected Behavior

Fetch more posts
### Actual Behavior

showing dots animation
### Environment

extension 
#### Operating System
win 10
#### Browser

chrome 82

**Comment by idoshamun** [comment]
Hi @SahilLangoo,

Thanks for reaching out and using Daily 😁 
Could you share the steps to reproduce this bug? It would help me solve this issue quickly.
By the way, are you sure you need to login again to fix or a simple refresh is enough?

**Comment by SahilLangoo** [comment]
I don't know it happens sometimes , posts doesn't load i tried to reload , hard reload , restarting browser then i logout and login again it works !

**Comment by idoshamun** [comment]
Could you please check the console in the DevTools next time it happens?

**Comment by SahilLangoo** [comment]
Sure will collect console log and network log !

**Comment by SahilLangoo** [comment]
It Doesn't Occurre anymore may be it was **cache**  or **network** issue !

**Comment by idoshamun** [comment]
Woohoo! It's so great to hear that.
Thanks for letting me know.
