### ISSUE TITLE
🐛 BUG: Add extension to browser link seems broken in firefox

### ISSUE THREAD

**Issue by PNDB-56** [dailydotdev/daily#1577]
### What went wrong? 🤔

After signing up for the first time, site asks if user want to add extension to their browser. when user clicks `Add daily.dev to browser` it just redirects to daily.dev homepage instead of providing a way to install the extension.

### Expected Behavior

On clicking `Add daily.dev to browser` it should new page user to browser's extension page or start adding extension to the browser or whatever the working behavior is defined as.

### Steps to Reproduce Issue

```bash
1. Signup/Login to daily.dev in firefox
2. when site prompts for adding extension click `Add daily.dev to browser`
3. site just redirects to home page
```

### Browsers

Firefox

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @PNDB-56 ,

Unfortunately, after weeks of back and forth with the Firefox review team we decided to temporarily remove the extension from the store. They asked us to change major things to comply with their policy. So until we fix it, you're welcome to use our webapp https://app.daily.dev/

You can track the status and progress in this ticket: https://github.com/dailydotdev/daily/issues/1320
I will close this one so we have one place of contact.
