### ISSUE TITLE
🐛 BUG: Used daily.dev, streak broke anyway.

### ISSUE THREAD

**Issue by Labham-Jain** [dailydotdev/daily#1584]
### What went wrong? 🤔

I did used daily.dev yesterday but it has not counted it in my streaks, I am back to 1.

### Screenshots

![image](https://github.com/user-attachments/assets/884c8465-eab9-4b46-9f42-1aca7073c60d)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Labham-Jain,

We will investigate the issue. In the meantime can you share your username please?

**Comment by Labham-Jain** [comment]
Hi,

Thanks for the response... my username is @labhamjain

**Comment by Descent098** [comment]
Running into the same issue on my end, username is @descent098

Also tried on mobile and still nothing

![msedge_cX6sFCAsOT](https://github.com/user-attachments/assets/aefe6252-6d65-44f1-ac1f-1aac5147b28a)

**Comment by sshanzel** [comment]
> Hi,
> 
> Thanks for the response... my username is @labhamjain.
> 
> Also there was dashed outline around the streaks that day.

Hi. After checking, it seems you did not read anything that day. To know more about how we count streak, kindly refer to this link: https://docs.daily.dev/docs/your-profile/weekly-goal#what-counts-as-a-reading-day

**Comment by Labham-Jain** [comment]
I did read posts that day, opened the app few times...

**Comment by sshanzel** [comment]
> I did read posts that day, opened the app few times...

Unfortunately, we can only know what is recorded in the app. If you are able to reproduce the issue, we'd be very glad to look into the issue.

@Descent098 as for your case, we are further investigating to see if anything weird happened in the system and should get back with a conclusion.

**Comment by Labham-Jain** [comment]
I have not been able to reproduce it in this week if it happens again I'll re-open this issue... Thanks for the support
