### ISSUE TITLE
🧩 FEATURE REQUEST: Daily news on a web app

### ISSUE THREAD

**Issue by Joaolfelicio** [dailydotdev/daily#159]
## Feature Request
Hey there, I would like to request to have the possibility to consult the daily news on a web page without being obligated to install the extensions, since sometimes I want to access it on my phone or at work (where I'm not allowed to install chrome extensions).

Thanks for the great work.
Best regards

**Comment by idoshamun** [comment]
Hi @Joaolfelicio,

Thanks for reaching out and sharing your situation. 😄
Unfortunately, we are very focused on keeping progress with the extension.
We know that extension is a very opinionated solution that might not fit all use cases and I will appreciate your understanding. 🙏
