### ISSUE TITLE
🐛 BUG: When a post blocked It is disappearing and appearing(so fast) and stays like that

### ISSUE THREAD

**Issue by mekadi** [dailydotdev/daily#1590]
### What went wrong? 🤔

When any post blocked in the main page it s disappearing and appearing so fast and stays visible.

### Expected Behavior

It should be disappeared and should not come back again.

### Steps to Reproduce Issue

```bash
1. Go to 'main page of the daily dev chrome extension'
2. Click on '"downvote" for any post after that select "block" option for s '
3. Click on '"block" option and select the tag who shared the post'
4. See the error
```

### Solution Proposed

It is already disappearing just make it not appear again

### Browsers

Brave

### OS

Linux

### Version of daily.dev

3.34.9

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @mekadi,

Can you please share a recording so I can better understand what you experience?

**Comment by mekadi** [comment]
https://github.com/user-attachments/assets/bbe0aa0d-141d-4528-877d-a456e7144a4d

**Comment by idoshamun** [comment]
Thanks for the video! I'm opening it up for the community to help :)

**Comment by satishkumarsajjan** [comment]
I think its good that it stays, giving us an option to change it.

**Comment by mekadi** [comment]
.
