### ISSUE TITLE
🐛 BUG: hidden profile button

### ISSUE THREAD

**Issue by WebVishnu** [dailydotdev/daily#1592]
### What went wrong? 🤔

Hidden profile button

### Expected Behavior

profile button should be visible on destop also

### Steps to Reproduce Issue

```bash
1. Go to homepage in your desktop and your profile button has a hidden class
2. Not able to get to my profile
```

### Solution Proposed

Remove the hidden class from the button in desktop screen

### Screenshots

![photo](https://github.com/user-attachments/assets/d59d8d27-74c3-4f81-ac1b-57062c4b1cd7)

### Environment

chrome

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

latest

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @WebVishnu,

That's very weird. Please share your extension version and screen size

**Comment by WebVishnu** [comment]
Extension Version : 3.34.9
Screen: 1920x1080

IG this is not the extension problem when I open a new tab it is showing it but as soon I redirecte to app.daily.dev website it is gone...

https://github.com/user-attachments/assets/7672c896-4750-4540-be00-c59f12621d0a

**Comment by WebVishnu** [comment]
> Hi @WebVishnu,
> 
> That's very weird. Please share your extension version and screen size

It still persists
