### ISSUE TITLE
🐛 BUG: Logout/SSO not working

### ISSUE THREAD

**Issue by minh-nguyen-covergo** [dailydotdev/daily#1594]
### What went wrong? 🤔

Can not logout and sign in using other gmail account

https://github.com/user-attachments/assets/8676dcb5-9878-440a-94ac-fc08b48cc13f

### Expected Behavior

Selected account should be logged in

### Steps to Reproduce Issue

```bash
1. Logged in as User 1
2. Log out
3. In SSO page choose Gmail and login as User 2
4. Still logged in as User 1
```

### Environment

MacOS 15.0 (24A335), Chrome Version 130.0.6723.117 (Official Build) (arm64)

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @minh-nguyen-covergo,

As you can see when you try to login with the google account, it says that this email is already associated with another account. Then ask you to use GitHub to login which is what you did and it takes you back to the previous account.
This is an expected behavior
