### ISSUE TITLE
🐛 BUG: Wrong dev card on hover, when mentioning 2 users.

### ISSUE THREAD

**Issue by 1aWebmarketing** [dailydotdev/daily#1596]
### What went wrong? 🤔

When hovering over a username, the devcard shown is wrong

### Expected Behavior

obvious :)

### Steps to Reproduce Issue

```bash
I attached a screenshot of my welcome thread in my squad
```

### Screenshots

https://imgdrop.io/image/aJVB4

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

current

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @1aWebmarketing,

Thanks for reporting. I opened it for contribution

**Comment by tu2463** [comment]
Hello, I would like to take issue with @julia02, @mhli1260, @JasmineRocket, and @alicekang1. We are a project team and would like to work on this together. Thanks!

**Comment by sshanzel** [comment]
@Abhi-Bohora good catch! Yes, exactly that. Has got to be how we manage the devcard tooltip.

**Comment by rebelchris** [comment]
@1aWebmarketing this got solved by @Abhi-Bohora recently.
Thanks for the fix 🙏
