### ISSUE TITLE
🐛 BUG: Broken images should display Daily image placeholders

### ISSUE THREAD

**Issue by zd-zero** [dailydotdev/daily#160]
### What went wrong? 🤔
Sometimes some of the cards contain a broken image, this happens if the response is not `200` which doesn't contain the proper image to be displayed thus results in a broken image display on the cards.

### Expected Behavior
It should properly show the image card from the source.

### Actual Behavior
<img width="340" alt="Screen Shot 2020-06-02 at 1 56 51 PM" src="https://user-images.githubusercontent.com/21978370/83485737-4115e080-a4da-11ea-974f-c0d0aa777cc5.png">

The image source is `https://indepth.dev/content/images/2020/06/Reactivity-in-2020.jpg`.

### Steps to Reproduce Issue
No proper way to reproduce just from the client-side, it only happens for sources that *Daily* cannot access the image. We can reproduce this from the source by setting it to an image that constantly returning `404` response. Like pointing it to a random path (`someurl/mock-no-image.png`) which ensures no image result.

### Solution
 If we can't pull out the image properly from the source. Suggesting that we could display a *Daily* image placeholder instead of the broken image.

<img width="318" alt="Screen Shot 2020-06-02 at 1 57 40 PM" src="https://user-images.githubusercontent.com/21978370/83485772-5428b080-a4da-11ea-8aa8-b8a6b67c0707.png">

#### Version of Daily
 Daily 2.0 v2.15.5

#### Browser
 Chrome v83.0.4103.61 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi @zd-zero,

Nice hearing from you again :)
Thanks for reporting this issue, I have manually fixed this post.
I will try to think further about a possible solution, currently, the placeholder is delivered by the server. The client "doesn't know" that there is no image so if it's broken the client cannot replace it by something else.

**Comment by cagdas001** [comment]
I think the API could send a placeholder image URL to the frontend, and if frontend fails to load the provided image, we can catch it with [onerror](https://www.w3schools.com/jsref/event_onerror.asp) attribute of `img` tag. And in the `onerror` function callback, we can simply replace the img src with the placeholder URL we got from the API earlier.

Something like this

* When the frontend first initialized, get the placeholder img and store it

```js
const placeholderImgURL = await getPlaceholderImg(); // the call to the api to get the placeholder url
```

* The `img` tag of cards

```html
<img src="URL_WITH_ERROR" onerror="onImgError" />
```

* onImgError

```js
const onImgError = () => {
  this.onerror = null;
  this.src = placeholderImgUrl;
}
```

**Comment by idoshamun** [comment]
Hi @cagdas001,

Actually you're right, the best thing is to store the placeholder image in the frontend as well.
It should be pretty straightforward to implement.
Would any of you @cagdas001 or @zd-zero like to contribute this one?
I will provide you the placeholder image.

**Comment by sshanzel** [comment]
Hi @idoshamun, this issue sounds interesting! I can start with this on the coming weekend. One question though, should we also include the resources in the Front-End or just create an API that will generate the random image (like this: https://source.unsplash.com/random) for the placeholder? So it won't be tedious when there's a new design, we'd only have to update the resource on the API and have the assets centralized. What do you think?

**Comment by idoshamun** [comment]
Hi @sshanzel,
I would love to get another great contribution from you. 🙏
I think, as a starter, we can just save the placeholder locally in the front-end to make sure it's available at all times.
Ping me on slack, and I'll send you the placeholder.

**Comment by kenanchristian** [comment]
Hi everyone, is this still up for grabs?
I'm interested in giving it a try if it's not worked on yet :)

**Comment by sshanzel** [comment]
> Hi everyone, is this still up for grabs?
> I'm interested in giving it a try if it's not worked on yet :)

Hi! I'm literally out of reach for development these past few weeks and the upcoming ones. Feel free to give it a try! 🍻

**Comment by idoshamun** [comment]
Thank you @kenanchristian for a super-fast contribution.
I will submit the new version to the stores in the next hour.
