### ISSUE TITLE
🐛 BUG: Personal update email not showing post info.

### ISSUE THREAD

**Issue by hmsgrs** [dailydotdev/daily#1600]
### What went wrong? 🤔

The daily personal update email is not showing some of the posts info, nor the images. Only the title of the poster appears in the box.

### Expected Behavior

It should show the preloaded images of the post with the description, as it does in the app.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Environment

chrome in macbook, gmail account.

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @hmsgrs,

Please send a screenshot so I can better understand the issue

**Comment by hmsgrs** [comment]
![Sin título](https://github.com/user-attachments/assets/7fc33387-f58b-42b4-80c8-a24ac5792704)

**Comment by hmsgrs** [comment]
![Sin título](https://github.com/user-attachments/assets/8087faa6-bde9-46c6-a94a-1bb059aca796)
it got worse, actually. Now it displays no article.

**Comment by idoshamun** [comment]
This is squad posts without a title. We need to address that

**Comment by capJavert** [comment]
@hmsgrs thank you for the report, we implemented changes to cover the above cases so hopefully your future digests should now look much better!
