### ISSUE TITLE
🐛 BUG: Reputation is not increasing

### ISSUE THREAD

**Issue by SHVM2324** [dailydotdev/daily#1601]
### What went wrong? 🤔

![Screenshot 2024-11-19 064418](https://github.com/user-attachments/assets/ec01e2be-8109-4b2d-b5cc-33da30e7d120)
Even after getting a upvote my reputation is stuck on 10 it is happening second or third time please resolve it

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Environment

windows 11 

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @SHVM2324 ,

You can only get reputation by users with 250+ upvote.

See our docs for more info:

https://docs.daily.dev/docs/your-profile/reputation
