### ISSUE TITLE
🐛 BUG: Duplicate posts

### ISSUE THREAD

**Issue by ruancodeco** [dailydotdev/daily#1602]
### What went wrong? 🤔

While scrolling through my feed, there are a lot of posts that show up twice (or more times). Sometimes the posts are quite close to each other, like in the very next row (3 columns per row), and sometimes they are duplicated after scrolling a bit. I have noticed that some of them are just a repost by someone else, but most of the time it is the exact same post.
[daily-dev-Where-developers-grow-together.webm](https://github.com/user-attachments/assets/877ca4fa-03b9-4fe2-99a9-df3d7ca8598d)

### Expected Behavior

I would not like to see the same posts over and over again.

### Steps to Reproduce Issue

```bash
1. Go to 'main feed'
2. Click on ''
3. Scroll down to 'the next  post that is the same as one already in the feed'
4. See the error (duplicate post(s))
```

### Environment

Windows 11, Chrome (latest)

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
It should be fixed now. Please let me know if encounter anything
