### ISSUE TITLE
🐛 BUG: Bookmark and Upvote/Downvote button state not changing the color after click in chrome browser extension.

### ISSUE THREAD

**Issue by safin777** [dailydotdev/daily#1603]
### What went wrong? 🤔

While I was trying to upvote, downvote, or bookmark any card items, it only showed the popup/toast message but not changing the upvote, downvote, or bookmark button color in chrome browser extension.

### Expected Behavior

It should be the Upvote - Green, Downvote-Red and Bookmark - orange color after changing the current state, else it will be transparent color.

### Steps to Reproduce Issue

```bash
1. Go to 'Daily dev extension dashboard UI '
2. Click on 'Click on Bookmark, upvote, downvote button of each card'
3. See the error
```

### Screenshots

https://screenrec.com/share/2NBJT1tz7Z

### Environment

windows

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by arbazkpathan** [comment]
See the promblem is that your browser cannot load stuff .
the way to fix it can be that you can try reinstalling the extention
or try resseting your browser catche reallow cookies

**Comment by idoshamun** [comment]
Hi @safin777,

I can't see the screen recording. But everything works on my end. As suggested, you can try resetting the local storage

**Comment by Abhi-Bohora** [comment]
works on my side too...✅
