### ISSUE TITLE
🐛 BUG: Search doesn't always return expected results for sources

### ISSUE THREAD

**Issue by randy** [dailydotdev/daily#1604]
### What went wrong? 🤔

I tried to search for "dhh" as a search and it didn't appear in the results

### Expected Behavior

"dhh" should have been in the results.

### Steps to Reproduce Issue

```bash
1. Go to 'Search'
2. Type in "dhh" (without the quotes)
3. Observe that results lack an entry for the "dhh" source
```

### Solution Proposed

Possibly sort by length and "exactness of match." Even if another source has "dhh" in it, because that's all I searched, the exact match should be listed first.

### Screenshots

![image](https://github.com/user-attachments/assets/1f177c41-3006-41f7-ad1c-0a7ffbb0cac5)

### Browsers

Chrome

### OS

Mac

### Additional Context

```bash
More context may be found on https://github.com/dailydotdev/daily/issues/1587
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
@randy thanks for reporting.

I've added the option now to also include handles in the search for sources.
![Screenshot 2024-11-21 at 10 30 57](https://github.com/user-attachments/assets/4fccf4e1-2190-4692-80b3-a8e7266fd4f8)
