### ISSUE TITLE
feat: highlight selected tags on the tags page

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1607]
### Discussed in https://github.com/dailydotdev/daily/discussions/1342

<div type='discussions-op-text'>

<sup>Originally posted by **plplmax** August 17, 2024</sup>
It will be nice if you highlight selected tags on the [tags](https://app.daily.dev/tags) page.

"Choose tags to follow" section in "Feed settings" does not show all tags, therefore, does not show all selected tags.
Now we should use search field above "Choose tags to follow" to check if some tag is selected.</div>

There is a hook called `useFeedSettings` (iirc) - we can cross check which tags are in there followed by the user then highlight those ones in the tags page.

**Comment by tu2463** [comment]
Hello, I would like to take issue with @jullia02, @mhli1260, @JasmineRocket, and @alicekang1. We are a project team and would like to work on this together. Thanks!

**Comment by nevilparmar11** [comment]
Hi @sshanzel, I will work on this, Thanks!

**Comment by rebelchris** [comment]
This is now live, thanks for the contribution @nevilparmar11
