### ISSUE TITLE
🐛 BUG: personal update email does not feature any stories

### ISSUE THREAD

**Issue by bitless** [dailydotdev/daily#1609]
### What went wrong? 🤔

No stories featured in personal update email

### Expected Behavior

Some stories in feed

### Steps to Reproduce Issue

```bash
1. Sign up
2. Populate interest tags
3. Wait a few days
4. Receive personal update email
```

### Solution Proposed

Dont send email if no stories match interest tags or send a general top-5 list of stories

### Screenshots

 ![Screenshot 2024-11-20 at 9 52 04 AM](https://github.com/user-attachments/assets/13738b1e-c38c-43e5-b8d9-4b3d69e4c1e6)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi this indeed is related to #1600 we are looking into the empty emails urgently.
Closing this to keep all comms in one thread.
