### ISSUE TITLE
🐛 BUG: Streak Count Issue

### ISSUE THREAD

**Issue by jalejotorresm** [dailydotdev/daily#1612]
### What went wrong? 🤔

I am not sure , but the streak icon is not showing as completed, even though I have browsed through several articles. I doubt if my streak will be affected tomorrow on this account.

### Expected Behavior

Along with the streak count, the icon should update with a fire icon, not the dotted circle one.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Environment

Windows 10, Firefox 132.0.2 (64-bit)

### Browsers

Firefox. Edge, Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by battim** [comment]
Same issue for me. I've tried in Edge and Chrome, both on Mac Sequoia 15.1.1

**Comment by battim** [comment]
It was on the wrong timezone. I set it to the correct timezone, but it still isn't updating my streak.
    On Thursday, November 21, 2024 at 05:00:51 PM MST, Lee Hansel Solevilla ***@***.***> wrote:  
 
 


Hi! Thank you for reporting, can you check if you have your timezone set to your current local timezone?

The settings should be located here: https://app.daily.dev/account/notifications

**Comment by sshanzel** [comment]
> It was on the wrong timezone. I set it to the correct timezone, but it still isn't updating my streak.

Hi. Great to hear you set it to the right value now. Unfortunately, we don't retroactively update the streak after changing the timezone as it can lead to misusing the feature itself.

**Comment by jalejotorresm** [comment]
@battim I made the update but the issue is still ongoing. Is that or the streak mark is showing on a past-day basis, trying to think it as a UI new feature perhaps

**Comment by sshanzel** [comment]
> @battim I made the update but the issue is still ongoing. Is that or the streak mark is showing on a past-day basis, trying to think it as a UI new feature perhaps

Thank you for updating your profile. However, it won't retroactively fix the issue you had yesterday, but moving forward, it will now reflect the rightful values.
