### ISSUE TITLE
🐛 BUG: Streak count not increasing

### ISSUE THREAD

**Issue by Beefy-py** [dailydotdev/daily#1617]
### What went wrong? 🤔

My streak does not increase even after clicking on multiple articles.
I use Chrome.

### Expected Behavior

My streak should increase from 82 to 83 after clicking on "read post"

### Screenshots

![image](https://github.com/user-attachments/assets/39e4ada8-2c1f-46de-b759-bb8673a1adb0)

### Environment

Windows 11, Version 131.0.6778.86 (Official Build) (64-bit)

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Beefy-py,

Can you please make sure your profile timezone matches your real timezone?
https://app.daily.dev/account/notifications

**Comment by Beefy-py** [comment]
> Hi @Beefy-py,
> 
> Can you please make sure your profile timezone matches your real timezone? https://app.daily.dev/account/notifications

Oh yeah I forgot to mention that I have set the timezone correctly.
It matches yes.

**Comment by Beefy-py** [comment]
It's a new day in my country and I checked to see if I lost my streak.
But it's still on 82.

**Comment by idoshamun** [comment]
We're looking into the issue

**Comment by sshanzel** [comment]
@Beefy-py to further investigate, we need your user id. Kindly paste here the value displayed from this link: https://api.daily.dev/id

Also, if you are using the extension, can you share the version of it?

**Comment by Beefy-py** [comment]
> @Beefy-py to further investigate, we need your user id. Kindly paste here the value displayed from this link: https://api.daily.dev/id
> 
> Also, if you are using the extension, can you share the version of it?

The extension's version is `3.35.2`
My user id is `CC0haBxsdv0aLHLK5YcA4`

Today my streak is 84 and not increasing to 85

**Comment by rebelchris** [comment]
Closing to keep all comms in #1619
