### ISSUE TITLE
🐛 BUG: streak broken even after numerous article reads , this is the third time it happens

### ISSUE THREAD

**Issue by bogi99** [dailydotdev/daily#1618]
### What went wrong? 🤔

i read the articles , every day, and the site does not register any of them, and declares mt streak broken, which is very broken behaviour , it used to work a couple of weeks ago, bit now it doesn't 

### Expected Behavior

I expect my streak to register an active day after i click and read a posted article, it really did not do that 

### Steps to Reproduce Issue

```bash
1. Go to 'main page'
2. Click on 'article'
3. Read article as you would
4. check streak counter 
5. it's not registering your reads
6. next day your streak is broken
```

### Environment

Linux Manjaro , Firefox  131.0.3 (64-bit)

### Browsers

Firefox

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @bogi99,

Can you please make sure your profile timezone matches your real timezone?
https://app.daily.dev/account/notifications

**Comment by bogi99** [comment]
I checked, my timezone EST set on the website matches that of my system timezone EST / Toronto . ON on my system setting

**Comment by sshanzel** [comment]
@bogi99 to further investigate, we need your user id. Kindly paste here the value displayed from this link: https://api.daily.dev/id

**Comment by celtboy** [comment]
Same issue here. `rQwcL4jtX9bjh4xc9mpBX`

**Comment by rebelchris** [comment]
Closing to keep all comms in #1619
