### ISSUE TITLE
🐛 BUG: on mobile, the icon is misaligned on feed

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/daily#1621]
### What went wrong? 🤔

Icon below is misaligned from its container.

![image](https://github.com/user-attachments/assets/168ede37-b9de-48e0-8fc6-3e328da9a783)

### Expected Behavior

Centered alignment

### Steps to Reproduce Issue

```bash
1. Go to the app.daily.dev on mobile.
2. Go to the feed.
3. See the misaligned icon referenced above.
```

### Solution Proposed

Fix the alignment of the icon from its container.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by DIMAX99** [comment]
is the icon removed?

**Comment by Abhi-Bohora** [comment]
@DIMAX99 Hi you can find this icon only on mobile. resize your browser and go to setting there you can see enable feed sorting menu turn that on and come back to feed you will see that icon which is misaligned.
![feed](https://github.com/user-attachments/assets/00c95cfc-7aba-4d4e-ba42-6d91d1e0953f)

**Comment by DIMAX99** [comment]
Do have to make a pull request here because i made a pull request in apps for this issue.

**Comment by Abhi-Bohora** [comment]
@DIMAX99 yes you have made the pr in the correct repository but in your pull request if you haven't linked the issue edit the pr description and mention the issue link in the pr description like this Link: [#issuenum](https://github.com/dailydotdev/daily/issues/issuenum)

**Comment by rebelchris** [comment]
@DIMAX99 thanks for fixing the issue appreciate it a lot 🙏
