### ISSUE TITLE
🐛 BUG: Post lists 3 comments but shows only 2

### ISSUE THREAD

**Issue by frank-connolly** [dailydotdev/daily#1623]
### What went wrong? 🤔

![image](https://github.com/user-attachments/assets/19bca9bc-acb2-435c-a659-d20be127a077)

### Expected Behavior

Comment count to match comments shown

### Steps to Reproduce Issue

```bash
1. Go to https://app.daily.dev/posts/qwk8ksucp
2. See the comment count shown below main post
3. Count actual number of comments and see a mismatch
```

### Solution Proposed

Make them match

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @frank-connolly,

This misalignment can happen as we sometimes flag comments as spam so they may be counted but not seen.
The beauty of distributed systems 🪄
