### ISSUE TITLE
🐛 BUG: Add tags from search not working

### ISSUE THREAD

**Issue by msayed-net** [dailydotdev/daily#163]
### What went wrong? 🤔

Trying to add tags from search like "flutter", nothing happens

### Expected Behavior

to be added

### Actual Behavior

reload content area with no change and not added to my tags

### Steps to Reproduce Issue

it's up to you

### Solution

it's up to you

### Environment

Mozilla Firefox (Desktop)

#### Operating System

MacOS

#### Version of Daily

2.15.6

**Comment by idoshamun** [comment]
Hi @msayed-net!

Thanks for reporting this bug, I was able to reproduce this issue.
I will work on a fix and let you know once it's done :)

**Comment by idoshamun** [comment]
The issue is now fixed and will be released in the upcoming version

**Comment by msayed-net** [comment]
Excellent, Thank you
