### ISSUE TITLE
🐛 BUG: Banner doesn't show on someone's/my profile

### ISSUE THREAD

**Issue by Wowsie** [dailydotdev/daily#1630]
### What went wrong? 🤔

Why some people's profile banner doesn't show on their profile or my profile
![image](https://github.com/user-attachments/assets/620d0bd0-99c7-4b43-b5c6-1990ef45cba8)
![image](https://github.com/user-attachments/assets/56ef9d3b-8024-4e85-8c39-4161d7c18c0f)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Wowsie,

The tooltip (banner) isn't shown on the profile page.
It is being shown only when you hover a profile image across the app, but not in the profile page

**Comment by Wowsie** [comment]
i mean my banner image doesn't show on the tooltip

**Comment by idoshamun** [comment]
Oh I see now. Thanks for explaining 🙏

**Comment by sshanzel** [comment]
> Why some people's profile banner doesn't show on their profile or my profile

You will have to adjust your settings for that in the devcard page. Kindly follow the steps below:
- Go to https://app.daily.dev/devcard.
- Click Customize.
- Select "Use profile cover".

![Screenshot 2024-12-02 at 8 41 35 PM](https://github.com/user-attachments/assets/d99d5cf9-4d6f-4137-a5ca-3366a387e588)
