### ISSUE TITLE
🧩 FEATURE REQUEST:  Adjust Reputation System Points to Promote Quality Content

### ISSUE THREAD

**Issue by muhammad-fiaz** [dailydotdev/daily#1631]
### Concise Description

Request to rebalance the reputation rewards for posts and comments to ensure both are fairly rewarded and maintain the platform's focus on high-quality content sharing.

### Description

![image](https://github.com/user-attachments/assets/7ddf9c0a-ffe7-4a42-b226-ab5625886eed)

The current reputation system rewards comment upvotes with +50 points, while post upvotes earn only +10 points. While encouraging discussions and community engagement is valuable, this imbalance could inadvertently shift the focus away from appreciating the effort required to curate and share high-quality posts 🔍.

This disparity may lead users to prioritize commenting, potentially resulting in spam or low-value discussions, instead of contributing meaningful and valuable resources to the community. While the intention behind rewarding comments is not inherently wrong, it risks diluting the platform's focus on sharing curated, high-quality content.

To ensure daily.dev continues to prioritize the sharing of valuable resources alongside fostering thoughtful discussions 🤝, this feature request proposes rebalancing the reputation rewards system ⚖️. Adjusting the weight of rewards for posts and comments would better reflect the effort and value of both contributions💡.

This change would encourage a healthier balance between engaging in meaningful discussions and maintaining the platform's core focus on high-quality content sharing with discussion. It would also help promote community picks, further rewarding high-value posts that contribute to the growth and usefulness of the platform.

Thank you for considering this request! :)

### Solution Proposed

Adjust the reputation rewards to create a healthier balance between encouraging meaningful discussions and rewarding users for sharing curated, high-quality posts.
- Increase the reputation rewards for post upvotes to better reflect the effort required to curate and share valuable resources.
- Reduce or balance the weight of comment upvotes slightly to ensure that discussions remain meaningful without overshadowing the importance of sharing high-quality posts.
- This adjustment would strike a healthier balance between fostering meaningful engagement and maintaining the platform's core focus on high-quality content sharing.

### Additional Context

```bash
This request is driven by observations that the current system may unintentionally promote spam or low-value engagement in an effort to gain a reputation through commenting. Adjusting the reputation weight will allow the platform to maintain its reputation as a space for valuable, curated content while fostering healthy discussions.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @muhammad-fiaz,

Thanks a lot for this thoughtful suggestion.
At the moment, more posts are being created than comments, even with the existing balance.
We experience spam in all fronts (posts and comments) and actively fighting it regardless of reputation.
At the moment we have no plans to change the reputation balance.
