### ISSUE TITLE
🐛 BUG: My streak doesn't update today

### ISSUE THREAD

**Issue by petehouston** [dailydotdev/daily#1632]
### What went wrong? 🤔

My streak stops at 97 today and doesn't update. 

### Expected Behavior

Streak should be updated normally

### Steps to Reproduce Issue

```bash
1. Go to 'daily.dev'
2. Click on 'any post or link'

3. Expect to see streak get updated
```

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by abhayrsr** [comment]
Hey, the issue is similar to #1617 
Team is looking for the solution.

**Comment by rebelchris** [comment]
Closing to keep everything in one topic #1617
