### ISSUE TITLE
Streak icon delay

### ISSUE THREAD

**Issue by pplalo** [dailydotdev/daily#1634]
### What went wrong? 🤔

When I keep my streak going, the streak icon is being set in a different day from today's streak. 
I'm using ZFold 6 Samsung in time zone GMT -6 from Mexico City
![Screenshot_20241204_203129_Chrome](https://github.com/user-attachments/assets/bdf817b3-45e7-478f-aa1e-ffc1c5123ed7)

### Expected Behavior

It should be in today's icon streak instead of yesterday's icon streak.

### Steps to Reproduce Issue

```bash
1. Go to home page
2. Verify your streak is not being still continued.
3. Read and article to extend your streak.
4. Review in which day the streak was extend ando you will notice the streak icon was set for yesterday's.
```

### Solution Proposed

The streak icon should be placed in today's streak icon.
![Screenshot_20241204_203129_Chrome](https://github.com/user-attachments/assets/dd340d60-9741-4035-bafd-06b05397a213)

### Environment

Samsung Z Fold 6 Android 14

### Browsers

Other

### OS

Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @pplalo thanks, we do have a issue with this and actively solving it.
You can keep track in #1619 to keep all comms in one thread.

Thanks for reporting.

**Comment by pplalo** [comment]
Thanks a lot!
