### ISSUE TITLE
🐛 BUG: No articles when opening a new tab with the extension

### ISSUE THREAD

**Issue by PoudrouxThomas** [dailydotdev/daily#1635]
### What went wrong? 🤔

When opening a new tab on fireefox with the extension, I have no articles in my feed. I have articles if I open the weebsite.

![image](https://github.com/user-attachments/assets/ac32c36b-a4c8-4520-8693-6586d19756af)

I have 76 followed filters.

### Expected Behavior

I expect to have articles I see in the homepagee

### Steps to Reproduce Issue

```bash
I just created my account, followed the first steps (setup my account informations, follow topics etc.), and installed the firefox extension. I tried restarting firefox, but I still have the issue
```

### Environment

Windows 10, Firefox 133.0

### Browsers

Firefox

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @PoudrouxThomas,

Our firefox version is currently out of date, we're waiting for the firefox team to approve the latest one.
Please subscribe to this here: https://github.com/dailydotdev/daily/issues/1320
