### ISSUE TITLE
🐛 BUG: streak icon does not display (or update)

### ISSUE THREAD

**Issue by arielonoriaga** [dailydotdev/daily#1636]
### What went wrong? 🤔

when opening a post to maintain the streak, the streak icon does not update to give visual feedback.when opening a post to maintain the streak, the streak icon does not update to give visual feedback.

### Expected Behavior

when opening a post without having read one on the day the icon in the top right bar is updated.

### Steps to Reproduce Issue

```bash
1. Go to daily dev tab (extension)
2. Click on any post without having read one before (on the day)
3. Go back to daily dev tab
4. See the error
```

### Screenshots

![image](https://github.com/user-attachments/assets/fc11f219-368e-469e-92d4-9f72ce96417b)
![image](https://github.com/user-attachments/assets/30b9d15e-2328-483e-bf3f-4f40cce70c51)

### Browsers

Brave

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @arielonoriaga ,

Thanks for reporting, these reports are super valuable for us.
We are aware of this specific issue and tracking all comms in #1619 
We will update there as soon as we fix it, we have a lead currently.

Closing this ticket.
