### ISSUE TITLE
🐛 BUG: Videos showing if disabled in feed settings

### ISSUE THREAD

**Issue by marvinpoo** [dailydotdev/daily#1639]
### What went wrong? 🤔

As a User I am able to deselect videos, being promised and therefore expecting them not to be shown in my feed anymore. Yet, not only rarely, but once, twice a day Videos get pushed into my feed. I have reported this bug through the app multiple times for months now. 

It was not yet fixed. Thankfully, that made me extra cautious and do a little in depth check which left me finding multiple GDPR violations, starting at the video embedding. See #1638 

### Expected Behavior

No videos on my feed.

### Steps to Reproduce Issue

```bash
1. Open feed
2. See videos
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @marvinpoo,

We had an issue with squad posts that share a video, as they were not marked as videos. This issue is now fixed.
