### ISSUE TITLE
🐛 BUG: Feed not showing.

### ISSUE THREAD

**Issue by sam15x7** [dailydotdev/daily#1642]
### What went wrong? 🤔

Dear daily.dev Team,

I am experiencing an issue with the feed filters on your platform. Despite selecting a wide range of filters to customize my feed, I keep encountering a message stating that the filters are "too specific," and no content is displayed.

I’ve ensured to include as many options as possible to avoid overly narrowing the results, but the problem persists. Could you please investigate this issue or provide guidance on how I can resolve it?

Thank you for your assistance.

### Expected Behavior

When I customized the feed filters, I expected the system to display relevant articles matching the selected topics and preferences. By selecting a broad range of filters, I aimed to ensure that the feed would not be overly restrictive and would provide a variety of curated content.

Instead, I encountered a message indicating that the filters are "too specific," and the feed failed to show any articles. This behavior was unexpected, as my selections were designed to maximize content rather than limit it.

I hope this clarifies my expectations. Please let me know if you need more details.
![image](https://github.com/user-attachments/assets/96f81a06-4da2-4d36-b6c5-9e541dfd18d9)

### Environment

Windows 11 , Firefox 

### Browsers

Firefox

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @sam15x7,

Our firefox version is currently out of date, we're waiting for the firefox team to approve the latest one.
Please subscribe to this here: https://github.com/dailydotdev/daily/issues/1320
