### ISSUE TITLE
🐛 BUG: Current Streak Icon does not update after viewing a new post

### ISSUE THREAD

**Issue by zataara** [dailydotdev/daily#1644]
### What went wrong? 🤔

When viewing a new post each day my icon no longer updates to display I have viewed a post of the day. The counter still correctly increments for the day and my streak is not lost. This appears to be a result of support updateing my time zone possibly. 

<img width="498" alt="Screenshot 2024-12-08 at 23 01 23" src="https://github.com/user-attachments/assets/7907c2fa-c85a-4277-85b5-9868b0a0746e">

### Expected Behavior

Once a post a is viewed the state shoudl reflect that by filling the lined border icon with a fire icon until that day is over for my particular time zone.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Environment

Desktop Web App, PWA.

### Browsers

Chrome, Safari

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @zataara thanks for logging.
We are aware of this issue and solving it asap.

It's mostly a FE issue at this point, do let us know if you ever loose your streak unintionally.

Closing this ticket to keep comms in #1619
