### ISSUE TITLE
🐛 BUG: Reputation problem

### ISSUE THREAD

**Issue by Hadil-Ben-Abdallah** [dailydotdev/daily#1645]
### What went wrong? 🤔

I've noticed that my reputation has decreased without any apparent reason. I only share posts within my own squad, so the only individuals who can remove my posts are the admins of daily.dev. However, I haven’t found any missing posts, nor have I received any downvotes. Despite this, my reputation recently dropped significantly, from 7.1K to 5.8K, which is both confusing and disheartening.

I kindly request clarification about what might have caused this drop. If it’s a mistake, I hope my lost reputation can be restored. Alternatively, I’d appreciate understanding the reason behind this change to prevent similar occurrences in the future.

### Expected Behavior

In case I really deserve to loose reputation, I think it would be better to get a notification to know the reason of that and avoid it next time.

### Environment

Windows 10, Chrome 131.0.6778.109

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Hadil-Ben-Abdallah,

We recently implemented a system to prevent reputation farming. It may impact some users that received reputation from suspicious users

**Comment by Summonair** [comment]
Hey I suffered from it too :( I really don't think it should lower reputation

**Comment by idoshamun** [comment]
Hi @Summonair,

I replied to your email already. It's not the same issue 🙏
