### ISSUE TITLE
🐛 BUG: Addons in Firefox not working (your feed filters are too specific)

### ISSUE THREAD

**Issue by Beeditor04** [dailydotdev/daily#1649]
### What went wrong? 🤔

I don't really know what's going on, maybe fetching bug related but as you can see the Addons behaviour whenever I create new tab, it's always stuck at 35 streaks (i currently have 71 streaks now) and features which I've never seen it before like Ranking stuff. The website work normally when I manually access to it.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

![image](https://github.com/user-attachments/assets/24c1d7a1-3b71-4d9a-9844-c339e7b3c58b) ![image](https://github.com/user-attachments/assets/2ed23f7c-96b9-4f8f-a39d-1e0a00506f08) ![image](https://github.com/user-attachments/assets/7e2d27ce-773d-4143-8b78-5a2fa0cc8463) ![image](https://github.com/user-attachments/assets/06ca1bb5-9cfe-4e69-8163-5aea268201ee)

### Browsers

Firefox

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @Beeditor04,

Our firefox version is currently out of date, we're waiting for the firefox team to approve the latest one.
Please subscribe to this here: #1320
