### ISSUE TITLE
🐛 BUG: Missing pending posts

### ISSUE THREAD

**Issue by frank-connolly** [dailydotdev/daily#1652]
### What went wrong? 🤔

I have 4 pending posts shown for my squad but I do not see them.

![image](https://github.com/user-attachments/assets/efa17799-4ee6-47f3-857e-27a6bfc4f0a2)

### Steps to Reproduce Issue

```bash
1. Go to 'Pending Posts'
2. See the error
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment]
Hi @frank-connolly, thank you for reporting! We've pushed a fix regarding the fact that the count is not accurate. Feel free to let us know if the issue persists.
