### ISSUE TITLE
🐛 BUG: ambiguous cookie banner

### ISSUE THREAD

**Issue by mindplay-dk** [dailydotdev/daily#1658]
### What went wrong? 🤔

Your cookie banner is fun:

![image](https://github.com/user-attachments/assets/ba514c7b-af1b-4a69-8b47-c121ab99b531)

but I don't believe your lawyers advised this? If they did, they don't know the EU cookie regulations.

* from this text, it isn't clear whether you're already using cookies without my consent, but it sounds like that's implied?
* from the button label ("I like cookies") it isn't clear what I'm consenting to. am I consenting to anything?
* the "x" close button on the banner is highly ambiguous - having no clear meaning, this is often used as a deceptive pattern
* there is no link to any actual cookie banner policy, and thus no actual agreement with any users

I'm not trying to be an ass, I'm only trying to help here. 🙂

### Expected Behavior

cookie banners must be clear and unambiguous - otherwise, the consent isn't legally binding, at least not in the EU.

I'm Danish, and I used to work at Usercentrics (a cookie banner vendor) so I'm not just opinionated about this stuff, I swear.  😅

but this is not a valid cookie banner under GDPR, and any consent you think you're collecting isn't legally consent.

for the regard, a minimum viable cookie banner probably looks something like this:

![image](https://github.com/user-attachments/assets/c235b574-6322-4681-ba90-bfbd71bd89e5)

you don't need 4 categories if you don't use cookies in those categories, but the banner must make clear what you're consenting to, must provide a clear option to decline, and must provide a link to an actual policy.

sorry, I know this is annoying, but you claim to be the "fastest growing developer platform in Denmark", so you better be ready 😅

talk to your lawyer again 😉

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by marvinpoo** [comment]
The Decline Button and Accept Button should have the same intensity in design. It is considered a negative pattern to make the accept button more engaging, especially making it green.

This kind of belongs to #1640

**Comment by mindplay-dk** [comment]
> It is considered a negative pattern to make the accept button more engaging, especially making it green.

absolutely, yes, I just grabbed that banner from a quick web search.

this does sound like a duplicate of #1640 so I think we can close this.

thanks 🙂
