### ISSUE TITLE
🐛 BUG: Feedback and Bug Report on Reputation Points Issue

### ISSUE THREAD

**Issue by Richard-Raph** [dailydotdev/daily#1661]
### What went wrong? 🤔

Hello Daily.dev Team,

First of all, I want to express my appreciation for the amazing platform you’ve built. The seamless integration of developer news, the community engagement features, and the reputation system have significantly enhanced my experience as a developer. It's inspiring to see how daily.dev has become a hub for developers worldwide.  

However, I’ve encountered an issue with the reputation points system that I wanted to bring to your attention. I’ve noticed that my reputation points keep getting deducted after reaching significant milestones. Here are the specifics:  

1. The first occurrence was when I had accumulated 8100 points, which suddenly dropped to 1100 points without any explanation.  
2. The second time, I reached 5300 points, and again, my points were reduced to 1100.  

This has happened twice now, and it’s a bit disheartening, especially since reaching these milestones is a rewarding experience for consistent activity and engagement on the platform.  

I’d appreciate it if this could be looked into, as it might be affecting other users as well. Thank you in advance for your attention to this matter, and keep up the fantastic work with daily.dev!  

Best regards,  
Richard Raphael

![F5cxAxeNlHAqBVCt67SDW](https://github.com/user-attachments/assets/a3cda7f9-7e2a-451e-b365-3c1872170b57)
![devcard](https://github.com/user-attachments/assets/f7d3e827-c450-42d4-9d83-41dad9d6441a)

### Expected Behavior

The reputation points system on daily.dev should allow users to steadily accumulate points without unexplained deductions. When nearing key milestones, such as the 10,000-point threshold required for final Devcard customizations, the system should maintain point accuracy.  

If any adjustments or deductions are necessary, these should be accompanied by clear explanations or notifications to ensure transparency. Unexpected drops, like going from 8100 to 1100 points or 5300 to 1100 points, disrupt user engagement and progress, especially when users are striving to unlock significant features.  

The points system should retain user trust by preserving consistency and providing explanations for any changes.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

**Proposed Solution:**  

1. **Debugging the Points System**: Investigate the root cause of the repeated point deductions. Specifically, examine the backend algorithms or processes handling reputation points to identify inconsistencies or errors.  
   
2. **Transparent Notifications**: Implement a system that alerts users to any deductions, detailing the reason behind them. This transparency will help users understand and adapt to any policies or technical limitations.  

3. **Point Restoration**: If deductions are found to be errors, restore the lost points to the affected accounts, ensuring users' progress is honored.  

4. **Auditing Features**: Introduce a user-accessible reputation audit trail, allowing users to view their points' history and verify changes over time.  

5. **Feedback Mechanism**: Create a clear feedback loop where users can report such issues directly within the platform, ensuring quicker resolutions.  

These steps would improve the user experience, build trust in the system, and encourage sustained engagement on Daily.dev.

### Screenshots

![DevCard from Github](https://raw.githubusercontent.com/Richard-Raph/Richard-Raph/main/devcard.png),   ![DevCard from daily.dev](https://api.daily.dev/devcards/v2/F5cxAxeNlHAqBVCt67SDW.png?type=default&r=sp4)

### Browsers

Chrome

### OS

Windows, Android

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by finfin** [comment]
I've also encountered a issue regarding reputation, that, my reputation is freezing.

According to doc the reputation should accumulate with upvotes or comments
But after some upvotes and comment (at least 10 upvotes / comments from eligible accounts) my reputation stays the same

<a href="https://app.daily.dev/fin488"><img src="https://api.daily.dev/devcards/v2/Xd57v4JZT.png?type=default&r=p09" width="356" alt="Fin Chen's Dev Card"/></a>

**Comment by idoshamun** [comment]
@Richard-Raph, I sent you an email about suspicious activity in your account before you opened this issue. Please read it carefully, it should provide the details

@finfin not all upvotes grant reputation, only those from users with +250 reputation. Please read more here: https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points

**Comment by finfin** [comment]
> @finfin not all upvotes grant reputation, only those from users with +250 reputation. Please read more here: https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points

@idoshamun yes I'm fully aware of this
take example, these two url got upvotes from user with +250, but my reputation didn't change
https://app.daily.dev/posts/this-is-the-second-half-of-my-css-variable-post-in-this-article-we-ll-look-into-the-details-of-var--l6tsdqh8v
https://app.daily.dev/posts/my-experience-implementing-dark-mode-on-my-personal-blog-using-the-newest-tailwind-css-v4-beta-with--lpbcmxcjq

**Comment by idoshamun** [comment]
I'm not sure they had +250 rep during the time of upvote

**Comment by Richard-Raph** [comment]
> @Richard-Raph, I sent you an email about suspicious activity in your account before you opened this issue. Please read it carefully, it should provide the details
> 
> @finfin not all upvotes grant reputation, only those from users with +250 reputation. Please read more here: https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points

> @idoshamun,  Alright, I understand now,
Thanks for your support
