### ISSUE TITLE
🐛 BUG: The post form on the squads pages is displaying incorrectly.

### ISSUE THREAD

**Issue by bruno-keiko** [dailydotdev/daily#1663]
### What went wrong? 🤔

![image](https://github.com/user-attachments/assets/307f2496-4b75-4d2b-9a34-e1d43a8a3367)
When I focus Input:
![image](https://github.com/user-attachments/assets/fa0d2d94-e491-44b2-9384-471c6bbfbb2e)

### Expected Behavior

![image](https://github.com/user-attachments/assets/bfa21629-f6ee-41e7-bf81-6cacab475a8f)

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/squads/ai'
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @bruno-keiko,

Please provide more details on the OS and browser you use
