### ISSUE TITLE
🐛 BUG: Nothing in my FEED | 'Your feed filters are too specific'

### ISSUE THREAD

**Issue by InformaticPc** [dailydotdev/daily#1667]
### **_'Your feed filters are too specific'_** 
***

My feed is empty when I open it, I even choose different filter(just one more) and still empy.
I receive email with my feed (is ok) and then if I press in my profile picture -> profile then I can go to "FEED" at top left and is full (is good in this case) so... I don't understand what is the first page that it show me up.
![image](https://github.com/user-attachments/assets/f8ec791c-5885-455b-9082-2cfa0a97fd74)
---
After I take this actions:  _profile picture -> profile_. Then I can go to _FEED_
![image](https://github.com/user-attachments/assets/6a2fa4e1-1ac3-4af8-9050-930fb8be282d)
---
I open it like this always
![image](https://github.com/user-attachments/assets/96fe0680-9054-4ef4-b202-1de00371149c)
--- 

### Expected Behavior

Show me up popular trends about my preference topics, I guess...

### Steps to Reproduce Issue

```bash
1. The first time when I click on the extension and it opens.
```

### Solution Proposed

Sorry, I'm not sure what is going on, could be a but config by my side. But I didn't touch nothing yet apart of putting my prefer topics for the first time.

### Screenshots

![image](https://github.com/user-attachments/assets/f8ec791c-5885-455b-9082-2cfa0a97fd74)

### Environment

Windows 11 Version	10.0.22631 Build 22631

### Browsers

Firefox

### OS

Windows

### Version of daily.dev

10.0.22631 Build 22631

### Additional Context

```bash
Always that I open a new tab in Firefox with that extension it happens.
![image](https://github.com/user-attachments/assets/96fe0680-9054-4ef4-b202-1de00371149c)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @InformaticPc You are on a very old Firefox version.
We decided to no longer support Firefox due to their policies.

You can find more information in this thread:
https://github.com/dailydotdev/daily/issues/1320
