### ISSUE TITLE
🐛 BUG: Devcard titles overflow are hidden

### ISSUE THREAD

**Issue by Snoupix** [dailydotdev/daily#1669]
### What went wrong? 🤔

The title is self explanatory

### Expected Behavior

Titles should be readable regarding their sizes

### Steps to Reproduce Issue

```bash
1. Go to Profile
2. Click on Devcard
3. See the error
(also fails the same way on the image tag generated)
```

### Screenshots

![screenshot](https://github.com/user-attachments/assets/fcc0f1cf-d4dc-4dc1-814c-8fc3b12a16ac)

### Browsers

Firefox

### OS

Linux

### Version of daily.dev

web, so latest stable ?

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @Snoupix thanks for raising this, I can reproduce this.
We'll look into this.

**Comment by Snoupix** [comment]
My pleasure @rebelchris, would be a good first issue for a beginner IMO

**Comment by rebelchris** [comment]
@Snoupix thanks for raising, it already got solved.
