### ISSUE TITLE
🧩 FEATURE REQUEST: User Setting to Optionally Open Links as a New Tab

### ISSUE THREAD

**Issue by NyWn** [dailydotdev/daily#167]
### Description

I would like to have an option in the user settings to open links as new tabs instead of directly navigating.

### Solution

The option could be inlined with the existing user preferences, like so:

<img width="867" alt="Screen Shot 2020-07-04 at 12 30 35 PM" src="https://user-images.githubusercontent.com/11378839/86516908-94899000-bdf2-11ea-8a15-cb12b3943241.png">

### Alternate Solutions

Obviously the same can be achieved by manually opening the link as a new tab, however it's _somewhat_ commonplace to have external links open as a new tabs these days.

p.s.
Thanks v. much for developing dailydotdev, I've been using it for a few months now and it's greatly broadened my daily reading list 🙌 .

**Comment by idoshamun** [comment]
Hi @NyWn,

Thanks for suggesting another great feature :)
I'm definitely up to implement this and I would love to get your contribution.
Would you like to hop-on this challenge? I will make sure to guide you through the whole process.

**Comment by NyWn** [comment]
Hi @idoshamun,

I'm a little tight on time these days (who isn't? :) ), but if you'd like to give me a "getting started" run down for anything I should know, I can see what I can do

**Comment by idoshamun** [comment]
This issue involves both updating the API and the extension itself.

API:
A new field called "openNewTab" (for example) should be added to the `Settings` entity.
It should also be added to the equivalent GraphQL type under `schema/settings.ts`.
And lastly also to the backward compatibility routes under `compatibility/settings.ts`.

Extension:
You can take a look at this PR about how to implement a new setting in the extension:
https://github.com/dailydotdev/daily-apps/pull/102
Once you implement this setting, you will have to change the `card` and `insane` component to take into account and change the anchor target based on the variable.

I understand these times are super busy, so please let me know if you want me to implement this instead.

**Comment by NyWn** [comment]
Great, thanks for the details @idoshamun - will take a look in the next few days I reckon.

**Comment by idoshamun** [comment]
Hi @NyWn,

Let me know if you have time for this issue or would you like me to proceed 😃
Thanks again for being super active!

**Comment by NyWn** [comment]
@idoshamun Here ya go!

 https://github.com/dailydotdev/daily-apps/pull/135

Sorry for the delay
