### ISSUE TITLE
🐛 BUG: Firefox login stuck in infinite loop

### ISSUE THREAD

**Issue by AndreiVladescu** [dailydotdev/daily#1673]
### What went wrong? 🤔

I attempted to log into my newly made account, by using sign in by GitHub. After creating the account, it redirected me to log in, with a "welcome back", but after logging in, it just redirects to the same webpage. I tried this 20~ times, incognito and also cleaned cache and cookies. No ad-blocker was running.
![login](https://github.com/user-attachments/assets/234f5673-590b-4f51-af12-5f7cc87d24e8)

For a split second, I can see that the website pulled my info and tries to do an initialization, but goes back to log in. I managed to do a screenshot.
![image](https://github.com/user-attachments/assets/11211f30-4bea-417e-b92e-32384276e7de)

### Expected Behavior

When I click "Log In" to log me in.

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/onboarding'
2. Click on 'Log In'
3. Goes back to "https://app.daily.dev/onboarding"
4. Infinite loop
```

### Environment

Windows 10 22H2

### Browsers

Firefox

### OS

Windows

### Code of Conduct

- [x] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @AndreiVladescu,

We found out an issue in our signup flow. Please try again
