### ISSUE TITLE
Can't format posts

### ISSUE THREAD

**Issue by SpyC0der77** [dailydotdev/daily#1674]
### What went wrong? 🤔

When creating a post, I used markdown. I clicked on preview, and it looked good. When I posted, it was plaintext.

### Expected Behavior

The markdown should be rendered

### Steps to Reproduce Issue

```bash
1. Go to create a post
2. Enter markdown
3. Click preview to make sure it is valid
4. Post
4. See the error
```

### Browsers

Other

### OS

iOS

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @SpyC0der77,

Can you share a screenshot please?

**Comment by SpyC0der77** [comment]
Here are some screenshots of the post. ![image](https://github.com/user-attachments/assets/77aa137d-4450-4705-8f71-11af7c062bea)![image](https://github.com/user-attachments/assets/9b89f55f-329e-4542-85ee-d31f96175330)![image](https://github.com/user-attachments/assets/509dbde7-fbcb-4f4b-ac06-9dd4f5c92116)

**Comment by idoshamun** [comment]
Please read more here: https://github.com/dailydotdev/daily/issues/1657
