### ISSUE TITLE
🐛 BUG: Reputation Point did not change correctly 

### ISSUE THREAD

**Issue by finfin** [dailydotdev/daily#1675]
### What went wrong? 🤔

Based on documentation, with upvote from user with reputation > 250, the post user should gain 10 reputation, but it did not happen.

### Expected Behavior

correctly gain reputation based on the rule 
https://docs.daily.dev/docs/your-profile/reputation

### Steps to Reproduce Issue

```bash
1. I got reputation of 110 at least from last lear
2. Posted some articles
3. Got some upvote from user with reputation 250+ ( for example https://app.daily.dev/posts/ai-bots-are-rising-fast-ai-crawlers-now-make-up-28-of-googlebot-s-activity-showing-their-growin-15yhi2bsk )
4. Reputation did not change
```

### Browsers

Other

### OS

Mac

### Additional Context

```bash
I've reported here previously:
https://github.com/dailydotdev/daily/issues/1661#issuecomment-2548289906

Got response of "I'm not sure they had +250 rep during the time of upvote"

So I observed a little while and in this [post](https://app.daily.dev/posts/ai-bots-are-rising-fast-ai-crawlers-now-make-up-28-of-googlebot-s-activity-showing-their-growin-15yhi2bsk) I got a user with 1.7K reputation upvoted, but the reputation still did not change after several days.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @finfin,

Every user is limited to 6 reputation grants per day. In your case, the user has reached their daily cap before upvoting you, hence you didn't receive the reputation as you describe.
