### ISSUE TITLE
🐛 BUG: Streak never fills for the current day

### ISSUE THREAD

**Issue by lukaskretzschmer** [dailydotdev/daily#1676]
### What went wrong? 🤔

![image](https://github.com/user-attachments/assets/51e7be97-b2a4-41fa-af81-426b9dd29116)
This never shows as complete, is it because I am in a negative timezone?
I do this everyday though.

### Expected Behavior

Streak filled or fire idk

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
I have no idea, be on a different timezone I guess, maybe negative tz.
```

### Solution Proposed

Match the client or profile setting's timezone with the server with a proper calculation.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @lukaskretzschmer,

We have an ongoing issue that we hope to fix soon.
https://github.com/dailydotdev/daily/issues/1619
