### ISSUE TITLE
🐛 BUG: Reputation is not awarded for upvotes on comments

### ISSUE THREAD

**Issue by antonthomas** [dailydotdev/daily#1678]
### What went wrong? 🤔

3 weeks ago I posted a comment that gained 5 upvotes, yet I don't seem to have gotten any reputation for it.

![image](https://github.com/user-attachments/assets/0b1f0220-7a45-4799-99c8-90603928eef1)

![image](https://github.com/user-attachments/assets/d0e51deb-3c9f-4004-bcc3-bcab6072c1a8)

### Expected Behavior

I expected to gain reputation according to the descibing page: [Reputation](https://docs.daily.dev/docs/your-profile/reputation)

### Steps to Reproduce Issue

```bash
NA
```

### Solution Proposed

NA

### Environment

Windows 11, MS Edge 131.0.2903.99 (64-bit)

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @antonthomas,

Reputation is granted only when someone with 250+ reputation upvote your content (post/comment).
Please read more here: https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points

**Comment by antonthomas** [comment]
Hi @idoshamun,

Thanks for your quick response, I must've read over that bit.

May I suggest adding a note to [How to earn reputation points](https://docs.daily.dev/docs/your-profile/reputation#how-to-earn-reputation-points) as it is now only mentioned in the section below: [Privileges unlocked with reputation](https://docs.daily.dev/docs/your-profile/reputation#privileges-unlocked-with-reputation)?

**Comment by idoshamun** [comment]
Yap, we will take care of it

**Comment by nimrodkra** [comment]
@antonthomas thanks for the valuable feedback! The fix is now live
