### ISSUE TITLE
🧩 FEATURE REQUEST: Sort Custom Bookmark Labels Alphabetically

### ISSUE THREAD

**Issue by NyWn** [dailydotdev/daily#168]
### Description

It'd be great to have custom bookmark labels sorted alphabetically descending

![Screen Shot 2020-07-14 at 6 14 51 PM](https://user-images.githubusercontent.com/11378839/87481743-f1105a80-c5fd-11ea-960c-0fd0edbc4237.png)

### Solution

Pretty clear I think :)

### Alternate Solutions

N/A

**Comment by idoshamun** [comment]
Hi @NyWn,

Definitely makes sense! Right now it's ordered by date of creation.

**Comment by idoshamun** [comment]
Diving into the code I see that's already implemented:
https://github.com/dailydotdev/daily-api/blob/master/src/schema/bookmarks.ts#L214
It's pretty weird that it's not ordered on your end.
Maybe there are some spaces or anything at the beginning of the `General` list?

**Comment by NyWn** [comment]
Weird, it's ordered now.. Closing as working 😄 
![Screen Shot 2020-07-15 at 11 54 09 AM](https://user-images.githubusercontent.com/11378839/87567177-fe772480-c691-11ea-9117-cbafe9e9e92e.png)
![Screen Shot 2020-07-15 at 11 54 23 AM](https://user-images.githubusercontent.com/11378839/87567179-ff0fbb00-c691-11ea-9327-61f9d748717f.png)
![Screen Shot 2020-07-15 at 11 54 29 AM](https://user-images.githubusercontent.com/11378839/87567182-ffa85180-c691-11ea-978e-4b937a2eb48c.png)

**Comment by idoshamun** [comment]
One edge case might be that once you created the list for the same session it will be on top of every other list.
If you just created the lists this might be the reason.
