### ISSUE TITLE
🐛 BUG: Deduplicate Tiles Pointing to Same Source

### ISSUE THREAD

**Issue by NyWn** [dailydotdev/daily#169]
### Description

I frequently come across duplicate articles that despite looking like they come from different sources (indicated by the mini "source tile" in the bottom left of the panel), they both point to the same destination, example:

![Screen Shot 2020-07-14 at 3 54 27 PM](https://user-images.githubusercontent.com/11378839/87470668-18a9f780-c5eb-11ea-860b-bc62ffda6ea9.png)
![Screen Shot 2020-07-14 at 3 54 31 PM](https://user-images.githubusercontent.com/11378839/87470670-19428e00-c5eb-11ea-97aa-a81b62fd5daa.png)

Ignoring that the picture and headline are the same, both articles point to the same destination: https://blog.bitsrc.io/14-javascript-code-optimization-tips-for-front-end-developers-a44763d3a0da

### Solution

I haven't spent much time digging into the `daily-redirector` repo or the underlying data structures, however a simple first check would obviously be against duplicate URLs. Being verbose, the rss data from each website feed for the given article is:

echojs:
```
<item>
  <title> 14 JavaScript Code Optimization Tips for Front-End Developers </title>
  <guid>https://blog.bitsrc.io/14-javascript-code-optimization-tips-for-front-end-developers-a44763d3a0da</guid>
  <link> https://blog.bitsrc.io/14-javascript-code-optimization-tips-for-front-end-developers-a44763d3a0da </link>
  <description>
    <![CDATA[ <a href="http://www.echojs.com/news/36914">Comments</a> ]]>
  </description>
  <comments>http://www.echojs.com/news/36914</comments>
</item>
```

bitsrc:
```
<item>
  <title>
  <![CDATA[ 14 JavaScript Code Optimization Tips for Front-End Developers ]]>
  </title>
  <link>https://blog.bitsrc.io/14-javascript-code-optimization-tips-for-front-end-developers-a44763d3a0da?source=rss----5c2fdf847f4a---4</link>
  <guid isPermaLink="false">https://medium.com/p/a44763d3a0da</guid>
  <category>
  <![CDATA[ programming ]]>
  </category>
  <category>
  ...
  </category>
  <dc:creator>
  <![CDATA[ Mahdhi Rezvi ]]>
  </dc:creator>
  <pubDate>Tue, 14 Jul 2020 18:28:54 GMT</pubDate>
  <atom:updated>2020-07-14T19:06:41.239Z</atom:updated>
  <content:encoded>
    <![CDATA[...]>
  </content:encoded>
</item>
```

Given that the link values are nearly the same, apart from the added query parameter in bitsrc's url, here's a bit of code I threw together to do a similarity check, which could suffice: https://jsfiddle.net/_nywn/6akvp05y/7/

### Alternate Solutions

N/A

**Comment by idoshamun** [comment]
Hi @NyWn,

Thanks for dedicating so much to improving daily.dev and investigating the issues.
I also noticed the duplicate articles and indeed your solution is pointing in the right direction but not completely.
We used to strip query params in the past but actually some sources require the query param otherwise the link is broken, for example:
https://developer.apple.com/news/?id=aprhkd7d
http://blogs.msdn.microsoft.com/devtestlab/?p=4035
It's very weird behavior for a blog, I agree, but this is it for now.
So maybe we can adapt your code to specific query params like `source`.
Probably every Medium based blog (like bitsrc) will act the same way.
What do you think?

**Comment by idoshamun** [comment]
For now, I've applied this fix:
https://github.com/dailydotdev/daily-functions/blob/master/crawler/index.js#L101
Before scraping a website I remove the `source` query param of Medium. This should be enough for preventing dups at least in this edge case. As I mentioned in my last comment, some websites heavily rely on query params so I can't remove them completely.

**Comment by NyWn** [comment]
> Hi @NyWn,
> 
> Thanks for dedicating so much to improving daily.dev and investigating the issues.
> I also noticed the duplicate articles and indeed your solution is pointing in the right direction but not completely.
> We used to strip query params in the past but actually some sources require the query param otherwise the link is broken, for example:
> https://developer.apple.com/news/?id=aprhkd7d
> http://blogs.msdn.microsoft.com/devtestlab/?p=4035
> It's very weird behavior for a blog, I agree, but this is it for now.
> So maybe we can adapt your code to specific query params like `source`.
> Probably every Medium based blog (like bitsrc) will act the same way.
> What do you think?

Agreed - removing query param would be a breaking change.. 

Looks like flower girl is still showing up 2x

![Screen Shot 2020-07-15 at 12 29 02 PM](https://user-images.githubusercontent.com/11378839/87571163-a17e6d00-c697-11ea-9125-1541bc784287.png)
![Screen Shot 2020-07-15 at 12 29 22 PM](https://user-images.githubusercontent.com/11378839/87571167-a2170380-c697-11ea-8c47-1040f7ae8c2d.png)

Looking at the response to `operationName=Feed` and excluding some values for brevity:
**Bits and Pieces**:
```
{
                    "node": {
                        "title": "14 JavaScript Code Optimization Tips for Front-End Developers",
                        "url": "https://blog.bitsrc.io/14-javascript-code-optimization-tips-for-front-end-developers-a44763d3a0da",
                        "image": "https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/31bf7fec2e7d3b26ec024d4469007615",
                        "ratio": 1.66666666666667,
                        "placeholder": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAGAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAhEAABAwMEAwAAAAAAAAAAAAABAgMEAAURBhIUMSFB0//EABUBAQEAAAAAAAAAAAAAAAAAAAQG/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAA1Ei/9oADAMBAAIRAxEAPwCvu09EybBhQnZDKZLKmw6QMtlB8kJz3twO/QqZc01a1LUTcJhJJJPET9KUqbZQqqBkdaOEOz//2Q==",
                        "readTime": 10,
                        "source": {
                            "id": "bit",
                            "name": "Bits and Pieces",
                            "image": "https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/bit",
                            "public": true,
                            "__typename": "Source"
                        }
                }
```

**JSK**:
```
{
                    "node": {
                        "title": "14 JavaScript Code Optimization Tips for Front-End Developers",
                        "url": "https://blog.bitsrc.io/14-javascript-code-optimization-tips-for-front-end-developers-a44763d3a0da",
                        "image": "https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/31bf7fec2e7d3b26ec024d4469007615",
                        "ratio": 1.66666666666667,
                        "placeholder": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAGAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAhEAABAwMEAwAAAAAAAAAAAAABAgMEAAURBhIUMSFB0//EABUBAQEAAAAAAAAAAAAAAAAAAAQG/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAA1Ei/9oADAMBAAIRAxEAPwCvu09EybBhQnZDKZLKmw6QMtlB8kJz3twO/QqZc01a1LUTcJhJJJPET9KUqbZQqqBkdaOEOz//2Q==",
                        "readTime": 10,
                        "source": {
                            "id": "jsk",
                            "name": "JSK",
                            "image": "https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/jsk",
                            "public": true,
                            "__typename": "Source"
                        }
                }
```

Clarity question: What is `ratio`?

1. 1:1 `url` value comparison here would work for deduplication 
2. Extra values like `ratio`, `image`, `placeholder` and `readTime` could be used for secondary dedupe logic. Same image should definitely not primary, wouldn't be reliable on its own.


As a left-field idea.. if we wanted to approach this from a different direction, I could propose some NLP-based methods. It's probably a little heavy-handed, and may stray too far from the core-purpose of the app as being a content aggregator. On the other hand, it could open doors in the future for content analysis and other enhancements (i.e. auto-generating tags where the feed does not).

**Comment by idoshamun** [comment]
Thanks for the deep investigation.
Actually, I think I already implemented 1:1 `url` comparison. 
It's super weird that it managed to go through, I'll check it ASAP.

**Comment by idoshamun** [comment]
Apparently I removed this check for some reason.
I've added it back including a test to cover it
