### ISSUE TITLE
🐛 BUG:  Article doesn't stay into the "read" state

### ISSUE THREAD

**Issue by salesh** [dailydotdev/daily#170]
### What went wrong? 🤔

When I open the article, the article goes into the "read" state, but when I refresh or open a new tab - the article returns as if it had not been read.
I also tried in Chrome and in Firefox.

### Expected Behavior

It should remain in a read state

### Actual Behavior

Shows as if it has not been opened/read

### Steps to Reproduce Issue

https://imgur.com/a/1mtFA7g

### Solution

https://imgur.com/a/JIhWOaf

Didn't have a lot of time to investigate this latest update from 23 July,  but I noticed this with a quick analysis.
I will check it more today what changes have taken place.

#### Operating System

Ubuntu 18.04

#### Version of Daily

2.18.2

#### Browser

Chrome and Firefox

**Comment by idoshamun** [comment]
Hi @salesh,

Thanks for reporting this issue, I can reproduce on my end as well.
In the last version, 2.18.2, we have migrated completely all API calls to `daily.dev`.
There might be an issue related to cookies, I'll check further and let you know.

**Comment by salesh** [comment]
Wow @idoshamun, what a speed  😁 Thank you very much :+1:

**Comment by idoshamun** [comment]
@salesh thank you 🔥
This was an easy one to spot 🕵️‍♂️
