### ISSUE TITLE
🐛 BUG: Unable to upgrade to a premium account

### ISSUE THREAD

**Issue by kingkarlito** [dailydotdev/daily#171]
### What went wrong? 🤔

    Unable to upgrade to a premium account, it ends up looping between https://daily.dev/premium and 
    https://daily.dev/almost-there

### Expected Behavior

    After clicking upgrade now, I would be directed to a checkout page to complete the transaction.

### Actual Behavior

    It ends up looping me back and forth between two pages.

### Steps to Reproduce Issue

    First, I start in the daily.dev extension page chrome-extension://jlmpjdjjbgclbocgajdjefcidcncaied/index.html

![1](https://user-images.githubusercontent.com/44263434/88452734-c5277d00-ce26-11ea-9a8a-1c1daa222935.jpg)

    I click Get Premium here from the extension page and it changes into the next screenshot

![2](https://user-images.githubusercontent.com/44263434/88452792-467f0f80-ce27-11ea-9ba6-244007867cf9.jpg)

    From here I click Upgrade Now, whether I select monthly or billed annually, I still end up in a loop unable to upgrade.

![3](https://user-images.githubusercontent.com/44263434/88452802-572f8580-ce27-11ea-806e-9fe2aad95acc.jpg)

    https://daily.dev/almost-there is loaded, and I eventually click https://daily.dev/premium after I confirm that I have completed 
    the steps marked with green check marks

![4](https://user-images.githubusercontent.com/44263434/88452815-69112880-ce27-11ea-9492-3c96527d87d9.jpg)

    https://daily.dev/premium is loaded, from here I click Upgrade Now, both Annually and Monthly end up on the same page...

![5](https://user-images.githubusercontent.com/44263434/88452830-8cd46e80-ce27-11ea-9f69-62c286e60bd3.jpg)

    And I'm back to https://daily.dev/almost-there , and from there on all I can do is loop between https://daily.dev/almost-there 
    and https://daily.dev/premium

    Never reaching the checkout page.

### Solution

    I would guess this issue has something to do with account logins between the extension page and the https://daily.dev   
    webpages.  On the extension page, chrome-extension://jlmpjdjjbgclbocgajdjefcidcncaied/index.html, I must be logged in to 
    even see the link to "Get Premium" from picture 1.  But after I click "Upgrade Now", seen in picture 2, I'm connecting to 
    https://daily.dev/... and I am no longer logged in to any account.  Also, there is no option to log in again on the 
    https://daily.dev webpages.  The "Get Started - It's Free" link on these websites directs you to the Chrome web store to 
    download the extension.  This would explain why I get repeatedly sent back to https://daily.dev/almost-there after I select   
    "Upgrade Now" from https://daily.dev/premium.  The second green check-mark on https://daily.dev/almost-there says "make 
    sure you are logged in to your user. If you did not create a user yet, please sign up and then proceed to the next step."  
    Continuing a log in from the extension page to the daily.dev website or the ability to log in from the daily.dev websites should 
    take care of this bug.

### Environment

    Oklahoma in July is just too hot!

### Operating System

    Windows 10 Pro version 2004

### Version of Daily 

    Daily.dev extension version 2.18.2

### Browser

    Chrome Version 84.0.4147.89 (Official Build) (64-bit)

###

    I'm KingKarlito and my email is andr9290@gmail.com if I didn't give enough info for you to be able to recreate this issue, feel 
    free to send an email.  Please email me once this bug is resolved so I can subscribe.

### Thank you for taking your time to report the issue! Appreciate your help.

    And thank you for reading all this.

**Comment by idoshamun** [comment]
Hi @kingkarlito,

Thank you for providing so many details.
I believe I've fixed the issue, could you try again, please?
