### ISSUE TITLE
🧩 FEATURE REQUEST: Remove friends invite CTA

### ISSUE THREAD

**Issue by Jarvvski** [dailydotdev/daily#172]
## Feature Request

Please allow the ability to hide/remove the CTA:

![image](https://user-images.githubusercontent.com/6012840/90107367-bf53f600-dd59-11ea-991c-c218b7195e42.png)

### Description

I pay for premium, and I consider this spam. I don't want to be pestered to tell my friends/colleagues about the app. I share things naturally, don't block my _new tab page_ with a CTA like this.

### Solution

Option in layout settings to hide/remove CTA.

### Alternate Solutions

N/A

**Comment by idoshamun** [comment]
Hi @Jarvvski,

First of all, thank you for being a premium user! 🤗
I can relate to what you are saying and we will proceed with hiding by default the CTA for the premium users.
I would just like to ask for your patience as we are working on a big release so it might take some time.
Hopefully, you can expect this release in the next week or so.
As always, I'm here for everything 😃

**Comment by Jarvvski** [comment]
Thanks for the quick turn around @idoshamun
