### ISSUE TITLE
🧩 FEATURE REQUEST: Add a point system to the feed so i can set the points to my favourite tags

### ISSUE THREAD

**Issue by sharmakushal** [dailydotdev/daily#173]
### Description

It will be better if we provide some point system to the tags so we can give more preference to that tags posts, for example, if I set the react point to 2 and node to 1 then the react posts are shown double then the node

**Comment by idoshamun** [comment]
Hi @sharmakushal,

Thank you for suggesting this great feature for improving our feed 🤗
This new system requires a lot of changes to our existing system design. Unfortunately, at the moment we are super busy and we will not be able to add to the product roadmap.
On another note, stay tuned for news that are about to come :)
