### ISSUE TITLE
🐛 BUG: Strange spacing on cards leads to messy structure

### ISSUE THREAD

**Issue by Jarvvski** [dailydotdev/daily#174]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/6012840/90328826-9aa58b80-dfb0-11ea-9745-b4b494389221.png)

Seems like the 'masonry' structure breaks when there isn't a 'time to read'? Should probably enforce some max height so that each card row remains the same.

### What went wrong? 🤔

Unsure.

### Expected Behavior

Masonry structure remains the same.

### Actual Behavior

Rows break in structure.

### Steps to Reproduce Issue

Load the page.

### Solution

Enforce max card size in the parent div?

#### Operating System

MacOS

#### Version of Daily

Chrome extension - 2.18.2

#### Browser

Chrome 84.0.4147.125

**Comment by idoshamun** [comment]
Hi Adam,

Thank you for reporting this issue 🙏
Luckily, we have already redesigned and implemented the layout system both for grid and list views.
We hope to release this version this week. I will close the issue for now but feel free to open again if the issue persists in the new version.

**Comment by Jarvvski** [comment]
@idoshamun got the new version running now. It looks great!

![image](https://user-images.githubusercontent.com/6012840/90479455-c3a85680-e13f-11ea-8b51-4f0a43d3c6bb.png)

**Comment by idoshamun** [comment]
Glad you like it! Hopefully, you can feel the performance boost as well 🙏
