### ISSUE TITLE
Daily Android App

### ISSUE THREAD

**Issue by ohari5336** [dailydotdev/daily#176]
I want some support of daily API for my this app:
https://github.com/ohari5336/Daily-Android-App

**Comment by idoshamun** [comment]
Hey!

Thanks for reaching out.
Unfortunately, our API is not available to 3rd party applications and we cannot provide support for such applications.
I kindly ask you to not proceed with this project for public use.
I hope you understand 🙏

**Comment by ohari5336** [comment]
Ok but I developing this app using your extension APIs if any problem then tell me or please give me permission

**Comment by idoshamun** [comment]
As I mentioned above, you cannot use our API. I'm sorry.
