### ISSUE TITLE
🧩 FEATURE REQUEST: Webpage Bookmark

### ISSUE THREAD

**Issue by drtobbyas** [dailydotdev/daily#177]
## Feature Request

Webpage Bookmark

### Description

I would like to see daily.dev equipped with functionality to bookmark pages(not just feeds provided by daily.dev) from the browser (much similar to how browser bookmarks work or Raindrop.io). And also able to create different folders for different categories of content. It would also be nice to have search functionality to search for bookmarked webpages. 

I really love daily.dev with awesome feeds at my fingertip. It's really splendid getting updated with the latest happenings in the tech world. 
It's painful sometimes I go voyage myself and find nice content on the internet that I bookmark using the browser bookmark(or what do I do). I wish I could add those to my bookmarked collection of awesome feeds I salvaged from daily.dev and maintaining a single diary. Instead, I end up maintaining two different collections, one in the browser and another with daily.dev

I really hope I could maintain a single collection with much ease. I guess many daily.dev users will appreciate this as well.

### Solution

An Icon in the toolbar(much like browser bookmark) to bookmark webpages and also select(or create) folder to add the webpage to

**Comment by idoshamun** [comment]
Hi @drtobbyas,

We have a premium feature that sync your daily.dev bookmarks with Pocket and Raindrop. Once you subscribe to the premium program, you can use these two platforms and save both web bookmarks and daily.dev bookmarks in one place.
Unfortunately, we don't offer any other solution at the moment.
Thanks for dedicating the time and reaching out 🙏
