### ISSUE TITLE
🧩 FEATURE REQUEST: Clicking a card's image in the Daily Newsletter articles should open the link

### ISSUE THREAD

**Issue by NyWn** [dailydotdev/daily#178]
### Description

Mostly as per title - current linkage to article is through the icon in the top right of the card.

### Solution

![Screen Shot 2020-08-25 at 11 07 17 AM](https://user-images.githubusercontent.com/11378839/91192004-72f6a780-e6c3-11ea-9584-076865535a4d.png)

Current link top right, click image to open link instead / as well 

### Alternate Solutions
N/A

**Comment by idoshamun** [comment]
Thanks for the feature request. It's a great idea and it's already live 🦄
