### ISSUE TITLE
🧩 FEATURE REQUEST: Move Hide Button next to Bookmark button in Card View

### ISSUE THREAD

**Issue by ZakharyH** [dailydotdev/daily#179]
### Description

Move the hide button from inside the card's context menu to the card itself. Perhaps also add a small popup that says "Post Hidden - Undo" where undo is a button that unhides the card. This saves a click when hiding cards, which adds up when scrolling through your feed in the morning.

### Solution
NA

### Alternate Solutions
NA

**Comment by idoshamun** [comment]
Hi @ZakharyH,

Thanks for the feature suggestion ✌️
I checked the analytics for the usage of this feature and unfortunately, it's rarely used.
For the time being, we will keep this button in the context menu and will not take out.
I hope you understand 🙏
