### ISSUE TITLE
🐛 BUG: "Failed to fetch information" when adding custom rss feed

### ISSUE THREAD

**Issue by ZakharyH** [dailydotdev/daily#180]
### What went wrong? 🤔

When trying to add a custom rss feed (in this case: https://www.anandtech.com/rss/), I receive an error saying it was unable to fetch the information of the rss feed

https://i.imgur.com/74e9VJM.png

### Expected Behavior

It should add the rss feed without issues

### Actual Behavior

I receive the error message when trying to add _any_ custom rss feed

#### Operating System

Linux

#### Version of Daily

v2.19.2

#### Browser

Vivaldi | 3.2.1967.47 (Stable channel) (64-bit)
Revision | 6b61acd1b5ee61882d22beddd8ec577e8cf4e771
OS | Linux
JavaScript | V8 8.4.371.23
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

**Comment by idoshamun** [comment]
Hey @ZakharyH,

I just got back from a vacation. I will do my best to take a look at it as soon as I can.
Thanks for reaching out! 🙏

**Comment by idoshamun** [comment]
Everything should work now 🔥
Let me know if you still encounter this issue.

**Comment by ZakharyH** [comment]
I no longer get the "Failed to Fetch Information error" but after I add the rss feed, it doesn't show any stories all i get is a blank page: https://i.imgur.com/Gu3Iurg.png

**Comment by idoshamun** [comment]
Once you add a new source, only new stories will be added. Currently, we don't fetch previous stories.

**Comment by ZakharyH** [comment]
Yeah everything seems to be working now. Thanks!
