### ISSUE TITLE
🐛 BUG: The ACTIVE USER Session cached on headers are a concern for any user of this extension.

### ISSUE THREAD

**Issue by samarthsaxena** [dailydotdev/daily#181]
### What went wrong? 🤔

The new tab(with the extension enabled ) shows all of the links where a user is currently logged in, which; as an end user's perspective is very concerning about the data being cached into the extension.

As an end-user, we expect to see the feature of this product but sharing our data on this related to other sites we're logged into.

### Expected Behavior

This extension MUST NOT cache or store authentication-tokens/passwords/session info of other windows.
If really needed then the user must have a choice to enable this explicitly.
This must not be the default behaviour.
### Actual Behavior

Explained in ISSUE
### Steps to Reproduce Issue

1. Just add the extension to chrome.
2. log into some other sites.
3. press ctrl+tab to open a new tab where this extension shows all the feeds and news.
4. on the top header section it'd show all the sessions where the current user is active. (<-- seems a concerning issue to me)
### Solution

option 1. Remove this.
option 2. let the user decide if this needs to be enabled via profile settings.

### Environment

Browser: Chrome 
#### Operating System
Windows 10
#### Version of Daily
// Version 2.19.2
#### Browser
Browser: Chrome

**Comment by idoshamun** [comment]
Hey @samarthsaxena,

Thanks for dedicating the time to fill this detailed issue.
Unfortunately, I am not able to understand exactly what part of the extension you are referring to.
Could you please send a screenshot?
