### ISSUE TITLE
🧩 FEATURE REQUEST: use as Home Page instead of New Tab Page

### ISSUE THREAD

**Issue by bsdaddict** [dailydotdev/daily#183]
## Feature Request

option to use daily.dev as Home Page instead of New Tab Page

### Description

I have my New Tab page set up the way I like and get utility from. I hardly ever use my Home Page button, however... It would be great to be able to set daily.dev extension as my home page and enjoy the best of both worlds.

### Solution

an option to set as Home Page or New Tab Page when installing, since settings page doesn't enable selecting extensions for home page.

### Alternate Solutions

A live daily.dev URL to set as home page, or serve a local http app with docker.

**Comment by idoshamun** [comment]
Hey!

At the moment, it is not possible to open daily.dev as a home page as we don't have a web version.
We are working hard to deliver some capabilities to the web, but it will take some time.
Thanks for understanding 🙏
