### ISSUE TITLE
🧩 FEATURE REQUEST: Filtering by Tags

### ISSUE THREAD

**Issue by jpadilladev** [dailydotdev/daily#186]
### Description

I would like to request some more filters on Daily.dev, so it is easier to see articles grouped by this filter. The filter I'm thinking on is a list of tags.
Sometimes you want to read articles from a particular topic (IMO, having a list of tags in "My Tags" is not enough, as I have lots of them)
By having this new filter, it would help focusing on news related to a topic / tag. 

### Solution

Having the Search bar is nice, but for a quick filtering is better to use something like [Material-UI Chips](https://material-ui.com/components/chips/#chip-array).
This should be a list of Tags (non-selected by default), and highlighted when selected - very similar to Google Images search by tags.
Potentially, there can be one or more than one tags selected.
This can be placed near the POPULAR / RECENT filters.

<img width="860" alt="Screenshot 2020-09-17 at 10 09 33" src="https://user-images.githubusercontent.com/7279364/93450580-0c356a00-f8ce-11ea-9270-cb066615567e.png">

**Comment by idoshamun** [comment]
Hey!

There is already a possibility to filter by tags. Move your mouse to the sidebar on the left and click the toggle button.
Our popular tag list will reveal and you can also search for tags.
You can add those tags to your feed or just check them one by one.
I'm closing this issue but feel free to open if you can't find it.
Thanks! 🙏

**Comment by jpadilladev** [comment]
Oh okay, so it´s possible to filter clicking on those tags.... Awesome! Thanks.

**Comment by idoshamun** [comment]
You bet!
I guess we should make it more clear.
