### ISSUE TITLE
🧩 FEATURE REQUEST: Add a setting to make the extension not always be the new tab page

### ISSUE THREAD

**Issue by henrispkl** [dailydotdev/daily#187]
### Description

I really like Daily, it truly amazed me as a source of dev news and information. However, I also like using Homey (another home page/new tab extension) for my daily links and most used websites. The problem is that you cant use the two together, since one overrides another as a default new tab page.

### Solution

What I propose is that there could be an optional setting to make the extension not be the default new tab page, but instead be only accessible through the extension button in the browser menu. This way the user could use another extension to be the "new tab" page but Daily would also be accessible in a new tab whenever the user clicked the extension button.

Ideally, it would be perfect if it was possible to make Daily the default home page when the user opens the browser but also have this setting to make it not be the "new tab" page, but I don't know if this would be possible since it seems that the standard in most browsers is to have the "new tab" button to simply open whatever is set to be the default home page.

**Comment by idoshamun** [comment]
Hey @henrispkl 👋

Thanks for the excellent feedback!
Unfortunately, Chrome doesn't allow toggling the New Tab feature so it's not possible to turn it off.
What you can do is to install your favorite New Tab extension last so it will take over the New Tab.
Then, you can simply click on the extension button to open the same page but without the New Tab.
For example, if you install Homey last, you can use daily.dev button to open our extension.
What do you think?

**Comment by henrispkl** [comment]
I did try to do this yesterday, but it didn't work at first. Today I tried it again and it worked correctly lol.
