### ISSUE TITLE
🐛 BUG: Integrated search not working

### ISSUE THREAD

**Issue by santoshgiridhar** [dailydotdev/daily#189]
### What went wrong? 🤔

https://www.awesomescreenshot.com/video/1095568?key=04fc669a733e104e71f28f53324871d2

### Expected Behavior

To search on contents based on the keyword.

### Actual Behavior

No results

### Steps to Reproduce Issue

https://www.awesomescreenshot.com/video/1095568?key=04fc669a733e104e71f28f53324871d2

#### Operating System
macOS Catalina

#### Browser

Chrome Version: 85.0.4183.121 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hey!

Thanks for sharing the details.
I'm aware that we have an issue with the search at the moment, it should be fixed today or tomorrow.
I appreciate your patience 🙏
