### ISSUE TITLE
🧩 FEATURE REQUEST: Replace homepage instead of new tab

### ISSUE THREAD

**Issue by KL13NT** [dailydotdev/daily#193]
### Description

The default behaviour overrides the new tab page provided by the browser to display the `index.html` and related extension files instead. This consumes more resources with every new tab and strains users' network connection even if they do not wish to read anything yet. 

### Solution
One way to solve this is by replacing the related entry in the extension manifest. Replace the `chrome_url_overrides` with the following structure and boom, voila.

```json
// ... 

"chrome_settings_overrides": {
	"homepage": "index.html"
},

// ...
```

This would replace the homepage instead of the new tab page. Much more convenient, and allows more control. 

### Alternate Solutions

If the new tab option must be retained then I suggest a condition in the `index.html` JavaScript that based on user settings either load the original browser files or the extension files.

I'd be willing to work on a PR for this for Hacktoberfest :smiley:

**Comment by idoshamun** [comment]
Hey @KL13NT,

Thanks for the detailed feature request and the solution suggestion 🙏
Unfortunately, it's not possible at the moment to change the manifest as it will require the explicit consent of the users to update to the new version and might drastically affect our community.

Are you familiar with the "Do Not Disturb" mode?
https://daily.dev/support

If it doesn't fit your request, please let me know.

**Comment by KL13NT** [comment]
Hi @idoshamun,

Thanks for the tip. I just tried it out, it seems to take me to `google.com` instead of the browser's default new tab page. Perhaps this could be editable? So for instance, when enabling the `Do Not Disturb` mode a text field with a default value of `google.com` shows up to allow you to change the default page so that a user can change it and have it saved to the same storage with the same permissions.

An extension to this option would be a few buttons that automatically either `reset` to default google.com, `use browser default`, or custom url. 

I'd have to check the inner workings of that `google.com` default first to know whether these are possible in the first place though.

**Comment by KL13NT** [comment]
After a quick look through dailydotdev/daily-apps I found that the google.com hardcoded value is present in the `standalone.js` file on line `37`. Perhaps this logic could be modified to reflect the changes I mentioned?

**Comment by idoshamun** [comment]
Wow! You're quick!
Yes, you're right. The value is indeed hardcoded. As far as I know, there is no way to get the browser's default but maybe things have changed.
But we can do it editable, there's an existing issue https://github.com/dailydotdev/daily/issues/103.
If you want to contribute it as part of Hacktoberfest, let me know and I'll check internally what can be done.
It must involve a new design.

**Comment by KL13NT** [comment]
Actually, it may not involve a new design at all! Upon further digging, I thought why not use the same fullscreen overlay and the same styling to the select/input fields to create a Do Not Disturb overlay instead of a dropdown? This would remove any UI development overhead and instead focus the development time on the storage/detection logic. 

Waiting for your response.

**Comment by idoshamun** [comment]
I'm not sure what you are referring too. 😅

**Comment by KL13NT** [comment]
Once a user installs the extension they're greeted with the tutorial and at the end of it they're presented this overlay/fullscreen card:
![image](https://user-images.githubusercontent.com/20807178/94658704-7228e500-0303-11eb-906c-3f5764f4fb95.png)

We could reuse the same container, just not its children. And reuse the `btn` class for the options along with a simple text field. 

And about the ability to get a browser's default, these defaults are usually documented, this Stackoverflow question has a lot of useful details. https://stackoverflow.com/questions/41819284/how-to-determine-in-which-browser-your-extension-background-script-is-executing

If detecting a default is impossible after reading that then a simple `custom` text field with a default value of `google.com` should be simple and sufficient for most use cases.

**Comment by KL13NT** [comment]
A quick mockup of the potential new design of it: 
![image](https://user-images.githubusercontent.com/20807178/94660190-a8fffa80-0305-11eb-84ce-db15444f22bc.png)
![image](https://user-images.githubusercontent.com/20807178/94660358-d8166c00-0305-11eb-9ee0-747caddd26dc.png)

**Comment by idoshamun** [comment]
Thanks for the awesome mockup!
I'll forward it to our designer, @tsahimatsliah.
Today we have a product planning meeting, I'll raise your suggestion and let you know as soon as I can.

**Comment by idoshamun** [comment]
@KL13NT we decided to proceed with this issue.
I'll close this one and let's proceed here: https://github.com/dailydotdev/daily/issues/103
