### ISSUE TITLE
🧩 FEATURE REQUEST: Do not disturb durations

### ISSUE THREAD

**Issue by ScooterSam** [dailydotdev/daily#194]
## Feature Request

![image](https://user-images.githubusercontent.com/4105581/94673257-6262ce00-030e-11eb-82d2-b0e7104c42f0.png)

### Description

It would be really nice to be able to set for 8 hours during work times, or even the ability to set for x hours.

### Solution

An additional option for 8 hours.

(optional) 
An option for "x hours" - this would show a modal which we can input the amount of hours

Thank you for building such an awesome extension :)

**Comment by idoshamun** [comment]
Hey @ScooterSam,

Thanks for reaching out with this great suggestion.
I just finished a product planning meeting and we decided to do some changes to the DND mode.
It includes your suggestion as well.
Let's proceed here:
https://github.com/dailydotdev/daily/issues/103
