### ISSUE TITLE
🧩 FEATURE REQUEST(docs): Add more languages

### ISSUE THREAD

**Issue by esau-morais** [dailydotdev/daily#198]
## Expected behavior

I believe Daily.dev, as an open-source project, needs to improve the documentation, adding more languages and democratize the access to information to other languages and countries.

## Actual behavior

Just English language, what is very restrictive.

## Solution

Follow this template to organize and improve the languages adding process:

#### Folder Structure

```
DevChallenge
|
|
└───.github/ISSUE_TEMPLATE
|
|
└───assets
│   
|
└───translations
|         |
|         |  README.language.md
|         |
|         |  Translations.md
|
|  README.md
```

- [ ] In the main README, add the link to more translations and the language icons

#### 🌎 *Read in [other languages](#)*

<br>

<kbd>[<img title="Deutsch" alt="Deutsch" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" width="22">](./translations/README.de.md)</kbd> <kbd>[<img title="Español" alt="Español" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/es.svg" width="22">](./translations/README.es.md)</kbd> <kbd>[<img title="Français" alt="Français" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22">](./translations/README.fr.md)</kbd> <kbd>[<img title="Shqip" alt="Shqip" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/br.svg" width="22">](./translations/README.pt_br.md)</kbd>

- [ ] Add a folder called `translations` to the project root

- [ ] Add  a file to the `translations` folder called `Translations.md`: Here will be all the languages in a table with the original name and link to the README

#### Translations

|                                                                                                                                                   | Link                               |
| ------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------- |
| <img alt="Español" title="Español" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/es.svg" width="22">                       | [Español](#) |     |
| <img alt="Português (Brasil)" title="Português (Brasil)" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/br.svg" width="22"> | [Português (Brasil)](#) |
| <img alt="Deutsch" title="Deutsch" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" width="22">                       | [Deutsch](#)          |
| <img alt="French" title="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22">                       | [French](#)          |

- [ ] In the `translations` folder, add a `README.language.md` file (the `language` must be changed by the language abbreviation)

-----

_Note: The icons can be found in these cdn's:_ 

- [ ] `Translations.md` → <https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/country.svg> (`country` must be changed by the country abbreviation)
- [ ] Main `README.md` → <https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/language.svg> (`language` must be changed by the language abbreviation)

**Comment by idoshamun** [comment]
Hey @esau-morais,

I agree that our docs can become much better.
Unfortunately, no one in the core team speaks any other language than English or Hebrew.
Even if someone will contribute the first version of the translation we will not be able to maintain it.
I guess for the time being we will have to remain with English.
Thank you for thinking about us 🙏

**Comment by esau-morais** [comment]
> Hey @esau-morais,
> 
> I agree that our docs can become much better.
> Unfortunately, no one in the core team speaks any other language than English or Hebrew.
> Even if someone will contribute the first version of the translation we will not be able to maintain it.
> I guess for the time being we will have to remain with English.
> Thank you for thinking about us

Thank you for the feedback!!

I agree with you, but not at all. From the moment Daily.dev has a community, it can be something able.

**Comment by idoshamun** [comment]
As a company, I cannot rely soley on the community. We must have the ability to update the docs by ourselves when needed.
At the moment we cannot take responsibility for the translations as it's too much of an operation.
I hope you understand.

**Comment by esau-morais** [comment]
I see. Thank you again for the feedback
