### ISSUE TITLE
🧩 FEATURE REQUEST: Add option to filter more sources

### ISSUE THREAD

**Issue by jeferson-sb** [dailydotdev/daily#199]
### Description

I would love to have an option to filter two or more sources at the same time, like Smashing magazine and CSS-Tricks
I like the Popular section, but seeing dozens of articles from (almost) different places every time it's kind of overwhelming 

### Solution

Currently, when I go to the sidebar menu, search and click I can only see one of clicked the sources at a time, it would be nice to select multiple and save this configuration for the next time I open a new tab

![image](https://user-images.githubusercontent.com/30840709/95377800-703dc380-08b9-11eb-8fc5-5265ac885ec0.png)
![Suggestion](https://user-images.githubusercontent.com/30840709/95377900-8b103800-08b9-11eb-862c-f6af9d992c86.png)

### Alternate Solutions

Maybe have another tab between Popular and Recent like "Based on your interests"

**Comment by idoshamun** [comment]
Hey @jeferson-sb,

Thanks for the effort of submitting this request and also creating this awesome mockup.
You can currently toggle on/off sources that you would like to see in your feed.
Open the sidebar click on the X button to remove a source from your list and the + button to add it.
By default, all sources are enabled and you can disable the ones you don't like.
What do you think?

**Comment by jeferson-sb** [comment]
Oh, that might help, I didn't know that
Thanks @idoshamun
