### ISSUE TITLE
🐛 BUG: Images aspect ratio not right

### ISSUE THREAD

**Issue by esau-morais** [dailydotdev/daily#200]
### What went wrong? 🤔

Firstly, my profile image was not being loaded. Then, I uploaded again and the photo aspect ratio was not right (it never happened) and the issue is just happening in the main page

![Issue correct way](https://res.cloudinary.com/emmorais/image/upload/v1602860843/Daily.dev/issue_correct.png)
_If you see, here is working_

![Issue wrong way](https://res.cloudinary.com/emmorais/image/upload/v1602861022/Daily.dev/issue_wrong.png)
_But here (in the main page) is not right_

![Post author issue](https://res.cloudinary.com/emmorais/image/upload/v1602861881/Daily.dev/author.png)
_Author image aspect ratio_

![Ambassadors issue](https://res.cloudinary.com/emmorais/image/upload/v1602863821/Daily.dev/ambassadors_issue.png)
_Ambassadors image_

### Expected Behavior

Profile picture aspect ratio right

### Actual Behavior

Profile picture aspect ratio not right

### Solution

1. Use `object-fit` CSS property in the image component to make the aspect ration right (main page issue and ambassadors)

    ```
      object-fit: cover
    ```

2. Define the `width` and `height` CSS property (author image)

    ```
      width: 100%;
      height: 100%;
      object-fit: cover
    ```
    _Note: If I just define the `max-width` and `max-height` (actual style), it will not work_

#### Operating System

Zorin OS (Linux)

#### Version of Daily

2.20.3

#### Browser

Chrome (laptop)

**Comment by idoshamun** [comment]
Hey @esau-morais,

Thanks for this issue 👍
We've already fixed the issue in the daily.dev website.
I'll fix it soon in the extension as well.

**Comment by idoshamun** [comment]
I added also `object-fit: cover;` in the extension. Will release it as part of the next version.
Let me know if we miss any other place. Thank you!
