### ISSUE TITLE
🧩 FEATURE REQUEST: Placeholder image in offline mode

### ISSUE THREAD

**Issue by RajnishKatharotiya** [dailydotdev/daily#201]
## Feature Request

When the user tries to open daily.dev tab without internet connectivity, it's serving news from cache but each image from news card is requesting several times and until then it's showing only alt title instead image.

### Solution
Instead of that, we can add a placeholder image when there is no internet connection and cached image.

### Advantages
- By adding a placeholder, we can prevent unwanted requests in the state of no internet. 
- Perfect image can indicate user to connect to the internet for a better experience. 
- Image as placeholder can improve user experience in offline mode.

**Comment by idoshamun** [comment]
Hey @RajnishKatharotiya,

Thanks for the suggestion.
If I remember correctly we should have something in place for this scenario. 
Maybe it's bugged. Let me check.

**Comment by RajnishKatharotiya** [comment]
Hi @idoshamun,
Okay,  If it's bugged or needed to implement. Please let me know. I will be happy to contribute.

**Comment by idoshamun** [comment]
Thanks! It would be great.
Here is the line where we set the image in case of an error:
https://github.com/dailydotdev/daily-apps/blob/master/packages/components/src/components/DaCardPost.vue#L48
You may proceed by checking it and fixing it if needed.
It might be needed to store the image locally although the image should be cached in most cases.
Let me know if you need further help

**Comment by RajnishKatharotiya** [comment]
Okay, I'll look into it. Thanks.

**Comment by Sameedahmad** [comment]
Are you working on this one @RajnishKatharotiya ??

**Comment by idoshamun** [comment]
Hey @Sameedahmad,

Looks like @RajnishKatharotiya is not available to work on this.
Would you like to do it instead? 🙏

**Comment by Sameedahmad** [comment]
Sure, I would love to work on this one, Would you elaborate on what exactly should I change?

**Comment by idoshamun** [comment]
The thing is that currently if the image fails to load it changes the source to a remote fallback image.
We would like to download the remote image and add it to the local folder so it will be available even without the internet.
This is where the magic happens:
https://github.com/dailydotdev/daily-apps/blob/master/packages/components/src/components/DaCardPost.vue#L140

Thanks!

**Comment by dhruv479** [comment]
Hey @idoshamun Can I pick up this task?

**Comment by dhruv479** [comment]
I looked into this issue, the images are generally cached very well in the memory, do we need to store the placeholder is assets and use that as the fallback ?

**Comment by idoshamun** [comment]
Yap exactly! @dhruv479 you can go ahead. I'll assign it to you.
Thank you so much :)
