### ISSUE TITLE
🐛 BUG: Unable to run the extension locally

### ISSUE THREAD

**Issue by saqibameen** [dailydotdev/daily#204]
### What went wrong? 🤔

The extension is not showing any feed while running locally and showing just the empty screen. 

### Expected Behavior

Work like the installed one.

### Actual Behavior

![Img](https://i.imgur.com/0Uy2vYt.png)

Here is the error:

![issue](https://i.imgur.com/XvxbCSM.png)

### Steps to Reproduce Issue

I followed the steps described in the readme to run it locally.

#### Operating System

macOS Catalina

#### Version of Daily

Took the latest pull from master 

#### Browser

Google Chrome

**Comment by idoshamun** [comment]
Hey!

Thanks for trying out daily.dev locally and reporting this issue 🙌
You can ignore the logs about the service worker that's fine when you use it locally.
Could you please send me the logs of the extension itself?
Open DevTools in the new tab and navigate to the Console tab.

**Comment by saqibameen** [comment]
Sure. Here is the console tab:

![](https://i.imgur.com/NLbuOu5.png)

And here is the terminal logs on running the docker-compose:

![](https://i.imgur.com/0Yj9GbH.png)

**Comment by idoshamun** [comment]
Everything looks fine. Could you check the Network tab? Look specifically at the GraphQL requests.
Even if the status code is 200 the response might hint that's something wrong...

**Comment by saqibameen** [comment]
Okay so I dug deeper, there was some issue with the Node version and I think I was missing the step to populate the database. One of the packages has some specific Node version requirements. I updated the node version and repeated all the steps and I was able to fix it. Thank you for your time.
