### ISSUE TITLE
🧩 FEATURE REQUEST: Move to top of page button

### ISSUE THREAD

**Issue by mojtabakaviani** [dailydotdev/daily#208]
Many times when reads posts need scrolling move to top of page, please add move up button or sticky header on top.

**Comment by idoshamun** [comment]
Hey! 👋

Thanks for reaching out.
I'll review this issue with the team and get back to you.

**Comment by anushkrishnav** [comment]
Can I work on the issue ?

**Comment by idoshamun** [comment]
Hey @anushkrishnav,

Thanks for the will to contribute!
I have to check what is the status of the design for this feature.

**Comment by idoshamun** [comment]
The design is ready! 🥳

Let's talk first about the user experience.
At first, the button is hidden. 
Once the user scrolls more than 50% of the screen, the button will appear with a transition.
On hover, the button will change its appearance, and on click, it will smoothly scroll to the top.
If the user scrolls back above the threshold (50% of the screen), the button should disappear with a transition.

The in/out transition should like this:
https://codepen.io/ig_design/pen/yrwgwO

Button style properties:
Width/height: 64px
Border radius: 100%
Bottom/right: 32px
Opacity: 0.8 (on hover should be 1)
Background: var(--theme-primary)

The icon inside is our Arrow icon (you can see examples of how to use icons in the codebase)
Width/height: 40px
Color: var(--theme-background-primary)

Let me know if you need further explanation.
Below you can see a demonstration of how it should look like.

![dark theme](https://user-images.githubusercontent.com/1993245/98462211-251a1780-21bb-11eb-9b81-f988c3ac108e.jpg)
![light theme](https://user-images.githubusercontent.com/1993245/98462214-2cd9bc00-21bb-11eb-83ff-f9db8fc50c13.jpg)

**Comment by mojtabakaviani** [comment]
thank you! 👏 
I will hope marge and release very soon.

**Comment by anushkrishnav** [comment]
Please assign it to me
I will work on it.

**Comment by idoshamun** [comment]
Hey @anushkrishnav!

Great talking to you again :)
Let's check what's @mojtabakaviani's status.
I think he started working on it.

**Comment by idoshamun** [comment]
@anushkrishnav looks like @mojtabakaviani is not available to work on this.
Would you like to proceed instead? 🙏

**Comment by anushkrishnav** [comment]
Where do I start ?

**Comment by idoshamun** [comment]
First, start by having a local environment for the extension:
https://github.com/dailydotdev/daily/issues/208#issuecomment-723557211

Then read my technical explanation for implementing the feature here:
https://github.com/dailydotdev/daily/issues/208#issuecomment-723557211

Feel free to ask any question and reach out for help :)

**Comment by mojtabakaviani** [comment]
@idoshamun Can assigned this again to me?

**Comment by idoshamun** [comment]
I need to understand who can complete this issue.
@mojtabakaviani would you have time to work on it? Because you were not available before...
@anushkrishnav have you started to work on this issue?

**Comment by mojtabakaviani** [comment]
@idoshamun I think that you work on it after post your design! I'm ready to work on it.

**Comment by idoshamun** [comment]
Let's wait for Monday, and give @anushkrishnav a chance to reply

**Comment by anushkrishnav** [comment]
I am a bit tied up with a hackathon so if @mojtabakaviani  wants to go ahead please do :)

**Comment by idoshamun** [comment]
It's settled then, @mojtabakaviani I'm assigning you :)

**Comment by mojtabakaviani** [comment]
@idoshamun  When release this feature?

**Comment by idoshamun** [comment]
This week probably. There's a big release coming soon...
