### ISSUE TITLE
🧩 FEATURE REQUEST: Option to disable in new tab but keep the app working

### ISSUE THREAD

**Issue by kishvanchee** [dailydotdev/daily#210]
## Feature Request

Option to disable in new tab but keep the extension working.

### Description

Right now the new tab by default opens daily.dev. I don't see an option to disable it *in new tab*. I would like the option to disable overriding the new tab, at the same time keep it enabled so that I can access it when I require it.

I can currently disable/enable the app completely from the add ons settings.

![Screenshot_20201102_101550](https://user-images.githubusercontent.com/24776049/97831194-52675100-1cf5-11eb-9799-813afb1a6dd6.png)
![Screenshot_20201102_101510](https://user-images.githubusercontent.com/24776049/97831198-53987e00-1cf5-11eb-8a03-6abef1b521ff.png)

### Solution
I would like the option to be present here (on right click) to *disable* override new tab setting. If possible adding this option to the main add on setting page would be ideal.

![Screenshot_20201102_101627](https://user-images.githubusercontent.com/24776049/97831193-51362400-1cf5-11eb-958e-52c5565c1d66.png)

**Comment by idoshamun** [comment]
Hey @kishvanchee,

Unfortunately, browsers don't provide API to disable the new tab feature.
We've implemented a custom Do Not Disturb mode in the application.
You can find it in the header of the extension. It's a clock-shaped button.
<img width="1907" alt="Screen Shot 2020-11-02 at 8 55 27" src="https://user-images.githubusercontent.com/1993245/97838657-53928100-1ce9-11eb-9a18-820c3b607f12.png">

**Comment by kishvanchee** [comment]
@idoshamun Thank you. This definitely seems to be a browser issue.

Anyone else who might come across this, I solved this using New Tab Override Addon.
