### ISSUE TITLE
🧩 FEATURE REQUEST: Most Popular Sites

### ISSUE THREAD

**Issue by Himato** [dailydotdev/daily#213]
### Description
I would like to have a tab for popular sites like the one you made most visited sites. Because I pinned some websites in the old new tab for the websites that I usually visit so that it's only one click away.

What I used to have: -

![Screenshot 2020-11-11 080847](https://user-images.githubusercontent.com/38123939/98775998-d9ec4880-23f6-11eb-8c64-ce5e1a226275.png)

### Solution
What I want to have: -

![popular_sites](https://user-images.githubusercontent.com/38123939/98776028-e670a100-23f6-11eb-850e-1246ff3e73c5.jpg)
 
### Alternate Solution
Or something like this, but for popular sites: -

![Screenshot 2020-11-11 081343](https://user-images.githubusercontent.com/38123939/98776073-f8524400-23f6-11eb-952b-0116ead6fd70.png)

And, thank you for this great extension, and for contributing in the open-source community.

**Comment by idoshamun** [comment]
Hey @Himato!

Thanks for using daily.dev and the kind words 🙌
As far as I know, there is no API to get these websites.
The only API that is available for extensions is the `topSites`.
Here is the documentation, if you fancy checking it out yourself as well 😉
https://developer.chrome.com/extensions/topSites

**Comment by Himato** [comment]
Thank you for your response. I thought about this also because I tried to see the best option, but you can just add an option for it in the layout for each user to add his popular websites because top sites aren't really useful in all cases and you might save it locally so that it doesn't take space in the database for no real benefit.

**Comment by idoshamun** [comment]
Unfortunately, developing our mechanism is out of scope at the moment 😢
In case you want to fall back to the default tab and keep daily.dev you can turn on the Do Not Disturb mode.
