### ISSUE TITLE
🧩 FEATURE REQUEST: Please give options to customize when daily.dev is opened.

### ISSUE THREAD

**Issue by Dhruv-Garg79** [dailydotdev/daily#216]
## Feature Request
Give options to customize when daily.dev is opened.

### Description

I would like the option to turn off daily.dev opening on every new tab page and only shown by keyboard shortcut or by pressing on the extension icon.

**Comment by AbhayAysola** [comment]
This is also something I would like to see implemented. I like my new tab page to be a minimal setup, and daily.dev doesn't support that. So implementing the daily.dev page opening with a keyboard shortcut or by pressing the extension icon would be nice.

**Comment by idoshamun** [comment]
Hey!

You can turn on the Do Not Disturb mode to disable the New Tab functionality.
Once it's turned off you can use the extension icon to open the feed.
Let me know what you think 🙌

**Comment by Dhruv-Garg79** [comment]
Hi! Thank you for your reply. It works as you mentioned by turning on do not disturb. 

But the daily.dev page is still loaded in a new tab and then instantly removed when do not disturb is turned on. I would like, if it can be changed from extension settings if it is possible.

**Comment by Dhruv-Garg79** [comment]
@idoshamun  There also seems to be some kind of bug in do not disturb functionality. When turned on It closes the daily.dev even when you go back from profile page.

steps:
1. opened daily.dev by clicking icon
2. go to profile page
3. pressed alt + left arrow to go back

what happened: the daily.dev page closed on it's own
what should have happened: It should have worked normally

I am not opening the separate bug for this because I don't know if this is the intentional functionality for Do Not Disturb feature.

**Comment by idoshamun** [comment]
Unfortunately, the browser doesn't provide a way to disable the new tab functionality temporarily. We had to "hack" our way to implement the Do Not Disturb.

Regarding your second issue, it's indeed a bug and we didn't plan it this way. I will need to confirm and check it. Thanks 👍

**Comment by idoshamun** [comment]
We have recently released version 3.0. @Dhruv-Garg79 can you please confirm that your issue persists?

**Comment by Dhruv-Garg79** [comment]
Hey, @idoshamun awesome! The issue is resolved.
