### ISSUE TITLE
🧩 FEATURE REQUEST: Please don't hijack new tab

### ISSUE THREAD

**Issue by imskm** [dailydotdev/daily#218]
## Feature Request

Please don't hijack new tab, Instead just open daily page when daily extension is clicked. 

### Description
I just want to be able to keep my original home page in new tab and just access the daily page via extension when I need it.

### Solution
Don't open daily page (list of articles when daily extension is clicked) when clicked on daily extension button instead open the daily page only when user clicks on daily extension button.

**Comment by AbhayAysola** [comment]
#216 . You can achieve this functionality by turning on Do Not Disturb mode. I have another new tab extension, and by using do not disturb mode, the extension and daily.dev work perfectly in parallel.

**Comment by idoshamun** [comment]
@AbhayAysola thank you for assisting me with such a quick reply! 🙏

Indeed you can use Do Not Disturb or install the desired New Tab extension after daily.dev.

Anyway, if you have further questions let's discuss it here #216

**Comment by imskm** [comment]
I've used New Tab extension in Firefox but It doesn't work as I needed. So installing new tab extension doesn't solve what I mentioned.
**What happens when I open new tab after installing and setting new tab extension:**
* It just opens new blank page with no favicon which is weird
* I tried setting custom url to about:home but it didn't work either.
Daily extension is very good extension to have and I want this but I can't use it for this problem. I might hack into code and try to figure out what I need. Let's see I can manage it to do what I need.

**Comment by idoshamun** [comment]
Unfortunately, the browser doesn't provide a way to disable the new tab functionality temporarily. We had to "hack" our way to implement the Do Not Disturb.

If you manage to find a solution to your problem, please let me know.
We might integrate it back into our product.

**Comment by imskm** [comment]
@idoshamun  Sure!

**Comment by Sm4o** [comment]
I can't seem to find the DND feature anymore. It would be great to have it back or try again hacking at this problem. It would be great to be able to click on daily.dev to load the page only when you want.

**Comment by idoshamun** [comment]
Hi @Sm4o,

We renamed it to "Pause New Tab" to be more explicit on what it does

**Comment by gcstr** [comment]
But why not give the users an _actual_ choice of choosing the new tabs page? The _Pause New Tab_ functionality only allows selecting a period when the addon is not displayed, but it is still taking over the new tab configuration.

* Pause new tab does not address the issue that the app hijacks the new tab page
* It is impossible to set another addon to the new tab page
* The notification stripe at the top has two buttons: unpause and _x_. The _x_, which appears to dismiss the notification, actually unpauses it, which is very misleading

> Unfortunately, the browser doesn't provide a way to disable the new tab functionality temporarily

Why temporarily is a must?

**Comment by idoshamun** [comment]
Hi @gcstr,

Unfortunately, Chrome (or any browser) doesn't allow to set the new tab functionality as optional or provide a way for developers to tweak it. Our "Pause New Tab" is a tricky implementation that redirects to the browser's default page.
Those who want to avoid the new tab functionality should use our webapp https://app.daily.dev.
This is the exact reason we built it. We couldn't get around the new tab, and we understand not everyone like this concept. I hope this makes sense.

**Comment by gcstr** [comment]
I believe the confusion is because I'm on Firefox. Different from Chrome, Firefox _allows_ the user to have multiple New Tab Page add-ons and select which one to use.

Dailydev add-on breaks this functionality, reverting back to your page if the user selects another add-on. The _pause_ button seems to be irrelevant for FF users. I'll use the web app, then.

**Comment by dnkdev** [comment]
daily.dev suck, especially extension. respectfully.

**Comment by pedro757** [comment]
I don't know who had the "GREAT" idea to enforce the use of a extension and hijack new tab, 

I think this puts a barrier to new people trying daily.dev, who don't want to install an extension. 

I don't want to see it as new tab, I don't want to get distracted.

Can we just type daily.dev and use it when we want to.

Uninstalling...

**Comment by idoshamun** [comment]
Glad you found out the webapp :)
For anyone else it's on app.daily.dev

**Comment by mrafnadeem-apimatic** [comment]
I like using daily.dev as long as it's not on my new tab. `app.daily.dev` should be the default.

**Comment by CtrlCarlitos** [comment]
Great job on the news content. I find the stuff useful. I removed the Chrome extension after realizing it hijacked my new tab.
