### ISSUE TITLE
🐛 BUG: Aspect ratio on author image in /blog not consistent when image size isn't 1:1

### ISSUE THREAD

**Issue by thinkverse** [dailydotdev/daily#220]
### What went wrong? 🤔

Hello again. 👋

Found an issue on `/blog` where the author image gets squished when the image size isn't in a 1:1 aspect ratio.

### Expected Behavior

Expected aspect ratio on author avatar to match other avatars.

![Screen shot of author image having a one-to-one aspect ratio](https://user-images.githubusercontent.com/2221746/99850671-13068480-2b7e-11eb-842d-74232018dee8.png)

### Actual Behavior

Aspect ratio not consistent when author image isn't a 1:1 size.

![Screen shot of author image not having a one-to-one aspect ratio](https://user-images.githubusercontent.com/2221746/99850750-35000700-2b7e-11eb-8b53-41ac24d86ac9.png)

### Steps to Reproduce Issue

Travel to [`daily.dev/blog`](https://daily.dev/blog), scroll down to `Engineering` section.
View the first post's author section. Works at the time of posting issue.

### Potential solutions

The solution mentioned in #200 might not work in this situation. I saw it's being utilized currently although not working correctly if the image's own aspect ratio isn't a 1:1. The reason being there isn't a parent container with a fixed width or fixed height or no fixed width on the image itself. Making the `img` form according to the source's aspect ratio.

#### Solution 1: Fixed height on parent container

![Screen shot of fixed author image with a red border around the parent container](https://user-images.githubusercontent.com/2221746/99852470-5d3d3500-2b81-11eb-9757-bef30adaed10.png)

Throwing a fixed height on the parent container `.article-publisher` will force the image to grow thanks to the `height: 100%;` trick thus activating the `max-height: 40px;` and `max-width: 40px;` making the `img` container limit the viewport to a 1:1 ratio even if the source aspect ratio doesn't match.

```css
.article-publisher {
    height: 40px;
    ...
}
```

#### Solution 2: Concrete width and height's on image

![Screen shot of fixed author image with a red border around the image and not the parent container](https://user-images.githubusercontent.com/2221746/99852943-53680180-2b82-11eb-9b5a-95f7e7a1cfc9.png)

Setting the 1:1 aspect ratio manually by adding concrete values to the `width` and `height` instead of using the `max-width` and `max-height` trick. This will remove the `max-width` and `max-height` CSS properties entirely since they won't be needed anymore.

```css
.article-publisher {
    width: 40px;
    height: 40px;
    ...
}
```

#### Operating System

macOS High Sierra.

#### Version of Daily

Unknown, not extension.

#### Browser

Issue viewable on:
- Chrome
- FireFox
- Brave
- Safari

Potential fix tested on:
- Chrome
- FireFox
- Brave

**Comment by idoshamun** [comment]
Hey @thinkverse,

Thanks for another great catch!
Our blog and landing page are created and hosted on Webflow which is a NoCode platform.
I'll forward this issue to my partner who is in charge of this project :)
I'll let you know once it's fixed :)

**Comment by thinkverse** [comment]
Always up for reporting issues I find. 👍 &nbsp; As I also encourage others to do as well. 🙂

**Comment by idoshamun** [comment]
Should be fixed now :)
