### ISSUE TITLE
Hide Images + RSS Sources?

### ISSUE THREAD

**Issue by Vondelphia** [dailydotdev/daily#221]
Might you know how I can "hide" or "remove" images from being shown on the new tab Card Layout? I'd rather just read the text. MAYBE if insane layout was a 2 or 3 col layout that'd be nice.... I thought maybe I could use Stylus but that doesn't work.

![image](https://user-images.githubusercontent.com/16372882/100288111-f97d8800-2f43-11eb-8020-eb27c5101cfd.png)

One more questions, where can I find a list of all the RSS Feeds / Sources being used for the "Public Sources"? Perhaps, you'd be so kind to export to .txt / .json?

**Comment by idoshamun** [comment]
Hey!

Thanks for using daily.dev, unfortunately, it's not possible at the moment to hide the images in the card mode.
For this exact reason we built insane mode but I can understand that you don't like it either.

Regarding the sources, they are all presented in the sidebar. Unfortunately, I cannot provide an exported file.
I hope you understand 🙏
