### ISSUE TITLE
🧩 FEATURE REQUEST: Android and IOS Application Development

### ISSUE THREAD

**Issue by rathanakumar** [dailydotdev/daily#222]
## Feature Request
 Android and IOS Application Development

### Description
 I love Daily  Dev. Before knowing about Daily Dev i was used medium for reading tech blogs. Medium has many channels like web ,mobile and extension etc., Sometimes i feel,  Android or IOS app for Daily Dev makes high visibility and usage.

### Solution
Dedicated Android And IOS App Development for Daily Dev.

**Comment by idoshamun** [comment]
Hey @rathanakumar,

Thanks for such a great idea.
We're working on a PWA version of daily.dev that will obviously support mobile devices :)
Stay tuned!
