### ISSUE TITLE
🐛 BUG: do not disturb banner hidden

### ISSUE THREAD

**Issue by zvikarp** [dailydotdev/daily#225]
### What went wrong? 🤔

Just a UI fix, the banner is hidden behind the weekly goal indicator.
![image](https://user-images.githubusercontent.com/13397207/102186233-faf2fe00-3eba-11eb-9a4f-93bb878b85f3.png)

### Steps to Reproduce Issue

Set to do not disturb 🙃

### Solution

Small UI fix, one option is to make the banner higher, so the weekly goal indicator won't cover the text. I'll be happy to open a pull request for this.

#### Operating System
Windows 10

#### Version of Daily
2.27.0

#### Browser
Chrome, Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi Zvi! 🙌

Thanks for reporting this issue.
We would like to proceed with your suggested solution.
We should move the DND banner to the top of the application.
There is one edge case that should be taken into account and it's when the promotional banner is shown together with the DND. In this case, the DND should be at the top, followed by the promotional banner.

I would be more than happy to guide you through the process of fixing it and opening a PR.

**Comment by zvikarp** [comment]
Wow, thank you.

I'm trying to run it locally, having issues with docker-compose:

```
$ docker-compose pull && docker-compose up
Pulling daily-postgres ... done
Pulling daily-mysql    ... done
Pulling daily-gateway  ... done
Pulling daily-api      ... done
Starting daily-apps_daily-postgres_1 ... done
Starting daily-apps_daily-mysql_1    ... done
Recreating daily-apps_daily-api_1     ... done
Recreating daily-apps_daily-gateway_1 ... done
Attaching to daily-apps_daily-postgres_1, daily-apps_daily-mysql_1, daily-apps_daily-gateway_1, 
daily-apps_daily-api_1
daily-api_1       | 2020/12/15 10:55:43 no such file or directory
daily-gateway_1   | 2020/12/15 10:55:43 no such file or directory
daily-postgres_1  | 
daily-postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
daily-postgres_1  | 
daily-postgres_1  | 2020-12-15 10:55:42.905 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
daily-postgres_1  | 2020-12-15 10:55:42.905 UTC [1] LOG:  listening on IPv6 address "::", port 5432
daily-postgres_1  | 2020-12-15 10:55:42.920 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
daily-postgres_1  | 2020-12-15 10:55:42.951 UTC [20] LOG:  database system was interrupted; last known up at 2020-12-15 10:54:50 UTC
daily-postgres_1  | 2020-12-15 10:55:43.537 UTC [20] LOG:  database system was not properly shut down; automatic recovery in progress
daily-postgres_1  | 2020-12-15 10:55:43.541 UTC [20] LOG:  redo starts at 0/165E850
daily-postgres_1  | 2020-12-15 10:55:43.541 UTC [20] LOG:  invalid record length at 0/165E888: wanted 24, got 0
daily-postgres_1  | 2020-12-15 10:55:43.541 UTC [20] LOG:  redo done at 0/165E850
daily-postgres_1  | 2020-12-15 10:55:43.563 UTC [1] LOG:  database system is ready to accept connections
daily-apps_daily-api_1 exited with code 1
daily-apps_daily-gateway_1 exited with code 1
```

I'm using windows so I believe it has to do with the commands `command: ["./wait-for.sh", ...`  but not sure.

By any chance have you got this error or know if it runs on windows?

**Comment by idoshamun** [comment]
I'm not familiar with this error but I guess it has to do with Windows. On
Mac/Linux it works perfectly fine. I agree with where you're pointing at.
It has to do with the path to the script.

**Comment by zvikarp** [comment]
I did the fix and opened a PR 😀, please let me know if any other changes need to be done.

BTW the issue with docker was with the difference between newlines in windows (CRLF) and Linux (LF), I came across some other issues and did a quick-fix. If you are interested in streamlining the process for windows, I'll be happy to do it in the future.

**Comment by idoshamun** [comment]
Wow, Zvi! This was super quick. Fixing both the Windows issue and the bug itself, very impressive.
I'll do my best to proceed with the review today or tomorrow. Please make sure I have also write access to the PR to apply minor fixes if needed.

It would be wonderful if you can create a PR for the Windows compatibility issue as well. 🤩

**Comment by zvikarp** [comment]
@idoshamun no rush, yes you have access to make changes to the PR.
I'll do my best to work on the Windows compatibility issue in the following few days.
