### ISSUE TITLE
🧩 FEATURE REQUEST: Don't show opened articles

### ISSUE THREAD

**Issue by MarkTanashchuk** [dailydotdev/daily#234]
Now when I open an article, its title becomes gray, but opened articles cannot be hidden, and every time I want to scroll a little more, I need to scroll through articles that I already saw and I don't need.

It would be great if I could hide them in some way

**Comment by idoshamun** [comment]
Hey @MarkTanashchuk,

This feature is already implemented and you can use it immediately once you sign up to daily.dev.
Open the settings panel and turn on the toggle as shown in the screenshot below.
<img width="1902" alt="Screen Shot 2020-12-20 at 15 50 25" src="https://user-images.githubusercontent.com/1993245/102715034-33d80c00-42db-11eb-8a69-0396eda77109.png">
