### ISSUE TITLE
🧩 FEATURE REQUEST:  Just one language 

### ISSUE THREAD

**Issue by GeeSuth** [dailydotdev/daily#238]
## Feature Request

Just show one language articles and tips 

### Description

if I interested in one programming language  and don't wanna see more articles , i thing be fine if there any remember filter 
to do that  

### Solution

add option (filter) to choose you interested language  

### Alternate Solutions

Anyway thank you!!!! you done amazing thing

**Comment by idoshamun** [comment]
Hi!

This is indeed possible 😇
All you need to do is sign-up, open the sidebar, click on the toggle button and choose the tags you like 🚀
