### ISSUE TITLE
🐛 BUG: Top left link does not go to home page

### ISSUE THREAD

**Issue by robwilde** [dailydotdev/daily#239]
### What went wrong? 🤔

In the profile section the home link in the top left corner is [daily.dev BETA](https://app.daily.dev/) which takes you to the "Something awesome is coming soon" page.

### Expected Behavior

That the link go back to the main or home page

### Actual Behavior

takes you to the "Something awesome is coming soon" page.

### Steps to Reproduce Issue
 
open a new tab
click on profile top right
click icon link top left

### Solution

update the link to go to the home or new tab page
perhaps change it to a back button would work well also

### Environment

Desktop PC

#### Operating System

Linux Elementary OS 5 (Ubuntu 18.4)

#### Version of Daily

updated to 2.28

#### Browser

Chromium in [wavebox.io](https://wavebox.io/)

**Comment by idoshamun** [comment]
Hi @robwilde,

The profile section is part of our web application and not the extension.
Unfortunately, we can't navigate you back to the extension from a regular website.
We're working on building a home page with a feed and everything just like in the extension.
Hopefully, it will be ready soon. Stay tuned!
