### ISSUE TITLE
🧩 FEATURE REQUEST: 

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [dailydotdev/daily#241]
### Description

- I would like to have small coding problems as a weekly goal stat like reading weekly goals, reading articles increase rank in the same way coding every day will increase the rank.

### Solution

- There should be a drop-down menu where the user will select one programing language and according to the language user chooses he/she will get small fun coding problems daily and by solving the problem users rank will increase 

### Alternate Solutions

- Weekly there should be a big coding problem and there must be an article related to it and solution of that problem should be published after one day so that user can try to solve the problem and if user stuck in that problem he/she can take help from an article and then also if they are not able to solve they can see solution next day. It will make daily.dev more engaging.

**Comment by idoshamun** [comment]
Hi @Nitesh-thapliyal,

Thanks for reaching out with your suggestion. 🙌
At the moment, our product roadmap is focused on helping developers staying up-to-date.
Your suggestion is off-topic so we will not be able to accept it. We're a small team and have to be very focused.
