### ISSUE TITLE
🐛 BUG: Local issue with the upvote count when canceling an upvote

### ISSUE THREAD

**Issue by teja463** [dailydotdev/daily#242]
### What went wrong? 🤔
Removing the upvote on comments decreases the upvote count by 2 instead of 1

### Expected Behavior
Undoing Upvote should decrease only by 1 point

### Actual Behavior
Undoing Upvote is decreasing by 2 points

### Steps to Reproduce Issue
1. Goto any post which has comments e.g. https://app.daily.dev/posts/o-Gn4rYsa
2. Goto comments section and click on the upvote icon, it increases the upvote count by 1
3. Now click on the same upvote icon it is decreasing the upvote count by 2 instead of 1

#### Operating System
Windows
#### Version of Daily
latest https://app.daily.dev/
#### Browser
Chrome

**Comment by idoshamun** [comment]
Hi @teja463,

Thanks for reporting.
I'll look into it as soon as possible!

**Comment by idoshamun** [comment]
I tried to reproduce this issue but I couldn't.
Whenever I canceled my upvote it decreased the reputation by a single point only.
Could you please try again? It could be that someone else canceled their upvote as well when you checked.

**Comment by teja463** [comment]
I just tried in Incognito same behavior. PFA video and chrome network tab har file zip
[app.daily.dev.har.zip](https://github.com/dailydotdev/daily/files/5776434/app.daily.dev.har.zip)



https://user-images.githubusercontent.com/4502488/103782540-97916180-505d-11eb-853a-faaa74949b49.MP4

**Comment by teja463** [comment]
@idoshamun tried in incognito, the upvote and cancel upvote count is acting a 
[app.daily.dev.har.zip](https://github.com/dailydotdev/daily/files/5776473/app.daily.dev.har.zip)


little off. There is a flickering of count decreased by 2 points and count stays the same. Also just keep playing with the upvote button the count is not consistent. PFA video and zipped har file

https://user-images.githubusercontent.com/4502488/103783572-e7245d00-505e-11eb-8140-448751c70551.MP4

**Comment by idoshamun** [comment]
Oh, I thought you mean the reputation points but I get your point now.
It's a local issue something with the optimist UI implementation. Once you refresh it looks OK.
I will fix it soon

**Comment by idoshamun** [comment]
I fixed the issue. Should be live in a few minutes.
Let me know if this issue persists.
