### ISSUE TITLE
🐛 BUG: Missing `title` property on the Web app's post cards

### ISSUE THREAD

**Issue by esau-morais** [dailydotdev/daily#248]
### What went wrong? 🤔

I was checking some differences between the extension and the web app, and just got to see that the postcards don't have a `title` property on the app.daily.dev

### Expected Behavior

Postcards should have a `title` property to improve the user experience (once it gives a proper title set).

**Note:** _I couldn't take a screenshot, once Windows doesn't have an interval time functionality_

### Actual Behavior

Postcards don't have a `title` property.

### Steps to Reproduce Issue

1. Open the [Daily.dev Web app](https://app.daily.dev/)
2. Hover a postcard

### Solution

Add `title` property to the `CardLink` component [here](https://github.com/dailydotdev/daily-webapp/blob/master/components/cards/PostCard.tsx#L93)

#### Operating System

Windows 10 OS Version 1909

#### Version of Daily

Daily.dev Web app doesn't have a specific version released

#### Browser

Chrome 87.0.4280.141/Laptop

**Comment by idoshamun** [comment]
Hi @esau-morais,

You're right. I'll fix that :)
