### ISSUE TITLE
🐛 BUG: Post not found (An error occurred with this application)

### ISSUE THREAD

**Issue by ftonato** [dailydotdev/daily#252]
### What went wrong? 🤔

I received an email that say `🥢 An article you wrote got picked by daily.dev`, when I click on the "Say hello" button I'm redirect to `https://app.daily.dev/posts/07eBf-nAk`, and when I try to open this link I got the message: **An error occurred with this application**.

### Expected Behavior

After open the URL I should be able to read my own article.

### Actual Behavior

So, I can't open the link that should redirect to my article.

### Steps to Reproduce Issue

1. Open this URL - https://app.daily.dev/posts/07eBf-nAk

#### Browser

https://whatismybrowser.com/w/4W7QFNY

**Comment by idoshamun** [comment]
Hey!

It's a current bug that we have in the system that private posts also matched up to an author.
These posts are originated from private sources that were added by premium users and not by our moderators.
Thus, the rest of the community doesn't have access to these posts.
We should fix this issue of matching private posts with authors. I'm sorry for the trouble.
