### ISSUE TITLE
🐛 BUG: Why is my feed full of Faunadb spam?

### ISSUE THREAD

**Issue by bachmannn** [dailydotdev/daily#254]
## 🐛 Bug Report

Why is my feed full of FaunaDb ads? I don't want to use their services, it is basically SPAM. 

Was source added recently? All them posts are old but say "posted recently" in daily dev and now my entire feed is full of FAUNA spam.

### What went wrong? 🤔

Feed is full of fauna spam

### Expected Behavior

Feed should not be full of fauna db spam

### Steps to Reproduce Issue

Look at your feed.

### Solution

Remove fauna db source

**Comment by idoshamun** [comment]
Hey!

I noticed this issue earlier today but didn't have the time to fix it. It's
not a new source but they might changed something in their RSS which
messed things up.
As a temporary solution you can turn off this source by opening the sidebar.
