### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by zvikarp** [dailydotdev/daily#255]
### What went wrong? 🤔

It's on the website/blog, looks like https://daily.dev/submit-a-story is missing a background...
![image](https://user-images.githubusercontent.com/13397207/107383073-4d3a4f00-6af9-11eb-9482-f5fec39c0081.png)
If I highlight the text I can see it, it is just the same color as the background.
#### Operating System

Windows 10 Home. In dark mode (and that might be messing with the text color).

#### Browser

I'm using the latest chrome (also tested on firefox).

**Comment by zvikarp** [comment]
I scrolled down more, the highlighted text show correctly, so it is probably not a missing background but a wrong style for the test. I don't have any wired chrome extensions that might be messing with this (and also it happens on firefox too).

![image](https://user-images.githubusercontent.com/13397207/107383723-f2edbe00-6af9-11eb-84ce-59ee69f14c4e.png)

**Comment by idoshamun** [comment]
Hey @zvikarp,

Thanks for letting us know.
We've already fixed it :)
