### ISSUE TITLE
🧩 FEATURE REQUEST: Edit comments and flag content

### ISSUE THREAD

**Issue by Kvaibhav01** [dailydotdev/daily#256]
### Description

I would like to request two updates to the current post pages:

1. **Adding an Edit ✏️ feature to comments**: When we comment on a post, we are not able to edit that comment. This will be helpful so that someone can correct false information or someone who just wants to edit a word or two.

2. **Having a Flag 🏳 for each post**: If for some reason a user sees that the post on the app feed is harmful to the community, spreading wrong information, is biased or not worthy of a read, then we can flag or maybe report that content

### Solution

1. **For the Edit feature**: I think a good way is to make the edit pencil icon visible on the hover of the comment. When the edit is going on we can have two buttons at the bottom: 'Cancel' and 'Update comment'. When the user clicks the 'Update comment' button, the comment will be updated. Of course, permission-wise, only the original comment author (and app admins) can have permission to update the comment.

Here's a basic idea I created on Figma:

_When a comment is hovered:_

<img width="610" alt="When a comment is hovered" src="https://user-images.githubusercontent.com/11731837/108068683-69edfe00-7088-11eb-9e73-34f8d1a20cb4.png">

_When a comment is being updated:_

<img width="610" alt="When a comment is being updated" src="https://user-images.githubusercontent.com/11731837/108068759-8427dc00-7088-11eb-91de-4e022609a227.png">

2. **For the Flag feature**: Similar thing here. Where we have all the sharing options a new Flag icon can be introduced:

<img width="69" alt="Share options with Flag" src="https://user-images.githubusercontent.com/11731837/108069115-fe586080-7088-11eb-996c-749944564308.png">

When a user clicks the Flag icon, then the process after that can be like a modal pops up which asks "why you want to flag this?" Optionally write a comment. etc.

**Comment by idoshamun** [comment]
Hey @Kvaibhav01,

Thanks for sharing your excellent ideas with us :)
I believe we should add them both to our backlog, but we are very busy adding the existing extension features to the webapp so hopefully, we can do it in between but it will take time. I will appreciate your patience.

In the meantime, if you encounter low-quality content report it as broken or NSFW and leave a comment that it's low quality and I'll make sure to review it.

Again, thanks for being so active and for the great mockups :)

**Comment by idoshamun** [comment]
We just released more flagging options!
Check out the release notes and make sure to update your extension to the latest version (not available on FF yet) or use the web app.
https://changelog.daily.dev/new-reporting-options-194205

**Comment by idoshamun** [comment]
And now you can also edit comments as well :)

**Comment by Kvaibhav01** [comment]
Thanks @idoshamun it works perfectly! 

A little change of button label from "Edit" to "Update" or "Update comment" will be helpful as when someone has updated the commend then he sees that "Edit" is written on the button, it might sound confusing as to what will happen when we click on the button; will the comment will update or will it goes back to the edit mode. 

<img width="100" alt="Screenshot 2021-05-06 at 10 37 17 PM" src="https://user-images.githubusercontent.com/11731837/117337949-9f51fd00-aebb-11eb-8287-9acf0ceffb6d.png">

**Comment by idoshamun** [comment]
@Kvaibhav01 that makes perfect sense.
I update the text to "Update". Thanks :)
