### ISSUE TITLE
🐛 BUG: earned popup is open every time 

### ISSUE THREAD

**Issue by ylcnfrht** [dailydotdev/daily#257]
## 🐛 Bug Report

earned popup came every time even I choose **NEVER SHOW THIS POPUP AGAIN**

<img width="314" alt="Screen Shot 2021-02-16 at 21 12 24" src="https://user-images.githubusercontent.com/22433665/108103937-aecf6000-709b-11eb-85bf-5328d7ca7a85.png">

#### Browser
Chrome

**Comment by idoshamun** [comment]
Hey @ylcnfrht!

Sorry for the trouble.
Did you click on the "Awesome!" button? Unless you click on it, this popup will stay on.
Please let me know so I can assist you further.

**Comment by idoshamun** [comment]
I'm closing this issue due to the long inactivity time...
