### ISSUE TITLE
🧩 FEATURE REQUEST: Need more options in do not disturb

### ISSUE THREAD

**Issue by AvinashKo** [dailydotdev/daily#259]
## Feature Request

Need one more option 8hours in do not disturb options. 1 hours is low and 1 day is high. 8 hours is right amount of time, so during office hours I can keep it in DND. I do spend some time in screen-sharing to business people, clicking on new tab opening a blog confuses during presentations.

### Solution

Add 8-hours option in Do-Not-Disturb dropdown.

### Alternate Solutions

Make automatically opening daily.dev on new tab an option in settings.

**Comment by idoshamun** [comment]
Hey @AvinashKo,

That's a great idea and actually should be pretty straightforward to implement.
Would you like to give it a try? I can guide you through the process.

**Comment by AvinashKo** [comment]
Hello, let me install the app locally, I would like to give it a try, will
spend some time over the weekend. Thank you.

**Comment by idoshamun** [comment]
We just recently released a new version with extended options for the DND :)
