### ISSUE TITLE
🐛 BUG: Daily prevents navigation to another address

### ISSUE THREAD

**Issue by cagdas001** [dailydotdev/daily#260]
### What went wrong? 🤔

When I open a new tab (Ctrl + T), and navigate to an address in a short time (without waiting Daily to initialize its landing page), Daily prevents me to go to this address. If Daily gets initialized before the intended address is loaded, it stops the navigation.

Unfortunately, I ended up disabling the extension because it happens a lot on a daily basis.

### Expected Behavior

Even though I'd go to an address without waiting for Daily to initialize its landing page, it should allow me go to this address, no matter if Daily is initialized or not during that time.

### Actual Behavior

If Daily landing page gets initialized before the navigated address, it stops the navigation.

### Steps to Reproduce Issue

I don't know how you can reproduce this issue, as it's a rare issue happening under certain conditions. Try to open a new tab, and go to an address immediately

### Solution

NA

#### Operating System
Windows 10 Education x64 
Version 2004 (OS Build 19041.804)

#### Version of Daily
2.29.5

#### Browser
Google Chrome
Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by cagdas001** [comment]
Some more info that might be helpful for debugging. I also tried Do Not Disturb mode. It didn't solve the issue. I guess you're still loading the extension to check if user enabled the DND mode, so the extension is still being loaded on new tabs. I think there might be something possibly wrong at the extension initialization logic

**Comment by idoshamun** [comment]
Hey @cagdas001,

That's a shame! Sorry for this experience.
In the meantime, may I suggest you try out our webapp? https://app.daily.dev
It doesn't provide all the extension features but it's very advanced and has mobile support.

I'll do my best to try and solve this issue. Could you please share your PC spec?
I'm not able to reproduce this behavior on my laptop.

**Comment by cagdas001** [comment]
Hey @idoshamun,

Information about the PC and browser is included in the description

> ### Environment
> 
> #### Operating System
> Windows 10 Education x64 
> Version 2004 (OS Build 19041.804)
> 
> #### Version of Daily
> 2.29.5
> 
> #### Browser
> Google Chrome
> Version 88.0.4324.182 (Official Build) (64-bit)

I'll try to take a screencast when it happens again, for you to understand the issue

**Comment by idoshamun** [comment]
Sorry for not mentioning it earlier, but I mean the hardware specifications. CPU, Memory, resolution, display size. Any other information that you think might help will be appreciated.

**Comment by cagdas001** [comment]
Here I created a minimal ExpressJS server responding after 5 secs. It also listens & logs specific keyboard events I'm using for opening tabs & navigating so you can make sure I'm following a valid key sequence

https://user-images.githubusercontent.com/28513447/109424900-e83a9080-79f6-11eb-8b4c-bd642a93fd16.mp4

Server implementation for reference:
```js
const ioHook = require('iohook');
const express = require('express')
const app = express()
const port = 3000

ioHook.on('keydown', event => {
  const keysMapping = {
    13: 'Enter!',
    84: 'T',
    86: 'V'
  }

  const key = keysMapping[event.rawcode]
  const logStr = `${event.ctrlKey ? 'Ctrl+' : ''}${key ? key : ''}`

  logStr.length > 'Ctrl+'.length && console.log(logStr)
});
ioHook.start();

app.get('/', async (req, res) => {
  await new Promise((resolve) => setTimeout(resolve, 5000))
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

**Comment by idoshamun** [comment]
Wow! This is super weird. I'll look into it.

**Comment by idoshamun** [comment]
Again even using your provided server I can't reproduce.
Could you please share your CPU and memory?

**Comment by cagdas001** [comment]
I guess this is not an issue with the extension. After investigating a bit more, I realized that it's also happening when the extension is disabled. So it should be an issue with the browser instead

Sorry for inconvenience

**Comment by idoshamun** [comment]
No worries. Thanks for the update ☺️
