### ISSUE TITLE
🐛 BUG: Not accepting GitHub username with hyphen

### ISSUE THREAD

**Issue by prateek-aher** [dailydotdev/daily#261]
### What went wrong? 🤔
It is not accepting my Github username i.e, 
prateek-aher
![image](https://user-images.githubusercontent.com/47930146/109625309-2e156700-7b65-11eb-95bf-b9a215b762f0.png)

There's no mistake in it, see here
![image](https://user-images.githubusercontent.com/47930146/109625619-8c424a00-7b65-11eb-9837-aa454f82c46b.png)

#### Operating System
Windows 10

#### Version of Daily
daily.dev beta

#### Browser
Google Chrome
Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hey @prateek-aher!

Sorry for this issue. I'll fix it immediately.

**Comment by idoshamun** [comment]
It should be fine now.
Please check again and let me know.

**Comment by prateek-aher** [comment]
Thanks @idoshamun 
It worked.
