### ISSUE TITLE
🧩 FEATURE REQUEST: Indication for Video link

### ISSUE THREAD

**Issue by hamatoyogi** [dailydotdev/daily#262]
### Description

I would like to request having a way to know if a link is a video. 

### Solution

What I had in mind was something like a banner, sash, tag, icon, or something of sorts to indicate a link like this is a video.

**Comment by idoshamun** [comment]
Hey! 

Nice to see you here as well :)
I don't have an estimation for delivery but let's leave it open so I can keep you posted on the progress.

**Comment by yanir21** [comment]
Hi, I'd Like to work on this issue. 
Can I get a design specification of some sort? 
My idea was a video icon on the bottom-right corner of the image

**Comment by idoshamun** [comment]
Hey @yanir21,

We would love to have you contributing to this one.
Unfortunately, our backend is not ready for such a feature.
We have to add the ability to detect such content in our scraper and then save it to the DB and propagate downstream through our API.
I will raise this issue in our next product planning and we'll continue from there. It might take a while but we would love your contribution once it's ready :)

**Comment by hamatoyogi** [comment]
Wouldn't mind collaborating on this @yanir21 if needed 😀

**Comment by rebelchris** [comment]
We will internally tackle this with Video links. not open to public.
Closing discussions as it's upcoming.
