### ISSUE TITLE
🧩 FEATURE REQUEST: Need an 'Open in background' option for opening the article in the background tab.

### ISSUE THREAD

**Issue by krishna-kb** [dailydotdev/daily#263]
### Description
"Open in background" option will open the link in the background tab. Basically simulate "Cmd+Click".
This will help in the use case when user is looking for articles to read and just wants to open multiple articles at once which can be read one by one.

### Solution
UX which I have in mind.
- This option will only be enabled when the existing "Open in new tab" option is enabled.
- When this option is enabled, user can click on a link and it will open in background as a new tab, similar to what happens after clicking "Cmd+Click"

I would love to contribute, please let me know if I should go ahead and create a pull request for this.

### Alternate Solutions
NA

**Comment by idoshamun** [comment]
Hey!

Unfortunately, the browser doesn't allow to set this behavior. If you want to open a new tab in the background you have to use the middle mouse button or cmd + click.
