### ISSUE TITLE
🧩 FEATURE REQUEST: Option to change the homepage

### ISSUE THREAD

**Issue by ovirex** [dailydotdev/daily#264]
### Description
I would like to be able to choose whether I want daily.dev to be my new homepage or not. It's quite annoying that by having the daily.dev extension you have to compromise your homepage.

### Solution
An option in the settings that allows you to choose whether you want daily.dev to be your new home page.

**Comment by idoshamun** [comment]
Hi,

The browser doesn't provide this API, and this is exactly why we created our brand new webapp.
Try it out, it has mobile support as well.
https://app.daily.dev/

**Comment by idoshamun** [comment]
Hi,

The browser doesn't provide this API, and this is exactly why we created our brand new webapp.
Try it out, it has mobile support as well.
https://app.daily.dev/

**Comment by pheu** [comment]
> Hi,
> 
> The browser doesn't provide this API, and this is exactly why we created our brand new webapp. Try it out, it has mobile support as well. https://app.daily.dev/

So how the extension sets up the homepage upon installation? I guess by some workaround, so the same way homepage could be changed back to default. I believe it's already done by the "Focus Mode". It's however non-intuitive for users to disable daily.dev homepage by adjusting focus mode and setting very high number of days.

**Comment by idoshamun** [comment]
The browser allows us to define an HTML page that will override the new tab page. It's something hardcoded in the manifest of the extension. As far as we know, it's not possible to adjust this value via our code.
"Focus Mode" still triggers our code but we deliberately redirect you to another page. So it's not like we can disable the new tab functionality, unfortunately.

**Comment by pheu** [comment]
> The browser allows us to define an HTML page that will override the new tab page. It's something hardcoded in the manifest of the extension. As far as we know, it's not possible to adjust this value via our code. "Focus Mode" still triggers our code but we deliberately redirect you to another page. So it's not like we can disable the new tab functionality, unfortunately.

Thanks for the reply. I see... Given that the main purpose of the extension seems to be actually replacing the homepage and API limitations I can understand there's not much point to add option to disable this functionality. As for me the homepage is little bit too distracting upon opening every new tab I will just stick to visiting daily.dev app from my bookmarks.

**Comment by idoshamun** [comment]
That makes perfect sense @pheu. Keep sharing your feedback :)
