### ISSUE TITLE
🐛 BUG: Unable to login in Firefox Nightly

### ISSUE THREAD

**Issue by rafifos** [dailydotdev/daily#268]
### What went wrong? 🤔

I'm unable to login with both GitHub and Google OAuth providers.

### Expected Behavior

After selecting any of the OAuth providers, the extension should log-in my user succesfully.

### Actual Behavior

When opening the network requests, everything seems good (`https://api.daily.dev/v1/auth/authorize` sends a 307, then redirects to `https://github.com/login/oauth/authorize` and finally, the callback request from `https://api.daily.dev/v1/auth/callback` returns a 307 to the extension with the `skip_authenticate` param inside the state object. But the extension just reloads itself, and it isn't authenticated anymore.

### Steps to Reproduce Issue

Download Firefox Nightly, apply [there](https://keybase.pub/rafifos/user.js) `user.js` settings and try to login into daily.dev

#### Operating System

Windows 10 Pro, Version 20H2 (build 19042.867)

#### Version of Daily

2.29.0

#### Browser

Firefox Nightly 89.0a1 (2021-03-26) (64-bits

**Comment by rafifos** [comment]
Turns out it was an issue with Firefox's FPI.

**Comment by idoshamun** [comment]
I'm glad to hear it was fixed 🥳
Enjoy daily.dev!
