### ISSUE TITLE
🧩 FEATURE REQUEST: Export/Import user's sources

### ISSUE THREAD

**Issue by LewisAlderman** [dailydotdev/daily#269]
### Description

Moving between machines/browsers are reassigning your ignored sources is a bother atm, and not exactly 'portable'.

Suggestion: 
Ability to export/import users defined sources, much like browser bookmarks!

### Solution

Export and import a parsable text file format (looks like MacOS chrome uses HTML, for example).

**Comment by idoshamun** [comment]
Hey @LewisAlderman,

There is no way to import or export user sources but they are synced once you log in.
If you don't have a daily.dev account yet, make sure to register, set your preferences, and then it will be automatically synced everywhere you go.
We recently launched a web app that is also synced with your personal preferences.
https://app.daily.dev

Let me know if it fits your needs 🙏

**Comment by LewisAlderman** [comment]
> Hey @LewisAlderman,
> 
> There is no way to import or export user sources but they are synced once you log in.
> If you don't have a daily.dev account yet, make sure to register, set your preferences, and then it will be automatically synced everywhere you go.
> We recently launched a web app that is also synced with your personal preferences.
> https://app.daily.dev
> 
> Let me know if it fits your needs 🙏

**Comment by LewisAlderman** [comment]
@idoshamun thanks! yes I hadn't noticed since! I only signed up _after_ switching between browser/machine a few times.

Perhaps this _could_ still prove useful as a "quality-of-life" feature, for instance, when recommending Daily.dev to a colleague, whom you are a aware is only interested in similar subjects, and you can quickly share your list with them - or even on social media! 👌

**Comment by idoshamun** [comment]
Indeed this could be useful.
We can make the feed itself shareable and then colleagues may apply the same settings to their feed.

Thank you for the suggestion! 💪

**Comment by rsohlot** [comment]
"I also feel that users should have the option to export their content (such as bookmarked links and subscribed sources).

I'm not referring to any specific use case but rather to the general principle of allowing users the freedom to back up their data.

Apologies if this comes across strongly, but restricting the ability to export data makes the platform feel restrictive, which I believe is not an ideal approach. (To be clear, I am not implying that this is the intention of daily.dev.)

That said, I haven't yet considered the feasibility or complexity of implementing this from a technical standpoint.

**Comment by muhammad-fiaz** [comment]
related discussion #2104
