### ISSUE TITLE
🐛 BUG: extension logs out on browser close 

### ISSUE THREAD

**Issue by Srini-B** [dailydotdev/daily#270]
### What went wrong? 🤔

Whenever I close the browser and open it again, I'm in a logged-out state, using it on ms edge dev ver 91.0.838.3. Used extensions from ms edge store and also from chrome store, same result

### Expected Behavior

Stay logged in as in chrome, no issues here

### Actual Behavior

Stay logged in

### Steps to Reproduce Issue

try it in the new edge version

#### Operating System

Windows 10 v2004

#### Version of Daily

2.30.1

#### Browser

Ms Edge dev v91.0.838.3

**Comment by idoshamun** [comment]
Hey @Srini-B,

Thanks for using daily.dev ✨
Do you have any cookie blockers of sorts that could interfere with our authentication system?
If not, could you please try to login into our web app and let me know if you experience the same issue.
https://app.daily.dev

**Comment by Srini-B** [comment]
I use adguard ad blocker windows app v7.5.3, which works only on websites, but that doesn't seem to affect chrome. I'll try the web app and report

**Comment by Srini-B** [comment]
same output for web app, log-out issue

**Comment by idoshamun** [comment]
This might be an issue with one of the extensions you have I guess that blocks our cookie.
Can you try to disable them?

**Comment by Srini-B** [comment]
seems to be issue only on windows, works fine on mac ill try disabling one by one

**Comment by idoshamun** [comment]
Ok, please share your finding so we can test it locally as well. 🙏

**Comment by Srini-B** [comment]
Turning off destroy 3rd party cookies saved the day.

**Comment by idoshamun** [comment]
That's great!
I'm not sure why it's treated as a 3rd party cookie. It should be 1st part cookie 🤔
But I'm glad to hear it works for you
