### ISSUE TITLE
🧩 FEATURE REQUEST: Github feed

### ISSUE THREAD

**Issue by RajvirSingh1313** [dailydotdev/daily#271]
## Feature Request
I recently started using daily.dev and as I am a developer I mostly use Github for all of my work and so I am very use to daily dev's news feed and Github's feed so I think what about having a section just right of the news in the daily.dev about Github feed which will contain Trending, Personal, etc.

I made an image for better understanding:-
![pr_for_dailydev](https://user-images.githubusercontent.com/63385587/113876705-9c3cf180-97d5-11eb-9833-3f0eaa2c4686.png)

I know you will need more info so till now I am kinda tried by making the above image so you can comment and I will try to reply as soon as I can.

**Comment by idoshamun** [comment]
Hey @RajvirSingh1313,

Thanks for the suggestion and for dedicating the time to create this mock-up. Which is super by the way!
Unfortunately, this feature is not part of our roadmap. We are focusing on delivering better and more relevant content, along with more community features.

**Comment by RajvirSingh1313** [comment]
No problem bro
