### ISSUE TITLE
🧩 FEATURE REQUEST: Sign-up with private email address

### ISSUE THREAD

**Issue by rendler-denis** [dailydotdev/daily#277]
## Feature Request
As a user I would like to be able to sign-up using a specific email address which allows me to maintain my privacy, but still be a member of the community.

### Description

I am using this browser extension for a few months now and I like it. I found useful articles and I would love to sign up. Unfortunately, at this time the only two sign-up options are Github or Google. Single Google clearly does not respect privacy and I am not comfortable giving access to my repositories I have no option for sign-ing up. At least, none that is visible.

### Solution

Allow users to sign-up via email.

**Comment by idoshamun** [comment]
Hey @rendler-denis!

Currently, we do not support a direct sign-up via email. Using third-party logins helps us to prevent abuse on our platform.
I do understand your point and I would like to say that we require only the necessary permissions from both GitHub and Google. And we don't use these permissions besides the registration to extract your name, email, and image.
I hope it makes sense to you :)
