### ISSUE TITLE
🧩 FEATURE REQUEST: Match browser color theme

### ISSUE THREAD

**Issue by omothm** [dailydotdev/daily#279]
### Description

I would like to have the option to set the color theme to match the browser's (or maybe the system's) color theme. When the browser changes to a light theme, the new tab page changes to a light theme. When the browser changes to a dark theme, the new tab page follows as well.

### Solution

Instead of the "Light Theme" switch under Preferences, a dropdown with these 3 options is recommended:

- Light Theme
- Dark Theme
- Match Browser Theme

### Alternate Solutions

N/A

**Comment by idoshamun** [comment]
Hey @omothm,

Thanks for this great suggestion.
We will consider it in our next product planning meeting :)

**Comment by idoshamun** [comment]
Following our last product planning, we have designed a solution for this issue, and we're willing to open it for contribution.

It should look like this, where the new "Auto" setting should match the browser theme.
![feature design](https://user-images.githubusercontent.com/1993245/122874471-b2ba0a00-d33b-11eb-88e3-68af9c30d87e.png)

How to get started?
* This issue involves only our client-side apps, which can be found here [dailydotdev/apps](https://github.com/dailydotdev/apps).
* Make sure to have the latest services running in your local environment. [Click here for instructions](https://github.com/dailydotdev/daily#%EF%B8%8F-setting-up-daily-services).
* The settings component is [here](https://github.com/dailydotdev/apps/blob/master/packages/shared/src/components/Settings.tsx).

Sketch Cloud project is available here with all the nitty-gritty 👇
https://www.sketch.com/s/2549ccf9-b98c-413f-96fb-81b05b59e65f/a/ygwyyeq

**Comment by Mahdhir** [comment]
I can look into this if this is still available 😄

**Comment by idoshamun** [comment]
@Mahdhir yes, please! 🤩
