### ISSUE TITLE
🧩 FEATURE REQUEST: Stop logging IP Address, Location and System Information in third-party services with "Opt Out" feature

### ISSUE THREAD

**Issue by bachmannn** [dailydotdev/daily#280]
## Feature Request

The extension is using a lot of third-party services that are known to hijack and log alot of personal data. They do this without your username to bypass "GDPR", refuse to delete or give you a copy. This goes against everything the community stands for.

### Description

Example of Invasive trackers in this extension like:

Cloudinary:
* When DNS requests are sent to fetch images, it is tracking what articles you are reading, on what device etc
* Your IP Address
* Your Location
* Sends all your cross-site cookies to track where you have been on the internet
* Your System Information from DNS Request Headers
* "bypassing" GDPR because there is no username, they can just keep and never delete this information or sell it to third parties
* Why is Cloudinary featured on your website? Are they paying you to collect all this user data?

Same issue with Mobile Ads/Analytics this extension uses:
* Your IP Address
* Your Location
* Sends all your cross-site cookies to track where you have been on the internet
* Your System Information from DNS Request Headers
* Bypassing GDPR and selling to third parties

This extension has more trackers and loads more dependencies, any of which run arbitrary code in your new tab than almost any other "spyware" extension on Google Chrome webstore.

### Solution

Give users an "Opt Out" button that does not track users entirely and loads images or other metadata about articles from the article website like an RSS reader does.

### Alternative Solution

Migrate to Google Cloud image delivery or AWS S3 bucket.

**Comment by idoshamun** [comment]
Hey @bachmannn,

Thanks for raising your concerns, privacy is very important for us.
I would like to address them one by one and to provide you with the relevant information.

1. Cloudinary - We will reach out to Cloudinary to understand exactly what data they store about our community. Cloudinary makes their money from selling services not data so I don't think this should be a problem. Also, I would love to see the source of information you rely on stating that Cloudinary "hijacks" personal data.
2. Analytics platforms - We use Google Analytics and Amplitude to track user behavior inside the application and learn what we can do better. We use this data for product purposes only.
3. Mobile Ads - We use two ad networks that only promote developers-oriented ads. Carbon Ads, and EthicalAds. They both focus on privacy and none of them track your activity nor they embed any third-party script in our product. The only exclusion is that some advertisers ask to implement a pixel image to track conversions. We don't use platforms that require implementing tracking of sorts.

Generally speaking, we don't sell data to any third party nonetheless personal data.

**Comment by idoshamun** [comment]
I'm closing this issue as I didn't get any response for 10 days. I can reopen in case it changes.
