### ISSUE TITLE
🧩 FEATURE REQUEST: Show the page as a new tab content on Firefox

### ISSUE THREAD

**Issue by DanielRios549** [dailydotdev/daily#282]
## Feature Request

I would like an option to show a new tab content for the default Firefox new tab instead of replacing it completely.

### Description

An option to activate the daily.app on the Firefox Home Content section, to show daily.app when the users scroll the page. This will the user still using the default new tab with its shortcuts, but additionally the news from daily.app when they scroll the page.

**Comment by idoshamun** [comment]
Hello @DanielRios549,

Is this Firefox Home Content section a thing? I'm not aware of it.
Is there an API to modify this section?
