### ISSUE TITLE
🐛 BUG: User's Social info is not updated correctly while switching between users

### ISSUE THREAD

**Issue by Showrin** [dailydotdev/daily#284]
### What went wrong? 🤔

I clicked on the writer's info in a blog. Then it took me to his profile. That time I clicked on my profile image (top-right of the browser). The info on that page was replaced by mine but the contact info (Twitter, Github, websites) didn't change. It's still showing the values of the previous user (writer's). When I reload the page, then it got updated. 

> **I didn't set any value in the social fields (Twitter, GitHub, Hashnode, Website). Then I set a value in GitHub field. And redo the above things. Then link in Github was replaced by mine, but the other fields were containing the value from the previous user.**

Here I attached a video.

https://user-images.githubusercontent.com/28985234/119403681-8b522c00-bd00-11eb-8a00-a4b58a3af2c5.mp4

### Expected Behavior

While switching to my account, the contact info should be updated with my data like other info.

### Actual Behavior

It's showing the contact info of the previous user. But other data was mine.

### Steps to Reproduce Issue

- First **delete data of these fields twitter, GitHub, Hashnode, Website**  from your daily.dev profile.
- Go to the profile of any user. In my case, I went to this profile https://app.daily.dev/vaibhavkhulbe
- Then click on your own profile image from the top-right corner of the browser
- Now you will see that all data changes except social data. 
- **If you have value in any social field, it will change. But if it's empty, then it will show the data from the previous user.**
 
### Solution

I think somehow, **the removal of the empty social field was missed**. Cause when you have data in your social field, it works fine. **But if you don't have value in any of the social fields, but the previous user has value on that field, it's not removed**. It remains here with the value of the previous user.

### Environment

N/A

#### Operating System
Windows 10

#### Version of Daily
Latest

#### Browser

Chrome

**Comment by idoshamun** [comment]
Hey @Showrin,

Thanks for reporting this issue!
I know what might cause this issue and I'll look into it.
