### ISSUE TITLE
🐛 BUG: iOS grabber obscures the bottom navigation bar

### ISSUE THREAD

**Issue by idoshamun** [dailydotdev/daily#285]
### What went wrong? 🤔

Once the web app is saved to the home screen on iOS the grabber line obscures the bottom navigation bar.
See screenshot below.

#### Operating System

iOS

#### Version of Daily

Webapp

#### Browser

Mobile Safari

![image](https://user-images.githubusercontent.com/1993245/119453946-a04eaf80-bd40-11eb-8f70-3817bfd2b9ba.png)

**Comment by ivanq3w** [comment]
It can be fixed with global css variables, like
padding-bottom: env(safe-area-inset-bottom, 0);

**Comment by idoshamun** [comment]
Awesome! Wanna give it a go?
You can find the footer bar component here:
https://github.com/dailydotdev/apps/blob/master/packages/webapp/components/FooterNavBar.tsx

**Comment by omBratteng** [comment]
So testing with `padding-bottom: env(safe-area-inset-bottom, 0);` on `nav`, this is what it looks like.
![IMG_1257](https://user-images.githubusercontent.com/1681525/123060824-5a523d80-d40b-11eb-9b58-e2485dfbe29d.png)

Albeit I am running iOS 15 Beta, so it might be fixed later on

**Comment by idoshamun** [comment]
Oh so now it's obscured by the address bar. But as you mentioned it's a beta version. So should we proceed with this fix in the meantime?

**Comment by omBratteng** [comment]
It's not the worst issue, as soon as you scroll down, the address bar moves down, and looks like this.
![IMG_1256](https://user-images.githubusercontent.com/1681525/123063743-f7ae7100-d40d-11eb-91d7-943bdfba7665.png)

I also tried to use `padding-bottom: env(safe-area-inset-bottom, 0);` in the PWA version, but then I had to add `viewport-fit=cover` to the `viewport` meta tag, and change `nav` to to have a `min-height: 3rem;` as it would look like this, where the padding is set, but height is reduced.
![IMG_1258](https://user-images.githubusercontent.com/1681525/123063004-4f98a800-d40d-11eb-831e-ea8adcad73cc.png)

Which looks like this in Safari
![IMG_1259](https://user-images.githubusercontent.com/1681525/123063679-ebc2af00-d40d-11eb-9ac6-a148b5a459f0.png)

I have opened a PR on this
