### ISSUE TITLE
🐛 BUG: Code blocks have an extra line.

### ISSUE THREAD

**Issue by matiasvlevi** [dailydotdev/daily#286]
### What went wrong? 🤔

`<pre>` elements have an extra line in https://daily.dev/blog articles.
This is especially irritating when we have 1 line code blocks.

### Expected Behavior

![Expected](https://i.ibb.co/gyTs98j/expetced.png)

### Actual Behavior

![Actual](https://i.ibb.co/DLNNfRJ/actual.png)

### Steps to Reproduce Issue

Present on every https://daily.dev/blog post with code blocks.

### Solution

Maybe remove a line break in the function that formats the content to html?

so it would look like this in the html:
```html
<pre><code> First line here
Second line
Third line
etc
</code></pre>
```

#### Browser

Im using Chrome, but this looks like an issue from the html.

**Comment by idoshamun** [comment]
Thanks for the report. We will check it out as soon as possible.

**Comment by orpic** [comment]
Hi @idoshamun 
Is this being worked on by someone, If not can you assign it to me I want to work on it.

**Comment by idoshamun** [comment]
Hi @orpic,

This is part of our blog, which is built on webflow. So it's possible to contribute. Thanks a lot!
