### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by akshat31** [dailydotdev/daily#287]
### What went wrong? 🤔

I am getting two is with same email, its backend issue must be, that email id which is affected with bug is **akshat.soni31@gmail.com**

### Expected Behavior

whom ever i login either google or github if email ID is same in that both same account should have open

### Actual Behavior

it is opening and creating two different account with same email ID

### Steps to Reproduce Issue

1) Create one gmail id
2) By using that same email id meintioned in step-1 create one github account
3) Use github and google to signup daily.dev
4) you can clearly see two account now

### Solution

this is backend issue, it must because backend is not checking email id with existing account while signing up irrespective of source

### Environment

production environment, in app.daily,dev

#### Operating System

All OS

#### Version of Daily

dont know

#### Browser

All browser because its backend issue

**Comment by idoshamun** [comment]
Hey @akshat31,

I followed up on your email, let's keep it going there and help you resolve the issue.
It's more appropriate in terms of privacy and security.
