### ISSUE TITLE
all my bookmarked article vanished🐛 BUG: 

### ISSUE THREAD

**Issue by hamed4000** [dailydotdev/daily#288]
after login with google account and sync all my bookmarked article vanished

**Comment by idoshamun** [comment]
Hey!

Sorry for this trouble, let's try to fix it together.
After hitting the sync button and registering, did you the sync completed popup?
Do you use Chrome or Firefox?

**Comment by hamed4000** [comment]
I use Chrome
Nothing happens after the loading sync is over, I mean completed popup weren't displayed

**Comment by idoshamun** [comment]
Could you please try again? I fixed several bugs in this matter.

**Comment by hamed4000** [comment]
now sync completed popup displayed, but some of my bookmark is back (last 25), Is there a special reason from me?

**Comment by idoshamun** [comment]
Perfect! What do you mean some of your bookmarks are back?

**Comment by hamed4000** [comment]
Only 25 articles from bookmarks returned, which are also old, which can be said that there are no newest bookmarks


_"sorry about my english writing"_

**Comment by idoshamun** [comment]
How many bookmarks you had originally?

**Comment by hamed4000** [comment]
I use this extensions more then 4,5 month, so I think more then 25, I guess more then 100

**Comment by idoshamun** [comment]
Oh wow! That's a lot... I don't know why this happened.
We did delete some posts that were reported or contained broken links that might explain the difference.
Anyway, now with your new account everything will be saved in our database and will be synced across the different devices you use. Please let me know what you think...

**Comment by hamed4000** [comment]
this is useful extensions I really into it,  Way to go!

**Comment by idoshamun** [comment]
Thank you! Can we close this issue or do you have anything else in mind?

**Comment by hamed4000** [comment]
of course
