### ISSUE TITLE
🐛 BUG: not loading more than 5 rows (4 full + 2 articles) in web app or extension

### ISSUE THREAD

**Issue by omBratteng** [dailydotdev/daily#289]
### What went wrong? 🤔
It doesn't load more than 4 full rows + one row with two articles. The amount of articles loaded on each row depends on screen size.
And scrolling to the bottom does not load more articles.
This happens on the web app and extension, but not the PWA app in Chrome.
Works fine in Safari, but not Firefox

### Expected Behavior
It should load more articles once you reach the bottom of the ones already loaded

### Actual Behavior
It only loads 4 full rows + 2 articles

### Steps to Reproduce Issue
- Open https://app.daily.dev/ in Chrome
- Scroll to bottom

#### Operating System
macOS 11.4 beta (20F5055c)

#### Version of Daily
3.0.1

#### Browser
Chrome 91.0.4472.77

**Comment by idoshamun** [comment]
Hey @omBratteng,

Thanks for the report. Can you please share your screen resolution?
And if possible please try again in the web app. I recently fixed (or possibly screwed) something that has to do with the infinite scroll.

**Comment by omBratteng** [comment]
@idoshamun 
This is from web app, just now it loaded a few mor articles on the bottom row, so it's 5 complete rows.
![image](https://user-images.githubusercontent.com/1681525/120504309-51e68400-c3c4-11eb-9863-e19f1870b254.png)

But the extension still only loads 4 rows + 2 articles (couldn't take one whole screenshot)
![image](https://user-images.githubusercontent.com/1681525/120504531-82c6b900-c3c4-11eb-94eb-c0ebcd090f44.png)
![image](https://user-images.githubusercontent.com/1681525/120504566-8a865d80-c3c4-11eb-934e-a55bf4f71a8a.png)

And I see the PWA app now does the same as the web app, 4 rows + 2, then at the bottom, loads the rest to fill the 5th row

**Comment by omBratteng** [comment]
From PWA, it loads too quickly for be able to take a screenshot of it before it loads the rest.
![image](https://user-images.githubusercontent.com/1681525/120504791-b73a7500-c3c4-11eb-8186-eb523965b528.png)
![image](https://user-images.githubusercontent.com/1681525/120504916-cfaa8f80-c3c4-11eb-8693-59b008a38418.png)

**Comment by idoshamun** [comment]
I just deployed a change in the infinite scroll for high res monitors like yours.
Can you try again? Please check both in the web app and PWA. There's no need for the extension as I need to release a version once we confirm this is resolved.

**Comment by omBratteng** [comment]
Looks to be working in both web app and PWA. Can confirm it also works now in Firefox, and still works in Safari 😄

**Comment by idoshamun** [comment]
Sweet! This calls for a new release. v3.0.2 here we come :)
Thanks for all the help 🙏

**Comment by idoshamun** [comment]
I submitted v3.0.2 to the stores. Hopefully, it will be approved soon :)

**Comment by omBratteng** [comment]
I'll keep an eye out for it

**Comment by omBratteng** [comment]
`3.0.2` is released, and it's fixed in the extension 🎉

**Comment by idoshamun** [comment]
Woohoo!!!
