### ISSUE TITLE
🧩 FEATURE REQUEST: Add an option to disable daily.dev as the home screen.

### ISSUE THREAD

**Issue by Isaac-the-Man** [dailydotdev/daily#292]
## Feature Request

Add an option to disable daily.dev as the home screen.

### Description

It would be great if there's a way to disable daily.dev as the default home screen of my browser. Most of the time I prefer the default chrome UI when I open a new tab. I can then choose to browse daily.dev manually by clicking the extension icon. 

### Solution

An enable/disable switch in the setting page is fine.

**Comment by rini94** [comment]
@Isaac-the-Man There's the web app for this reason. It's in the beta stage, I believe. The link to the web app is at the bottom of their website.

**Comment by Isaac-the-Man** [comment]
@rini94 thanks for pointing that out. However, it'll be much easier if I can just click on the extension icon to access the webapp instead of going to their webapp via the url. This way I won't need to uninstall the extension too.

**Comment by idoshamun** [comment]
Hey @Isaac-the-Man, you can turn on the Do Not Disturb mode if you want to keep the extension but disable the new tab functionality.

Thanks @rini94 for helping us out here :)

**Comment by Isaac-the-Man** [comment]
@idoshamun thanks that is exactly what I needed! The name "Do Not Disturb" seems kind of counter-intuitive though.

**Comment by idoshamun** [comment]
Sweet! Glad I could help.
Any other name comes to mind when you think about this feature?
Originally it was named by the one who requested this feature just like you.
