### ISSUE TITLE
🧩 FEATURE REQUEST: Listing all the read articles in a single place 

### ISSUE THREAD

**Issue by DefCon-007** [dailydotdev/daily#293]
### Description

I would like to have a place where I can see all the articles I have read till now. 

#### Need 
Most of the times when we are working on something we realise that we read something related somewhere before but we tend to forget from where, since daily.dev has now become a defacto place for me to read development related news, it would be great to have all the read articles in a single place and possibly allowing me to search from them too. 

### Solution

If not doing already, save the article which user has opened and add a new section which lists all these articles. 

### Alternate Solutions

NA

**Comment by idoshamun** [comment]
Hey @DefCon-007,

That's a great idea. I love it.
I'll raise it to vote in the next product planning!

**Comment by nimrodkra** [comment]
@DefCon-007 the reading history is live :) https://app.daily.dev/posts/RrTBj82uI
You can find it here:

![Screen Shot 2022-01-27 at 16 23 37](https://user-images.githubusercontent.com/41470823/151377810-c31378e1-ebdc-42ce-af1d-cd6748c0910a.png)

**Comment by DefCon-007** [comment]
Thanks for the update @nimrodkra. This looks amazing. :D
