### ISSUE TITLE
🧩 FEATURE REQUEST: Add unfollow button on blog list sidebar

### ISSUE THREAD

**Issue by cikupin** [dailydotdev/daily#296]
## Feature Request

Add unfollow button on blog list sidebar

### Description

Hi daily team,

Currently I have an issue with daily.dev blog source in the sidebar. Whenever I click blog source title, it will unfollow blog from my list. So that to see blog post list I have to click the arrow next to it. 

<img width="432" alt="Screen Shot 2021-06-21 at 17 58 59 2" src="https://user-images.githubusercontent.com/9508513/122753700-d427e100-d2bc-11eb-98c0-82ef77053544.png">

This is confusing to some users (not only me, but from my friends too). I suggest that you improve the UI to be clearer about this.

### Solution

I request suggestion to change the UI to these specification:
- Whenever use click blog title, it will open blog list page on the right side.
- User click trash icon will remove blog from source list

<img width="432" alt="Screen Shot 2021-06-21 at 17 58 59_unfollow_button" src="https://user-images.githubusercontent.com/9508513/122769127-79978080-d2ce-11eb-94ef-4a3e80e367bf.png">

**Comment by idoshamun** [comment]
Hey @cikupin,

This is a great suggestion. You know why? Because we've just finished a product planning for the upcoming two weeks or so and it's part of it!
Hang tight till we ship it :)

**Comment by cikupin** [comment]
@idoshamun Awesome. Can't wait to see it 👍

**Comment by idoshamun** [comment]
The feature is live in our web app and soon will be available on the extension as well 🚀
