### ISSUE TITLE
Make the article title clickable on the article page

### ISSUE THREAD

**Issue by idoshamun** [dailydotdev/daily#298]
We want to turn the title on the article page into a clickable anchor element that navigates to the article.
Here's an example of such a page:
https://app.daily.dev/posts/fYXYHRX0r

How to get started?
* This issue involves only our client-side apps, which can be found here [dailydotdev/apps](https://www.sketch.com/s/2549ccf9-b98c-413f-96fb-81b05b59e65f/a/9PZRRDp).
* Make sure to have the latest services running in your local environment. [Click here for instructions](https://github.com/dailydotdev/daily#%EF%B8%8F-setting-up-daily-services).
* The title element of the article page is [here](https://github.com/dailydotdev/apps/blob/master/packages/webapp/pages/posts/%5Bid%5D.tsx#L485).

Implementation details:
The title element should be an anchor element just like the image element on the same page:
https://github.com/dailydotdev/apps/blob/master/packages/webapp/pages/posts/%5Bid%5D.tsx#L509

**Comment by Mahdhir** [comment]
Hi @idoshamun 
Unable to `docker-compose up` 

Getting the below error.

`F:\OSS\apps>docker-compose pull && docker-compose up
Pulling daily-postgres ... done
Pulling daily-mysql    ... done
Pulling daily-gateway  ... done
Pulling daily-api      ... done
Starting apps_daily-mysql_1    ... done
Starting apps_daily-postgres_1 ... done
Starting apps_daily-gateway_1  ... done
Starting apps_daily-api_1      ... done
Attaching to apps_daily-mysql_1, apps_daily-postgres_1, apps_daily-api_1, apps_daily-gateway_1
daily-api_1       | 2021/06/22 09:01:40 no such file or directory
daily-gateway_1   | 2021/06/22 09:01:40 no such file or directory
daily-postgres_1  |
daily-postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
daily-postgres_1  | 
daily-postgres_1  | 2021-06-22 09:01:36.285 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
daily-postgres_1  | 2021-06-22 09:01:36.285 UTC [1] LOG:  listening on IPv6 address "::", port 5432
daily-postgres_1  | 2021-06-22 09:01:36.673 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
daily-postgres_1  | 2021-06-22 09:01:37.121 UTC [20] LOG:  database system was shut down at 2021-06-22 09:00:53 UTC
daily-postgres_1  | 2021-06-22 09:01:37.280 UTC [1] LOG:  database system is ready to accept connections
apps_daily-api_1 exited with code 1
apps_daily-gateway_1 exited with code 1`

OS - Windows 10
Ran the command through bash and command prompt.

**Comment by idoshamun** [comment]
I remember there was someone that used Windows as well that had this problem but I don't remember how we end up fixing it. Let me google it.

**Comment by idoshamun** [comment]
I found the relevant issue that we fixed before (https://github.com/dailydotdev/daily-apps/pull/284).
I applied the relevant changes to this repo, please try to clone again and let me know if it works. 🙏

**Comment by Mahdhir** [comment]
That issue was fixed.
Now getting an issue while trying to `npx lerna run build`
Ran `npx lerna bootstrap` and then `npx lerna run build`. Received the below error 😅

`Failed to compile.

./node_modules/@dailydotdev/shared/icons/toc.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <?xml version="1.0" encoding="UTF-8"?>
| <svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1"
|      xmlns="http://www.w3.org/2000/svg"


> Build error occurred
Error: > Build failed because of webpack errors
    at F:\OSS\apps\packages\webapp\node_modules\next\dist\build\index.js:17:924
    at async Span.traceAsyncFn (F:\OSS\apps\packages\webapp\node_modules\next\dist\telemetry\trace\trace.js:6:584)
lerna ERR! npm run build exited 1 in 'webapp'`

**Comment by idoshamun** [comment]
This must be another Windows issue. I need to get a Windows station and try setting up the repo there.
Sorry for the trouble 😅

**Comment by Mahdhir** [comment]
Haha 
It's fine
I'll try it on a Mac then

**Comment by Dhaiwat10** [comment]
I wanted to take up this one but I am also getting the same error on Windows. 😞

**Comment by Dhaiwat10** [comment]
Trying on Ubuntu now. 🤞

**Comment by Dhaiwat10** [comment]
![Screenshot from 2021-06-23 05-59-20](https://user-images.githubusercontent.com/39617427/123016455-41846080-d3e8-11eb-9540-2d8e4d65e724.png)

Getting this error while trying to populating the DB on Ubuntu :(

**Comment by idoshamun** [comment]
Oh, there's a missing step in the docs. I need to fix it.
Please run:
```
docker exec daily-apps_daily-api_1 npm run db:migrate:latest
```

And only then populate the db

**Comment by Dhaiwat10** [comment]
![image](https://user-images.githubusercontent.com/39617427/123058610-a1016100-d426-11eb-9ce5-4a8e09aaf3fe.png)

This is the error I'm getting both on Windows & Linux.

**Comment by idoshamun** [comment]
Ok. I know why.
Give me some time to update the docs today and do a dry run myself.
I'll let you know when it's ready.

**Comment by Dhaiwat10** [comment]
Sure thing. Thanks!

**Comment by idoshamun** [comment]
I fixed the instructions. Please follow it from the start.
I tried it on a clean machine, and it works. Please let me know if you stumble upon any difficulty.

**Comment by Dhaiwat10** [comment]
I finally got it running on a Linux machine. Thanks, Ido!

**Comment by Dhaiwat10** [comment]
![vid](https://user-images.githubusercontent.com/39617427/123191247-972b3c80-d4be-11eb-8fcc-8737b8d8c887.gif)

I think I did it. Didn't take long. 😄 Should I open a PR at the apps repo?

**Comment by idoshamun** [comment]
Woop woop! That's awesome. Let's proceed with a PR 🤘

**Comment by Dhaiwat10** [comment]
Created the PR ^ 😄
