### ISSUE TITLE
🐛 BUG: Fix Windows support for the apps repo

### ISSUE THREAD

**Issue by idoshamun** [dailydotdev/daily#299]
### What went wrong? 🤔

Following #298, @Mahdhir mentioned that he had trouble compiling the apps repo due to a webpack issue.
More info here:
https://github.com/dailydotdev/daily/issues/298#issuecomment-865956728

### Expected Behavior

The web app project and the entire apps repo should compile successfully on Windows.

This can be tricky to solve but I would love to get some help from a developer with a Windows machine who is willing to get their hands dirty with some webpack work. 🙈

**Comment by Dhaiwat10** [comment]
I have a Windows machine so I could be of help. I don't know a lot about webpack though.

**Comment by idoshamun** [comment]
Hey @Dhaiwat10,

Great talking to you again :)
It would be great if for starters you could try to build the extension.
We already know there's something going on with the web app build but maybe the extension is fine.

To build the extension clone the project and run the following:
```
npm i -g lerna
lerna bootstrap
cd packages/extension
npm run build:chrome
```

**Comment by Dhaiwat10** [comment]
Tried building the extension on Windows. I am getting loads of errors, most of them are like this:

```
ERROR in ../shared/icons/x.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <?xml version="1.0" encoding="UTF-8"?>
| <svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
|     <!-- Generator: Sketch 52.5 (67469) - http://www.bohemiancoding.com/sketch -->
```

**Comment by Dhaiwat10** [comment]
Looks like a problem with a svg loader of some sort.

**Comment by idoshamun** [comment]
Ok, I think I have an idea. It has to do with the different path separators between Windows and Unix/Linux systems.
Let's fix the problem for the extension first. Please open the `webpack.config.js` in the extension repo.
Replace all occurrences of: `/node_modules\/(?!@dailydotdev)/` with `/node_modules(\/|\\)(?!@dailydotdev)/`.
Let's see if it works.

**Comment by Dhaiwat10** [comment]
The build still fails with the same type of errors.

**Comment by idoshamun** [comment]
Oh, I know why...
I missed this line:
`/icons\/.*\.svg$/`
Replace it with:
`/icons(\/|\\).*\.svg$/`

**Comment by Dhaiwat10** [comment]
![image](https://user-images.githubusercontent.com/39617427/124084174-57d78f80-da6c-11eb-94c2-cad9471b58bd.png)

Is that good?

**Comment by idoshamun** [comment]
Yes! That's awesome. Can you try and apply these two changes in the `next.config.js` in the webapp repo?

**Comment by Dhaiwat10** [comment]
![image](https://user-images.githubusercontent.com/39617427/124085763-0203e700-da6e-11eb-8859-dca24b4da980.png)

The build succeeds without any errors.

**Comment by idoshamun** [comment]
Woop Woop!
Can you submit a PR with these changes, please?

**Comment by Dhaiwat10** [comment]
![image](https://user-images.githubusercontent.com/39617427/124086148-6757d800-da6e-11eb-855e-1ccce4653fb4.png)

Sure. But I was wondering what should I do with these two new files that got created? Should I include them in the commit, or delete them?

**Comment by idoshamun** [comment]
You should remove them before commiting

**Comment by Dhaiwat10** [comment]
^ Created.

**Comment by idoshamun** [comment]
Thanks for @Dhaiwat10!
It was magnificent teamwork that we pulled off and now all Windows contributors can enjoy it.
