### ISSUE TITLE
🐛 BUG: "Start the discussion" bar on the article page is partially hidden in mobile Safari

### ISSUE THREAD

**Issue by idoshamun** [dailydotdev/daily#300]
### What went wrong? 🤔

The "Start the discussion" bar on the article page is partially hidden in mobile Safari due to the grabber.
![File](https://user-images.githubusercontent.com/1993245/123543409-ec817b00-d756-11eb-8b07-2e0a1a3ed314.jpg)

### Expected Behavior

The bar should be 100% visible in mobile Safari and other browsers.

### Steps to Reproduce Issue

* Open app.daily.dev on mobile Safari
* Hit the comment button on a random post
* Look at the bottom of the screen

### Solution

A possible solution can be similar to what we implemented here:
https://github.com/dailydotdev/apps/pull/587

**Comment by miralsuthar** [comment]
I would like to take this.

**Comment by idoshamun** [comment]
Hey @miralsuthar,

That would be awesome. 🤘
Let me know if you need guidance.

**Comment by miralsuthar** [comment]
Hey, I am getting this error whenever I try to run the web app.

![image](https://user-images.githubusercontent.com/57826091/124075385-6325bd80-da62-11eb-9a2d-1f48d57328de.png)

**Comment by idoshamun** [comment]
It looks like you are using Windows and unfortunately, we have an issue running our local environment on Windows.
We have an open issue about it:
https://github.com/dailydotdev/daily/issues/299
We're doing our best to solve it but if you have any ideas you are more than welcome to share :)

**Comment by idoshamun** [comment]
Try to do delete the .next and node_modules in the webapp repo and run `lerna bootstrap` again. Let's see what happens.
https://github.com/vercel/next.js/issues/6287#issuecomment-493300054

**Comment by miralsuthar** [comment]
I saw the bug #299 has been solved. So now I can use it in windows too right?

**Comment by idoshamun** [comment]
Yes! Make sure to pull the new changes :)

**Comment by miralsuthar** [comment]
Hey, in my browser the UI looking bit different.
![Screenshot_4](https://user-images.githubusercontent.com/57826091/124117646-02ac7580-da8e-11eb-82f4-74d487be2eb9.png)
![Screenshot_6](https://user-images.githubusercontent.com/57826091/124117659-05a76600-da8e-11eb-8f2e-6432b8782fea.png)

**Comment by idoshamun** [comment]
This looks like a Tailwind purge issue.
Can you try to change the directory separators in this file:
https://github.com/dailydotdev/apps/blob/master/packages/webapp/tailwind.config.js
to match the Windows convention. I think this is it.

**Comment by miralsuthar** [comment]
Is this ok?
![WhatsApp Image 2021-07-01 at 7 56 22 PM](https://user-images.githubusercontent.com/57826091/124141551-20d29f80-daa7-11eb-9db9-4d8a6d45e789.jpeg)

**Comment by idoshamun** [comment]
This looks perfect! :)
