### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by dukesy710** [dailydotdev/daily#301]
### What went wrong? 🤔

Signed in using google, then got redirected to the 'Setup my profile' view where the only missing field is username. I enter a username and click finish but 'my email already exists' error occurs as shown in the screenshot below. 

![Untitled presentation](https://user-images.githubusercontent.com/35784444/123680249-c5a37180-d848-11eb-8ee9-4de2ffbbcd51.png)

The same thing happens from the 'Complete your profile' dialog - I cannot save changes as my email already exists. 

My profile with the email already exists, I just want to update my username. 

I don't mind not having a username, but because my profile is not complete every time I open a new tab it redirects to 'Setup my profile' and this redirect is disrupting my flow. 

### Expected Behavior

Username is updated.

### Actual Behavior

Cannot update username. 

### Steps to Reproduce Issue

- Did not have an account
- Clicked login 
- Selected login with Google
- Redirected to 'Setup my profile' - which now happens on every new tab opening 

### Solution

Seems to be trying to create instead of update - do an update from the 'Complete your profile' dialog. 

The issue might be because there is only a Login (no sign up) that needs to 'create' on the first time login, and it might be trying to 'create' on subsequent logins, but it should just update the non-unique/non-indexed fields.   

### Environment

Google chrome 

#### Operating System

Ubuntu

#### Version of Daily

3.1.0 

#### Browser

Google chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Can you please send us an email with your account email address to support@daily.dev?
Let's proceed there.

**Comment by dukesy710** [comment]
Sure will do. Thanks


*Michael Dukes**BScEng (Electrical), BEngSc (BME)*
*Software Engineer*
