### ISSUE TITLE
🧩 FEATURE REQUEST:  Integration with vimium-C

### ISSUE THREAD

**Issue by GiancarloAparicio** [dailydotdev/daily#302]
## Feature Request
I know there is already a feature request on vim shortcuts, but I think it would be better to integrate it with vimium-c
https://github.com/gdh1995/vimium-c

### Description
Like the pdf viewer integration with vimium-c.
Where if you have vimium-c installed, all your configuration works and if you do not have it installed, it only has its default behavior of the extension
https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj?hl=es

### Solution
Integration with the vimium-c extension
https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

**Comment by idoshamun** [comment]
Hey @GiancarloAparicio,

I saw you replied on #122 let's keep talking there.
I don't want us to be too implementation-oriented. Let's talk about the values and features that we would like to bring.
Maybe there're alternatives to vimium-c that we want to consider.
