### ISSUE TITLE
🧩 FEATURE REQUEST: Option to Delete Account

### ISSUE THREAD

**Issue by DasikaMadhu** [dailydotdev/daily#303]
## Feature Request
Option to delete an existing account 

### Description

A button in the Account section or elsewhere to be able to delete existing account

**Comment by idoshamun** [comment]
Hey @DasikaMadhu,

We will add it to the roadmap.
This is indeed a necessary feature.

**Comment by Shylajhaa** [comment]
@idoshamun Is this available to work on? If yes, can I work on this?

**Comment by idoshamun** [comment]
Hi @Shylajhaa!

Actually it's already live. Forgot to close this issue 😓 
https://docs.daily.dev/docs/your-profile/deleting-your-profile
