### ISSUE TITLE
🐛 BUG: The extension has a long loading time, sometimes it does not load neither the main page nor the news of a specific topic. I tried to uninstall and install but it doesn't work.

### ISSUE THREAD

**Issue by LeoCovarrubias** [dailydotdev/daily#305]
### What went wrong? 🤔
The extension has a long loading time, sometimes it does not load neither the main page nor the news of a specific topic. I tried to uninstall and install but it doesn't work.

![imagen](https://user-images.githubusercontent.com/54729665/125309416-5d986500-e2f7-11eb-886e-1426e66c3936.png)

**Comment by idoshamun** [comment]
Hey @LeoCovarrubias,

Unfortunately, we are having technical issues.
We are working hard to solve it ASAP! 🙏

**Comment by idoshamun** [comment]
It should be fine now. Let me know if you experience anything else.
