### ISSUE TITLE
I want to delete my account

### ISSUE THREAD

**Issue by CiaraBurkett** [dailydotdev/daily#306]
I want to delete my account and all of my personal information. I don't see that option anywhere.

**Comment by idoshamun** [comment]
Hey!

Please shoot us an email at support at daily.dev

**Comment by gvdr** [comment]
Hey, I want to delete my account too. And no, I don't want to have to write you an email. Act on it swiftly, as you may be in breach of GDPR regulations.

**Comment by idoshamun** [comment]
@gvdr I'm asking for an email to validate your account, not because I fancy making this process longer. And anyway, according to your GitHub profile you are located in New Zealand :P
Again, please send us an email as mentioned above.

**Comment by gvdr** [comment]
Yes, I'm based in New Zealand but I am a EU citizen, so GDPR applies to me as well ;-)

**Comment by idoshamun** [comment]
As mentioned before please send us an email. Otherwise I cannot confirm your account...
