### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by justnewbee** [dailydotdev/daily#307]
### What went wrong? 🤔

![image](https://user-images.githubusercontent.com/2276086/126595181-52d84958-b58c-473f-8879-df891d734a6c.png)

Every time I open a new tab in Firefox, it will be redirected: https://app.daily.dev/register?redirect_uri=moz-extension://905b81a8-8230-0b4a-bdba-cb54c8cdc73f/index.html

And I got this error...

Cannot go back, cannot cancel, cannot proceed

Very annoying

### Expected Behavior

WHY? I have logged in, but why it tells me that my email is taken?

**Comment by idoshamun** [comment]
Hey! Our registration flow includes third-party authentication and providing more information about you.
In case we detect that your email is used with another account we can't let you complete the registration.
It might be that in the past you used another provider to log in to our system. Please send us an email to support at daily.dev and we will take it from there. It's not recommended to share here personal information.
