### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by MohannadBahaa** [dailydotdev/daily#308]
### What went wrong? 🤔
    When I press on the new tap I am getting this error 
   

>  `Uncaught TypeError: Cannot read property 'local' of undefined`

![Capture](https://user-images.githubusercontent.com/28856488/128265259-4087bbf7-ce6a-497e-b9d4-821e09772e94.PNG)

### Expected Behavior
get all articles 

### Actual Behavior
I am not able to read articles, I am seeing a blank page without articles 

### Steps to Reproduce Issue

- just click on the new tab
make sure in your browser you are doing this :

![Capture1](https://user-images.githubusercontent.com/28856488/128265094-3fdbd5e9-2c9f-4810-a603-e96a9056b40d.PNG)

**Comment by mrevjd** [comment]
Having the same issue with:
Chrome Version 92.0.4515.131 (Official Build) (64-bit)
Ubuntu Cinnamon 20.04 

However Firefox 90.0.2 (64-bit) works

**Comment by idoshamun** [comment]
Hey!

v3.4.0 was broken, unfortunately, please make sure to update to the latest version v3.4.1.
