### ISSUE TITLE
🐛 BUG: Cannot open new tab

### ISSUE THREAD

**Issue by darkpiv** [dailydotdev/daily#309]
### What went wrong? 🤔

A new tab in Firefox crash

### Expected Behavior
Open a new tab with DailyDev content on it

### Actual Behavior
Show nothing on new tab

### Steps to Reproduce Issue
Open new tab
![image](https://user-images.githubusercontent.com/5578040/128279356-4431a46f-ac9e-41aa-98a2-c4533c8f58f0.png)

### Solution
I'm not sure but the Chrome works fine

#### Version of Daily
3.4.0
#### Browser
Firefox: 90.0.2
OS: Manjaro

**Comment by toanbku** [comment]
I also have the same problem

**Browser:**
Chrome 92.0  
OS: Mac OS

![image](https://user-images.githubusercontent.com/28706996/128283891-4e38b114-c4f5-425e-a7ef-cd71de6cd937.png)

**Comment by idoshamun** [comment]
Hey!

Thanks for reporting.
v3.4.0 was broken, unfortunately, please make sure to update to the latest version v3.4.1.
