### ISSUE TITLE
🐛 BUG: https://app.daily.dev/devcard repport that something went wrong

### ISSUE THREAD

**Issue by souhaiebtar** [dailydotdev/daily#312]
### What went wrong? 🤔

i tried to open `https://app.daily.dev/devcard` but i got a message ` something went wrong`

### Expected Behavior

i expected that i get something correct like a page or something like that

### Actual Behavior

i got a message `Something went wrong, please try again...`

and when i used inspect, i found that there is 2 problem:

1. `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.amplitude.com/`
2.  `GEThttps://api.daily.dev/devcards/43b054798c58499899fc86678531d65f.png?r=fos`  error 500 internal server error

### Steps to Reproduce Issue

you only need to open the page `https://app.daily.dev/devcard` (make sure that you already have an account)

**Comment by idoshamun** [comment]
Can you please check if your profile information is complete?
I think your account is missing a username.
Go to your profile page and hit account details.
