### ISSUE TITLE
🐛 BUG: blocked sources are still being displayed when browsing by tags

### ISSUE THREAD

**Issue by creativenull** [dailydotdev/daily#313]
### What went wrong? 🤔

Blocking a source from the sources section and then going to the tags section to browse posts by a tag still shows the blocked source as part of the posts shown within that tag.

### Expected Behavior

Blocked sources should not be shown even when browsing posts by tags.

### Actual Behavior

Blocked sources are still shown when browsing by tags.

### Steps to Reproduce Issue

1. Go to the sources section from the left sidebar
![image](https://user-images.githubusercontent.com/3767728/129065712-0f8276f0-1efe-451b-b41c-51c7fa3d9723.png)
2. Block sources
![image](https://user-images.githubusercontent.com/3767728/129065446-19ed7efd-0dd0-4bad-860d-042244a3b9b2.png)
3. Go to the tags section from the left sidebar
4. Browse any tag (in this instance browsing the "deno" tag)
![image](https://user-images.githubusercontent.com/3767728/129065767-f9892f5e-1f6f-4cb9-8d4d-7cf00027af61.png)
5. Scroll down and you will still see the blocked source being shown
![image](https://user-images.githubusercontent.com/3767728/129065995-20278edc-2183-4f99-a8a4-65a838c28c31.png)

### Solution

I have not had the chance to look at the code but from what I see implementing a filter to exclude blocked sources when showing posts by tags could be the way to go.

#### Operating System

Windows 10 21H1

#### Version of Daily

v3.5.0

#### Browser

Firefox v90.0.2

**Comment by idoshamun** [comment]
Hey @creativenull,

The preferences in the sidebar affect only your personal feed.
Tag-based are not affected by your selection, neither the most upvoted and discussed feeds.
We should make it more clear. I can definitely understand the confusion.

**Comment by creativenull** [comment]
Hey thanks for the update!

Any plans to have that feature on tag-based browsing?

**Comment by idoshamun** [comment]
Unfortunately, not at the moment. 
We're focused on improving the main feed content.
