### ISSUE TITLE
🐛 BUG: Web Tools Weekly feed not updating

### ISSUE THREAD

**Issue by impressivewebs** [dailydotdev/daily#314]
### What went wrong? 🤔

My newsletter Web Tools Weekly (https://webtoolsweekly.com/) is included in the list of resources, but the feed hasn't updated since June 2. The URL is here:

https://app.daily.dev/sources/webtoolsweekly

### Expected Behavior

A new issue should be posted each week.

### Actual Behavior

Issues haven't been added since June 2.

### Steps to Reproduce Issue

NA

### Solution

NA

### Environment

NA

#### Operating System

NA

#### Version of Daily

3.5.0

#### Browser

NA

**Comment by idoshamun** [comment]
Hey @impressivewebs,

I'll check it out and let you know :)

**Comment by idoshamun** [comment]
I checked into our system and find out that it has to do with the RSS third-party system we are using.
We are looking into replacing it with an in-house solution, it will take a while but eventually, it should fix the issue.
I'll the issue open for now.

**Comment by impressivewebs** [comment]
Hi @idoshamun, just FYI I noticed that my newsletter's last two issues have appeared in the feed, so I think this is fixed now. The only thing I should probably correct is the fact that the social cards in the HTML didn't provide the correct "subject line" for the feed title.

**Comment by idoshamun** [comment]
That's great to hear! We have some heuristics regarding the title we use, and if you go to the article you will see that the title everywhere is "Web Tools Weekly". This is why our scraper chose this title.
