### ISSUE TITLE
🧩 FEATURE REQUEST: Add dislike

### ISSUE THREAD

**Issue by GiancarloAparicio** [dailydotdev/daily#316]
## Feature Request

Adding a button I don't like

### Description
Looking for some posts to read I came across one of the worst I've read and it seems strange to me that I would recommend it daily.
Even in the comments of the article that is mentioned.
![test](https://user-images.githubusercontent.com/61440825/129280741-712cbcb3-1d09-47cb-8d73-8cc6012c0116.png)

That way you could see in a way if an article is just clickbait or also if it has a considerable amount of I don't like that they are deleted

**Comment by idoshamun** [comment]
Hey @GiancarloAparicio,

A dislike/downvote option is asked every now and then and we to think about the right implementation that can prevent abuse and etc. At the moment we decided to provide a rich reporting functionality that acts like a downvote or can even make posts be removed.
I hope this makes sense to you. I'll leave this issue open so we can address it in our future product meetings.

**Comment by ariaieboy** [comment]
@idoshamun 
can't you make that dislike button a personal thing ? 
like what we have in google news feed and other feeds so we just dislike the post that we dont like and daily.dev dont show us that kind of posts later or at least show us less articles like that.

**Comment by idoshamun** [comment]
@ariaieboy thanks for the suggestion. Unfortunately, we don't have an advanced recommendation system like Google News but we do plan to give a similar option. The new option will allow you to block relevant tags directly from the card menu.
What do you think about that?

**Comment by rebelchris** [comment]
You can now block tags or report the post.
Closing this issue, but feel free to log any new issues.

**Comment by nimrodkra** [comment]
Downvotes are now live! 🎉 [Check it out](https://app.daily.dev/posts/QK301jNUY)
