### ISSUE TITLE
🧩 FEATURE REQUEST: block certain sources from the feed

### ISSUE THREAD

**Issue by antoniel** [dailydotdev/daily#322]
## Feature Request
A section to block a list of source's on the feed, like a source blacklist.

### Description

As a user I would like to block some sites from my feed, use case there's specific sources in a tag that I'm not interested in see the content, mostly because the target audience of these source doesn't includes me, so a blocked source sections would be pretty nice.

### Solution

Store the user blacklist with the user's preference and from that only server the posts that excludes the blacklisted source.

### Alternate Solutions

Store the user's blacklist in localStorage and on rendering process hide or skip these cards from the feed.

**Comment by antoniel** [comment]
I see, but i would like block specific sources e.g https://reactjsexample.com/, don't want to see any content from this source but still want to see \#react tag

**Comment by idoshamun** [comment]
Yes, you can block the source from the sidebar. There's a toggle menu at
the top that switches between tags and sources.

**Comment by antoniel** [comment]
Coool, thanks for the real quick support
