### ISSUE TITLE
🐛 BUG: This email is already used

### ISSUE THREAD

**Issue by quocanh89** [dailydotdev/daily#323]
### What went wrong? 🤔
![Capture](https://user-images.githubusercontent.com/20266333/132080763-8aaf9273-b62d-415c-a3ec-66f207d73900.JPG)
When i sign up my acc by github, and also by gmail. This email is already used.

**Comment by idoshamun** [comment]
Hey!

It's because you signed in with two providers.
At the moment, we don't support it. I can assist you by deleting one of them.
Please let me know which one by sending an email to support at daily dot dev
