### ISSUE TITLE
🧩 FEATURE REQUEST: Better login options

### ISSUE THREAD

**Issue by edent** [dailydotdev/daily#326]
## Feature Request
I don't want to sign in usong GitHub or Google. I want to create an account usong a unique email address and password.

Please provide an option to creat an accoint rather than using a social login.

### Description

* I don't trust you woth my GitHub or Google details.
* Lots of people don't have either of these services.
* Letting users use a unique email address and password to sign up means the user is always in control of their data.

### Solution

You could use something like Auth0 if you don't want to roll your own user database.

**Comment by idoshamun** [comment]
We will add an email and password sign-up, but I can't guarantee it will be any time soon.
Regarding the social logins, we ask for minimal permissions and don't even store the access token in our database. So even if something bad happens, we don't store relevant information about the login provider that can be misused.
It is used only for the initial fetch of personal information to prefill the registration form that follows and to confirm your identity.
I hope that makes sense

**Comment by idoshamun** [comment]
We've just released our new authentication system. Please check out the release notes and try out the new features.
https://app.daily.dev/posts/IEnARQTZA
Looking forward to hear your feedback :)
