### ISSUE TITLE
Bug: Profile Page - Heatmap Year Selection

### ISSUE THREAD

**Issue by KiliMcgee** [dailydotdev/daily#327]
On the profile page, there's a bug that causes the app to crash when attempting to set the calendar year to anything other than the default option of "Last year". In order to reproduce this error, choose any of the options from the calendar dropdown as shown in the screenshot below.

<img width="625" alt="Screen Shot 2021-05-24 at 9 43 43 PM" src="https://user-images.githubusercontent.com/35938628/119427493-1f100200-bcd9-11eb-9c61-cb9074375536.png">

The app crashes and the page goes blank with the message "An unexpected error has occurred". There's also an accompanying stack trace indicating that a RangeError has been encountered. Please see the attached screenshot below.
 
<img width="1228" alt="Screen Shot 2021-05-24 at 9 41 39 PM" src="https://user-images.githubusercontent.com/35938628/119427384-ebcd7300-bcd8-11eb-8dd8-f9122aff5591.png">

**Comment by rebelchris** [comment]
@KiliMcgee This was due to a timezone issue, it should have been fixed.
Please feel free to log again if it still happens.
