### ISSUE TITLE
🐛 BUG: Calendar not in sync

### ISSUE THREAD

**Issue by martinlbradley** [dailydotdev/daily#329]

**Comment by martinlbradley** [comment]
When I read an article, the "Articles read in the last year" bar is updating the count for yesterday, even when an empty dot is showning for the current day.

**Comment by idoshamun** [comment]
This is probably caused by timezone differences. Currently, we calculate this matrix in UTC time and you're probably located somewhere else. We will add timezone support in the future

**Comment by nimrodkra** [comment]
Hi @martinlbradley we have some good news! We shipped today a new feature following your feedback! Now you can add the time zone to your profile: https://changelog.daily.dev/add-time-zone-213792
