### ISSUE TITLE
🐛 BUG: Claimed articles not displaying on profile

### ISSUE THREAD

**Issue by skarthikeyan96** [dailydotdev/daily#330]
### What went wrong? 🤔

Even after adding the twitter username in my account to claim the article which I wrote , I am not able to see the author badge or it is not showing up on the articles list.

### Expected Behavior

1. As mentioned after commenting on my post , I should have gotten the author badge
2. It is not appearing on the `your articles` list. 

Post Link: https://app.daily.dev/posts/kiWJQ4EOF
Twitter username : @karthik_coder

Screenshot of the tweet: 

![image](https://user-images.githubusercontent.com/23126394/134459387-e6648b7a-8320-4dce-b366-b3e7aeb25783.png)

### Steps to Reproduce Issue

- Create new tab in browser with daily.dev installed so that the daily.dev feed displays.
- Go to this link [https://app.daily.dev/posts/kiWJQ4EOF]( https://app.daily.dev/posts/kiWJQ4EOF).
- Go to my [daily.dev](https://app.daily.dev/green_arrow996) profile page.
- You can see articles has not been updated.

#### Operating System
Mac OS 
#### Version of Daily
latest
#### Browser
chrome

**Comment by idoshamun** [comment]
It is fixed now :)

**Comment by skarthikeyan96** [comment]
@idoshamun Thank you
