### ISSUE TITLE
🧩 FEATURE REQUEST: Making YouTube Videos, podcast, ... regular daily.

### ISSUE THREAD

**Issue by wtrungvu** [dailydotdev/daily#331]
## Feature Request

Making YouTube videos, podcast, ... 

### Description

Making YouTube video, podcast, ... 
YouTube channel, podcast channel, ...
Advertise for everyone to know.
Creating new videos, podcast everydays... everyweek ...
What's new everyday?
What's trending?
What things that devs should know?
...

just an funny ideas... you can add more suggestions 😅😂

**Comment by idoshamun** [comment]
Hey!

Thanks for the suggestion. At the moment we're trying to perfect our written content feed and then we might want to explore new types of content.
