### ISSUE TITLE
🐛 BUG: hide read posts not working

### ISSUE THREAD

**Issue by ariaieboy** [dailydotdev/daily#335]
### What went wrong? 🤔

i've enabled the hide read posts in the prefrence setting but it's not working as expected
![image](https://user-images.githubusercontent.com/15873972/137014036-16e41db8-da2a-4ccd-b8ee-8f830ac9cf09.png)

### Expected Behavior

i want to hide the read posts from my feed in any tab like recent popular etc
### Actual Behavior

but its not working and as you can see in the picture above the read posts are still in my feed
#### Operating System
windows 11 dev insider build
#### Version of Daily
3.7.0
#### Browser
chrome

**Comment by idoshamun** [comment]
I'll look into it, thanks for reporting.
Anyway, this setting will become obsolete soon as we're rolling out a new feed algorithm that already takes it into account by default.
