### ISSUE TITLE
🧩 FEATURE REQUEST: Option to modify or remove most visited site section

### ISSUE THREAD

**Issue by shaivik** [dailydotdev/daily#337]
## Feature Request

Option to modify and remove the most visited site section.

### Description

- Right now, the most visited site section on the page is static and there is no control over it to modify these sites. It would be better if we could pin websites of our choice in this section similar to what we do in bookmarks bar.  
- Also once we add this section there is no option to remove it. Providing the option to remove this in profile page could be helpful. 

### Solution

**Modify sites:**
- Open a modal on clicking the edit button. 
- In the modal allow the option to add/remove/modify the sites. Limit the list length to 8. 
<img width="390" alt="Screenshot 2021-10-13 at 12 42 54 PM" src="https://user-images.githubusercontent.com/33276089/137085055-688eeb72-e902-43be-b416-bf1de705f006.png">

<img width="957" alt="Screenshot 2021-10-13 at 12 46 43 PM" src="https://user-images.githubusercontent.com/33276089/137085312-c2717a2d-db8d-4371-9bcf-5b0ffaa550db.png">

**Removing section:**
- In the account details modal have an option to disable this section. 
<img width="456" alt="Screenshot 2021-10-13 at 12 33 29 PM" src="https://user-images.githubusercontent.com/33276089/137084516-a0a89e3d-6b14-44c4-9dd0-5f2f3f080b96.png">

**Comment by rebelchris** [comment]
Hi @shaivik thanks for logging this!

We just released a new version of the extension where you have this option! 👀
Let us know if you have more great additions.

<img width="1440" alt="Screenshot 2021-11-18 at 18 01 39" src="https://user-images.githubusercontent.com/554874/142451296-83f7572d-28ee-444c-9865-0a35b0d793ed.png">
