### ISSUE TITLE
🧩 FEATURE REQUEST: notification system

### ISSUE THREAD

**Issue by ariaieboy** [dailydotdev/daily#338]
### Description

having some features like comments and upvoting is really cool and it will be awesomee to have a notification systm that we recieve notification on up vote or at least at commnet reply so we can see who replied to our comment and interact more on that subject

**Comment by rebelchris** [comment]
@ariaieboy You might have noticed we recently introduced a notification center 🥳
We'll be expanding it soon so keep a close eye for more features to come.
