### ISSUE TITLE
🐛 BUG: search component behaviour  

### ISSUE THREAD

**Issue by Laaaaannn** [dailydotdev/daily#342]
### What went wrong? 🤔
- The search component is hiding when clicking the right side of input

### Expected Behavior
- It should not close the search input

### Actual Behavior
- it should focus on the search input

### Steps to Reproduce Issue
- https://user-images.githubusercontent.com/14991331/140378390-82118514-0f0f-41ad-ae3e-96170eafef13.mp4

### Solution
- change the implementation of the close button by using conditional rendering instead of adding .invisible class?

### Environment
- n/a

#### Operating System
- Mac

#### Version of Daily
- n/a

#### Browser
- Google Chrome: Version 95.0.4638.54
- ![Uploading Screen Shot 2021-11-05 at 12.40.55 AM.png…]()

**Comment by idoshamun** [comment]
Hi @Laaaaannn,

Thanks a lot for reporting this.
We are soon planning a re-layout for the application which involves changing the behavior of the search bar.
So stay tuned :)

**Comment by MadhaviMandalia** [comment]
Hello @idoshamun ,
Can I help on this issue?

Thanks & Regards.

**Comment by idoshamun** [comment]
Hi @MadhaviMandalia,

We would be very happy to get your help on this.
First, please confirm that the issue still holds as we introduced a new layout recently which changed things a bit.

**Comment by sshanzel** [comment]
Hi @MadhaviMandalia, thank you so much for the willingness to work on this issue. Unfortunately, we have introduced a new guideline for our search input field and this got resolved along the way ([open PR](https://github.com/dailydotdev/apps/pull/921)). Would love to hear more from you in the future!
