### ISSUE TITLE
🧩 FEATURE REQUEST: Custom RSS Feeds on an user basis

### ISSUE THREAD

**Issue by AnishDe12020** [dailydotdev/daily#344]
## Feature Request

An option for users to add RSS Feeds (of any news site they want, e.g. their github feed, specific hashnode feeds etc) and the feed will show up on the daily.dev page (probably on a different tab or something) from where they can read the articles like any news reader. In this case daily.dev will not only give people with devnews (which it is doing currently) but will also work as a great RSS reader. 

### Description

Daily.dev will also work as a modern RSS feed reader where the user can add sources he wishes to and then he can read his feed on the daily.dev extension itself (ie on the home page). 

### Solution

Adding an option where the user can add RSS feeds of their choice and the feed will show up on the extension.

### Alternate Solutions

NA

**Comment by csbain** [comment]
I'd like to second this, it would be really good to have an rss feed to have on our companies slack/teams/etc... and raise awareness about these articles internally.

I've had a look at some of the source code but every reference to an rss capability - mainly in https://github.com/dailydotdev/daily-api/blob/d3f909d721ddca1ac747bbded0d74f661e961ef8/__tests__/rss.ts

seems to point to the possibility of accessing /rss/f/:userId if you're a premium user... in this case how does one go about getting premium access?

Thanks,

Chris

**Comment by imsaptarshi** [comment]
agree agree

**Comment by idoshamun** [comment]
We used to have these options on our Premium features. Unfortunately, this didn't work out, and at the moment we don't have plans to bring it back. We focus now on improving our feed, ranking, content relevancy, considering also letting people post news just like in Hacker News. But daily.dev is not going to be a full-blown RSS reader any time soon. Sorry! 😅

**Comment by noeddi2be** [comment]
I would also love to see this implemented! 😃
