### ISSUE TITLE
🐛 BUG: Typo on sidebar (Advanced Options)

### ISSUE THREAD

**Issue by JoaoOliveira85** [dailydotdev/daily#345]
### What went wrong? 🤔

Typo on sidebar. 

### Expected Behavior

On Advanced options > "Non-editorial content" the text reads:

> Show user-generated posts that **we’re** created on external blogging platforms. [...]

### Actual Behavior

On Advanced options > "Non-editorial content" the text should read:

> Show user-generated posts that **were** created on external blogging platforms. [...]

### Steps to Reproduce Issue

Open the side menu ("cog" icon), select "Advanced" and then read the "Non-editorial content" description. 

### Solution

Fix the text, make a PR and drink a nice warm cup of coffee with the knowledge of a job well done. It seems the text comes from the dB so I don't think I can fix it myself.  :(

### Environment

Desktop

#### Operating System

macOS and Linux Mint

#### Version of Daily

3.9.0

#### Browser

Firefox and Brave

**Comment by idoshamun** [comment]
Hi @JoaoOliveira85,

Thanks for your sharp eyes! 👀 
I fixed the issue. It's indeed stored in our DB
