### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by JoseOsp** [dailydotdev/daily#346]
### What went wrong? 🤔

I cant not use my git hub to login and I know I already connect my account . How can I login? Can you help me please.

### Expected Behavior

That if I want to login with my github that works

### Actual Behavior

When I try to login using GitHub doesn’t work

### Steps to Reproduce Issue

login with gihub, that redirect me to github I login on github but after appears a error page and is not possible to continue

### Solution

`NA`

### Environment

`NA`

#### Operating System
MAC ios

#### Version of Daily
3.9.1

#### Browser

Browser info: Chrome

#### Account email

joseerneyosp@gmail.com

#### GitHub usser

[JoseOsp](https://github.com/JoseOsp)

**Comment by idoshamun** [comment]
Hi @JoseOsp,

Please try again now :)
