### ISSUE TITLE
🐛 BUG: Can not login

### ISSUE THREAD

**Issue by ntctuyen** [dailydotdev/daily#348]
### What went wrong? 🤔

![image](https://user-images.githubusercontent.com/27688125/141649630-73e46f6d-c643-4344-8396-f5a05dee1285.png)

Sign in buttons but the text signs up, after clicking on Sign in with Google, It redirected to the [Registration page:](https://app.daily.dev/register?redirect_uri=https%3A%2F%2Fapp.daily.dev%2F&mode=default) 

![image](https://user-images.githubusercontent.com/27688125/141649700-c2b89eb4-a184-4711-ab96-1e2f522b2a71.png)

When inputting the username, it shows an error message is **This email is already used**. But after going back to 
https://app.daily.dev/, I logged in.

### Expected Behavior

Can log in to daily dev as normal

### Actual Behavior

Redirect to the Registration page

### Steps to Reproduce Issue

Click on the Login button on the top right and click on Sign in With Google (Github)

### Solution

N/A

### Environment

N/A

#### Operating System

Ubuntu 20.04.3 LTS

#### Version of Daily

3.9.1

#### Browser

Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi @ntctuyen,

You have two accounts registered under the same email. One with your Google and the other with your GitHub account.
Please let me know which one you would like to keep.
This happens due to an issue we've in our authentication system and we hope to solve it soon.

**Comment by ntctuyen** [comment]
Hi @idoshamun, I want to keep the google account. Thanks for your effort 🤗

**Comment by idoshamun** [comment]
Done!

**Comment by duannx** [comment]
Hi @idoshamun, i have the issue too. Please help me with this. My email is xuanduannguyen@gmail.com. I want to keep the Google account

**Comment by idoshamun** [comment]
Hi @duannx,
I deleted your GitHub account :)

**Comment by duannx** [comment]
@idoshamun Thank you very much 😄

**Comment by linosorice** [comment]
@idoshamun I have the same problem. My email is lino.sorice@gmail.com and I want to keep the google account.

**Comment by idoshamun** [comment]
@linosorice that's done :)
