### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by invntiv** [dailydotdev/daily#349]
### What went wrong? 🤔
Account data seems to be corrupted; the article count is UNDEFINED and the devcard is no longer visible or able to be generated. Additionally, the age of my account is also incorrect. It's been set to November (probably set to today's date because today is when I implemented the GitHub Action that would pull the generated devcard SVG into my README.md profile)

[Imgur album link of the three seeemingly related bugs](https://imgur.com/a/l1Xh2Mr)

### Expected Behavior

I should be able to generate a dev card. My account creation date should be correct.

### Actual Behavior

Can't access dev card or rank.

### Steps to Reproduce Issue

Unknown, definitely related to GitHub Action. This is YAML file:
`
name: DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}`

#### Operating System

OSX Catalina 10.15.7

#### Browser

Chrome

**Comment by rebelchris** [comment]
Hi @invntiv thanks for reporting this!
Working to solve this ASAP

**Comment by rebelchris** [comment]
Hello @invntiv we just deployed a hotfix that solves this issue.
Please do let us know if there is anything else off 👏

Closing this for now.
