### ISSUE TITLE
🐛 BUG: Can't update my profile infos without changing my email ID

### ISSUE THREAD

**Issue by adoniasvitorio** [dailydotdev/daily#350]
### What went wrong? 🤔
When I try update my company Info I received Form Request "This email is already used"

### Expected Behavior
 I expect update only  my company info. 

### Actual Behavior
Not update my info and give bad messagem about my email.

### Steps to Reproduce Issue
1 - Click **Profile Settings**.
2 - Click **Account details**.
3 - Update my **Company Info**.
4 - Click **Save Changes**.

### Solution
I wold like to update my info

#### Operating System
Ubuntu 20.04.3 LTS
#### Browser
Chrome

**Comment by idoshamun** [comment]
Please send us an email to support at daily.dev with all the information and we will fix it.
We don't want you to share personal info here :)
