### ISSUE TITLE
🐛 BUG: account details saving problem

### ISSUE THREAD

**Issue by ariaieboy** [dailydotdev/daily#351]
### What went wrong? 🤔
Hi i want set my timezone in the account details but when i press the save button i'm seeing an error under email input that says "This email is already used"

### Expected Behavior
it must save the settings without any error

### Actual Behavior
its not saving anything and showing error

### Steps to Reproduce Issue
open account details with filled inputs change timezone and press Enter

#### Operating System
windows 11
#### Browser
chrome

**Comment by idoshamun** [comment]
Please try again now
