### ISSUE TITLE
🧩 FEATURE REQUEST: light theme & automatic mode

### ISSUE THREAD

**Issue by dmig** [dailydotdev/daily#354]
## Feature Request
Light and dark themes along with automatic switching become widely spread. I'd suggest implementing a new theme and a tri-state theme selector: auto-light-dark.

**Comment by nimrodkra** [comment]
Hi @dmig, thanks for submitting this feature request. We already support those three states (dark, light, and auto). Here's a link to the docs, explaining how to change your theme: https://docs.daily.dev/docs/settingyourfeed/customize-your-feed/theme

**Comment by dmig** [comment]
Sorry, now I remember why I chose dark... Automatic switching has never been working!

**Comment by chiptus** [comment]
Link isn't working, and can't find anywhere to choose light theme

**Comment by nimrodkra** [comment]
Hi Chaim, to switch to light theme click on the “Customize” button in the
left sidebar. Inside you can switch between dark/light/auto modes.

**Comment by nimrodkra** [comment]
Sure, on mobile as well. Click on the hamburger menu which is located left
to the daily.dev logo. Then the sidebar will open, scroll down and you
should be able to see the “Customize” section. Click on it and a modal will
open with the option to change a theme inside. Let me know if it worked [image:
🚀]

**Comment by chiptus** [comment]
Thanks, found it. Why isn't "auto" the default?

**Comment by nimrodkra** [comment]
Awesome! The reason is to have alignment between expectations of people
who see the product screenshots in the store or on our website (which is
showcased in dark mode) and the first experience of using the product. Auto
theme seems to be counterintuitive for the majority of our new users.
