### ISSUE TITLE
🐛 BUG: automatic light/dark theme switching is broken

### ISSUE THREAD

**Issue by dmig** [dailydotdev/daily#355]
## 🐛 Bug Report
Automatic light/dark theme never worked actually. When set to 'auto' it always set light theme.

### What went wrong? 🤔
No automatic theme switching.

### Expected Behavior
Dark theme set along with browser dark mode, as other sites do.

### Actual Behavior
Theme is always light

### Steps to Reproduce Issue
Set theme selector to 'auto', switch browser to dark mode either passing `--force-dark-mode` to chrome/chromium or switching it system-wide.

See the screenshot. On the right, there is devdocs.io set to auto, on the left -- daily.dev extension set to auto.

### Solution
None.

#### Operating System
Linux

#### Version of Daily
3.10.0

#### Browser
Google Chrome/Chromium 7x.xx-96.xx

![Screenshot from 2021-11-20 21-08-36](https://user-images.githubusercontent.com/388564/142740060-29044e40-a369-411d-a3b1-2be0aaed067e.png)

**Comment by idoshamun** [comment]
Hi @dmig,
Thanks for reporting this issue, we will do our best to fix this issue.

**Comment by sshanzel** [comment]
Hi @dmig, thank you for reaching out with your concern. I tried the theme functionality just now and it seemed to work very well. May I ask, do you have any apps installed that might be overriding your system settings?

My chrome version on the recording below: v95.0.4638.69


https://user-images.githubusercontent.com/13744167/142810934-b7d6add6-25a1-40ab-8545-80f68069bc97.mov

**Comment by dmig** [comment]
There is a bug in Linux Chrome with system-wide dark theme detection: https://bugs.chromium.org/p/chromium/issues/detail?id=998903. So I use `--force-dark-mode` to launch it with dark UI. Looks like I needed to add another option for the dark mode to work in extensions: `--enable-features=WebUIDarkMode`.

So, this is a Chrome bug rather than this extension. My apologies.
