### ISSUE TITLE
🐛 BUG: error saving account details

### ISSUE THREAD

**Issue by dmig** [dailydotdev/daily#356]
## 🐛 Bug Report
'This email is already used' error message instead of closing 'account settings' dialog.

### Steps to Reproduce Issue
1. Open 'Account Settings'
2. Press 'Save' button

#### Version of Daily
3.10.0

#### Browser
Google Chrome 96

![Screenshot from 2021-11-20 14-15-03](https://user-images.githubusercontent.com/388564/142740169-42be0bf7-a211-4388-bcf9-2bc8404e20ff.png)

**Comment by OlaoluwaM** [comment]
I also have this issue, but mine might be because I have logged in with both google and github. Is there a way to merge accounts or close one?

**Comment by idoshamun** [comment]
Hi @dmig,

I fixed this issue. It happens because we don't support merging two social accounts. Please confirm this works.

@OlaoluwaM please shot us an email at support at daily dot dev and we will be happy to assist.
