### ISSUE TITLE
🐛 BUG: wrong icons used for settings and sidebar

### ISSUE THREAD

**Issue by dmig** [dailydotdev/daily#357]
## 🐛 Bug Report
All UI guidelines advise to use _cog_, _toolbox_ or _sliders_ icon for opening application settings dialog. But not in daily.dev. It uses its own icon looking like a table. Which is totally confusing for unexpected behaviour.

Another problem is: daily.dev uses _cog_ icon for sidebar. Which is also confusing.

### Solution
- Use _cog_ icon for settings.
- Use special _sidebar_ or _filter_ (that what it actually is) icon for sidebar

#### Version of Daily
3.10.0

**Comment by idoshamun** [comment]
Hi @dmig,

I'll forward your concern to our design team and we will do our best to address it.
Anyway, we will change this layout pretty soon. Just giving you a hint 😉
