### ISSUE TITLE
🐛 BUG: daily.dev logo cannot be seen clearly when switched to dark default mode in github

### ISSUE THREAD

**Issue by Shubh28698** [dailydotdev/daily#359]
## 🐛 Bug Report

  

 What went wrong? 🤔
 When Switched to Dark mode in github, one cannot see daily.dev logo clearly. 
    
How did you expect it to behave?
It should be seen clearly in dark mode also.

Steps to Reproduce Issue:
1. Visit https://github.com/dailydotdev/daily.
2. Navigate to top of Readme.md section.
3. One cannot see the logo in dark mode there

Solution:
Logo with correct colour schemes might be able to resolve this issue

attaching screenshot for reference
![Issue](https://user-images.githubusercontent.com/39756589/142764689-79fcbc2a-b594-4512-9e48-3df4c4b335c8.PNG)

**Comment by idoshamun** [comment]
Hi @Shubh28698,

We will check how to address this issue. If you know how to support dark/light theme in markdown you are more than welcome to submit a PR :)

**Comment by idoshamun** [comment]
We added a background to the image, please confirm the fix

**Comment by Shubh28698** [comment]
Hi Ido,

The fix seems perfect!

Thank you!!

**Comment by Shubh28698** [comment]
I have checked it across all the themes and looks cool now
