### ISSUE TITLE
🐛 BUG: Unable to save Account Details ( Time Change - Email Validation blocking update)

### ISSUE THREAD

**Issue by DionneNoellaBarretto** [dailydotdev/daily#360]
## 🐛 Bug Report

**NOTE:** Similar issue was fixed few weeks ago https://github.com/dailydotdev/daily/issues/340 

### What went wrong? 🤔
Unable to 'Save Changes' for Account Details > update to timezone field
![image](https://user-images.githubusercontent.com/16610213/142768107-976fff22-8e7f-4af8-8a37-afdb78c3d0f6.png)
### Expected Behavior

Should I change a field / update a section in the Account Details pane , I should be able to click Save Changes 

### Actual Behavior

When I make updates the email address field validation check is blocking my ability to save changes

### Steps to Reproduce Issue

Navigate to Account Details from the top right corner and attempt to change any field ( in this case I tried to update my timezone) and then click Save Changes

#### Browser

All browsers on the desktop / mobile

**Comment by idoshamun** [comment]
This should be fixed now. Please confirm :)
