### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by Kvaibhav01** [dailydotdev/daily#365]
## 🐛 Bug Report

This is related to the sidebar:

<img width="429" alt="A screenshot showing the sidebar panel of the extension." src="https://user-images.githubusercontent.com/11731837/142825176-4236803d-b645-4084-9147-8f6b5e7e6772.png">

### Expected Behavior

1. When we click outside of the sidebar it should close. Currently, it's not closing and the only way to close is using the cog icon:

![A GIF showing the opening and closing of the sidebar.](https://user-images.githubusercontent.com/11731837/142825353-ffe72b2d-0a92-47c5-9f3a-ec30a3276c0b.gif)

2. The cog icon itself should change to a close (**✗**) icon when it's opened so that users know beforehand that this will be used to close. Currently, it stays like a cog ⚙️.

3. Also, we can also add a keyboard shortcut to close this panel when hitting the ESC key.

#### Version of Daily
3.10.0 (Extenstion)

#### Browser
Firefox Developer Edition (95.0b10)

**Comment by idoshamun** [comment]
Hi @Kvaibhav01,

Thanks a lot for the feedback, I'll raise it internally and let you know.
We're about to introduce something new anyway so stay tuned :)

**Comment by joshwcorbett** [comment]
I think the new sidebar design fixes this issue. Expanded/collapsed states don't need to feature a 'click outside to close' feature.

**Comment by idoshamun** [comment]
Yap, you're right. We do want to turn the feed filters user interface into a popup rather than a secondary sidebar. What do you think?

**Comment by joshwcorbett** [comment]
@idoshamun I think a popup is a little intrusive, perhaps the feed filters can replace sidebar content? And close when sidebar is closed or user hits save?

**Comment by idoshamun** [comment]
@joshwcorbett there's no save button actually so we don't know when you actually finish messing around with your filters.
We decided to create another sidebar on top of the existing one because we needed more space for some long tags and settings there on one hand, but on the other, we didn't the main sidebar to be this big. Just sharing some of our considerations.
