### ISSUE TITLE
🧩 FEATURE REQUEST: Add Cloudflare Blog to sources

### ISSUE THREAD

**Issue by RafidMuhymin** [dailydotdev/daily#368]
## Feature Request

Please add the [Cloudflare Blog](https://blog.cloudflare.com/) to the list of sources.

### Description

**Daily.dev** is missing a great and important source of blog posts on development, **The Cloudflare Blog**. Their blogs are so informative and also very important if you are interested in the workflow of Cloudflare. So, I think it'll be a good one to add. I tried to add it via the Suggest new source option but I think it only accepts RSS feeds.

**Comment by idoshamun** [comment]
Hi!

We have it already but I do see that it doesn't get updated. I'll check it.

https://app.daily.dev/sources/cloudflare

**Comment by RafidMuhymin** [comment]
@idoshamun Didn't know that you can read posts from a specific source like that!

**Comment by idoshamun** [comment]
I investigated further this issue and apparently, Cloudflare introduced a scraping blocker. This is why their recent posts are not being fetched by our bots. I'll keep you posted

**Comment by rebelchris** [comment]
@RafidMuhymin They are showing again, please let us know if anything else pops-up
