### ISSUE TITLE
🐛 BUG: Weird behaviour of the checkbox in rank pop-up (UI/UX issue)

### ISSUE THREAD

**Issue by Kvaibhav01** [dailydotdev/daily#371]
### What went wrong? 🤔

The rank pop-up which has an option to opt-out of it has some issues in the checkbox. Not working correctly I think.

### Expected Behavior

I expect that these issues to be fixed:

1. **UI/Accessibility issue**: When I click the checkbox, there should be enough _contrast_ between the checkmark (black #0f1217 color) and the filled blue color (#3255e4) of the background. Currently, it's **3.18** which barely passes the [WCAG 2 Level AA Large](https://www.w3.org/WAI/WCAG2AA-Conformance). I just did a quick fix to increase it to 5.17 which passes both WCAG 2 Level AA/AAA Large just by using the background color of the pop-up (#edf0f6):

<img width="169" alt="Pop-up checkmark fix for contrast" src="https://user-images.githubusercontent.com/11731837/144568223-b2f59468-cf9e-48a9-83d6-d83899ab8ef8.png">

It's a small fix but I think it can improve the accessibility.

2. **UX issue**: Here as you can see in the GIF below if we try to uncheck the checkbox, the hover-based icon (with just the check and no dark blue background) shows up and feels like it's still checked. **We have to click again outside the checkbox (somewhere on the pop-up background) to fully uncheck it**. This requires the users for an additional step. 

![GIF showing weird behaviour of the checkbox](https://user-images.githubusercontent.com/11731837/144569030-f245ab9b-d331-48f5-9466-f701453f5fe5.gif)

Maybe @tsahimatsliah can have a look at this. 

#### Version of Daily
Browser extension version 3.10.3

#### Browser
Firefox Developer Edition version 95.0b12

**Comment by idoshamun** [comment]
Hi @Kvaibhav01,

Thanks for yet another important issue!
I'll forward it to @tsahimatsliah and let you know :)

**Comment by tsahimatsliah** [comment]
@Kvaibhav01 , I always like your feedback and appreciate your time and effort to help us improve.

1. We know this issue already, and it is on our roadmap, 
We should fix it with other accessibility issues like our buttons' icon/text color.

2. The quick and easy way to fix it is to remove the icon from the unselected box. (Attached example)
I accept your feedback and add it to our tasks.

![image](https://user-images.githubusercontent.com/41912669/144840364-047307c9-2446-41cb-bb49-0fdca0e62a20.png)

**Comment by Kvaibhav01** [comment]
Yes, that looks much better! Thank you for accepting 🙌

**Comment by rebelchris** [comment]
@Kvaibhav01 Thanks for logging, this issue has been resolved.
