### ISSUE TITLE
🐛 BUG: cannot update profile (email already in use)

### ISSUE THREAD

**Issue by iamludal** [dailydotdev/daily#374]
### What went wrong? 🤔

When I want to update my profile information (here, my bio), I receive an error message telling me that the email is already in use (well, yes, by me...). By the way, I did not touch this field. I only changed the bio.

### Expected Behavior

My profile should be updated, and I shouldn't get this error message.

### Actual Behavior

I have an error message that tells me my email is already in use (yes, by me).

### Steps to Reproduce Issue

Navigate to your profile page, and try to update your bio.

### Solution

Ignore the email field for the route: `PUT https://api.daily.dev/v1/users/me`

#### Operating System

Linux (Ubuntu 21.04)

#### Version of Daily

3.10.3

#### Browser

Google Chrome 96.0.4664.45

**Comment by idoshamun** [comment]
Hi!

Please send us an email to support at daily.dev and we will resolve this issue for you.
It is happening due to a legacy issue with our authentication system. We will fix it soon.
