### ISSUE TITLE
Loading indicator on profile page

### ISSUE THREAD

**Issue by AnishDe12020** [dailydotdev/daily#377]
Loading the stats on the user's profile page often takes some time. There can be something like a loading indicator or a loading skeleton instead of a blank component

P.S. - I am willing to work on this

**Comment by idoshamun** [comment]
Hi @AnishDe12020,

Thanks for the suggestion.
Any specific components inside the profile page?

**Comment by AnishDe12020** [comment]
> Hi @AnishDe12020,
> 
> Thanks for the suggestion. Any specific components inside the profile page?

The posts section probably will be the one

**Comment by idoshamun** [comment]
Let me raise it internally and get back to you :)
