### ISSUE TITLE
🧩 FEATURE REQUEST: Add `action-devcard` to the README of this repo

### ISSUE THREAD

**Issue by omBratteng** [dailydotdev/daily#383]
## Feature Request

Add the https://github.com/dailydotdev/action-devcard repo to the list in this README, so people can discover it here as well.

**Comment by idoshamun** [comment]
Hi @omBratteng,

This is a great suggestion. You can go ahead and add it :)

**Comment by idoshamun** [comment]
Thanks @ankanbag101 for adding it to the readme :)

**Comment by omBratteng** [comment]
Awesome @ankanbag101, thanks!
