### ISSUE TITLE
Master Branch should be renamed to Main

### ISSUE THREAD

**Issue by InHuOfficial** [dailydotdev/daily#390]
As part of a review with Eddie Jaoude and Francesco Ciulla, Eddie suggested using the modern naming convention of "Main" instead of "Master" for the primary branch.

## Actions
Rename "Master" branch to "Main"

**Comment by blakecoding** [comment]
why? What are the advantages?

**Comment by idoshamun** [comment]
Hi @InHuOfficial,

Our newer repos already include this change but unfortunately, we didn't change the old repos that we created before "main". We will do it soon

**Comment by rebelchris** [comment]
@InHuOfficial I'm happy to say we moved the older branches to main now as well 🙏
