### ISSUE TITLE
🧩 FEATURE REQUEST: Livestream review suggestions

### ISSUE THREAD

**Issue by krshkodes** [dailydotdev/daily#391]
## Feature Request

- Use releases.
- Hide Packages

![image](https://user-images.githubusercontent.com/91655303/147256387-06c0dfad-6193-4a94-9cda-57cfc098d79d.png)

- Move the wiki to a docs folder

![image](https://user-images.githubusercontent.com/91655303/147256413-26fc99fe-96a1-4297-b1e4-4e01093fe819.png)

- Pull Request Template

- GitHub Actions CI

- Make the branch  `main`

### Description

Watch live stream recording here => https://www.youtube.com/watch?v=wQvlaYc5nl8

**Comment by eddiejaoude** [comment]
Some thoughts...

- using conventional commits which is awesome! So could create releases a GitHub Action with a change log https://github.com/EddieHubCommunity/LinkFree/releases
- Wiki to have a link to docs repo
- Maybe use `quickstart` in the getting started section

**Comment by idoshamun** [comment]
Hi @krishguptadev and @eddiejaoude,

Thanks for this feedback. I already applied some of it.
Decided to remove the wiki for now as it's not updated and the updated version is our docs.
As for the changelog we do have our manually written changelog here: changelog.daily.dev.
I'll follow up with the rest later on. Thanks a lot :)

**Comment by eddiejaoude** [comment]
Awesome! Great to hear! Have a great festive season and a wonderful 2022, hopefully with lots more geeking out and collabs!
