### ISSUE TITLE
🐛 BUG: Can't sign in

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [dailydotdev/daily#394]
### What went wrong? 🤔

Can't SignIn.

### Expected Behavior
I should be able to signIn

### Steps to Reproduce Issue

https://user-images.githubusercontent.com/14947957/147358679-077a527d-d79d-4e1d-b827-f38f1cef890c.mp4

#### Browser
Chrome

**Comment by idoshamun** [comment]
The issue is caused because you registered with the same email address with two different accounts.
Please use your GitHub account, it should work now.

**Comment by mohamedGamalAbuGalala** [comment]
Confirmed 🙌🏼
