### ISSUE TITLE
🐛 BUG: Opens upvoted page as default page

### ISSUE THREAD

**Issue by RajvirSingh1313** [dailydotdev/daily#399]
## 🐛 Bug Report
![image](https://user-images.githubusercontent.com/63385587/147577731-4d9d5055-b1a2-44a0-9e8c-71c960d6c1bb.png)

It is not a bug, but it seems like it. Whenever a new tab is opened, the app shows upvoted as the default page but the sidebar shows popular as the current page. When I click on the popular page from the sidebar then it opens the popular page. I think there is good amount of chance that I am the only who is getting this issue

### Expected Behavior
Sidebar and opened page in sync and having popular page opened every time new tab is opened.

### Actual Behavior
The sidebar and opened page are not in sync.

### Steps to Reproduce Issue
Open a new tab, see at the sidebar and at the currently opened page.

### Solution
I think this can be converted into a feature, by providing an option for having a default page. It would be easier.

### Environment
Ubuntu 20.04

#### Operating System
Linux - Ubuntu

#### Version of Daily
3.11.1

#### Browser
Chrome

**Comment by idoshamun** [comment]
Hi @RajvirSingh1313,

We will look into it :)

**Comment by RajvirSingh1313** [comment]
Thanks alot

**Comment by RajvirSingh1313** [comment]
@idoshamun It is solved, I just reinstalled the extension and it is working fine now. But I think it would be good if you can add the default page option to the settings. Let me know what you think, as it is not easy to make a change in a large project. So I would like to know your opinions on this. I am going to close this issue, you can answer me (when you will be free) on this discussion https://github.com/dailydotdev/daily/discussions/370

**Comment by rebelchris** [comment]
Hi @RajvirSingh1313,

We are actually pushing a new version out as we speak.
This version will solve the default feed to which ever feed you visited last.

Keep an eye out for this update.
And again thanks a lot for logging the issue 🙌

**Comment by RajvirSingh1313** [comment]
@rebelchris Yeah Sure!, thanks for adding it
