### ISSUE TITLE
Duplicate post in feed

### ISSUE THREAD

**Issue by iamsajithk** [dailydotdev/daily#403]
![image](https://user-images.githubusercontent.com/11171512/147415202-22710aa6-a39e-4761-ad57-bc8b039bf889.png)

**Comment by idoshamun** [comment]
Hi @iamsajithk,

Thanks for the report. I'll try to find the root cause

**Comment by rebelchris** [comment]
Hi @iamsajithk thanks again for logging this.
We updated our database to no longer allow duplicate content, and the way we handle our import.

You should not see them anymore, but please feel free to log it, if this does happen again.

**Comment by iamsajithk** [comment]
Hi @rebelchris 
I have found one another today. Attaching the screen recording below.
[Screen Recording](https://youtu.be/a1xs9-uG3Ig)

**Comment by rebelchris** [comment]
@iamsajithk thanks a lot for this screen recording, that helps a lot.
Looks like the feed can still show duplicate items, we are looking into this issue

**Comment by rebelchris** [comment]
Duplicate ticket existing keeping conversation there:
https://github.com/dailydotdev/daily/issues/403
