### ISSUE TITLE
When you register and you click on the finish button, there is no redirection to the home page

### ISSUE THREAD

**Issue by datscyril** [dailydotdev/daily#405]

**Comment by sshanzel** [comment]
Hi! Hope you are doing well. Just wanted to check, were you successful with your registration? We have tried both on webapp and extension to register new users but it seems to redirect us on the right page.

If in time we'll be able to reproduce the case, we will definitely fix it and let you know about it. Thank you!

**Comment by datscyril** [comment]
Hi! Happy new Year ! The registration was successful yes. It can be my browsers extensions, I'll check it out and let you know! 

I really appreciate your job guys keep going 👏
