### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by chrishrtmn** [dailydotdev/daily#41]
#### Feature Suggestion

I use Safari for Mac as my primary browser and love this extension on Brave/Chrome - any plans for an extension for Safari?

**Comment by idoshamun** [comment]
Hi @chrishrtmn,

Thanks for reaching out!
I remember myself checking the possibility of building a Safari extension but something blocked us from proceeding down this path.
Maybe I have to check again, stay tuned :)

**Comment by idoshamun** [comment]
Now that Daily is open source, anyone can contribute.
Would you like to give it a try? We will support you and help you design the solution.

**Comment by L-Clem** [comment]
Can't the new support for the _WebExtension API_ by _MacOS Big Sur_, be of any help ?
[Quoting APPLE](https://developer.apple.com/macos/) :
> Safari Extensions
With support for the popular WebExtension API, it’s even easier to bring powerful extensions to Safari. Xcode 12 even includes a porting tool to streamline the process.
The new Extensions category on the Mac App Store showcases Safari extensions, with editorial spotlights and top charts to help users discover and download great extensions from the developer community.

<br>
Even so, thanks a lot for this great extension that you are providing us.

**Comment by idoshamun** [comment]
This is big news, honestly.
I tried yesterday to convert daily.dev using their automated tool but some features are still lacking.
Authentication doesn't work at all and the sidebar doesn't open.
I didn't try to fix or investigate further these issues as I have no time currently, hopefully as Safari's Web Extension support will evolve it will be easier.
I will keep my eyes and ears open as it's important for us as well to deliver a Safari version.
In addition, there's no plan as far as I understand, to support the new tab functionality. 
So anyway, it's going to be just a button in the browser and not the full experience.

**Comment by L-Clem** [comment]
> Now that Daily is open source, anyone can contribute.
> 
> Would you like to give it a try? We will support you and help you design the solution.

@idoshamun I'm not very well versed in building extensions but I will try to convert daily.dev extension in a Safari one with the tools that Apple puts at our disposal in xCode. If it is conclusive I will open a pull-request.

**Comment by L-Clem** [comment]
> This is big news, honestly.
> 
> I tried yesterday to convert daily.dev using their automated tool but some features are still lacking.
> 
> Authentication doesn't work at all and the sidebar doesn't open.
> 
> I didn't try to fix or investigate further these issues as I have no time currently, hopefully as Safari's Web Extension support will evolve it will be easier.
> 
> I will keep my eyes and ears open as it's important for us as well to deliver a Safari version.
> 
> In addition, there's no plan as far as I understand, to support the new tab functionality. 
> 
> So anyway, it's going to be just a button in the browser and not the full experience.

Normally there is a way to make Safari open the extension as the default new tab. If I had more knowledge I would have loved doing it for this extension. Maybe I will try it to see if I can do something (and learn from doing it btw).

**Comment by idoshamun** [comment]
@L-Clem let me know if you have any progress. Thanks :)

**Comment by wtrungvu** [comment]
I really want this extension to be used on safari

**Comment by idoshamun** [comment]
Our web version is a few weeks away!
You will be able to use it on Safari and every other browser.

**Comment by idoshamun** [comment]
There's a beta version of the webapp which already includes our feed.
https://app.daily.dev/
I'm closing this issue as there is no plan to add a Safari extension, now that there's a web version.
We will slowly roll out all the features.

**Comment by forybm** [comment]
Recently, I changed my web browser from chrome to safari.
Most of them are satisfied, but I was sad that the daily.dev was not supported.
However, thanks to the recently launched web version, it has been solved a lot.

Thank you 😄
