### ISSUE TITLE
🧩 FEATURE REQUEST: Add recent tab in sidebar

### ISSUE THREAD

**Issue by avneesh0612** [dailydotdev/daily#410]
## Feature Request
Add a recent tab in the sidebar

### Description
https://app.daily.dev/recent works but there isn't any link for it in the sidebar.

### Solution
Add an icon like a clock that links to recent posts page.

**Comment by idoshamun** [comment]
Hi @avneesh0612,

We're planning the return of the recent feed very soon.
It'll be quite a different implementation of what it used to be but stay tune :)

**Comment by avneesh0612** [comment]
okay cool!

**Comment by mrevjd** [comment]
> ## Feature Request
> Add a recent tab in the sidebar
> 
> ### Description
> https://app.daily.dev/recent works but there isn't any link for it in the sidebar.
> 
> ### Solution
> Add an icon like a clock that links to recent posts page.

https://app.daily.dev/recent now no longer works. Very disappointing.

**Comment by idoshamun** [comment]
@mrevjd you can keep track here:
https://github.com/dailydotdev/apps/pull/822
The PR is ready will probably get merged tomorrow

**Comment by nimrodkra** [comment]
@avneesh0612 The change is live: https://app.daily.dev/posts/e-dQ6UyIA

**Comment by avneesh0612** [comment]
just saw it, awsm!
