### ISSUE TITLE
🧩 FEATURE REQUEST: Option to edit frequently visited sites bar.

### ISSUE THREAD

**Issue by BudhirajaMadhav** [dailydotdev/daily#412]
### Description

I would like if I could remove or add any site manually from/to the most  frequently visited sites bar.
![image](https://user-images.githubusercontent.com/73742540/148599243-f0ee7524-3e14-45eb-8c1c-d6c00b655290.png)

### Solution

I haven't gone through the code but suppose it must have been implemented by LFU Cache, if it's that writing fns to delete from hashmap and DLL would work.
Looking forward to discussion in comments.

Like this: 
![image](https://user-images.githubusercontent.com/73742540/148599337-53542712-daf4-4964-b093-9a7fd833ab55.png)

**Comment by idoshamun** [comment]
Hi @BudhirajaMadhav,

Thanks for the suggestion. It's already on our roadmap, I can't commit to a specific timeline but stay tuned :)

**Comment by BudhirajaMadhav** [comment]
Okay :D

**Comment by nimrodkra** [comment]
@BudhirajaMadhav the `Custom link` feature is ready! 
Check it out here: https://app.daily.dev/posts/rIZ_uqa1Q
