### ISSUE TITLE
🐛 BUG: Adding a redirect to https://api.daily.dev/

### ISSUE THREAD

**Issue by BudhirajaMadhav** [dailydotdev/daily#413]
### What went wrong? 🤔

I manually opened [api.daily.dev](https://api.daily.dev) and it showed this 
![image](https://user-images.githubusercontent.com/73742540/148600270-33a3f4a3-c90b-4f07-8503-0e6cd2a10c68.png)

### Expected Behavior

It doesn't look good if the main `/` route of any site is showing this, I would request if you could add a redirect here. A quick thing to be done ofcourse.

**Comment by BudhirajaMadhav** [comment]
Can I be assigned?

**Comment by idoshamun** [comment]
Hi @BudhirajaMadhav,

Sure! That's a great idea. The best place to implement it is our [daily-gateway](https://github.com/dailydotdev/daily-gateway) repo.
We want to redirect to `https://daily.dev` in case someone visits directly `https://api.daily.dev`.
Let me know if you need any guidance.

**Comment by BudhirajaMadhav** [comment]
Should I make an issue there, or Can this one be transferred?

**Comment by idoshamun** [comment]
No need to transfer. We centralize all issues here. You can start if you
want 😃

**Comment by BudhirajaMadhav** [comment]
- https://github.com/dailydotdev/daily-gateway/pull/405 Merged
