### ISSUE TITLE
🐛 BUG: weird behavior of home tab sometimes

### ISSUE THREAD

**Issue by arpitdalal** [dailydotdev/daily#418]
## 🐛 Bug Report

Seeing posts on top of each other on the home tab in pwa sometimes.

### What went wrong? 🤔
Stacked posts on top of each other on the home tab in pwa
![Screenshot_20220109-112950.jpg](https://user-images.githubusercontent.com/61059807/148691743-f4f10a7f-8825-4d13-8767-d2b775dcca48.jpg)

### Expected Behavior
Posts not stacked on top of each other

### Actual Behavior
Posts stacked on top of each other

### Steps to Reproduce Issue
I have seen that this usually happens after the weekly goal popup/modal.

### Solution
I haven't had a chance to look at code yet.

### Environment
Pwa installed on Android 11/Oxygen OS 11

#### Operating System
Android 11/Oxygen OS 11

#### Version of Daily
Version 1 (from play store as I couldn't find a version number in the pwa itself)

#### Browser
Pwa runs on Firefox mobile v95.2.0 (Build #2015851755)

**Comment by idoshamun** [comment]
Oppsss this probably happens due to our virtual grid library.
We will have to check it.

**Comment by rebelchris** [comment]
@arpitdalal Great news 🥳
We changed the way our feed is loaded so this shouldn't occur anymore.
Closing the ticket, feel free to test it out and happy to hear what you think
