### ISSUE TITLE
🐛 BUG: We can add a blank comment

### ISSUE THREAD

**Issue by Posandu** [dailydotdev/daily#422]
### What went wrong? 🤔

Type a blank space in the comment field and post it.

### Expected Behavior

Show an error message

### Actual Behavior

The comment posts with a blank

### Steps to Reproduce Issue

Go to a post
Press space key
Press enter key

### Solution

This JS snippet can be used

```javascript
String.prototype.isEmpty = function() {
    // This doesn't work the same way as the isEmpty function used 
    // in the first example, it will return true for strings containing only whitespace
    return (this.length === 0 || !this.trim());
};
"example".isEmpty() // false
"    ".isEmpty() //true
```

#### Operating System
Windows

#### Version of Daily 
Latest

#### Browser
Chrome

**Comment by idoshamun** [comment]
Oh thank you very much for this discovery, @Posandu.
We will fix it :)

**Comment by sshanzel** [comment]
Hi @Posandu, thank you for reporting! This should now be fixed by our latest update 🚢 

Relevant PR: https://github.com/dailydotdev/apps/pull/829
