### ISSUE TITLE
Error loading PWA on iPad

### ISSUE THREAD

**Issue by tcampbPPU** [dailydotdev/daily#425]
Recently I have been unable to use the daily.dev PWA application on my iPad, the same issue does not appear to be happening on my iPhone, where I am logged into the same account. The is the error I am seeing below:
![image](https://user-images.githubusercontent.com/25044744/149639971-08e199a2-96a0-4d33-ba5f-46beac52e74d.png)

Willing to provide more info if needed

Thanks!

**Comment by idoshamun** [comment]
Hi @tcampbPPU,

We will try to reproduce this issue and let you know.
Thanks a lot for reporting this.

**Comment by rebelchris** [comment]
@tcampbPPU Hi there, and thanks for logging this issue.
Would you mind updating to the latest version: `v3.13.0` and see if that solves it?

Closing this for now, but feel free to open it if it's not solved for you.

**Comment by tcampbPPU** [comment]
Looks like issue has been resolved as it's working as expected again 👍
