### ISSUE TITLE
🐛 BUG: News Not Sorting By Published Date Anymore!?

### ISSUE THREAD

**Issue by ldobreira** [dailydotdev/daily#427]
### What went wrong? 🤔
Before the latest update, the browser extension (Firefox) was working great, but now for some reason, the browser extension is not listing the latest news by published date anymore. My feed is showing random news from 10 days ago. The menu offers  Popular news, Most upvoted, Best discussions and that's it, there is no latest news. I'm I missing something? Docs talk about a "Sort by date" menu, but I don't have it... The "Show feed sorting menu" is not available on the customize menu.

### Expected Behavior

Before the news was sorted by published date. And that was great, fresh, and recent news. Now is just random stuff... I'm getting content from Oct 27 2021 and other random dates, instead of getting recent news like before.

### Actual Behavior

My feed is showing random news from 10 days ago. The menu offers Popular news, Most upvoted, Best discussions and that's it, there is no latest news. And no, the "Show feed sorting menu" is not available on the customize menu.

#### Operating System

Windows 10

#### Version of Daily

3.12.0

#### Browser

PC, Firefox 96.0.1 (64-bit)

**Comment by idoshamun** [comment]
Hi @ldobreira,

Please update to version 3.13.0 and you will get the new sorting option in the customize menu :)
We should indicate the minimum version for every feature so it will be more clear.
