### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by Anshuman71** [dailydotdev/daily#431]
### What went wrong? 🤔

When I try to add my website link, it gives me an error that the email exists.

### Expected Behavior
Allow me to add a website link

### Actual Behavior
Doesn't let me save information because the email field gives an error.

#### Operating System
Linux

#### Browser
Chrome

**Comment by Anshuman71** [comment]
![image](https://user-images.githubusercontent.com/28081510/150143026-6ac71e5b-af64-4fb2-a5ca-6bae41d537e6.png)

**Comment by rebelchris** [comment]
@idoshamun are you able to solve the login for anshu5074@gmail.com?

**Comment by idoshamun** [comment]
@Anshuman71 it should work now.
Thanks @rebelchris!

**Comment by Anshuman71** [comment]
thanks @idoshamun
