### ISSUE TITLE
🐛 BUG: Feed Sorting Always Changes Back To "Recommended"

### ISSUE THREAD

**Issue by ldobreira** [dailydotdev/daily#433]
### What went wrong? 🤔

I just want to get my feed sorted by date, unfortunately, the sort always changes back to "Recommended" after a refresh or new tab.

### Expected Behavior

I just want to get my feed sorted by date every time. 

### Actual Behavior

The sort always changes back to "Recommended" after a refresh or new tab.

#### Operating System

Windows 10

#### Version of Daily

3.13.0

#### Browser

Firefox 96.0.1 (64-bit)

**Comment by rebelchris** [comment]
Hi @ldobreira thank you for filing this request.
We didn't plan the function like this, but are working on deploying it in the next release as a lot of people would like to see it like this.

Will keep you posted on when you can upgrade.

**Comment by ldobreira** [comment]
Thank you so much @rebelchris

**Comment by rebelchris** [comment]
Great news @ldobreira if you update to V3.13.1 you'll be able to persist your choice.

Closing this ticket for now.
