### ISSUE TITLE
🐛 BUG: Reps less than upvotes

### ISSUE THREAD

**Issue by avneesh0612** [dailydotdev/daily#442]
### What went wrong? 🤔

The number of reps is less than the number of upvotes on posts. Although reps = upvotes on posts + comments.

![image](https://user-images.githubusercontent.com/76690419/151097341-35fd5353-26ca-4ff3-93be-f62db639bf7a.png)
https://app.daily.dev/avneesh0612

### Expected Behavior

I expect the reps to be more or equal to the number of upvotes on post.

#### Operating System

Windows 11

#### Version of Daily

Latest

#### Browser
Brave (Chromium based)

**Comment by kr-anurag** [comment]
yep, im facing this issue too

**Comment by AnishDe12020** [comment]
Same problem here

**Comment by idoshamun** [comment]
When we attribute articles retroactively we don't add the reputation retrospectively as well. You will get the reputation only from the day we confirmed your account and attributed the articles. I hope this makes sense.

**Comment by avneesh0612** [comment]
Oh ok
