### ISSUE TITLE
🧩 FEATURE REQUEST: Make a daily.dev mobile app

### ISSUE THREAD

**Issue by RainboeStrykr** [dailydotdev/daily#443]
## Feature Request

Make a mobile app for Android and IOS

### Description

I would like to have a daily.dev mobile app as there is lack of developer focused news app on the market and this could give rise to a kind of social media for writers whose posts get featured.

### Solution

A simple app that can be downloaded from Play Store or App Store

### Alternate Solutions

Tried using different news feed apps like Flipboard but there is no dev-focused news in any of these companies' products

**Comment by rebelchris** [comment]
Hi @RainboeStrykr we do have a PWA that you can already use.
You can find all the information around it here: https://docs.daily.dev/docs/getting-started/pwa
