### ISSUE TITLE
Suggest a new source link not found

### ISSUE THREAD

**Issue by gouravkhunger** [dailydotdev/daily#444]
Hi daily.dev team,

I wanted to suggest a new content source. [In the docs](https://docs.daily.dev/docs/for-content-creators/suggest-new-source#submitting-your-source), it's suggested to use "Suggest new source" button on the sidebar. But I don't see any such button:

<img src="https://i.ibb.co/VTsVwpR/image.png" height="500" />

Maybe because the sidebar changed some time ago and docs weren't updated. How to suggest a new source now?

**Comment by rebelchris** [comment]
Hi @gouravkhunger we are updating the docs as we speak.
You can find it by clicking on the Feed Filter icon (right from the My Feed button)

![Screenshot 2022-01-26 at 08 55 58](https://user-images.githubusercontent.com/554874/151117005-c701409d-fede-4c20-98b5-40fc7be791de.png)

We'll let you know once the docs are up to date again 🙏

**Comment by gouravkhunger** [comment]
Thanks @rebelchris. Submitted @genicsblog 🎉
