### ISSUE TITLE
🐛 BUG: Registration process fails on Setup your profile page for Google Oauth flow.

### ISSUE THREAD

**Issue by AkashKumarVerma** [dailydotdev/daily#448]
### What went wrong? 🤔
Registering through google OAuth in Firefox is stuck at `Set your profile` page
![Screenshot](https://user-images.githubusercontent.com/6884951/151293698-8ed0765a-512b-4177-997d-d067dc36d1db.png)

### Expected Behavior
Registration should complete

### Actual Behavior
Pressing Finish button does nothing.

### Steps to Reproduce Issue
Register using Google OAuth in Firefox

#### Operating System
Window 11

#### Version of Daily
3.13.1

#### Browser
Firefox - 96.0.2

Please let me know if any additional details are required.

**Comment by idoshamun** [comment]
This can be fixed manually please send us the email you used for the registration and we will fix it.
Email to support at daily.dev.
Thanks!
