### ISSUE TITLE
🧩 FEATURE REQUEST: Sticky sort menu

### ISSUE THREAD

**Issue by alekskimeu** [dailydotdev/daily#449]
### Description

Great that now we can sort articles by Date and Recommended. However, it's kinda difficult to sort or switch your sort preference when you've already scrolled down the page because the sort menu gets hid as one scrolls down. I'm aware that there is a 'Back to top' link but I feel making this sort menu always visible is somehow user friendly.

I would be great if this menu stayed fixed at the top to allow for ease selection no matter where one is on the page.

### Solution

Make the sort menu stick at the top on page scroll just like the logo and the profile link.

**Comment by rebelchris** [comment]
Hi @alekskimeu thanks for this wonderful idea.
would you mind adding this under the Discussion session?

**Comment by alekskimeu** [comment]
Sure @rebelchris
