### ISSUE TITLE
🐛 BUG: Block a tag not working

### ISSUE THREAD

**Issue by naptestdev** [dailydotdev/daily#461]
### What went wrong? 🤔

![image](https://user-images.githubusercontent.com/88878684/152988593-0b907c84-38b5-46be-a3a7-779c726b695d.png)
I tried to block the # php tag but it didn't work, even if I refresh the page. The php content still show up.

### Solution

Maybe u should check the filtering problem in your code

#### Operating System
MacOS Big Bur 11.6

#### Version of Daily
I use the main website app.daily.dev

#### Browser
Chrome 98 (latest)
I'm using mac, not on mobile device

**Comment by rebelchris** [comment]
Hi @naptestdev are you blocking the tag on the my-feed page?
This is the only feed where this is effective at the moment.

I'll ask the docs team to update our documentation on this.
Which you can find here:
https://docs.daily.dev/docs/settingyourfeed/blocking-tags-sources
