### ISSUE TITLE
"Bookmark" button on "Reading history" items

### ISSUE THREAD

**Issue by selique** [dailydotdev/daily#464]
### Discussed in https://github.com/dailydotdev/daily/discussions/463

<div type='discussions-op-text'>

<sup>Originally posted by **selique** February  9, 2022</sup>
is so useful if have the feature "Save Bookmark Item" on page "Reading History" for more easily management of items without the need to enter on items details </div>

**Comment by rebelchris** [comment]
Hi @selique great request and we are actually currently working on that 👀

Will update it here if it's live 🥳

Sneak peak: 
![Screenshot 2022-02-09 at 09 03 01](https://user-images.githubusercontent.com/554874/153138977-6549d8fc-2500-43d5-b5be-6dc581062005.png)

**Comment by rebelchris** [comment]
@selique Totally forgot to respond but this is live
