### ISSUE TITLE
🐛 BUG: Daily is showing an infinite number of errors in Chrome console.

### ISSUE THREAD

**Issue by moeen-mahmud** [dailydotdev/daily#466]
### What went wrong? 🤔

Today, like the other days, I was working on an official project, and during my break time, I grabbed a coffee and started to read some articles from my _favourite_ extension. After a while, I noticed my chrome console counted a tremendous amount of errors. I was surprised and reloaded the **"new tab"**, and then this 👇🏻  happened.

![DailyDevIsBreaking](https://user-images.githubusercontent.com/61315959/153581299-4ff6d06d-5b16-4095-98dd-5d6a65860318.gif)

**Note:** I re-install the extension but did not resolve the problem. I cleared my browser cache and everything else that I thought would solve, but nothing happened. 

### Expected Behavior

As I said, I'm a regular user of this extension and never saw anything like that.

### Actual Behavior

NA

### Steps to Reproduce Issue

NA

### Solution

NA

#### Operating System

Windows 11 

#### Version of Daily

3.15.2

#### Browser
Chrome

**Comment by idoshamun** [comment]
Hi @moeen-mahmud,

It seems to work now. Can you confirm?
Might be a temporary with Cloudinary or your internet connection

**Comment by moeen-mahmud** [comment]
Hello @idoshamun 

Thanks for the reply.
My internet connection was all right then.
But, just now, I reinstalled it again. Fortunately, it works as expected!
