### ISSUE TITLE
🐛 BUG: Application error on client side

### ISSUE THREAD

**Issue by Rahul664** [dailydotdev/daily#467]
### What went wrong? 🤔
I receive this error message on chrome, safari when i try to open the extension "Application error: a client-side exception has occurred (see the browser console for more information)."  Is this extension issue or just in my case. I am using chrome on Mac M1 pro.

To be specific this thing happens only when I log into my github account and if i am not logged in i do not have any issues

 
<img width="1728" alt="Screen Shot 2022-02-13 at 10 50 54 AM" src="https://user-images.githubusercontent.com/22545253/153771034-0a65a2e3-8785-4fb4-951b-23ce8aca0e0e.png">

**Comment by rebelchris** [comment]
Hi @Rahul664 thanks for logging this issue, we are on it and will let you know once we have fixed it.

**Comment by idoshamun** [comment]
@Rahul664 can you share a print screen with the console open, please? It would be helpful for us to debug the issue

**Comment by Rahul664** [comment]
> Hi @Rahul664 thanks for logging this issue, we are on it and will let you know once we have fixed it.

Hi @rebelchris. Yes, here it is.

I tried fixing by following the console output but this issue is across all the devices phone, linux and windows.
This happens only when I log in through my Github account. If I am not logged in the extension works fine.

<img width="1728" alt="Screen Shot 2022-02-13 at 9 44 08 PM" src="https://user-images.githubusercontent.com/22545253/153806912-f2c1a592-2262-4fc2-a420-be6e2c2e2313.png">

**Comment by rebelchris** [comment]
@Rahul664 Thanks a lot for this screenshot.
We have just published a fix that would solve this.

Could you let us know if it works for you now?
