### ISSUE TITLE
🐛 BUG: Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by Rahul664** [dailydotdev/daily#479]
### What went wrong? 🤔
This is the same issue I faced 2 days ago. Whenever i log in to Github account I face this issue.

<img width="1728" alt="Screen Shot 2022-02-16 at 8 29 26 AM" src="https://user-images.githubusercontent.com/22545253/154311044-6a0adf10-ef4c-410c-a83a-66dbafc630fa.png">

**Comment by Rahul664** [comment]
Hi @rebelchris, yes the extension is working fine now. Thank you the quick fix.

**Comment by rebelchris** [comment]
@Rahul664 Glad to hear, it seems to be very hard to determine, are you perhaps ok with us reaching out to test something in the near future?

Feel free to decline, but would love you to test the fix out next time 🙏

**Comment by Rahul664** [comment]
Hi @rebelchris I will be happy to be part of your testing to fix the issue. You can reach me @ rahulhoskeri7@gmail.com.
