### ISSUE TITLE
🐛 BUG: 2x Daily Progress in a day

### ISSUE THREAD

**Issue by joshwcorbett** [dailydotdev/daily#482]
### What went wrong? 🤔

I have multiple computers I work from, both with Chrome as my preferred browser of choice and the daily.dev extension installed and signed in on the same account. I've found that by opening an article listed on daily dev both from at home and at work on the same day, I can earn 2x the progress towards my reading status.

### Expected Behavior

I expected for the extension to keep track of if my account has already read an article today, and not reward me a +1 if an article has already been read.

### Actual Behavior

I get a +1 toward my reading progress on my work computer, and upon returning home and opening an article from the extension... I receive another +1, doubling my daily reading status. This has made keeping legendary status that much easier lol.

### Steps to Reproduce Issue

I assume it shouldn't work too much differently to reproduce. Sign in to the same daily dev account on two different computers and open an article at a different time of day. I typically have a gap of 6 hours between opening at work and at home.

### Solution

Maybe this is on purpose, maybe it isn't, maybe there's not supposed to be a solution... I don't know enough about the intricacies of this extension, but double rewarding throughout the day I think should be fixed by tying some kind of `readArticleToday` boolean on the account and updating it to true if an article is opened.

### Environment

I have an intel iMac at work, and an m1 mac mini at home both running the latest version of Chrome.

#### Operating System

MacOS 12.2.1

#### Version of Daily

Whichever version got the profile facelift

#### Browser

Chrome 98

**Comment by idoshamun** [comment]
Hi @joshwcorbett,

We're aware of this situation. It happens due to a timezone issue we have in the calculation (devs hate timezones for a reason, huh?).
@rebelchris and I are actively working on it, hopefully, we will resolve it soon.

**Comment by rebelchris** [comment]
@joshwcorbett Pretty sure this has been resolved.
Please feel free to open a new ticket if it still applies.
