### ISSUE TITLE
🧩 FEATURE REQUEST: Martin Flower articles as a data source

### ISSUE THREAD

**Issue by ilan-pinto** [dailydotdev/daily#488]
## Feature Request

Add Martin Flower articles as a data source

### Description

Generally, it would be nice to have some design and software engineering Architecture articles and blogs 
Currently feels that most of the articles relate to front-end development

**Comment by idoshamun** [comment]
@ilan-pinto indeed Martin Fowler's awesome blog is already on our list. You can see it here:
https://app.daily.dev/sources/mafo
At this point most of our users care about web development, this is why by default you will see more of this.
I highly suggest filtering your feed to suit your needs so we can surface better content for you.
Have a look here:
https://docs.daily.dev/docs/settingyourfeed/filtering-content-feed
Let me know if I can help :)
