### ISSUE TITLE
Attribute id redefined

### ISSUE THREAD

**Issue by 0x11DFE** [dailydotdev/daily#491]
My devcard is not working. https://raw.githubusercontent.com/0x11DFE/0x11DFE/devcard/devcard.svg

**Comment by idoshamun** [comment]
I transferred the issue to the other repo as suggested by @omBratteng

**Comment by idoshamun** [comment]
Should be fixed now. Please run the Action again

**Comment by 0x11DFE** [comment]
> Should be fixed now. Please run the Action again

Yes it is !
