### ISSUE TITLE
🐛 BUG: Flicker page when close account settings

### ISSUE THREAD

**Issue by tcelestino** [dailydotdev/daily#497]
### What went wrong? 🤔

I've signed up using my GitHub's account, I was redirected to "Set up your profile" page. I closed this page and I was redirected to "Reading History" page. It happened:

![Screen Recording 2022-03-10 at 06 47 28](https://user-images.githubusercontent.com/190265/157637094-10a230e8-fee1-43d4-8f2b-5bf2ec19cfe6.gif)

### Expected Behavior

Not see flicker when account settings is closed after sign up

### Actual Behavior

All  pages are flicker

### Steps to Reproduce Issue

- Sign up using GitHub's account
- Close set up profile page

### Solution

I don't know 😞 

### Environment

Macbook Air M1 running in the latest version Firefox

#### Operating System

macOS Monterey 12.2.1 

#### Version of Daily

3.15.4

#### Browser

Firefox 98

**Comment by rebelchris** [comment]
Hi @tcelestino thanks for logging this, it does indeed seem like a bug!
I'll log this as such with the team and we'll find a fix for it.

**Comment by rebelchris** [comment]
We changed the entire login process and thus this is outdated.
