### ISSUE TITLE
🐛 BUG: Weekly Goal Filter Broke page when filter by year

### ISSUE THREAD

**Issue by mnzsss** [dailydotdev/daily#501]
### What went wrong? 🤔

When I will filter my weekly goal the pages cash using 2021

![Screenshot_20220311_114610](https://user-images.githubusercontent.com/51327920/157889907-9f97fc48-9e9c-4190-b365-b592db2f3a39.png)

![Screenshot_20220311_114638](https://user-images.githubusercontent.com/51327920/157889978-62b5e6aa-8dd9-406e-93e2-ce9c1e23247f.png)

## Solution

Maybe u should check the filtering problem in your code

### Environment

I'm using Brave (Version 1.36.111 Chromium: 99.0.4844.51 (Official Build) (64-bit))
Running in Ubuntu 20.01

**Comment by rebelchris** [comment]
@mnzsss Thanks a lot for bringing this to our attention.
We'll start working on this as soon as possible, we must have missed something there.

Will keep you posted here as too when this is fixed.

**Comment by nilooy** [comment]
I couldn't reproduce the issue. it works fine on my end.

https://user-images.githubusercontent.com/32486682/160020022-0371af2c-c0aa-43c9-9e19-287a871ade87.mov

**Comment by mnzsss** [comment]
This problem still taking place

![Peek 2022-03-24 23-07](https://user-images.githubusercontent.com/51327920/160040544-da911635-ab99-4ec0-b8f4-4a1b679c6aed.gif)

**Comment by sshanzel** [comment]
@mnzsss at what timezone you are currently at right now? I'll try to replicate everything with regards to setup and see why it is happening.

I have the same case with @nilooy - I went to your profile and started filtering but all seems to work as intended.

**Comment by mnzsss** [comment]
> @mnzsss at what timezone you are currently at right now? I'll try to replicate everything with regards to setup and see why it is happening.
> 
> I have the same case with @nilooy - I went to your profile and started filtering but all seems to work as intended.

My timezone is UTC -3

**Comment by sshanzel** [comment]
Hi @mnzsss! Apologies for the time it has taken to fix the concern, after further investigation, we have found the root cause. If interested, you can check the tagged PR above for details. Thank you so much for reporting the issue and bearing with us 🙇
