### ISSUE TITLE
🐛 BUG: Not able to update the TimeZone information from the profile details

### ISSUE THREAD

**Issue by atapas** [dailydotdev/daily#502]
### What went wrong? 🤔

I'm trying to update the TimeZone information from the profile. But getting an error that email id is already used. Please note I do not intend to edit my email id.

![image](https://user-images.githubusercontent.com/3633137/158571198-7f670da4-e63a-4802-8e78-4416945cb47f.png)

### Expected Behavior

Allow me to update the TimeZone alone without an error.

### Actual Behavior

The error
![image](https://user-images.githubusercontent.com/3633137/158571401-2c3fad2b-7169-4dff-8911-080c08e17ff3.png)

### Steps to Reproduce Issue

- Click on your profile photo from the top-right.
- Click on the Account Details button.
- Now in the popup try changing the Timezone value.

### Solution

NA

### Environment

NA

#### Operating System
Windows
#### Version of Daily
NA
#### Browser

Chrome Latest

**Comment by rebelchris** [comment]
@atapas thanks for logging, roping @idoshamun in, he will fix this for you 🙌

**Comment by idoshamun** [comment]
Fixed. Please try again :)

**Comment by atapas** [comment]
Thanks @rebelchris and @idoshamun 

It works now!
