### ISSUE TITLE
🐛 BUG: Drop in Daily Reward!!!

### ISSUE THREAD

**Issue by doubleprincez** [dailydotdev/daily#505]
### What went wrong? 🤔

I checked my status today and noticed all my reading status per tags are gone and my status dropped!!!

### Expected Behavior

Today I'm supposed to be in legendary reading status having all favorite reading status per tags all filled up.

### Actual Behavior

Today, it has dropped down to diamond from legendary and this is the second time I'm noticing this!
 

### Solution

Kindly find out my status the day before (20, March 2022) and yesterday (21, March 2022) to determine what status I am supposed to have today

#### Operating System
Windows 7 on EliteBook 8540w Core i7

#### Version of Daily
3.15.4

#### Browser

Chrome Version 99.0.4844.74 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi @doubleprincez,

Our weekly goal resets every week. So you have 7 days to achieve a new rank and then it resets.
You can read more about it here:
https://docs.daily.dev/docs/your-profile/weekly-goal
