### ISSUE TITLE
🧩 FEATURE REQUEST: Code Snippets

### ISSUE THREAD

**Issue by nilooy** [dailydotdev/daily#506]
## Feature Request
A dedicated page in daily.dev for useful code snippets where devs can post their code snippets and search with their desired code snippets. This can make our life lot easier by having a reliable tab to go and look for code snippets. 

### Description
I found myself in situation when i need to look for code snippets to speed up the process of writing codes. Although we have few AI extensions which helps sometimes but i don't think they are ready to be used daily in our work. 
> #### May this can open up a safe space for devs to share their cool peace of code 

### Solution

1. A new menu on sidebar, eg: Code Snippets
2. A new `snippet list page` with a grid of cards, like the one we have for news on daily.dev with code snippet's title and small desc.
3. Search Filter & Sort (eg: upvote, newest, by programming language, search by keyword)
5. Each Clickable snippet card will lead to it's single `snippet card page` and show the code and it's description
6. Each snippet card will have a discussion section where devs can do CREATE, UPDATE & DELETE operation.
7. Ability to upvote, downvote or save them.
8.  A Button `ADD SNIPPET` on the main `snippet list page` to add new snippet.
9.  ADD SNIPPET FORM
        - Title field: text
        - Description field: richtext editor
        - Code field: textarea with code highlighting.
        - Programming Language field: select field with autocomplete for programming langs.
        - Tags Field
10. Integrate dev badge rating with snippets.

### Screenshots
<img width="1414" alt="Screenshot 2022-03-23 at 20 37 11" src="https://user-images.githubusercontent.com/32486682/159724822-7224f074-2ca4-46c2-8dc8-919b038147cb.png">

<img width="1413" alt="Screenshot 2022-03-23 at 20 59 05" src="https://user-images.githubusercontent.com/32486682/159729251-425b26df-f513-4323-9914-985c209ed947.png">

### Alternate Solutions
NA

**Comment by nimrodkra** [comment]
@nilooy Thanks for the suggestion! I can see how much effort and thought you've given it :) At the moment it's out of scope in terms of our product roadmap as we aim to focus on other areas. Just out of pure curiosity, how do you find code snippets today?

**Comment by nilooy** [comment]
@nimrodkra Thanks for appreciating it. Usually, i do traditional google search, look on stackoverflow or write by myself. I really like the idea of daily.dev and was just having a thought. It's just a nice to have thing but not a necessary one.
