### ISSUE TITLE
🧩 FEATURE REQUEST: Possibility to disable/enable dailydev as homepage in browser (Chrome)

### ISSUE THREAD

**Issue by GetoXs** [dailydotdev/daily#513]
## Feature Request

Possibility to disable/enable dailydev as homepage in browser.

### Description

Current state: DailyDev override homepage for browser without any confirmation from user. And that's ok, but user is unable to disable DailyDev as homepage.
In my case I use DailyDev using extension button. My homepage in dedicated to different extensions. 

### Solution

In Customize settings possibility to control dailydev as Homepage in Chrome (FF too?).

**Comment by nimrodkra** [comment]
Hi @GetoXs, we have two solutions for you in that case:
1. To use the Focus Mode:
![Screen Shot 2022-04-08 at 19 24 40](https://user-images.githubusercontent.com/41470823/162483139-3de2b919-5d3c-42b2-a6f8-2e1fdc9b4f20.png)
2. Use the web app instead: https://app.daily.dev
