### ISSUE TITLE
Time Spent Alert

### ISSUE THREAD

**Issue by keshavashiya** [dailydotdev/daily#519]
Hi Team,

Can we have **`Time Spent Alert`** so we've been notified if we're spending more time on it, since while reading blogs we forgot to get back to work and this leads to miss deadlines.

Thanks

_Originally posted by @keshavashiya in https://github.com/dailydotdev/daily/discussions/518_

**Comment by idoshamun** [comment]
Closing as it's a duplicate of https://github.com/dailydotdev/daily/discussions/518
