### ISSUE TITLE
🐛 BUG: Email already used while trying to save my profile infos after an update

### ISSUE THREAD

**Issue by Marouanelya** [dailydotdev/daily#521]
### What went wrong? 🤔

I can't save my profile infos after I changed my username.. 

### Expected Behavior

Save my profile with the new username.

### Actual Behavior

It show the message that the email is already used.

### Steps to Reproduce Issue

Go to: Profile section -> Accout details -> Change the username -> Save 

### Solution

Do not check that the email adress is unique if it has not been changed.

### Environment

I installed the extention on Chrome and reproduced the issues when I opened a new tab in the browser. 

#### Operating System

Windows 10

#### Version of Daily

3.15.5

#### Browser

Browser info:
        Chrome

**Comment by idoshamun** [comment]
I see you have two accounts under the same email (we need to fix this issue), you have a github and a google account. Which would you like to keep?

**Comment by Marouanelya** [comment]
I would like to keep my google account please.

**Comment by idoshamun** [comment]
It should be fine now

**Comment by Marouanelya** [comment]
Yes, it works ! Thank you !
