### ISSUE TITLE
🐛 BUG: 406 error on main page and 403 on api

### ISSUE THREAD

**Issue by ariaieboy** [dailydotdev/daily#527]
### What went wrong? 🤔
main page and api endpoints are not accessible with iran ip address.

### Expected Behavior
i know that because of US sanctions alot of technology companies blocked iranian IP addresses but since in daily.dev term of use there is no mentioning about the IP blocking and sanctioning iran so i expect that your site and app be accessible using iranians IP

### Actual Behavior
right now when i try to access the main site daily.dev it will show me this error :
```
406 Not Acceptable
openresty
```
and the api endpoints return this response with status code of `403` :
```
Error: Forbidden
Your client does not have permission to get URL / from this server.
```

### Steps to Reproduce Issue
you need an IP address from iran if you send a request using that ip address you will see this errors

### Solution
it might be from the cloud provider that you guys using for example amazon and google cloud blocked iranians IP addresses or maybe your CDN rules. 

#### Operating System
windows 11

#### Browser
chrome descktop

**Comment by idoshamun** [comment]
Hi @ariaieboy,

It's very frustrating to hear about the sanctions and the fact that daily.dev is blocked in some places like Iran.
Unfortunately, we have nothing to do with it at the moment as we use google cloud.
The only thing I can suggest is using VPN for the time being.
I'm sorry for this inconvenience. 🙏
