### ISSUE TITLE
🐛 BUG: Can't switch from Recommanded to by date

### ISSUE THREAD

**Issue by HamsterBoomer** [dailydotdev/daily#531]
### Environment

Windows 10 

Brave browser

**Comment by rebelchris** [comment]
Hi @HamsterBoomer thank for logging this issue.
Do you have some more information about the expected behaviour and what's actually happening?

And we'd love some background information, are you using the extension or the web application?

**Comment by HamsterBoomer** [comment]
Goodmorning,
In the last several days this issue did not come up again. Neither on the
web application, mobile app or via the extention.
Please close this bug.
Thank you.
