### ISSUE TITLE
🧩 FEATURE REQUEST: Add shortcuts at the top center of feeds

### ISSUE THREAD

**Issue by mussacharles60** [dailydotdev/daily#536]
## Feature Request

Move shortcuts to the top center of the feeds

### Description
I have 10 to 15 `most visited sites` or `shortcuts` in my `chrome new tab`, this makes easy to find the latest visited site and to view it quickly on chrome in desktop.
But the issue is in daily.dev's `new tab` there's a limited view of the custom shortcuts where it appears in top right corner of the feeds.
I would like it to appear at the top center of the feeds where it can easily be expanded when there are more shortcuts to be viewed like in the chrome's new tab

### Solution
The shortcuts is already there but just move it a little bit to the top center of the feeds where I can quickly find a desired shortcut.
1. Also expand it to occupy a little bit of space like in the chrome's new tab if possible.
2. Increase a size of site's icon and a little bit of margin/space of each site in shortcut 👍

`Thanks, this is just my opinions otherwise it looks great.`

**Comment by idoshamun** [comment]
Hi @mussacharles60,

Thank you for reaching out.
The focus of our extension is the feed, this is why we decided to place the most visited sites at the site of the application.
We have no plans to change its placement or style in the near future. I hope you understand.
