### ISSUE TITLE
🧩 FEATURE REQUEST: Allow users to be able to change the sync of their Github or Google account

### ISSUE THREAD

**Issue by irlanvi** [dailydotdev/daily#537]
## Feature Request

Users can change their account sync

### Description

I have an account registered with my Github a few months ago. But several weeks after that i created my second account under a different Github, and now i think i prefer to be on that second account rather than the first.

But unfortunately, i always log into that first account every time i try to log in with this Github. I can't change my login method. 

### Solution

it would be great if users could change their login way with another account. Besides being able to change their Github or Google account, users can also move their account into another Github if their old Github is no longer accessible or something else happens.

**Comment by idoshamun** [comment]
Hi @irlanvila,

You're definitely right. We are planning to improve our authentication system in the very near future.
We will take this feedback into account.

**Comment by mabdullahadeel** [comment]
> Hi @irlanvila,
> 
> You're definitely right. We are planning to improve our authentication system in the very near future. We will take this feedback into account.

Yeah, I think this should be prioritized. The problem I am facing is that the google account I used to sign up with daily.dev would not be accessible to me in a few days. Before that, I wanted to change my login creds to another google account but unfortunately, the platform does not allow it.

It would be really nice to add this feature soon.

I know the consequences but you can do something like stackshare.io. What they are doing is the user has to connect one of the social auth at least and then switch to another one to delete the previous one.

Nonetheless, any strategy will work. But this feature should be prioritized.

Thanks

**Comment by idoshamun** [comment]
Hi @mabdullahadeel,

It's already in progress. Please stay tuned for more updates.

**Comment by idoshamun** [comment]
We've just released our new authentication system. Please check out the release notes and try out the new features.
https://app.daily.dev/posts/IEnARQTZA
Looking forward to hear your feedback :)
