### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by rafaeldellaquila** [dailydotdev/daily#543]
### What went wrong? 🤔

When i try to change my nickname or other details on profile edit settings we got a error with "This email is already used".
[PRINT HERE](https://prnt.sc/VB1QgbMbP0jK)

### Expected Behavior

I expect to do my changes on my profile without a email revalidation

### Actual Behavior

i got this message when i edit my profile

### Steps to Reproduce Issue

User Profile > Account Details.

### Solution

I think there is some conditional expression out of place

### Environment
Its a Notebook Intel i7, 32GB RAM, SSD, Nvidia 1050TI...

#### Operating System
Windows 10.

#### Version of Daily
3.15.6

#### Browser
Google Chrome

Thank you, i love ur app.

**Comment by idoshamun** [comment]
Hi @rafaeldellaquila!

Please try again it should be fine now :)
