### ISSUE TITLE
🐛 BUG: Share or copy article button doesn't give the right URL

### ISSUE THREAD

**Issue by 0wx** [dailydotdev/daily#548]
### What went wrong? 🤔
When pressing the copy URL button will give the extension URL instead of article URL
![image](https://user-images.githubusercontent.com/28288911/171856191-4ec85dbd-fd8c-4196-ac2f-01ad5de31b64.png)

the share button is the same 
![image](https://user-images.githubusercontent.com/28288911/171856305-5d756bc5-93d6-4a1b-af1b-4173c40d9b39.png)

### Expected Behavior
Can copy or share the right articl URL

### Actual Behavior
Give different URL

#### Version of Daily
v.3.16.1
#### Browser
Chrome

Note: maybe add QR code would be nice too.

**Comment by rebelchris** [comment]
PR is opened that will address this issue: https://github.com/dailydotdev/apps/pull/994

**Comment by 0wx** [comment]
@rebelchris great, thank you
