### ISSUE TITLE
🐛 BUG: Not able to comment on the post via companion

### ISSUE THREAD

**Issue by Pradumnasaraf** [dailydotdev/daily#549]
### What went wrong? 🤔

![Screenshot from 2022-06-03 21-50-49](https://user-images.githubusercontent.com/51878265/171907449-a45d5c04-777c-45b6-aa98-f69604edd5fd.png)

### Expected Behavior

Comment should be added publicly

### Actual Behavior

It's not resisting a comment and giving `graphql 204` error

#### Operating System
Ubuntu 20.04 LTS

#### Version of Daily
(v3.16.1)

#### Browser
Chorome

**Comment by idoshamun** [comment]
Hi @Pradumnasaraf,

Thanks for reporting! Can you share the console output please when it happens?

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf,
> 
> Thanks for reporting! Can you share the console output please when it happens?

Hey! Ido, currently everything is working fine. As soon I get that bug/error I will share the logs.
