### ISSUE TITLE
🐛 BUG: Companion tooltip typo

### ISSUE THREAD

**Issue by liorhirsch** [dailydotdev/daily#552]
### What went wrong? 🤔

In the new Companion feature, there is a button on the toolbox bar with a typo in the tooltip. The 'comments' button opens the comment modal and not the article's comments.
![image](https://user-images.githubusercontent.com/11360871/171911916-c0182f41-ca68-4fb2-bed6-1e2a15a6710d.png)

### Expected Behavior
The tooltip's text should be 'comment'.

### Actual Behavior
The tooltip's text is 'comments', which confused me when I clicked it and the comment modal opened, instead of the article's comments.

### Steps to Reproduce Issue
NA

### Solution
NA

### Environment
Beta version

#### Operating System
Windows
#### Version of Daily
3.16.1
#### Browser
Chrome

**Comment by idoshamun** [comment]
Hi @liorhirsch,

Thank you for the report. We need to fix it!

**Comment by rebelchris** [comment]
@liorhirsch This has been fixed in version 3.16.3 of the extension.
Thanks for reporting it 💖
