### ISSUE TITLE
🐛 BUG: companion mode still persists even if we go to another page on a website internally

### ISSUE THREAD

**Issue by murtuzaalisurti** [dailydotdev/daily#554]
### What went wrong? 🤔

The companion mode persists when we move from one page to another in the same website. That should not happen.

![chrome_9ebgH8aIOH](https://user-images.githubusercontent.com/68743212/171921366-16cc8af4-c8d1-4c50-80fb-4a6f975b4567.jpg)

### Expected Behavior

The widget should be removed if a user leaves the article page!

### Actual Behavior

The widget is evident on every page!

### Steps to Reproduce Issue

First, go to an article on daily.dev and then visit another page on the same website internally!

### Environment

Chrome on Windows

#### Operating System

Windows

#### Version of Daily

3.16.1

#### Browser

Chrome

**Comment by rebelchris** [comment]
@murtuzaalisurti This is solved in the latest version. Thanks for logging it 💖
