### ISSUE TITLE
🐛 BUG:  companion mode breaks some sites - (for example DEV.to)

### ISSUE THREAD

**Issue by murtuzaalisurti** [dailydotdev/daily#555]
## 🐛 Bug Report

When navigating internally, it looks like some sites are not at all displaying content when companion widget is enabled!

### What went wrong? 🤔

When navigating internally, it looks like some sites are not at all displaying content when companion widget is enabled! It breaks some sites. I experienced this on DEV.to

![chrome_X8rTKXywEu](https://user-images.githubusercontent.com/68743212/171922289-1a5f8393-ce79-45ac-a9f2-39abe5ca6083.jpg)

### Steps to Reproduce Issue

Navigate from an article having companion widget, to another page on the same website.

### Environment

Chrome on Windows

#### Operating System

Windows

#### Version of Daily

3.16.1

#### Browser

Chrome

**Comment by idoshamun** [comment]
Hi @murtuzaalisurti,

Thank you for reporting this critical issue. Can you please share the exact URL that produces this issue?

**Comment by murtuzaalisurti** [comment]
> Hi @murtuzaalisurti,
> 
> Thank you for reporting this critical issue. Can you please share the exact URL that produces this issue?

[https://api.daily.dev/r/VcVWZ7Aus](https://api.daily.dev/r/VcVWZ7Aus)

***Note that this issue is evident sometimes only. You may or may not encounter it. I was not able to reproduce it every time. It happened only one or two times.***

**Comment by rebelchris** [comment]
@murtuzaalisurti Thanks for reporting this behaviour has been addressed in the latest version: 3.16.3 💖
