### ISSUE TITLE
🐛 BUG: Trying to add a comment and it failed, preview was also empty

### ISSUE THREAD

**Issue by GrfxGuru** [dailydotdev/daily#557]
### What went wrong? 🤔

I was viewing the article to introduce the new widget and wanted to add a comment. When I tried to submit it said there was an error and the preview was also empty (not showing my comment). I'm using the latest Chrome on the latest macOS.

### Expected Behavior

I expected my comment to be added without an error, I also expected the preview to display my message.

### Actual Behavior

I received an error when trying to submit and the preview was empty

### Steps to Reproduce Issue

Try to add a comment using Chrome on macOS. This was reproducible 100% for me every time I tried on this article https://daily.dev/blog/the-companion

#### Operating System

macOS

#### Browser

Chrome

<img width="477" alt="CleanShot 2022-06-03 at 13 18 19@2x" src="https://user-images.githubusercontent.com/298919/171923832-5657bf6e-2f54-4734-9953-afb201ed1cbc.png">
<img width="475" alt="CleanShot 2022-06-03 at 13 17 58@2x" src="https://user-images.githubusercontent.com/298919/171923833-9b7f83e4-d0c3-4e8c-b268-ed4af36f486a.png">

**Comment by idoshamun** [comment]
Hi @GrfxGuru,

Thanks for the report. Seems like a dup of #549 so let's keep the convo there. :)
