### ISSUE TITLE
🧩 FEATURE REQUEST: Add a close button

### ISSUE THREAD

**Issue by bobbyiliev** [dailydotdev/daily#559]
## Feature Request

Add a button that hides the widget completely.

### Description

On SPA sites, as the pages do not really refresh, there is no way to hide the widget unless you do an actual refresh.

Example:

![SPA example, widget stays open all time across all pages](https://user-images.githubusercontent.com/21223421/172006067-cfe4cddd-e7d4-42f4-9d8a-be94e2ca7381.gif)

### Solution

It would be nice to have a button that people could click and hide the widget completely.

### Alternate Solutions

Detect that the URL has changed, even though there is no actual refresh and hide the widget.

**Comment by idoshamun** [comment]
Hi @bobbyiliev,

Thanks for the report. It seems like a dup of #554. Let's keep the discussion there :)
