### ISSUE TITLE
🐛 BUG: Chat button overlaps with consent preferences button

### ISSUE THREAD

**Issue by bobbyiliev** [dailydotdev/daily#560]
## 🐛 Bug Report

On the feedback page at https://daily.dev/feedback, the chat button overlaps with the consent preferences button.

### What went wrong? 🤔

Here is a screenshot of this:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/21223421/172006527-cc93cddb-6935-4700-98b6-efed291e90bb.png">

### Steps to Reproduce Issue

Tested this on Chrome.

### Solution
Maybe move the consent preferences button to the left?

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/21223421/172006873-2f60d62c-31c2-4899-982c-0a8adf2d625f.png">

#### Operating System

MacOs

#### Version of Daily

Issue is with the webapp.

#### Browser

    Browser info:
        Chrome

**Comment by nimrodkra** [comment]
Hi @bobbyiliev thanks for the feedback! We fixed the issue.
