### ISSUE TITLE
🐛 BUG: Extension injects more than 600 `<daily-companion-app>` nodes to the DOM

### ISSUE THREAD

**Issue by Posandu** [dailydotdev/daily#561]
### What went wrong? 🤔

When I was debugging my application, I found out there are more than 600 `<daily-companion-app>` elements in the DOM. This is causing the developer tools to lag.

### Expected Behavior

Only 1 `<daily-companion-app>` should be there

### Actual Behavior

Extension adds more than 600 `<daily-companion-app>` elements to the DOM.

### Steps to Reproduce Issue

Install the latest version of the extension. (Make sure you have beta access)
Enable companion widget.
Open a simple webpage and see its HTML source code using DevTools.

![image](https://user-images.githubusercontent.com/76736580/172034482-6ce169d1-a151-4af1-893e-f62338fb39a2.png)

#### Operating System

Windows 10 latest version.

#### Version of Daily
3.16.1

#### Browser

Firefox latest version.

**Comment by idoshamun** [comment]
Hi @Posandu,

Thanks for reporting this critical issue. We should fix it ASAP.

**Comment by rebelchris** [comment]
@Posandu Thanks for the report, this behaviour has been fixed in version: 3.16.3
