### ISSUE TITLE
🐛 BUG: Companion resets scrollbar when changing application

### ISSUE THREAD

**Issue by dusthijsvdh** [dailydotdev/daily#563]
### What went wrong? 🤔

When the companion feature is open and the chat is expanded, it scrolls back to the top if you switch to a different application and back. For example, if you scroll down for a few comments, then `alt + tab` or click on another application and then switch back, it scrolls to the top comment again.

### Expected Behavior

When switching applications, I'd expect the chat scrollbar to stay in the same position and not scroll back to the top.

### Actual Behavior

I recorded a short video where I switch between notepad and Google Chrome, and here it jumps to the top every time you switch back to Google Chrome. It doesn't have to be notepad, it does it with all applications or even clicking on the developer tool.

video: 

https://user-images.githubusercontent.com/25427808/172219409-10988229-1adf-4990-a828-de7122bbe17d.mp4

### Steps to Reproduce Issue

1. Open an article where the companion feature will activate
2. Open the comments and scroll down a bit
3. Switch to a different application
4. Switch back to the article

### Solution

No clue, because the console doesn't show any errors. Might have to do something with the browser pausing something on the background.

#### Operating System

Windows 11 21H2

#### Version of Daily

Beta version / 3.16.1

#### Browser

Google Chrome 102.0.5005.63

**Comment by idoshamun** [comment]
Hi @dusthijsvdh,

Thanks for the report. It happens because we reload the comments on focus but it shouldn't affect the scrollbar.
We will sort it out.

**Comment by rebelchris** [comment]
@dusthijsvdh Thanks a lot for reporting this, we fixed this behaviour in version 3.16.3
