### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by dodo-the-dev** [dailydotdev/daily#564]
### What went wrong? 🤔

Unable to comment from the companion app

### Expected Behavior

Being able to click the comment icon, add a comment and hit enter.

### Actual Behavior

The box comes up, but when I try to click the "Write your comment..." it doesn't allow me to click it, so I can't type anything.
edit: I tried again, and I finally got a cursor at the beginning of the placeholder text. I could then enter the text, but when I tried to submit the comment, it says "Something went wrong, try again". It still doesn't allow me even when I try to recreate the comment.

### Steps to Reproduce Issue

u/k

### Solution

n/a
#### Operating System
Linux 22.04LTS

#### Version of Daily
3.16.1

#### Browser
Firefox 101.0 for Linux

**Comment by dodo-the-dev** [comment]
![image](https://user-images.githubusercontent.com/5068651/172234359-08ca165d-7c60-46b3-bd42-91d11accf9ed.png)

**Comment by idoshamun** [comment]
Hi @dodo-the-dev,

Thanks for the report. This is a dup of #549, we're already working on it!
