### ISSUE TITLE
🐛 BUG: Daily companion broken thumbnail image

### ISSUE THREAD

**Issue by bobbyiliev** [dailydotdev/daily#566]
## 🐛 Bug Report

In some cases, the Daily companion thumbnail images do not load.

### What went wrong? 🤔

Noticed the problem on this GH repo:

https://github.com/thedevdojo/wave

The image from DEV.to is not loading and appears broken.

### Expected Behavior

Load a default image if the original one is not loading, or hide the img element.

### Actual Behavior

<img width="554" alt="image" src="https://user-images.githubusercontent.com/21223421/172322631-7bd32d2f-a20e-41d2-9faf-2d96fb0b9879.png">

### Steps to Reproduce Issue

Visit the following repo:

https://github.com/thedevdojo/wave

Open the Daily.dev companion.

#### Operating System

MacOs

#### Version of Daily

Latest.

#### Browser

Chrome

**Comment by rebelchris** [comment]
@bobbyiliev Thanks for the report, we implemented a fallback image in version 3.16.3
Thanks a lot for the report 👏
