### ISSUE TITLE
🐛 BUG: Can't comment on GitHub repos via Daily Companion 

### ISSUE THREAD

**Issue by bobbyiliev** [dailydotdev/daily#567]
## 🐛 Bug Report

When writing a comment via Daily Companion on a GH repo, and when you use a special key like `s` for search or `y`, GH detects this event and prevents you from writing a comment.

### What went wrong? 🤔

To reproduce:

- Visit this repo: https://github.com/thedevdojo/wave
- Open the Daily Companion
- Try to write a comment that contains `s` for example.
- You will see that the GH search opens rather than actually typing the letter 

### Expected Behavior

Being able to post a comment.

### Actual Behavior

Not being able to post a comment.

### Solution

Maybe hide the Daily Companion on GH? 

#### Operating System

MacOs

#### Version of Daily

Latest

#### Browser

Chrome

**Comment by idoshamun** [comment]
Hi @bobbyiliev,

Thanks for the awesome catch. We will sort it out :)

**Comment by rebelchris** [comment]
@bobbyiliev Thanks for this report.
We deployed a fix to this in version 3.16.3

Would you mind checking this issue works as intended for you?

**Comment by bobbyiliev** [comment]
Neat! Seems to be all sorted out now, thank you @rebelchris 🙌
