### ISSUE TITLE
Generating a dev card issue (Firefox - Mobile App)

### ISSUE THREAD

**Issue by RaheemAmer** [dailydotdev/daily#568]
### What went wrong? 🤔

- Generating a dev card results in an error with "Something went wrong, please try again..."

### Browser & Environment

- Firefox Desktop version and mobile application both of them ran into the same issue

#### Operating System
- Windows 10

#### (1) Firefox Desktop 
<img src="https://user-images.githubusercontent.com/18606136/172353864-83cffb05-13f7-41f4-ad6e-6133ae7353d1.png" alt="Grab your Dev Card daily dev(Firefox-Version)" width="400px">

<hr>

#### (2) Mobile App Version
<img src="https://user-images.githubusercontent.com/18606136/172353976-79adb106-8a70-4ad8-aa12-54b7cb80fa09.jpeg" alt="Grab your Dev Card daily dev(Mobile Version)" width="200px" >

**Comment by idoshamun** [comment]
Thanks @RaheemAmer for reporting.
We're on it!

**Comment by idoshamun** [comment]
It should be fine now :)

**Comment by RaheemAmer** [comment]
Indeed, thanks for the quick reply and fix. Have a great day <3
