### ISSUE TITLE
🐛 BUG: This email is already used

### ISSUE THREAD

**Issue by elkhan** [dailydotdev/daily#570]
Hi!
Since it is been mentioned in a couple bug reports already I guess you know the problem. Can't sign in - `This email is already used`
Could you delete one of the accounts please?

**Comment by idoshamun** [comment]
Which one you would like to keep Google or GitHub?

**Comment by rebelchris** [comment]
@elkhan Could you please let us know which one you would like to keep?

**Comment by elkhan** [comment]
@rebelchris Hi! Sorry, was on vacation. Google if possible. Thanks!

**Comment by idoshamun** [comment]
@elkhan that's done. please try again :)
