### ISSUE TITLE
🐛 BUG: The widget open up in website that has nothing to do with daily dev

### ISSUE THREAD

**Issue by 0wx** [dailydotdev/daily#575]
### What went wrong? 🤔

![image](https://user-images.githubusercontent.com/28288911/172754554-685cf71c-f5bd-4c02-9938-3673459a8df7.png)
![image](https://user-images.githubusercontent.com/28288911/172754666-30aeadb2-1a14-4217-9e4f-98094f8fbcdf.png)

It's not supposed to has the widget in it

### Steps to Reproduce Issue

Going to https://7minuteworkout.jnj.com/
then click the [Google Play](https://play.google.com/store/apps/details?id=com.jnj.sevenminuteworkout&referrer=utm_source%3D7minuteworkout.jnj.com%26utm_medium%3Dwebsite%26utm_content%3Dhomepage%26utm_campaign%3DHOME) button
and the widget appear
#### Operating System
PopOS 22.04
#### Version of Daily
3.16.1
#### Browser
Chrome

**Comment by idoshamun** [comment]
Hi @0wx,

Thanks for the report. I found the original article that shared this link on daily.dev
https://app.daily.dev/posts/e2f5023189ed4bd3dee2d78d2ff44fa2

This is why it shows the companion on it

**Comment by 0wx** [comment]
@idoshamun you might want to not ignore the url parameter for the companion, the widget will appear on every google play apps link since they use parameter `id=com.package`

**Comment by idoshamun** [comment]
You're right! By default we ignore query params, so we will not be sensitive to utm and son on. But we will add google play to our allow list

**Comment by 0wx** [comment]
> You're right! By default we ignore query params, so we will not be sensitive to utm and son on. But we will add google play to our allow list

and also please add hacker news in the allow list

**Comment by sshanzel** [comment]
> and also please add hacker news in the allow list

Do you have any sample URL that happens to behave the same way as your primary concern? Can't seem to find any for further investigation.

**Comment by 0wx** [comment]
@sshanzel https://news.ycombinator.com/item?id=32048148

**Comment by sshanzel** [comment]
> @sshanzel https://news.ycombinator.com/item?id=32048148

It looks like this post actually available in our system. It just didn't have the AI-generated TLDR.

**Comment by 0wx** [comment]
[image: image.png]
Well any hackernews post has the same title in the companion widget

Pada tanggal Sen, 11 Jul 2022 pukul 12.04 Lee Hansel Solevilla <
***@***.***> menulis:
