### ISSUE TITLE
🐛 BUG: Background on auto-complete results won't match the content size

### ISSUE THREAD

**Issue by Thermalpac** [dailydotdev/daily#576]
### Expected Behavior

As a user writing a new comment
When I type `@` to mention someone
And the suggestions results are bigger than the default box size
Then the box size increases and the background increases accordingly

### Actual Behavior

The background won't match the box size

![image](https://user-images.githubusercontent.com/87901771/172855962-c4d78fe1-9115-4965-b2fc-8294a0c30686.png)

### Steps to Reproduce Issue
Try to have results with many characters. Example on the screenshot works with suggestions found with `@someone` as of today.

#### Operating System

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

#### Version of Daily
3.16.1

#### Browser
Brave [Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by idoshamun** [comment]
Hi @Thermalpac,

Thanks for reporting. We have managed to reproduce and we will fix it

**Comment by rebelchris** [comment]
@Thermalpac Thanks for logging this issue, this is resolved in the latest version.
