### ISSUE TITLE
🐛 BUG: Comments scroll changes position when switching tabs

### ISSUE THREAD

**Issue by Thermalpac** [dailydotdev/daily#577]
### Expected Behavior

As a user reading the comments on the extension
When I scroll the comments on tab A on my browser
And I switch to another tab on my browser
And I switch back to tab A
Then scroll position in the comments in the extension is the same as before

### Actual Behavior

![daily-dev-comments](https://user-images.githubusercontent.com/87901771/172857286-f1eea9ca-b18a-4299-a568-58076c4c1cdc.gif)

- When switching to another tab, then switching back to the tab where I used the extension to scroll the comments ; 
- The scroll went way up. I expected it to either:
    - be at the same position as before switching tab (position that can change if a comment above is added/modified/deleted of course)
    - scroll up but at the top of the scroll, not up but at a random position

### Steps to Reproduce Issue

- Read comments on the extension and scroll down
- Switch to another tab
- Switch back to the first tab
- Then the scroll has moved 

#### Operating System

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

#### Version of Daily
3.16.1

#### Browser
Brave [Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by idoshamun** [comment]
Hi @Thermalpac,

It should be fixed already, please make sure to update to 3.16.3
