### ISSUE TITLE
🐛 BUG: Clicking Load more loads same articles

### ISSUE THREAD

**Issue by Posandu** [dailydotdev/daily#585]
### What went wrong? 🤔

I opened a profile on daily.dev and when I click load more the same articles load instead of loading the other articles.

### Expected Behavior

When I click load more, other articles should load

### Actual Behavior

Loads the same articles

### Steps to Reproduce Issue

Go to https://app.daily.dev/posandu (Or any daily.dev profile)

Scroll to the articles section
![image](https://user-images.githubusercontent.com/76736580/174219792-5ac7f30d-dca9-4329-b4fa-361129bf1719.png)

Click load more

After clicking load more, you should see the same content
![image](https://user-images.githubusercontent.com/76736580/174219859-99b2e01d-d5e7-43a3-8803-c6ca5a06b1fc.png)

#### Operating System
Windows 10

#### Version of Daily
3.16.4

#### Browser

The bug happens on all browsers, even if I tried it on incognito mode without extensions.

**Comment by rebelchris** [comment]
Hi @Posandu,

Thanks for logging this issue, we identified it and are working on a solution 💪

**Comment by rebelchris** [comment]
@Posandu We solved the issue, it should be back to normal behaviour 💖

**Comment by Posandu** [comment]
Yes, it's working correctly.
