### ISSUE TITLE
🐛 BUG: UI bug with the dropdown menu

### ISSUE THREAD

**Issue by AnishDe12020** [dailydotdev/daily#586]
### What went wrong? 🤔
![image](https://user-images.githubusercontent.com/63192115/174349376-4aad2d82-06fe-491b-ab81-4aed8b9119d6.png)
Weird white border focus outline that does not go over all the 4 sides (typically it should look good when it is on all 4 sides). Also, the d of recommended is half cut.

### Expected Behavior

border on all 4 sides, full recommended text being visible

### Actual Behavior

d of recommended is half-cut and the border is only on sides

### Steps to Reproduce Issue

open the daily.dev app, click (or focus) on the dropdown button for filters

### Solution

adding a top and bottom margin to the bottom fixes the margin issue (did it in devtools)
![image](https://user-images.githubusercontent.com/63192115/174350113-dadb7102-b95b-4547-a475-580b9c78a828.png)
(ignore the padding, it is disabled, was just testing what can fix it)

for the recommended text, making the right margin 0 helps (remove `mr-1`)
![image](https://user-images.githubusercontent.com/63192115/174350342-06521e61-4d14-46d5-89f2-32aa5c525bf8.png)

#### Operating System
Pop! OS 22.04 LTS (base on ubuntu 22.04 lts)

#### Version of Daily
webapp (app.daily.dev), new tab v3.16.4

#### Browser
Brave: 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit) 
Chrome: 102.0.5005.115 (Official Build) (64-bit) 

Happens on both

~~I will try to pr this tomorrow morning, quite sleepy now (12 hours from me writing this). if i am not able to, i will update this message~~
see below message (https://github.com/dailydotdev/daily/issues/586#issuecomment-1159368543)

**Comment by AnishDe12020** [comment]
**PROBLEMS WITH RUNNING LOCALLY DURING CONTRIBUTING. DOES NOT OCCUR ON PROD**

So, I got it running locally (with docker-compose) and the webapp is running as well but now I am not able to enable sorting (and hence cannot see the dropdown)

![image](https://user-images.githubusercontent.com/63192115/174424722-10139935-b1f1-4a1f-808c-d802f3ddf198.png)

Enabling sorting in the customize modal does nothing and the switch automatically gets turned off (seems to be a state issue/the setting not getting registered or smth)

Also, there are some console errors, don't know if these are normal in a local environment
![image](https://user-images.githubusercontent.com/63192115/174424749-4fa8a88e-c041-448c-a209-a3d25981c1ab.png)

I will try to do something and will update my progress here if I get it working but if I cannot, i won't be able to do the pr

**Comment by rebelchris** [comment]
@kirillkurko or @sshanzel would you be able to help Anish get set up locally? 🙏

**Comment by kirillkurko** [comment]
> @kirillkurko or @sshanzel would you be able to help Anish get set up locally? 🙏

I'm having same issue now 😂, so @sshanzel can you please help both of us

**Comment by kirillkurko** [comment]
What I see from the screenshot is that proposed fix introduces empty space added above and below the button

**Comment by sshanzel** [comment]
Hi @AnishDe12020! Thank you so much for the desire in making your code contribution! We are more than happy to help you every step of the way.

I think your screenshot made me realize another issue. The message seems to be blocking the header where it displays the actual dropdown. The quickest way to go about this is to click the "+ Choose tags", then follow just any tag (one should do). The header message relating to creating your feed should be gone (since you have the settings already enabled).

Ensure the other containers are running (API, gateway, DBs), and you should be able to seamlessly work on it. Good luck! 🚢

**Comment by AnishDe12020** [comment]
Hey, I was not able to choose tags (clicking the create button does nothing), here is how the console looks - 
![image](https://user-images.githubusercontent.com/63192115/174807041-ed8f627b-82c6-4372-b406-75d9eed3c9c1.png)

However, I think I found a hacky way to show the dropdown. Basically, I modified the `getFeedTitle` to not return the create geed button for the time being.

I also removed this line temporarily
```
        {sortingEnabled && isSortableFeed && (
```

Then I just fixed the dropdown and here is a pr (i have removed all the hacky modifications, it is just the class name changes) :D - https://github.com/dailydotdev/apps/pull/1041
