### ISSUE TITLE
🧩 FEATURE REQUEST: Sort my feed and search by date

### ISSUE THREAD

**Issue by emmalearnscode** [dailydotdev/daily#587]
## Feature Request

Add the ability to sort the My Feed and Search results by date so that newest articles appear first. 

### Description
At the moment I get a range of articles some as far back as 2020 on the first page of results. Although that's great for discoverability sometimes I want to find the most recent articles and therefore being able to sort by date would be really useful.

### Solution

As an option that I can choose on the My feed and search results pages, near the top of the page

### Alternate Solutions
NA

**Comment by idoshamun** [comment]
Hi @emmalearnscode,

We already have this feature :)
You can see how to activate the sorting menu here:
https://docs.daily.dev/docs/key-features/default-feeds#sort-by-date-prev-recent-feed

**Comment by emmalearnscode** [comment]
Ok, having to activate it in the customize section is pretty poor UX in my experience. A sorting/filtering function is something most people have come to expect as an inbuilt part of websites, not something they need to find in settings and switch on before they can use it. Most, like me, will not search in settings to see if such a feature exists. Would definitely suggest making this on by default.

However, as far as I can see this still only applies to the main feed. I would also like to be able to sort search results by date and I'm getting no such drop down appear on that page even though I toggled the option on for my feed.

**Comment by idoshamun** [comment]
Unfortunately, we don't provide this option in the search. I forgot to link it in my previous comment, but we already have a discussion going on improving our search. So it's better to keep it there: https://github.com/dailydotdev/daily/discussions/294

As for the UX concern you mention, I understand your perspective. We had several implementation options but decided to proceed with the current one as it removes elements from the main page. We might reconsider this decision in the future.
