### ISSUE TITLE
🧩 FEATURE REQUEST: Reorder feature for companion widget

### ISSUE THREAD

**Issue by Kvaibhav01** [dailydotdev/daily#588]
### Description

I would like the new **companion widget to reorder** by dragging it up and down the page.

### Solution

Currently, the widget sticks horizontally to the center of the page. Sometimes some content gets hidden underneath the widget and so we are not able to see/read it. Here's a screenshot of a similar thing that happened with me today:

<img width="406" alt="A screenshot showing text content hidden behind daily.dev companion widget." src="https://user-images.githubusercontent.com/11731837/174531650-f14a78e3-950b-415a-864e-4fcd28b15636.png">

By having the ability to reorder the widget we can easily see the entire content and it becomes more flexible. When we hover over the widget (not its individual icons), there can be a mouse drag cursor.

**Comment by idoshamun** [comment]
Hi @Kvaibhav01,

Thanks you for the suggestion.
It's already logged here: https://github.com/dailydotdev/daily/issues/550
So let's keep the discussion there :)
