### ISSUE TITLE
🐛 BUG: Facebook recommending on posts are not working

### ISSUE THREAD

**Issue by Laaaaannn** [dailydotdev/daily#589]
## 🐛 Bug Report
- Unable to share the articles on Facebook (404 not found)

### What went wrong? 🤔
- The Facebook crawler on the articles didn't work I think because of the `[id]` in the meta tags
![image](https://user-images.githubusercontent.com/14991331/174805011-ce9758fc-dd5e-4f28-a39d-356401b55027.png)

### Expected Behavior
- it should display the title, description, link & image of the shared article

### Actual Behavior
- it doesn't get the proper value of the meta tags

### Steps to Reproduce Issue
- Go to https://app.daily.dev/posts/F4zPFnAx9
- Click the Facebook recommend button
![image](https://user-images.githubusercontent.com/14991331/174805819-38fe6b36-1279-4927-b65c-13b4d055a7f3.png)

### Solution
- Meta tags should be in a proper value I guess/

### Environment
- Production

#### Operating System
- Windows
#### Version of Daily
- latest
#### Browser
- Chrome (webapp)

**Comment by rebelchris** [comment]
Thanks a lot @Laaaaannn this has been a known issue, but I think you might be on to something here.
I'll add it to our board for further investigation 👀

**Comment by Laaaaannn** [comment]
I'll raise a pull request if I find the solution for this. Thanks @rebelchris

**Comment by rebelchris** [comment]
@Laaaaannn We managed to migrate to Next 12.
You should now be able to share the articles, however we are still optimising as it will sometimes not add the image and title automatically.
