### ISSUE TITLE
🐛 BUG: filter dropdown layout clipping

### ISSUE THREAD

**Issue by murtuzaalisurti** [dailydotdev/daily#592]
### What went wrong? 🤔

The dropdown filter is clipping.

![chrome_HKFrs2Ohl4](https://user-images.githubusercontent.com/68743212/174952280-bcfb0365-0ed3-4d01-9827-1815c6b380c8.gif)

### Expected Behavior

It should be fully visible.

### Environment

Chrome on Windows 10

#### Operating System

Windows 10

#### Version of Daily

Latest version 

#### Browser

Google Chrome v103

**Comment by idoshamun** [comment]
Hi @murtuzaalisurti!

Thanks for your bug report. Can you validate it persists in the newest version (3.16.6)?

**Comment by murtuzaalisurti** [comment]
Yeah @idoshamun it's in the latest version


![chrome_anJggcctlt](https://user-images.githubusercontent.com/68743212/175806026-7b8bbb03-1e12-4c0a-b1e9-735f9d566e12.jpg)

**Comment by rebelchris** [comment]
@murtuzaalisurti thanks for logging this issue, we are looking at solutions for this.
Will keep you posted here
