### ISSUE TITLE
🐛 BUG: Companion shows in reader view

### ISSUE THREAD

**Issue by GrahamTheDev** [dailydotdev/daily#605]
### What went wrong? 🤔
Companion widget shows while in reader view

### Expected Behavior
Companion doesn't show

### Actual Behavior
It shows

### Steps to Reproduce Issue
Open page with companion and activate reader view.

### Solution
Don't show it in reader view

### Environment
Brave browser

#### Version of Daily
V1.16.4

#### Browser
Brave browser

**Comment by idoshamun** [comment]
Hi @GrahamTheDev,

Thanks for reporting.
I'll let you know once we fix it :)

**Comment by rebelchris** [comment]
@GrahamTheDev I've tested the native reader modes.
- Chrome
- Firefox
- Brave

These all work as intended and don't show the companion.
Are we talking about third party reader mode plugins here?
