### ISSUE TITLE
🐛 BUG: always opens doesnt remember collapsed state on FireFox. [companion]

### ISSUE THREAD

**Issue by GrahamTheDev** [dailydotdev/daily#607]
always opens doesn't remember collapsed state on FireFox.

**Comment by sshanzel** [comment]
Hi @GrahamTheDev, can you check if the issue still persists? I installed the latest version and it seems to be fixed now.

**Comment by rebelchris** [comment]
Closing for now, we did some improvements to this a while ago.
Feel free to re-open if it persists.
