### ISSUE TITLE
🐛 BUG: [companion] Markdown Preview doesn't work

### ISSUE THREAD

**Issue by GrahamTheDev** [dailydotdev/daily#609]
Sometimes when you preview your post on companion the p[review doesn't work or update.

**Comment by sshanzel** [comment]
I think it actually does. Did you have any specific use-case about it not working?

I used `# Test` as example:

![image](https://user-images.githubusercontent.com/13744167/177237516-24c99683-386e-45d8-8979-295c590ebe3e.png)
