### ISSUE TITLE
🐛 BUG: modal accessibility 

### ISSUE THREAD

**Issue by rebelchris** [dailydotdev/daily#610]
### What went wrong? 🤔

Modals are not accessibility friendly.
- tab doens't always work (example companion -> new comment)
- esc doesn't work

**Comment by Utkarshn10** [comment]
Hey @rebelchris which modals are we talking about here? I tried this one and it seems to be working fine. Esc also works here.
![image](https://github.com/dailydotdev/daily/assets/58587256/4e9dc57a-fa8d-4c7d-911d-d1a9415487fd)
