### ISSUE TITLE
🐛 BUG: Popup rendered outside of the screen

### ISSUE THREAD

**Issue by barelsh** [dailydotdev/daily#620]
### What went wrong? 🤔

The popup on the top right is rendered outside of the screen
![image](https://user-images.githubusercontent.com/40689128/176910983-f498ba3f-1a06-45ef-9315-bea470b0a945.png)

### Expected Behavior

Put things you want people to see inside their screens 🙃 

### Environment

Chrome version 102.0.5005.63

#### Operating System

Windows 11

#### Browser

Chrome on PC

**Comment by rebelchris** [comment]
@barelsh thanks for logging this, we'll look into it and get back to you.

**Comment by sshanzel** [comment]
Hi @barelsh, we have rolled out a new version of the extension (v3.16.8), it should include the fix for this issue. I will be closing this one now though feel free to let us know if the concern still persists!
