### ISSUE TITLE
🧩 FEATURE REQUEST: Advanced authentication features

### ISSUE THREAD

**Issue by jihan212** [dailydotdev/daily#625]
## Feature Request

Adding login service & editing account 

### Description

1. Please add login service in daily.dev homepage. I changed my google account in chrome. Then I installed daily dev & now i have to sign in another account ! I lost all my previous articles. This is annoying. Fix this issue & let us login existing account. And editing account description will also can help in this issue. Thanks in advance

**Comment by idoshamun** [comment]
Hi @jihan212,

We already have a login service, it's the same popup for sign-up.
If you use your existing Google account it should have connected you to your existing daily.dev account.
When you use a new account that our system is not familiar with it creates a new account for you.

**Comment by jihan212** [comment]
In the login popup there are "Connect with GitHub" & "Connect with Google" options. If I click "Connect with Google" then it connects with google account that logged in this browser. 
Now the problem is that I already have a daily dev account with "example1@gmail.com" which was previously logged into the browser. Now I changed my previous mail to "example2@gmail.com" in browser. Now if I go with "Connect with Google" in popup it directs with "example2@gmail.com". But I want to login with previous mail means "example1@gmail.com". 
So my problem is that I am logged into the browser with a mail and to daily dev with another mail

**Comment by idoshamun** [comment]
Hi @jihan212,

We are now revamping our authentication system to prevent cases as you mention.
If there's any way I can help now to fix your issue, please send an email to support at daily.dev.

**Comment by idoshamun** [comment]
We just released the authentication system a few days ago. Feel free to check it out and let me know what you think.
https://app.daily.dev/posts/IEnARQTZA
