### ISSUE TITLE
🐛 BUG: the `tldr` overflowing outside the box

### ISSUE THREAD

**Issue by 0wx** [dailydotdev/daily#628]
### What went wrong? 🤔
everything is fine until I press `show more`
![image](https://user-images.githubusercontent.com/28288911/179453619-bcf2ffb3-58d9-4bdc-a9bc-5661e8f85b82.png)

![image](https://user-images.githubusercontent.com/28288911/179453459-5da25c09-01a5-48a5-bdc5-82aed810d60a.png)

Post url:
https://api.daily.dev/r/LcekgSa6v

**Comment by idoshamun** [comment]
Thanks a lot! We will look into it :)

**Comment by rebelchris** [comment]
@0wx Thanks again for reporting this.
We fixed the issue in our latest version 🙏
