### ISSUE TITLE
🧩 FEATURE REQUEST: Add a link to the source when an article is not directly linked

### ISSUE THREAD

**Issue by Seblor** [dailydotdev/daily#632]
## Feature Request

Sorry if that has already been suggested, I couldn't find anything related.

### Description

For articles that are linked from another source, like hackernews, it would be great to have a link redirecting to the hackernews page with the comment section as there often is interesting discussions and/or resources.

### Solution

Add a button "Visit source" (or some other name) that would redirect to the direct source instead of the redirected article.

**Comment by idoshamun** [comment]
Hi @Seblor,

Thanks for suggesting this feature :)
This is a dup of: https://github.com/dailydotdev/daily/discussions/579
So let's keep the discussion there.
