### ISSUE TITLE
🐛 BUG: Submit new article form not working

### ISSUE THREAD

**Issue by bobbyiliev** [dailydotdev/daily#662]
## 🐛 Bug Report

The 'Submit article' form is not currently working for me.

### What went wrong? 🤔
When clicking on the submit new article button I get the following form:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/21223421/184300432-f7decf37-9bae-4925-b0cf-3a50601f3f00.png">

### Actual Behavior

The form does not work.

### Steps to Reproduce Issue

Open your web console and click on the submit article button.

### Environment

Chrome

#### Operating System
MacOS
#### Version of Daily
Version
3.16.12

#### Browser
Chrome

**Comment by idoshamun** [comment]
Hi @bobbyiliev,

Can you try again please? I think we fixed the issue

**Comment by bobbyiliev** [comment]
Seems to be all working now @idoshamun thank you for the quick fix!
