### ISSUE TITLE
🐛 BUG: The customize option don't save my  choices in my profile before I reload the page.

#Before nothing. 

I love dayl.dev, all news in one place, the video on YouTube for promotional,  the best. Lots of features, sources... just blow my mind. 
For all the people working on this awesome project, 👍 thanks. 

### ISSUE THREAD

**Issue by Nitsua13** [dailydotdev/daily#671]
## 🐛 Bug Report

I put the configuration in the customize panel of the left, for example changing the layout to grid, that's what I wanted more), works as soon I stay on the page, when I reload the page nothing is saved.  

### What went wrong? 🤔

The problem is associated with my account, don't save the changes in the customize panel before I reload the page. 

If I don't login and I change the options on this panel and I reload the page, this time saves it all. 

I tried in all the devices (Chrome, Firefox, Android as PWA even using the extension from Crhome). I also deleted the cache  in all of them, just in case. 

### Expected Behavior

Change the customize options associated to my profile. Then the app retains the configuration that I put even when I reload the page. If is possible this change can affect all my devices. 

### Actual Behavior

If I logged in and I changed the customize options and the view for example.  If I select grid layout change or the density, etc. But if I reload the page nothing save. 

### Steps to Reproduce Issue

Well I can tell the steps that I follow before figure the issue. 

1- Login with a Google account
2-Change inside the customize panel inside preference the Open Links in new panel option to off. 
3- Reload the page (in first I used a Chrome extension)
* Note: in this points woks, but I dont like the results
4-Change again the preference panel, the Open Links new tab option, this time to on,  and also change the view to block elements (several mistakes, never come back :))
5-  I don't like the results again,  and I changed to the grid default layout,  but nothing changes when I reload the page. 
6- Then I tried all my devices in the flow order: extension Chrome Windows PC, Chrome (app.aily) Windows PC, PWA on my Android 12 mobile, Firefox PC. 

#### Chrome,  I also tried Firefox 

        
Mobile device!?
Yes, I also try in my  Xiaomi mobile, Android 12. Same result

Thanks for all the work as I say at the beginning, the best app of devs News, all in one place.

**Comment by idoshamun** [comment]
Hi @Nitsua13,

We had an issue in our servers, can you check again please?
