### ISSUE TITLE
🐛 BUG: Chnage in docker compose commands

### ISSUE THREAD

**Issue by Pradumnasaraf** [dailydotdev/daily#705]
> ## Change in Docker Compose commands

In **Compose V2** the `docker-compose` command has changed to `docker compose`. But in the README, under section [Setting Up Daily Services](https://github.com/dailydotdev/daily#%EF%B8%8F-setting-up-daily-services) it says to use the old one and it won't work for many folks. As, v1 has now been deprecated and development has moved over to v2. Reference [docs](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command) for compose 

### Issue screenshot:

![Screenshot from 2022-09-12 16-47-45](https://user-images.githubusercontent.com/51878265/189654828-56c56993-adf7-40bb-b472-6ee1da73551d.png)

**Comment by idoshamun** [comment]
Hi @Pradumnasaraf,

Thanks for spotting it. Feel free to submit a PR if you'd like :)
