### ISSUE TITLE
🧩 FEATURE REQUEST: Convert all issue templates to issue forms

### ISSUE THREAD

**Issue by Panquesito7** [dailydotdev/daily#711]
### Description

We should use the new provided GitHub issue forms. This can prevent blank issues or issues without enough information.
We can mark fields as optional or as required, which will make things much efficient, IMO.

### Solution

Add the new GitHub issue forms. https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

### Alternate Solutions

Improve the current issue templates, such as adding links to the contributing guidelines, disabling blank issues, etc..

**Comment by idoshamun** [comment]
Thanks for the suggestion @Panquesito7!
We will look into it.

**Comment by idoshamun** [comment]
Hi @Utkarshn10,

We've already completed it and forgot to close the issue. Sorry and thanks!
