### ISSUE TITLE
GraphQL error: the server responded with a status of 503 (Service Unavailable)

### ISSUE THREAD

**Issue by honglix** [dailydotdev/daily#712]
### What went wrong? 🤔
I've followed the setup guide to start up the apps, but it always shows the GraphQL error like this:

`next-dev.js?3515:24 Error: GraphQL Error (Code: 503): {"response":{"error":"Service Unavailable","status":503,"headers":{"map":{"access-control-allow-credentials":"true","access-control-allow-origin":"http://localhost:5002","connection":"close","content-length":"19","content-type":"text/plain; charset=utf-8","date":"Thu, 15 Sep 2022 15:37:58 GMT","vary":"Origin, Accept-Encoding"}}},"request":{"query":"\n  query Banner($lastSeen: DateTime) {\n    banner(lastSeen: $lastSeen) {\n      timestamp\n      cta\n      subtitle\n      theme\n      title\n      url\n    }\n  }\n","variables":{"lastSeen":"1970-01-01T00:00:00.000Z"}}}`

![Screen Shot 2022-09-15 at 11 37 07 AM](https://user-images.githubusercontent.com/37600784/190446704-c84b1bcf-bef2-46ca-9a80-f1930257c391.png)

**Comment by Shubhdeep12** [comment]
same here. :(

**Comment by idoshamun** [comment]
Hi!

Thanks for trying to set up our repo.
We're very busy at the moment shipping a new authentication system.
Once we finish that, we will look at it more carefully and assist.

**Comment by Shubhdeep12** [comment]
Ok sure @idoshamun 
I even tried running webapp on gitpod.
But even then graphQL API was getting failed with 503 response.

**Comment by rebelchris** [comment]
Hi @Shubhdeep12 and @honglix we just deployed a fix that addresses this issue.
I'd love to hear if everything works for you now.

If not feel free to re-open this ticket.
And thanks again for logging these issues with us.
