### ISSUE TITLE
🐛 BUG: Profile image keeps reverting back to the initial one (DailyDev and DevCard profile image fix)

### ISSUE THREAD

**Issue by ramzxs** [dailydotdev/daily#718]
## 🐛 Bug Report

Profile image keeps reverting back to the initial one.

Changing my profile image for the Profile and Account Details pages, and ultimately for my Dev Card seems not working properly.

### What went wrong? 🤔

After a few seconds upon uploading a new profile image on the Account Details popup screen, my profile image will instantly change on the same Account Details screen, and also on the upper-rightmost of the Main Screen. However, after a few seconds, both will return to my initial profile image.

![DevCard - Issue](https://user-images.githubusercontent.com/1073426/192169620-44a29338-a147-4bba-b682-df23ba6ba4c2.png)

### Expected Behavior

It should have permanently updated the profile image I want to use in your app, especially for my Dev Card.

### Actual Behavior

Upload a new profile image, and just wait for few seconds, the profile image container keeps going back and forth to the initial and the newly uploaded photo.

### Environment

Running using Brave on a Windows 11 PC.

#### Operating System

Windows 11 v22H2

#### Version of Daily

Latest (2022-09-26 around 07:00:00)

#### Browser

Brave Desktop 
Version 1.46.7 Chromium: 106.0.5249.55 (Official Build) nightly (64-bit](https://brave.com/latest/

**Comment by idoshamun** [comment]
This should be fixed now, please confirm :)

**Comment by ramzxs** [comment]
Yes it is! Good job!
