### ISSUE TITLE
🐛 BUG: After authenticating with github new registration doesn't work 

### ISSUE THREAD

**Issue by tonymaynard97** [dailydotdev/daily#724]
### What went wrong? 🤔

Filled out all my tags and then tried signing in with github, successfully authenticated but the redirect doesn't work correctly. Also tried twice with both having the same response.

### Expected Behavior
Once authenticated, show the standard tile interface with the tags attached.

### Actual Behavior

Black screen with a shell of daily.dev and https://app.daily.dev/register?redirect_uri=https%3A%2F%2Fapp.daily.dev%2F%3Fcreate_filters%3Dtrue&mode=default url 

### Steps to Reproduce Issue

- Click Register with github after selecting a few tags
- Authenticate in the popup 
- Observe redirect 

### Environment

chrome 106.0.5249.61
Desktop 

#### Operating System
Mac Monterey 12.3
#### Version of Daily

<img width="1099" alt="Screenshot 2022-09-29 at 21 42 02" src="https://user-images.githubusercontent.com/43003807/193138661-7b6d4202-842c-44dd-9068-5912940167f0.png">

**Comment by idoshamun** [comment]
Hi @tonymaynard97,

We will look into it.
Anyway, we're about to release a revamped version of our authentication that should fix this issue and introduce new features.
I'll keep you posted.

**Comment by idoshamun** [comment]
Hi @tonymaynard97,

We released our new authentication system. Can you try again please?

**Comment by tonymaynard97** [comment]
That worked, thank you!
