### ISSUE TITLE
🐛 BUG: Wrong custom shortcuts icons

### ISSUE THREAD

**Issue by lior21** [dailydotdev/daily#725]
### What went wrong? 🤔
The current icons service that is used for showing the custom shorcuts icons in a new tab, not returning the right icons in some cases.
It looks like an issue in the 3rd party icons service, but it affects the daily.dev new tab.
The icons are important especially since there is no other way to recognize the website in the custom link (like a title next to the icon)

### Expected Behavior
The custom icons in a new tab should look the same as in the default browser's new tab.
This is how the icons look in the default browser's new tab (not daily.dev's tab):
![image](https://user-images.githubusercontent.com/42876247/193252721-27d6b149-7f1f-4710-bc41-0d11879b9450.png)

### Actual Behavior
The custom icons looks different. Most of google services icons are showing google's icon instead of the specific service icon:
![image](https://user-images.githubusercontent.com/42876247/193253339-e47e5fa7-dd1a-465e-8f55-0003bc280a46.png)

### Steps to Reproduce Issue
add `photos.google.com` to your custom shortcuts. the expected icon is this one: 
![image](https://user-images.githubusercontent.com/42876247/193251929-17fc885a-b891-41f8-a54d-b58a1156e356.png)
but the actual icon is
![image](https://user-images.githubusercontent.com/42876247/193252028-38fb454b-9e1e-4534-8091-99192ce23a54.png)

### Solution
Switch to another 3rd party icons service

### Environment
The extension's new tab

#### Operating System
Windows 10

#### Version of Daily
3.16.16

#### Browser
Edge/Chrome

**Comment by idoshamun** [comment]
Hi @lior21,

We're indeed using a third-party service for it.
https://github.com/mat/besticon

We'll try to find our way around it and see how we can fix that.

**Comment by rebelchris** [comment]
Closing this one in favor of keeping this ticket:
https://github.com/dailydotdev/daily/issues/1399
