### ISSUE TITLE
🐛 BUG: Links always open in new tab

### ISSUE THREAD

**Issue by lior21** [dailydotdev/daily#727]
### What went wrong? 🤔
In the settings there is an option to toggle "Open links in new tab".
It seems like turnning OFF this option doesn't affect some of the most basic links in the app. they always open in new tab whether the option is enabled or not.
![image](https://user-images.githubusercontent.com/42876247/193426156-76026322-a075-4116-a8a9-e1067526ae16.png)

**Links that work as expected:**
1. the Read Article button **on the feed**
![image](https://user-images.githubusercontent.com/42876247/193426423-4bcf7c16-7b6f-4bdd-b830-2a12c7746332.png)

**Links that DO NOT work as expected:**
1. the Read Article button inside an article modal
2. the article's image inside an article modal
![image](https://user-images.githubusercontent.com/42876247/193426073-74fa1dce-3a4a-4e02-bcae-39db36c6d231.png)

### Expected Behavior
While the option is turned OFF, don't open links in new tab. especially links to articles.

### Actual Behavior
Some of the links are opened in new tab, without considering this option.

### Steps to Reproduce Issue
1. Go to the feed
4. Click an article (NOT the Read Article button)
5. now in the opened modal, click on the Read Article button or on the image in the article

### Solution
Make these links target to follow the user settings

### Environment
Web app + Extension's new tab

#### Operating System
Windows 10

#### Browser
Edge/Chrome

**Comment by idoshamun** [comment]
Hi @lior21,

Thanks for the report. We will fix it.

**Comment by NinadSutrave** [comment]
Hey @idoshamun may I work on this issue if no one else is currently working on it? 
If yes, pls let me know by assigning it to me.

**Comment by idoshamun** [comment]
Hi @NinadSutrave,

I think it should be fixed by now and we forgot to close the issue.
Did you experience it lately?

**Comment by NinadSutrave** [comment]
I checked it right now and it is working, my bad! 
Are there any other issues that a beginner could work on?

**Comment by idoshamun** [comment]
Perhaps @rebelchris can provide some suggestions :)
