### ISSUE TITLE
🧩 FEATURE REQUEST: Multiple customisable feeds

### ISSUE THREAD

**Issue by Aerochrome** [dailydotdev/daily#733]
## Feature Request
The ability to add more than one customisable feed, instead of just "My feed"

### Description

The idea is to be able to dynamically add new feeds which can be named individually (e.g. "Laravel Feed") and can have independent tag filters.

Use case for this would be to have multiple feeds that keep you up to date about different topics.
Like one feed for a specific framework, one feed for security related stuff, etc.

### Solution

Maybe new section called "custom feeds" below the "My feed" entry, with a little plus icon besides the headline which then leads you to a prompt to create a new feed and choose tags for said feed (just like the initial setup for "My feed" works)

### Alternate Solutions

N/A

**Comment by idoshamun** [comment]
Hi @Aerochrome,

Thanks for the suggestion. Let's keep the discussion here #336
