### ISSUE TITLE
🧩 FEATURE REQUEST: Customisable feed with multiple contents 

### ISSUE THREAD

**Issue by Amad3eu** [dailydotdev/daily#734]
## Feature Request
The ability to add more than one customizable feed instead of just one ("My Feed").

## Description
The idea is to be able to dynamically add new feeds that can be individually named (eg "React Feed") and can have independent tag filters.

Use case for this would be to have multiple feeds to keep you updated on different topics.
Like a feed for a specific framework, a feed for security related stuff, etc.

## Solution
Perhaps a new section called "Custom Feeds" below the "My Feed" entry, with a little plus icon next to the header that then leads to a prompt to create a new feed and select tags for that feed (which is how the initial setup for "My Feed" works)

## Alternate Solutions
N/A

**Comment by idoshamun** [comment]
Hi @Amad3eu,

Thanks for the suggestion. Let's keep the discussion here #336
