### ISSUE TITLE
I have always 10 reputations🐛 BUG: 

### ISSUE THREAD

**Issue by WebmonsterA** [dailydotdev/daily#737]
### Expected Behavior
I cant win reputation (always 10)

**Comment by idoshamun** [comment]
Hi @WebmonsterA,

What have you tried to do to get more reputation?
You can read more about how to win reputation here: https://docs.daily.dev/docs/how-does-daily-dev-work/reputation

**Comment by WebmonsterA** [comment]
Hi
I read this article, but i never win reputation :(

**Comment by idoshamun** [comment]
Please read our guide on how to earn reputation. It is not possible to earn reputation by reading
https://docs.daily.dev/docs/how-does-daily-dev-work/reputation

**Comment by lawson-ng** [comment]
Hi @idoshamun 
I have a comment which got 3 upvotes but my reputations always are 10. 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/72881474/221738169-5a2417d4-db9d-49a5-96ad-23e53e2aa7be.png">

<img width="646" alt="image" src="https://user-images.githubusercontent.com/72881474/221738254-ee589cf8-d457-4efe-9240-de355c947871.png">

**Comment by idoshamun** [comment]
Hi @lawson-ng,

As mentioned in our docs, you get reputation only when someone with at least 250 rep upvotes your comment.
Take a look here: https://docs.daily.dev/docs/how-does-daily-dev-work/reputation
