### ISSUE TITLE
🐛 BUG: The timezone list is a little bit wonky, the order is weird

### ISSUE THREAD

**Issue by omBratteng** [dailydotdev/daily#739]
### What went wrong? 🤔

The order of the timezones are in a strange order. `UTC 0` between two `UTF -4`, `UTF -3` could also be before and after a `UTC -4`.

### Expected Behavior

Timezones are in correct order.

### Actual Behavior

The order of the timezones are in a strange order. `UTC 0` between two `UTF -4`, `UTF -3` could also be before and after a `UTC -4`.

https://user-images.githubusercontent.com/1681525/194825008-a6e52221-9cb3-40b9-a959-9e238c156f2c.mp4

### Steps to Reproduce Issue

Go to https://app.daily.dev/account/others and scroll in the Timezone list

#### Operating System

macOS 12.6

#### Version of Daily

Web version, app.daily.dev (https://app.daily.dev/account/others)

#### Browser

Chrome 106.0.5249.103

**Comment by omBratteng** [comment]
Timezones are never easy 😓

**Comment by omBratteng** [comment]
Just want to bump this. A new issue occurred, it is showing UTC+1 as UTC+25
![image](https://user-images.githubusercontent.com/1681525/224784947-db21f6e6-23d2-4b55-be35-03ffaed5d9ce.png)

**Comment by idoshamun** [comment]
Thanks for the report @omBratteng, we will fix it!

**Comment by sshanzel** [comment]
Hi @omBratteng thanks for raising the issue! We should have fixed this in the commit below. Let us know if the issue still persists!

https://github.com/dailydotdev/apps/commit/1fdcd356679abf2876b477c361371583643abdfb
