### ISSUE TITLE
🐛 BUG: Tags' link not working properly

### ISSUE THREAD

**Issue by Azzarox** [dailydotdev/daily#748]
### What went wrong? 🤔
When search for a specific tag/category and pressed on “View” the link in the address bar says undefined and doesn't load the correct posts.

### Expected Behavior
To show the posts which are categorized by the clicked specific tag/category.

### Actual Behavior
Doesn't show the posts related to the specific tag/category.

### Steps to Reproduce Issue
1. From the homepage, click on the icon next to 'My Feed' heading at the top of the page. When hovered on the icon, it says 'Feed filters'.
&nbsp;
![step-1](https://user-images.githubusercontent.com/62171309/198309834-8947ddc4-12b9-4610-89de-427f6d2fdfb9.png)
&nbsp;

2. By now there should be an open window with menus: “Manage tags”,  “Advanced” and “Blocked list”. Click the “Manage Tags” (usually is the default one). Head to the search bar and write some category/tag. Ex: blockchain or react. (I tested with both and the outcome is the same)
&nbsp;
![step-2](https://user-images.githubusercontent.com/62171309/198310104-2362ee5b-0518-4319-874a-cee1ee61561b.png)
&nbsp;
3. By now should have many tags related to the search query. I wrote 'react'. Click on the 3 vertical dots at the far right of the tag.
&nbsp;
![Step-3](https://user-images.githubusercontent.com/62171309/198310258-316ebf2f-9cbc-4b82-b081-87b871055c10.png)
&nbsp;
4. After the 3 dots are clicked, there are 2 menus. 'View' and 'Block'. Click on the View.
&nbsp;
![Step-4](https://user-images.githubusercontent.com/62171309/198310274-0279f605-4a1f-411f-b79b-a1cbaa3e88db.png)
&nbsp;
5. After the View button is clicked, it is supposed to redirect to posts related only to the 'react' tag. Unfortunately, it redirects to /undefined
&nbsp;
![Step-6](https://user-images.githubusercontent.com/62171309/198310304-db1a63e7-8ef8-414f-9f7c-14139ff46ab5.png)

6. The same happens with the mobile version as well
Video: Unfortunately, the video's quality is lost, and it's not that high. However, I think the problem could'be seen regardless of the quality.

https://user-images.githubusercontent.com/62171309/198313349-c6449064-41ab-4f15-b5d1-a6da3b6dd7a6.mp4

### Solution
The bug is fixed if you go and manually type in the address bar the desired tag.
![Step6 1](https://user-images.githubusercontent.com/62171309/198309641-5b59aab7-8717-4aa3-91c6-aeb0b1443842.png)

### Environment
Firefox on Windows 10 Pro
Mobile: daily.dev application on Huawei P smart 2019.

#### Operating System
Window 10 Pro
Mobile: 
— Name: Huawei P smart 2019 
— Model: POT-LX1
— OS: Android 12 (a.k.a EMUI 12)
#### Version of Daily
Latest version
#### Browser
Firefox 106.0.1 (64-bit)

**Comment by idoshamun** [comment]
Hi @Azzarox,

Thanks for reporting! We'll look into that

**Comment by rebelchris** [comment]
Hi @Azzarox we solved the bug on the webapp already: app.daily.dev
The extension is coming soon.

Thanks again for logging this issue with us 🙏

**Comment by Azzarox** [comment]
I'm glad I could help! Thank you, for doing everything you can to bring such a cool service!
