### ISSUE TITLE
🧩 FEATURE REQUEST: Add smooth hover transition effect to all buttons

### ISSUE THREAD

**Issue by AnshuPathak-88825** [dailydotdev/daily#754]
pls assign me this issue

**Comment by idoshamun** [comment]
Hi @AnshuPathak-88825,

I forwarded this request to our design team, once they will provide the rules for the transitions, I'll get back to you :)

**Comment by AnshuPathak-88825** [comment]
I'll be waiting for you reply

**Comment by rebelchris** [comment]
Hi @AnshuPathak-88825 If you are up for it we created the design specs for it.
Basically the elements described in the design file can receive this 0.2 transition. 
https://www.sketch.com/s/2549ccf9-b98c-413f-96fb-81b05b59e65f/v/av7Jwp/p/6513C6CA-CC13-4B1E-9B88-B03E6736A232/canvas

If you have any further questions, don't hesitate to ask them.

**Comment by AnshuPathak-88825** [comment]
Yaa I'll do it pls assign this issue to me

**Comment by AnshuPathak-88825** [comment]
Do you have any discord server and slack channel ?

**Comment by AnshuPathak-88825** [comment]
@rebelchris ?

**Comment by rebelchris** [comment]
Hey sorry we don't have any public slack or discord at the moment.
Do you have any questions, as we can always setup a call.

**Comment by AnshuPathak-88825** [comment]
Currently I I'm busy in college study for exam so I'll start working on it in February

**Comment by ManishBisht777** [comment]
hi @AnshuPathak-88825 let me know if you need any help with this. we can split this into multiple pages hence it would be easy to review as well

**Comment by sanjeetiitr** [comment]
@rebelchris pl assign this issue to me.

**Comment by sshanzel** [comment]
Hi @AnshuPathak-88825 thank you for raising and wanting to fix this issue. Just wanted to check if you would still want to work on it.

**Comment by AnshuPathak-88825** [comment]
Sorry  I took so much time just because I forget about this issue now  I'm working on it so I'll try to resolve this issue by this week

**Comment by sshanzel** [comment]
@AnshuPathak-88825 all cool! If you need any help on anything, feel free to let me know and I'd be glad to help you out 🚢

**Comment by AnshuPathak-88825** [comment]
![Screenshot from 2023-04-14 17-06-40](https://user-images.githubusercontent.com/78332454/232033538-ec302f0d-ce15-4d1a-9bf2-f998fb565681.png)
@sshanzel I'm getting error while setup webapp in my local machine

**Comment by sshanzel** [comment]
> @sshanzel I'm getting error while setup webapp in my local machine

Using GitPod should allow you to work on this issue. Quick link: https://gitpod.io/#https://github.com/dailydotdev/apps/

Our local environment is a bit complicated to set up, but the suggested approach above should be able to tackle the task at hand. Let me know if you need further help to navigate it, I'd be glad to connect.

**Comment by AnshuPathak-88825** [comment]
I'm getting this error in gitpod
![Screenshot from 2023-04-15 16-28-32](https://user-images.githubusercontent.com/78332454/232209906-56dc2939-d38d-4af2-afc6-f940d331df56.png)

**Comment by AnshuPathak-88825** [comment]
![Screenshot from 2023-04-19 22-51-23](https://user-images.githubusercontent.com/78332454/233152110-d4cd582e-f5fa-471d-8a00-2d1a5766b91e.png)
design link not working

**Comment by sshanzel** [comment]
> design link not working

Apologies for the inconvenience. Kindly check the link below and let me know if you need some help clarifying the explanation in the design. As usual, feel free to send a message on Twitter as we did for the dev environment 🥳

**Comment by AnshuPathak-88825** [comment]
yaa sure

**Comment by rebelchris** [comment]
Closed as completed 🙏
