### ISSUE TITLE
🐛 [SETUP-ERROR]:  Garden not setting up.

### ISSUE THREAD

**Issue by dynamitechetan** [dailydotdev/daily#758]
I followed the instructions in the readme and I am successfully able to run the project with docker, have seed data and launch the webapp.

However, when i open the chrome extension, i get this error.. 
```
Failed to load resource:  http://api.apps.local.app.garden/boot?v=3.17.3   net::ERR_CONNECTION_REFUSED
```
<img width="422" alt="image" src="https://user-images.githubusercontent.com/14369357/198902355-9276a329-3fa5-4de9-91b3-a07711fff01c.png">

I saw there are no instructions to setup/run garden on the machine. Can someone please help here?

**Comment by idoshamun** [comment]
Hi @dynamitechetan,

Can you please use docker compose or gitpod instead? We are aware we have some issues with garden at the moment
