### ISSUE TITLE
🐛 BUG: improper styling in tooltip

### ISSUE THREAD

**Issue by murtuzaalisurti** [dailydotdev/daily#760]
## 🐛 Bug Report
Improper styling of tooltip suggesting users to manage their personal feed preferences.

### What went wrong? 🤔

![Screenshot (223)](https://user-images.githubusercontent.com/68743212/199536440-152a8488-573b-473e-9531-3d1df4a41ae7.png)

### Environment
Windows 10 - Google Chrome

#### Operating System
Windows 10

#### Version of Daily
3.17.5

#### Browser
Chrome 106.0.5249.121

**Comment by jessej-samuel** [comment]
Yep! The tooltip would be better directed ```top```

**Comment by idoshamun** [comment]
Should be fixed now! Thanks for reporting :)
