### ISSUE TITLE
🧩 FEATURE REQUEST:  Bookmarks button outside the menu directly on the card and on the companion widget

### ISSUE THREAD

**Issue by falcon-Z** [dailydotdev/daily#761]
### Description

Add Bookmark Button directly on the Card and Companion widget rather than having it under a menu as it would make bookmarking articles much easier and quicker.

### Solution
N/A

### Alternate Solutions
N/A

**Comment by idoshamun** [comment]
Hi,

Thanks for the suggestion this is a dup of https://github.com/dailydotdev/daily/discussions/638.
Let's keep the discussion there.
