### ISSUE TITLE
🐛 BUG: Failing search results redirect to empty reading history page

### ISSUE THREAD

**Issue by intelagense** [dailydotdev/daily#765]
### What went wrong? 🤔

I searched my reading history for an article but had a typo in my search query and ended up with zero results.
The page displayed that my reading history was empty instead of indicating there were no search results found.

Further testing showed that this also happens with searches under 3 characters in length.

### Expected Behavior

- Staying on the search results page with a clear statement that there were no results from my search.
- Not losing the input form with my previous search text that might need to be adjusted and resubmitted.

### Actual Behavior

Redirected to a page that displayed this:
> "Your reading history is empty."
> "Go back to your feed and read posts that spark your interest. Each post you read will be listed here."

There was no indication that the search failed and the search form was no longer visible. 

### Steps to Reproduce Issue

1. While logged in, Click or tap "Reading history" in the sidebar
1. Select the "Search reading history" field.
1. Search for something that shouldn't exist or search for a word that is 3 characters or less in length.
1. Submit the form and observe the resulting behavior.

### Solution

1. A conditional to check if any results were found. If no search results were found then the page should indicate that there were no search results and offer hints to improve the search text or request that the user checks for misspellings. 
1. A conditional to check the length of the search text and lets the user know that the search string is too short before allowing the form to be submitted.

### Environment

💡 Note: The original environment is detailed below but I was able to replicate the same behavior in Safari on mobile.

#### Operating System

Windows 10
22H2 19045.2251

#### Version of Daily

3.17.6

#### Browser

Chrome
Version 107.0.5304.107 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi @intelagense,

Thanks for reporting this issue. We will investigate and keep you posted :)

**Comment by itsajay1029** [comment]
Can I work on this issue @rebelchris ?
Please assign it to me

**Comment by rebelchris** [comment]
@itsajay1029 Awesome, let me know if you need any context or guidance.

**Comment by itsajay1029** [comment]
Can you help me understand the bug @rebelchris ?

**Comment by intelagense** [comment]
@itsajay1029  Here are some screenshots so you can try to replicate the behavior 

**Go to the Reading history:**
![image](https://user-images.githubusercontent.com/18331781/212982046-153cd021-8ee6-4b09-9a31-504a6f09e201.png)
---
**If you search for something that exists then the search performs as intended:**
![image](https://user-images.githubusercontent.com/18331781/212982249-13bcf427-d808-4950-95e9-798bf272dcb4.png)
---
**if you search for something that doesn't exist:**
![image](https://user-images.githubusercontent.com/18331781/212982545-58f876dc-ca01-45c2-b254-2a9e2ac2b8b8.png)
---
**this happens:**
![image](https://user-images.githubusercontent.com/18331781/212982622-807e78f9-43d7-4859-9b2c-e647bfa9b4f5.png)
---
The search input disappears and you have to navigate back into Reading history page to try searching again.

**Comment by intelagense** [comment]
Also I believe the problem is here: [fallback in history page](https://github.com/dailydotdev/apps/blob/539e948b317ed55a2d7c12a3560e7e0344d25f59/packages/webapp/pages/history.tsx#L57)
