### ISSUE TITLE
🧩 FEATURE REQUEST: 

### ISSUE THREAD

**Issue by Steven-zion** [dailydotdev/daily#766]
### Description
When i do a search using the search bar lets say 'docker', alot of  articles come up which is so annoying and time consuming because not all the articles explain what i wanted, for example i want docker intro using nodejs and maybe the first 20 are related to docker and python, flask, postgre etc

### Solution
Add a sort dropdown which will enable me narrow down my search, sort can be according to language e.g. nodejs, python etc. it may also be according to date because i saw an article traced back to 2020, i want a latest article. we can also sort according to source e.g. hashnode, dev.to, freecodecamp etc most of us trust certain article platforms more than the others 

### Alternate Solutions
if i scroll 50 articles down & don't find what i want i should be able to type another search specific term easily because the latest feature is i have to scrolll up again to do a search, when i scroll make the search bar fix itself on the bar with the logo, companion feature and pofile settings - in the middle

**Comment by idoshamun** [comment]
Hi @Steven-zion,

Thanks for the suggestion. We already have an active discussion on improving our search capabilities.
You can have a look here: https://github.com/dailydotdev/daily/discussions/294
