### ISSUE TITLE
🧩 FEATURE REQUEST: Fuzzy / General search 

### ISSUE THREAD

**Issue by lukejans** [dailydotdev/daily#772]
### Description

I have noticed a problem with daily dev in that you wont find what you're looking for unless you know the complete title word for word with identical matches. This is frustrating and limiting as knowing EXACTLY what you want is almost never the case. Therefore I think its necessary to add a toggle function to do exact search matching and fuzzy search matching!

### Solution

Adding a toggle on the search bar would be a great improvement and maybe the way this fuzzy search works would be to eliminate exact typing and have the engine look into the article or the description / tldr to show more results. Then the feedback to the user on search would be articles with the most word matches starting at the top and descending to least from there and giving tags a high priority also ex. #JavaScript, #git... Overall I think the exact search drives users away from using the platform to search specific article and mostly sends them to un curated google. 

Thank you for taking your time to read my feat request and hope to see discussion around this soon! Apologies in advanced if this has been discussed somewhere else as I could not find it in the feature request section.

Happy coding, Luke Janssen!

**Comment by idoshamun** [comment]
Hi @lukejans!

Thanks for the feedback. Search is a feature that needs a serious upgrade, and we know it. Unfortunately, our focus is somewhere else at the moment.
To keep the discussion on search centralized, please use this thread: https://github.com/dailydotdev/daily/discussions/294, and I'll close this issue.

P.S. love your picks!
