### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by mineshp-mecha** [dailydotdev/daily#775]
### What went wrong? 🤔

  Before getting started we have option to choose topics that we want to follow, so when i am selecting few topics after hitting _Done_ button but it is showing 'Choose at lease NaN topics to follow' :cry:    

### Expected Behavior

    It should be redirect to the main page or landing page for specific user. :+1: 

### Actual Behavior

    Error on Done click: 'Choose at lease NaN to follow'

### Steps to Reproduce Issue

 Using mozila firefox and this one this first screen

### Solution

1.   Get length of total topics
2. if selected topics has length greater than 0 then allow to submit

#### Browser
    Browser info:
        Mozila Firefox

![image](https://user-images.githubusercontent.com/104123812/205261156-aab7101b-c20c-4297-aeb1-5c5eb12f0cdc.png)

**Comment by vFlagz** [comment]
Same here
MacOS Ventura
Google Chrome

**Comment by rebelchris** [comment]
@mineshp-mecha @vFlagz thanks for logging this issue, it should work now again.
Thanks for logging this for our attention.

**Comment by mineshp-mecha** [comment]
yes it is working now, thanks!!
