### ISSUE TITLE
🐛 BUG: New tab not working properly on Opera GX

### ISSUE THREAD

**Issue by ayoub3bidi** [dailydotdev/daily#787]
## 🐛 Bug Report
Before anything else, I want to say that I am a huge fan of this extension ❤️.
### What went wrong? 🤔
While using Google Chrome the extension is working fine but when I switched to Opera GX I found out that the new tab is showing the extension like it wasn't installed, but when I click on the extension icon on the navbar It navigates me to the tab expected. I waited for quite some time now for a quick fix but it appears that no one has mentioned this bug before.

### Expected Behavior
When I click on a new tab the extension shows me the new interface created by the extension.

### Actual Behavior
When I click on a new tab it shows me a normal tab.

### Steps to Reproduce Issue

1. Install the extension on Opera GX

2.  Click on a new tab.

### Solution
Unfortunately, I don't have an answer.

### Environment
I didn't quite understand what I should put here.

#### Operating System
Windows 10

#### Version of Daily
Latest version

#### Browser
Opera GX

**Comment by idoshamun** [comment]
Hi @ayoub3bidi,

Unfortunately, we don't officially support Opera GX but I'll see what we can do about it

**Comment by ayoub3bidi** [comment]
Thanks❤️
