### ISSUE TITLE
🐛 BUG: STEP #4 fails - QueryFailedError: relation "public.advanced_settings" does not exist

### ISSUE THREAD

**Issue by Ayushpandey80** [dailydotdev/daily#803]
### What went wrong? 🤔

On trying Step 4, we get an error on terminal.

Stacktrace added.

`importing AdvancedSettings
QueryFailedError: relation "public.advanced_settings" does not exist
    at PostgresQueryRunner.query (/opt/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/opt/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async importEntity (/opt/app/bin/import.js:14:9)
    at async start (/opt/app/bin/import.js:19:5) {
  query: 'INSERT INTO "public"."advanced_settings"("title", "description", "defaultEnabledState") VALUES ($1, $2, $3), ($4, $5, $6), ($7, $8, $9), ($10, $11, $12), ($13, $14, $15) RETURNING "id", "defaultEnabledState"',
  parameters: [
    'Tech magazines',
    'Show tech news posts that are not related directly to programming, for example, reports about tech companies, startups, venture capital, and scientific discoveries.',
    true,
    'Newsletters',
    'Show posts that were published on developer newsletters. Such posts usually contain curated lists and opinionated essays.',
    true,
    'Product launches',
    'Show posts that aim to help you discover new product launches or major releases to existing developer tools.',
    true,
    'Showcases',
    'Show posts that aim to showcase a project or other types of code snippets. These posts usually provide a demo-only of the showcased work without broader context around it.',
    true,
    'Non-editorial content',
    'Show user-generated posts that were created on external blogging platforms. Such posts are usually not checked by professional editors for fact accuracy, spelling, grammar, and punctuation.',
    true
  ],
  driverError: error: relation "public.advanced_settings" does not exist
      at Parser.parseErrorMessage (/opt/app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/opt/app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/opt/app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/opt/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 123,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '13',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1156',
    routine: 'parserOpenTable'
  },
  length: 123,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '13',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1156',
  routine: 'parserOpenTable'
}
`
#### Screenshot of the error: 
https://ibb.co/rk4Jkvd

### Operating System 
MacOs Ventura Version 13.0.1

**Comment by Ayushpandey80** [comment]
Step 3 was success. screenshot added.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/7960136/214214845-f54f966d-e5a7-4dd5-bd5b-ec395eb2b82b.png">

**Comment by rebelchris** [comment]
@Ayushpandey80 Thanks for logging the issue.
I'll log it for a quick research.

In the mean time, we actually recommend using our GitPod version for development.
You can quickly open it via the [`apps` repo](https://github.com/dailydotdev/apps).

**Comment by rebelchris** [comment]
@Ayushpandey80 I also modified step 3 a bit, with the most updated version, so you can also try to re-run that.

**Comment by Ayushpandey80** [comment]
Issue fixed after the changes you made. Thanks @rebelchris
