### ISSUE TITLE
🧩 FEATURE REQUEST: Allow Gmail access from daily.dev page

### ISSUE THREAD

**Issue by AndreaDellaValle** [dailydotdev/daily#807]
## Feature Request

Would be super appreciated to have one-click access to Gmail

### Description

Chrome + Gmail + Google users are used to accessing their Gmail accounts with one clicker from the browser home page.
After installing Daily.dev this requires a search instead of a simple new tab opening.
_I know this sounds like a super minor, but as a new Daily.dev user I was about to uninstall it almost immediately because of this (I hope to be not your average case)._

### Solution

I think this could be done by taking users' emails retrieved from Google Oauth API data to fill the link to their respective Gmail accounts like this `https://mail.google.com/mail/u/${user.name}@gmail.com`.

Thank you for your great work 💪

**Comment by idoshamun** [comment]
Hi @AndreaDellaValle,

Have you tried our shortcuts feature? You can set whatever shortcuts you want.
I believe this should address your concern.
Please let me know what you think :)

**Comment by AndreaDellaValle** [comment]
Yes but actually, I think the new tab approach is too invasive in my case, Gmail link was the bare minimum to me, but also all the other links are gone (or at least, that's what it seems to me). 
So I think I'll try your APIs instead, or try to make a PR for the extension if I find a feasible solution.

On the other side, if you are willing to provide a more seamless experience within the new-tab extension I can try to give you some hints (I'm listing only them, **without checking the feasibility**):
- Prefill shortcuts with the user's one
- Put the feed aside/along the default user page with all of their customizations
- Set user's expectation on what will happen: when you first see a Daily.dev add/readme/post your expectation is to be up to date with dev news, not you have your browser totally changed, to make a trivial example, with Arc, it's very clear that your browsing experience is gonna change, maybe you can try to be more explicit about this.
