### ISSUE TITLE
🐛 BUG: Don't show post option should be hidden from feeds where it doesn't apply

### ISSUE THREAD

**Issue by mauchchhash** [dailydotdev/daily#824]
## 🐛 Bug Report

I keep clicking "Don't show posts from The Verge" and it goes on and shows me posts from The Verge.

### What went wrong? 🤔
"Don't show posts from XYZ" not working.

### Expected Behavior
Doesn't show post from XYZ after I click on "Don't show posts from XYZ" from the menu of an article box.

### Actual Behavior
Goes on and continues show me article from XYZ.

### Steps to Reproduce Issue
 Click on "Don't show posts from The Verge" on a post from The Verge

**Comment by idoshamun** [comment]
Hi @mauchchhash,

The "Don't show" feature works only in my feed at the moment.
If you keep seeing these articles you are probably on another feed.
Can you confirm please?

**Comment by mauchchhash** [comment]
I see this in the feed that opens when I open a new tab. on the left hand side menu bar it shows I am in the "Popular" page. I don't see any "My Feed".
![Capture1](https://user-images.githubusercontent.com/51711462/221844211-4e09edff-6f28-43ff-9dc6-a9171b98a1f6.PNG)

**Comment by idoshamun** [comment]
@mauchchhash You need to complete the onboarding by selecting your favorite topics

**Comment by mauchchhash** [comment]
Oh ok I get it. But maybe the "Don't show posts from XYZ" option sould be hidden if it's only working for my feed at this moment.

**Comment by idoshamun** [comment]
Yes, you're right. I'll forward it internally

**Comment by rebelchris** [comment]
@idoshamun Is this actually still relevant with all recent changes we did?

**Comment by idoshamun** [comment]
I think we can close it as it is fixed now
