### ISSUE TITLE
🐛 BUG:  Log in error not showing

### ISSUE THREAD

**Issue by kenhorlador** [dailydotdev/daily#825]
### What went wrong? 🤔
It doesn't show an error when I enter a wrong password.

### Expected Behavior
I expect it to throw an error when I enter a different password.

### Actual Behavior
It doesn't do anything. 

### Solution
Show an error if the user inputs a wrong password.

### Environment
i5 12th gen processor with 16gb of ram

#### Operating System
Windows 11 Pro

#### Browser
Brave Browser

**Comment by sshanzel** [comment]
Hi @kenhorlador! Thanks for reporting the issue. There should be an indicator under the `email` field when you have an invalid combination.

![image](https://user-images.githubusercontent.com/13744167/221770341-10874a7c-1934-40a7-a056-c27bb1c48a32.png)

**Comment by idoshamun** [comment]
And if it's not the case, can you please share your network panel in the devtools so we can have a better sense of what's going on please?

**Comment by kenhorlador** [comment]
Hello, thank you for the sudden response. I checked it again and it's now working. I would like to suggest that it'd be best if you'll add a distinctive UI when showing errors. Anw, I just want the OS community to have a excellent product. Kudos to the team. I'll be closing this now. 
Have a blessed day!

**Comment by sshanzel** [comment]
> Hello, thank you for the sudden response. I checked it again and it's now working. I would like to suggest that it'd be best if you'll add a distinctive UI when showing errors. Anw, I just want the OS community to have a excellent product. Kudos to the team. I'll be closing this now.
Have a blessed day!

Thank you for the kind words! I agree with your thoughts, I actually forwarded this to our design team for verification on the day you raised the issue as I also realized that this needs to be more noticeable. We will apply the fix soon! 🙌
