### ISSUE TITLE
🐛 BUG: "load more" functionality on listview is broken

### ISSUE THREAD

**Issue by cytostatic** [dailydotdev/daily#828]
## 🐛 Bug Report

On Windows 11 in MS Edge the listview "My Feed" or "Popular" seems to stop working correctly. This behavior is noticeable in the Browser Extension and even in the web app.

### What went wrong? 🤔

When the page is scrolled to the end too fast, no more content is loaded. It is working as expected on mobile devices and even in Chrome on Windows but not in MS Edge.

There is a weird behavior. If the page is scrolled to the end, wait a bit, then scroll up a bit and wait again. More content gets loaded.

#### Operating System

Latest Windows 11

#### Version of Daily

Latest

#### Browser

MS Edge Version 110.0.1587.63 (Offizielles Build) (64-Bit)

**Comment by rebelchris** [comment]
@cytostatic thanks for reporting, we'll look into this.

**Comment by sshanzel** [comment]
Hi @Abhijeetmishr - this should be the primary ticket. Mentioning you here so I can assign this to you 🚢

**Comment by Abhijeetmishr** [comment]
Hey @sshanzel please do.
Happy to contribute.

**Comment by Abhijeetmishr** [comment]
Hi @sshanzel If you don't mind asking you few questions regarding project setup and all.
I am able to setup and open project using gitpod and running in local.
But before that do we have to fork this repo first then open it in gitpod ?

This is the first time I am using gitpod.

**Comment by Abhijeetmishr** [comment]
**I am not able to login locally into daily.dev. How to test infinite scroll behavior ?**
![image](https://github.com/dailydotdev/daily/assets/43075376/9f5e6336-1c62-4d55-b314-33ea6e637a1d)

```
export interface UseFeedInfiniteScrollProps {
  fetchPage: () => Promise<unknown> | void;
  canFetchMore: boolean;
}

export const InfiniteScrollScreenOffset = classed(
  'div',
  'absolute bottom-screen desktopL:bottom-screen-20 left-0 w-px h-px opacity-0 pointer-events-none',
);

export default function useFeedInfiniteScroll({
  fetchPage,
  canFetchMore,
}: UseFeedInfiniteScrollProps): (node?: Element | null) => void {
  const { ref: infiniteScrollRef, inView } = useInView({
    rootMargin: '20px',
    threshold: 1,
  });

  useEffect(() => {
    if (inView && canFetchMore) {
      fetchPage();
    }
    // @NOTE see https://dailydotdev.atlassian.net/l/cp/dK9h1zoM
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [inView, canFetchMore]);

  return infiniteScrollRef;
}

```
I guess this is code responsible for infinite scrolling of feeds

**Comment by Abhijeetmishr** [comment]
> Hi @Abhijeetmishr do you mind sending your Twitter link or somewhere I can contact you? So we can have an easier time discussing the points.

Here you go
https://twitter.com/ABHIJEET_OO7

Thanks

**Comment by rebelchris** [comment]
We recently modified the ref and how it loads more posts.
I believe this fixes the issue addressed here.

If people still have this issue, please open a new ticket and we'll take it from there.
