### ISSUE TITLE
🐛 BUG: Upvote button and counter from popup differs from the article list

### ISSUE THREAD

**Issue by NachoNievaG** [dailydotdev/daily#830]
### What went wrong? 🤔
After opening a TL;DR view, upvoting, and going back to the article list, the upvote counter was updated yet the upvote button let me upvote again.

The upvote count starts to work weirdly after this.
https://user-images.githubusercontent.com/83428506/223110327-301dd6c0-330c-456b-b049-c20e614fa09a.mov

### Expected Behavior
After upvoting in the post, and exit, the upvote button of the same article should be green, and the upvote count should be the same.

### Actual Behavior
The counter updated, yet i could still upvote

### Steps to Reproduce Issue

1. Locate an article in a list.
2. Open that article without losing track of it.
3. Upvote (note the count and button state)
4. Go back to the list and check the article item. (note the count and button state)
5. Add upvote, from here the behavior is weird

### Solution
Sorry, i'm not that much of a front-end guy :(

#### Operating System
MacOS Monterey 12.4
#### Version of Daily
Web
#### Browser
Firefox 110.0

**Comment by idoshamun** [comment]
Hi @NachoNievaG,

Thanks for reporting this issue!
It's a UI glitch, our backend doesn't allow multiple upvotes so don't you worry about abusing the system but we have to address this issue nevertheless.

**Comment by rebelchris** [comment]
@NachoNievaG thanks for reporting we provided a fix for this use-case which is now live on the webapp :)
