### ISSUE TITLE
🐛 BUG: Prohibited usernames not enforced

### ISSUE THREAD

**Issue by flame-0** [dailydotdev/daily#833]
Users are able to register with prohibited usernames such as `account`, `callback`, and `posts`.

Example, https://app.daily.dev/account where it uses [profile](https://app.daily.dev/account/profile), [security](https://app.daily.dev/account/security), [notifications](https://app.daily.dev/account/notifications), and [others](https://app.daily.dev/account/others).

![image](https://user-images.githubusercontent.com/40175769/223763055-c001f1b8-5a51-4614-aa6b-a5fefa0c8f85.png)

**Comment by flame-0** [comment]
Currently, I am using the username `callback`, and it's just blank, as expected. Now, no one can see my profile.

**Comment by idoshamun** [comment]
Hi @flame-0,

Good catch! We'll fix it. Thanks a lot

**Comment by Noothan-am** [comment]
hey @idoshamun, is this issue resolved?

**Comment by idoshamun** [comment]
Unfortunately not yet

**Comment by rebelchris** [comment]
Closed as completed by @idoshamun
