### ISSUE TITLE
Ban tags from feed

### ISSUE THREAD

**Issue by jonasschultheiss** [dailydotdev/daily#84]
#### Feature Suggestion

I recently got daily and I really, really like it.

The only problem I have is, that I get shown articles of, as an example, GO or Golang. I'm not interested at all, but it gets shown to me because of the a # that I selected previously, #development as an example. Or Angular articles because of #web.

In my opinion it would be great, if a user could select tags/# which he *doesn't* want on his feed.

**Comment by idoshamun** [comment]
Hi @quest1onmark,
We really appreciate these kind words :)
Regarding your feature suggestion it is very much like #55.
At first as you can see there we thought this feature might cause some conflicts but now we are rethinking the whole feed queries that we currently have.
You can keep track here on the implementation of the new query endpoint https://github.com/dailynowco/daily-api/issues/22.
I will leave this issue open to remind me we have to address this as well.

**Comment by sshanzel** [comment]
Hi! I would love to contribute, just let me know where i should look to get started with this. Thanks a lot! Great extension btw, lovin' it also.

**Comment by idoshamun** [comment]
Hi @sshanzel,
Thank you for being so eager to contribute. Unfortunately, this feature is not at the right stage. 
Hopefully, in the upcoming days, I will submit some issues for community contribution :)

**Comment by sshanzel** [comment]
No worries, i just love contributing on things that i actually use "daily". Lol. Guess I'll check the issues tab for another thing to hit! :P

**Comment by maxter161** [comment]
Now after having the GraphQL feature added, would you reconsider implementing this feature?

**Comment by idoshamun** [comment]
Hi @maxter161,
Thanks for raising again this issue.
We are now considering the future roadmap for Daily 3.0, this feature might find its way in as part of advanced feed filtering. Might take a while though.
In the meantime stay safe :)

**Comment by idoshamun** [comment]
Good news everyone!
This feature got prioritized and we're working hard to deliver it fast.
Expect it to launch soon! (very soon)

**Comment by idoshamun** [comment]
The feature is live in our web app and soon will be available on the extension as well 🚀
