### ISSUE TITLE
🐛 BUG: Adjacent Repeating Posts

### ISSUE THREAD

**Issue by Anmol-Baranwal** [dailydotdev/daily#840]
## 🐛 Bug Report

The same post is repeated twice side by side

### What went wrong? 🤔

The same post is repeated twice side by side, which feels inconsistent. It's okay if there is a difference of a few rows, but showing the same post in an adjacent manner is definitely a bug.

> Awesome UI Interactions with Scroll Reveal

![Awesome UI Interactions with Scroll Reveal](https://user-images.githubusercontent.com/74038190/225414164-b879bcdc-f534-47b2-a620-0f2f00625b17.png)

> Raycast AI 

![Raycast AI](https://user-images.githubusercontent.com/74038190/225414171-a660bb3a-03b0-4a93-8548-b00b691cbcf4.png)

### Expected Behavior

This creates confusion, so the usual behavior is expected.

### Steps to Reproduce Issue

1. The posts are repeating in the `Most Upvoted` section. 

I tried to reproduce this issue and encountered the same bug with a different post.
> I'm not aware of any other sections affected by this issue.

### Environment

Chrome OS Latest Version 

#### Operating System

Windows 10

#### Version of Daily

> Don't know for sure.

#### Browser

Chrome Desktop (I have already attached screenshots above for reference)

**Comment by idoshamun** [comment]
Hi @Anmol-Baranwal,

Thanks for the report. We will fix it!

**Comment by rebelchris** [comment]
We fixed this a while a go.
@Anmol-Baranwal closing this topic for now, but feel free to let me know if it's still happening on your side.

**Comment by Anmol-Baranwal** [comment]
> We fixed this a while a go. @Anmol-Baranwal closing this topic for now, but feel free to let me know if it's still happening on your side.

It has been some time since I used daily.dev. Thanks for letting me know that the issue is fixed.
