### ISSUE TITLE
Of🧩 FEATURE REQUEST: Can I have a list of tags readily available to use?

### ISSUE THREAD

**Issue by qwertydiy2** [dailydotdev/daily#841]
I know this is not exactly a feature but I found that your tags were great for SEO purposes and I was just wondering if it was possible to get a plaintext list of them. Also I was wondering if there is a place where this is updated.

**Comment by idoshamun** [comment]
Hi @qwertydiy2,

We don't provide a way to get the full list of our tags.
Thanks for reaching out!
