### ISSUE TITLE
🐛 BUG: DevCard breaking through menu styling issue

### ISSUE THREAD

**Issue by SiddheshBangar** [dailydotdev/daily#844]
### What went wrong? 🤔
While using daily.dev web app on IOS device the dev card is hovering over the side menu which makes it troubling to navigate through the side menu
![issue](https://user-images.githubusercontent.com/80825073/226119247-fd80ac6e-6b28-4226-8538-01cebe0bdf7d.jpg)

### Expected Behavior
The Dev card that is generated should go behind the side menu

### Actual Behavior
The Dev card is getting in between the side menu when the side menu is popped up

### Steps to Reproduce Issue
Create a shortcut of daily.dev app on your IOS device
Later try to generate your dev card on it
Bring the side menu by swiping from the left 

#### Operating System
iPhone 11 

#### Browser
Safari

**Comment by idoshamun** [comment]
Hi @SiddheshBangar,

Thanks for the report. We will fix it!

**Comment by rebelchris** [comment]
@SiddheshBangar We just released a fix for this.
Do let us know if you experience any other weird behaviours 🙏
