### ISSUE TITLE
🐛 BUG: Hyphen disrupts the name

### ISSUE THREAD

**Issue by Anmol-Baranwal** [dailydotdev/daily#855]
## 🐛 Bug Report

I have a username on daily.dev as Anmol-Baranwal, but it isn't properly tagged when someone replies directly. 

### What went wrong? 🤔

![image](https://user-images.githubusercontent.com/74038190/227603650-e8af19a6-5089-4bfb-a342-82f1ce511d48.png)

![image](https://user-images.githubusercontent.com/74038190/227604510-3fc46591-16d7-45a6-a357-7eb557e0af3c.png)

Due to this, people cannot visit my profile by clicking the link, since the hyphen disrupts the same.

This is very frustrating because it shows the name of someone else and really seems weird.

> I use Anmol-Baranwal across 10+ platforms, and so I am using it to maintain consistency.

Please fix this as soon as possible, as I want people to be directed to my profile rather than others.

**Comment by idoshamun** [comment]
Hi @Anmol-Baranwal,

Thanks for reporting this. We will address it.

**Comment by ArslanYM** [comment]
@idoshamun any thoughts on how we can fix it?
