### ISSUE TITLE
🐛 BUG: Daily Dev icon/content blocking YouTube page

### ISSUE THREAD

**Issue by zinebelouarradi** [dailydotdev/daily#856]
Description
I'm experiencing an issue where the Daily Dev icon and content are blocking my YouTube page, preventing it from reloading. The issue occurs consistently and is reproducible across multiple browsers and devices.

Steps to Reproduce
Visit a YouTube page while the Daily Dev icon is present on the screen.
Wait for the page to load.
Observe that the Daily Dev icon and buttons are blocking the YouTube page and preventing it from reloading.

Screenshots
<img width="889" alt="Screenshot 2023-03-25 at 14 58 09" src="https://user-images.githubusercontent.com/58147119/227725629-aef9958b-b463-441c-94b9-2e772f3a07da.png">

Additional Information
Browser and version: Chrome Version 111.0.5563.64 (Official Build) (x86_64)
Operating system: macOs

**Comment by rebelchris** [comment]
@zinebelouarradi Thanks for logging this issue, we will investigate this and solve it.
Will keep you posted in this thread.

**Comment by rebelchris** [comment]
Hi @zinebelouarradi This was fixed yesterday by our team on investigation.
Are you still experiencing this issue?
