### ISSUE TITLE
🐛 BUG: Hashnode profile not showing on Daily.dev account

### ISSUE THREAD

**Issue by Anmol-Baranwal** [dailydotdev/daily#861]
## 🐛 Bug Report

Despite entering the correct Hashnode username in the Daily.dev account details, the branding logo of Hashnode is not visible on my profile.

### What went wrong? 🤔

My Hashnode profile: https://hashnode.com/@anmolbaranwal
My Hashnode Blog: https://anmolbaranwal.hashnode.dev/

Daily.dev account details with correct Hashnode username:
![Screenshot (3184)](https://user-images.githubusercontent.com/74038190/229357928-f94d3b19-97a0-4cca-a0ed-6a21e810ef4f.png)

<br>

Daily.dev profile is not updated:
![image](https://user-images.githubusercontent.com/74038190/229357988-7d0df97e-59ab-4f0b-b4d5-6b753481ba95.png)

<br>

I received an error message on my account dashboard that said `Invalid hashnode` when I tried using the full URL `anmolbaranwal.hashnode.dev`. Can you please help me resolve this issue?

#### Operating System

Windows 10

#### Browser

Chrome

**Comment by idoshamun** [comment]
Hi @Anmol-Baranwal,

Thanks for reporting it 🙏

**Comment by mrswapnilsahu** [comment]
Hi @idoshamun ,

Can I work on this issue?

**Comment by mrswapnilsahu** [comment]
Hi @sshanzel ,
![WhatsApp Image 2023-05-05 at 00 41 46](https://user-images.githubusercontent.com/23381895/236305642-54a29522-cd1c-4ad7-9fb2-f173f95151ac.jpeg)

I am getting this error when I am trying to run the app locally.

**Comment by mrswapnilsahu** [comment]
@rebelchris @sshanzel Can u plz hop in here and help

**Comment by sshanzel** [comment]
Hi @mrswapnilsahu! Really sorry that it has taken some time for us to respond. We are glad to let you know that we have recently made changes to our GitPod setup and have verified that it is now working again. You can find the link in the README but you can use the quick link I have included below 🥳 

https://gitpod.io/#https://github.com/dailydotdev/apps/

**Comment by mrswapnilsahu** [comment]
@sshanzel Thanks for the help it's working now. How I can login to my account in local ? 
Right now I am getting this
![image](https://github.com/dailydotdev/daily/assets/23381895/5fb471bf-da2b-4626-9955-d46ededc4b76)

**Comment by sshanzel** [comment]
@mrswapnilsahu Unfortunately, the authentication system has yet to work with GitPod, we will only be able to test it once you have raised a PR and see the preview deployment whether the relevant component would now show properly.

Also after checking the network tabs, it seems the issue is with the missing `hashnode` property on the profile query. There should be a query named `USER_BY_ID_STATIC_FIELDS_QUERY` that can be found in `src/graphql/users.ts`. I think by adding the missing property, it should fetch the necessary information to display.

**Comment by mrswapnilsahu** [comment]
@sshanzel Okay got it. Raised the PR for the same.

**Comment by sshanzel** [comment]
> @sshanzel Okay got it. Raised the PR for the same.

Wow! You are definitely fast! Will check this now 🤯
