### ISSUE TITLE
🧩 FEATURE REQUEST: Add more information to squad post input

### ISSUE THREAD

**Issue by amandamartin-dev** [dailydotdev/daily#869]
### Description

As a new user, it is unclear in a squad that there are 2 steps to post an article:
Step 1: entering the link and clicking post
![postInput](https://user-images.githubusercontent.com/97615019/231285244-487b4ac8-7d10-43fc-b32b-7b997e9f60e5.PNG)

which opens the modal to..
Step 2: Adding a description where you ultimately complete your post
![postStep2](https://user-images.githubusercontent.com/97615019/231285291-b4e7cc2d-f96c-4ad0-9354-a3416fb674b0.PNG)

### Solution

Low hanging fruit solution:  
Change the button text on Step 1 from "Post" to "Next" and the button on step 2 from "Done" to "Post"

### Alternate Solutions
Secondary "low hanging fruit" idea:
In addition to the above text swap, also include an adjustment to the placeholder text in Step one to help the user understand there is a second part.  Something like "Step 1/2: Enter a link"

More involved solution:
Get rid of the 2 part process and replace with a single form with 2 part input (url and text)

**Comment by idoshamun** [comment]
Hi @amandamartin-dev,

Thanks a lot for the feedback.
We'll do our best to improve this process.

**Comment by amandamartin-dev** [comment]
> Thanks a lot for the feedback. We'll do our best to improve this process.

Np! If you want to move forward with one of these ideas, happy to take on the issue or continue the discussion if you'd like to brainstorm other options. Thanks for the consideration

**Comment by sshanzel** [comment]
Hi @amandamartin-dev thank you so much for the feedback. We have recently made changes to address the concern and we do hope that the experience is better now.

With that, we will be closing this now. Please feel free to let us know if you have additional thoughts, it is highly appreciated 🙏
