### ISSUE TITLE
🧩 FEATURE REQUEST: Be able to read articles from bookmarked sources

### ISSUE THREAD

**Issue by leandromonaco** [dailydotdev/daily#870]
## Feature Request

Be able to read articles from my favorite sources rather than random ones based on tagging.

### Description

At the moment the work around is to hit the Source URL (e.g. https://app.daily.dev/sources/dotnet), but being able to bookmark in the app would be really handy.

### Solution

Something similar to what Feedly does

**Comment by sshanzel** [comment]
Hi @leandromonaco! You should be able to get to the Source's feed by clicking on their icon, or as how you did it, type the relevant URL. 

> but being able to bookmark in the app would be really handy.

You should be able to bookmark posts from the feed itself! When you hover a card, you should be able to see an icon with three dots and click it for the options menu to show (like in the screenshot below). From there, you should be able to hit "Save to bookmarks". Let me know if that helps! 🚀 

![image](https://user-images.githubusercontent.com/13744167/231331372-ab5598df-ea16-4ebe-a622-d2284373fdea.png)

**Comment by sshanzel** [comment]
> I can bookmark articles, but can't bookmark sources, which is what I'm looking for with this feature request.

Oh, right. Like some quick links to help you easily navigate. Thanks for the idea! I'll forward it to the team.

**Comment by sshanzel** [comment]
Hi @leandromonaco! After checking with the team, the feature used to be present in the app, but after doing some revamping, it was decided to be removed, though it is in our backlog to be brought back. I will let you know once it comes near the development. Again, thank you for the suggestion!

**Comment by leandromonaco** [comment]
Thanks for following this up, @sshanzel.

I'll stay tuned 👀

**Comment by leandromonaco** [comment]
Hello, this issue is marked as completed, but I couldn't easily find how to use this on Mobile. Is there a release notes about it?

**Comment by sshanzel** [comment]
Hi @leandromonaco, thank you for your interest, the reason we had to close it is that, as mentioned, we currently have nothing planned to have this back.
