### ISSUE TITLE
🐛 BUG: Home tab crash

### ISSUE THREAD

**Issue by mnzsss** [dailydotdev/daily#875]
### What went wrong? 🤔

I can't see posts in new tab.

### Steps to Reproduce Issue

```bash
1. Open new tab
```

### Screenshots

```bash
![when open a new tab](https://user-images.githubusercontent.com/51327920/233479594-2dcdb4e2-1cfa-4b75-b101-6777d233e8c4.png)

![open bundle resource in devtools](https://user-images.githubusercontent.com/51327920/233479717-b62833e6-ee04-427b-a625-96055a1f87dc.png)
```

### Environment

I'm using Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit) Running in Arch Linux

### Browsers

Brave

### OS

Linux

### Version of daily.dev

3.24.9

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/dailydotdev/.github/blob/master/CONTRIBUTING.md) of this project.

**Comment by idoshamun** [comment]
Hi @mnzsss,

Thanks for reporting. Can you provide your daily dev username please?

**Comment by mnzsss** [comment]
> Hi @mnzsss,
> 
> Thanks for reporting. Can you provide your daily dev username please?

My nickname is - mnzss

**Comment by sshanzel** [comment]
Hi @mnzsss thank you for reporting the issue. We should have fixed this by now, let us know if the concern still persists. Also, we really appreciate the screenshots you've included so just wanted to give you our thanks for that.

**Comment by mnzsss** [comment]
> Hi @mnzsss thank you for reporting the issue. We should have fixed this by now, let us know if the concern still persists. Also, we really appreciate the screenshots you've included so just wanted to give you our thanks for that.

Thanks for supporting!
