### ISSUE TITLE
[Bug] - Broken styling for the username input field in signup modal

### ISSUE THREAD

**Issue by Avi-88** [dailydotdev/daily#877]
The styling for the username input  field breaks and renders a default input field which breaks the consistency of the form 

![broken input](https://user-images.githubusercontent.com/79744258/219111674-f264b9b1-0016-43a4-93f3-8b7879a8a5d3.png)

The bg-transparent is being overridden by another css styling, removing the (!important) property from that should fix this. I would be glad to work on this . Please let me know if there are any corrections,  so I can attach a quick PR for this, thanks

**Comment by mrswapnilsahu** [comment]
@sshanzel Looks like @scjuly19 haven't raised any PR for it yet. Can I work on this now?

**Comment by sshanzel** [comment]
Hi @mrswapnilsahu, sure thing. Let me assign you this, kindly refer to the comment I made above for the guide on how to start with this one. Thank you for the interest!

**Comment by binalajudiya** [comment]
@sshanzel Is the issue still open?

**Comment by sshanzel** [comment]
Yes. Let me know if you want me to assign it to you 🙌
