### ISSUE TITLE
🐛 BUG: Username tag is not working properly

### ISSUE THREAD

**Issue by Anmol-Baranwal** [dailydotdev/daily#880]
### What went wrong? 🤔

When replying to [daily account](https://app.daily.dev/minji.mario), the text isn't highlighted as it should be, which causes it to not work correctly.

![image](https://user-images.githubusercontent.com/74038190/234344512-415e02b8-357d-4645-a82e-9932411faef7.png)

### Expected Behavior

It should be highlighted as usual.

<br>

![image](https://user-images.githubusercontent.com/74038190/234344828-2907b7f1-9e85-489a-90a9-ea654da1422a.png)

### Steps to Reproduce Issue

```bash
1. Reply to `@minji.mario` won't work.
```

### Solution Proposed

This issue may be occurring due to the `dot (.)` in the username.

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Anmol-Baranwal,

Thanks for yet another good catch!
We will fix it.

**Comment by AshwanthramKL** [comment]
Hey @idoshamun, I'd like to work on this.

**Comment by sshanzel** [comment]
Hey there @AshwanthramKL thank you for wanting to help us fix the raised issue! 🥳 

The core issue here is that we are using two different kinds of regex pattern for identifying a mention and when updating the user's handle. Our ideal solution would make them use the same reference for checking regex pattern. The regex patterns can be found in [this repo](https://github.com/dailydotdev/daily-api). Let me know if you need further guidance!

We have some test cases (in daily-api repo) you can play around with it to verify if existing mentioning still works including the one we are trying to fix here. You might have to pull the daily-api repo and run `docker-compose` then introduce a new test case showing usage of mention with dot `.` character.

**Comment by AshwanthramKL** [comment]
> Hey there @AshwanthramKL thank you for wanting to help us fix the raised issue! 🥳
> 
> The core issue here is that we are using two different kinds of regex pattern for identifying a mention and when updating the user's handle. Our ideal solution would make them use the same reference for checking regex pattern. The regex patterns can be found in [this repo](https://github.com/dailydotdev/daily-api). Let me know if you need further guidance!
> 
> We have some test cases (in daily-api repo) you can play around with to verify if existing mentioning still works including the one we are trying to fix here. You might have to pull the daily-api repo and run `docker-compose` then introduce a new test case showing usage of mention with dot `.` character.

Hey @sshanzel, thanks for the guidance. I'll start working on it. Will let you know if I need further guidance(which I probably will )

**Comment by rebelchris** [comment]
Closed by @idoshamun recent username fix
