### ISSUE TITLE
🧩 FEATURE REQUEST:  Customize Theme

### ISSUE THREAD

**Issue by louishuyng** [dailydotdev/daily#886]
### Concise Description

Daily App that able users to customize the UI

### Description

Like other browsers, when opening the home page, they let us customize the background image or theme. 

As a daily app, we don't have strong customization on UI as much, which may feel a little bit boring while opening this new tab page every time

I know that the content is great, also UI looks great by the way and I really appreciate that. However, as developers, they also want to be different and wanna more customize the tool they are using. Hence, it would be great if we have more options on theming for them

### Solution Proposed

My proposal is that we should have one feature that lets users select the theme they want instead of the default. I have 2 ideas for doing that

## First Approach
- Let the user choose the default theme list like 
  - Gruvbox
  - One dark
  - Solarized
  - etc...
 
- Let the user customize the background color it could be a `tab bar`, `background`, `sidebar` color, etc ...
- Let the user choose the background image they want or have a predefined image there for them to select first

This one is quite simple to implement however it is not scalable as the second approach

## Second Approach
- Create a theme marketplace
- Build a standard library or convention that can let other developers contribute the theme they like

This one is more complex than the first one however it is quite scalable and developers may enjoy working on the theme they want and can share it with the others

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @louishuyng,

Thanks for the awesome suggestion.
We have an existing discussion, let's keep it there.
https://github.com/dailydotdev/daily/discussions/881
