### ISSUE TITLE
🐛 BUG: White screen on newsfeed

### ISSUE THREAD

**Issue by maximusrus** [dailydotdev/daily#887]
### What went wrong? 🤔

Hi!
It was a pleasure to use daily.dev. But two days ago after I saved the page on the home screen it started to show white screen after login or when I press login.
I tried:
- Reboot device
- Clear cache (it helped for one time)
- Use regular website (it stopped working too)
- Delete Home Screen page and use web version

My device:
- iPhone 13 Pro Max
- iOS 16.4.1

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Safari

### Browsers

Safari

### OS

iOS

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by maximusrus** [comment]
I think I’ve found out the reason. I turned off the content & privacy restrictions on the iPhone and it started to work. This topic can be closed though I don’t understand what blocks daily.dev

**Comment by idoshamun** [comment]
Thanks for sharing the root cause. We will try to research this ourselves as well :)
