### ISSUE TITLE
🐛 BUG: Squad member popup doesn't show if redirect backs

### ISSUE THREAD

**Issue by NiazMorshed2007** [dailydotdev/daily#899]
### What went wrong? 🤔

If I click to see the members in a squad, it opens a list of members in a popup.
From there if I click on a member profile and then redirect back to the squad page the popup no longer shows.
It can be a bad ux.

Here is a video to understand more clearly:

https://github.com/dailydotdev/daily/assets/77217706/7bf92cff-eb7e-4463-bd7f-dbe4816eae5e

### Expected Behavior

Expected to be the popup open if redirects back.

### Steps to Reproduce Issue

```bash
1. Click on squad members button on top
2. Now popup shows up, click on a member to view their profile
3. Now redirect back to the squad page
4. ** Notice the popup no longer shows
```

### Browsers

Brave

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @NiazMorshed2007,

Thanks for reporting this.
My best suggestion would be to middle-click on the profile to open it in a new tab and keep the context of the current page.
Would that work for you?

**Comment by NiazMorshed2007** [comment]
@idoshamun That would also work, but seems like it isn't working at the moment.

**Comment by idoshamun** [comment]
@NiazMorshed2007 I just checked and confirmed that it does work. Can you please send a video or explain step by step what you do?

**Comment by rebelchris** [comment]
@NiazMorshed2007 This seems to be working, please do re-open if it happens again or any different issues occur.
