### ISSUE TITLE
🧩 FEATURE REQUEST:  Add border radius to the post highlighting border

### ISSUE THREAD

**Issue by RiteshK-611** [dailydotdev/daily#916]
### Concise Description

Add border radius to the post highlighting border

### Description

Add border radius to the green post/ highlighting border

![image](https://github.com/dailydotdev/daily/assets/61982298/4427e007-586d-4510-ad60-b20835ba16e7)

### Solution Proposed

Border radius of the green highlighting border can be same as that of the post's border radius.

![image](https://github.com/dailydotdev/daily/assets/61982298/0ea01eb3-f083-4611-92a1-d96becd8da12)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment]
@RiteshK-611 nice catch right there! Thank you for reporting the concern. We have now opened it for contributors 🚢

**Comment by RiteshK-611** [comment]
I'll contribute! 🙂

**Comment by sshanzel** [comment]
> I'm contributing! 🙂

Wow! That is interesting! We currently have 3 kinds of cards. The component names are (searchable in the project):
- ArticlePostCard.
- SharePostCard (the sample screenshot you have given).
- WelcomePostCard.

The reason I have listed the items above is, I think the issue could be present in those ones too. So feel free to validate if those items require fixes too. Thank you!

**Comment by RiteshK-611** [comment]
> > I'm contributing! 🙂
> 
> Wow! That is interesting! We currently have 3 kinds of cards. The component names are (searchable in the project):
> 
> * ArticlePostCard.
> * SharePostCard (the sample screenshot you have given).
> * WelcomePostCard.
> 
> The reason I have listed the items above is, I think the issue could be present in those ones too. So feel free to validate if those items require fixes too. Thank you!

Sure!

**Comment by RiteshK-611** [comment]
Closing this issue as we successfully added this feature 🥳 
Thank you!

Thanks @sshanzel & @rebelchris for helping!
