### ISSUE TITLE
🐛 BUG:  Add required alert to the URL field

### ISSUE THREAD

**Issue by RiteshK-611** [dailydotdev/daily#919]
### Concise Description

Add field required alert to the URL field

### Description
When we directly click on "Post" button without filling any field, it does not show any form of alert like this url field is required or please enter url.

<img src="https://github.com/dailydotdev/daily/assets/61982298/aa5653e7-7238-4ef9-982a-49a028dccb89" alt="image" width="500"/>

By the way it does work but when you enter any kind of letter or word and then click "Post" button

<img src="https://github.com/dailydotdev/daily/assets/61982298/3504f837-c615-4890-b79e-44c828a2ba33" alt="image" width="500"/>

### Solution Proposed

URL field must show some kind of alert like "Please enter URL"

### Additional Context

All the screenshots are from ===> Squad > New Post > Share a link

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
@RiteshK-611 thanks for reporting!
We will log it down

**Comment by RiteshK-611** [comment]
Let me know if in any way I can help you guys! 😉

**Comment by Victory-M** [comment]
Hey @idoshamun, I'd like to work on this.

**Comment by idoshamun** [comment]
Let me check if we can have a quick design for it

**Comment by RiteshK-611** [comment]
Sure!

**Comment by RiteshK-611** [comment]
> Let me check if we can have a quick design for it

Sure!

Let me know... I would love to resolve my issue 🙂

**Comment by sshanzel** [comment]
Hi @RiteshK-611. Good to see you again! If you are up for the challenge, feel free to fix the component that needs to have a `required` property so we can leverage the browser's native behavior.

@Victory-M we appreciate the motivation to work on this, though let's see if Ritesh is up for it as he was the first one to ask.

**Comment by RiteshK-611** [comment]
Thanks @sshanzel for the opportunity!
I'm up for this challenge 💪

**Comment by RiteshK-611** [comment]
Hi @sshanzel 

I did raised a PR for this, I some how manage to add the `required` property to the TestField as "Squads" page is not accessible to us through gitpod or in any other way. Let me know if I made any mistake in that.

**Comment by sshanzel** [comment]
Amazing. Thank you for awesome work! I will test it today and get back to you about the result 🚀

**Comment by RiteshK-611** [comment]
Thanks @sshanzel and team for such support and appreciation 🫡

**Comment by RiteshK-611** [comment]
Closing this issue as [PR](https://github.com/dailydotdev/apps/pull/1916) for this got successfully merged 🎉
