### ISSUE TITLE
Add user-defined browser bookmarks in bookmark page

### ISSUE THREAD

**Issue by ZhouJiaZhi** [dailydotdev/daily#92]
just like google chrome 'TOBY'
if 'daily' support this feature ， then  I can remove 'toby'

**Comment by idoshamun** [comment]
Hi @ffbh,
Thanks for reaching out :)
Unfortunately, I am not familiar with TOBY just heard about it a bit.
Could you please elaborate more on the feature you request?

**Comment by ffbh** [comment]
@idoshamun 
I want to add some user-defined bookmarks to the bookmarks page.
1. Bookmark support grouping
2. Bookmarks in each group support display and hide
3. Add all the currently open tabs to a new group with one click.

**Comment by idoshamun** [comment]
Thank you for elaborating but currently we believe adding user-defined bookmarks is not aligned with our product roadmap. Daily is focused on developers content rather than a general purpose environment. Hopefully you understand :)
