### ISSUE TITLE
🧩 FEATURE REQUEST: MacOS App

### ISSUE THREAD

**Issue by akhil-raj-git** [dailydotdev/daily#923]
### Concise Description

Desktop App For daily.dev

### Description

A feature rich MacOS app for daily.dev would be great. This app would include:

- A separate app launcher on Macs
- daily.dev widgets
- Notifications

### Solution Proposed

To reduce effort and code, I would recommend having a Flutter app to distribute across all desktop platforms such as Windows, MacOS, and/or Linux. This would mean one codebase so it would reduce overall effort and improve maintainability.

Why Flutter? Because it is the closest cross-platform language with near native performance.

OS Specific features such as Notifications and Widgets may need to be developed with Swift on MacOS in addition to the standard Flutter app. But this should be more of a minor addition, as opposed to building the entire app in Swift.

### Additional Context

```bash
NA
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @akhil-raj-git,

If you wish to use daily.dev as a standalone mac app you can install our PWA via Safari, and it should install it as a standalone app.
I hope this makes sense.
