### ISSUE TITLE
🐛 BUG:  Replace "reading history" with more space for URL 

### ISSUE THREAD

**Issue by RiteshK-611** [dailydotdev/daily#928]
### Concise Description

Replace "reading history" with more space for URL 

### Description

Here in squads, in the URL section "reading history" is taking up unnecessary space while entering URL

<img src="https://github.com/dailydotdev/daily/assets/61982298/9b0a760a-785f-4948-b7f9-254bb9a2b1c3" alt="img" width="400" />

<img src="https://github.com/dailydotdev/daily/assets/61982298/6a0aeb00-e501-4cd0-8b75-eff364818f48" alt="img" width="400" />

<hr/>

Whereas, in the New Post of squads, in URL section of Share Link "reading history" is not taking unnecessary space while entering URL

<img src="https://github.com/dailydotdev/daily/assets/61982298/6e719426-5220-4c63-8bec-10f83b5f2774" alt="img" width="400" />

<img src="https://github.com/dailydotdev/daily/assets/61982298/420e6cd1-ea66-4476-af25-60cad730babb" alt="img" width="400" />

### Solution Proposed

We can have same code/component for URL section on Squad page as that of used in URL section of Share Link 

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by RiteshK-611** [comment]
Let me know if I can help resolve this issue 🙂

**Comment by sshanzel** [comment]
Wow, you have some sharp eyes! Feel free to raise a PR! 🚀

**Comment by RiteshK-611** [comment]
@sshanzel In Gitpod is there any way to test the code changes made on Squads page? It'll be really helpful.

**Comment by sshanzel** [comment]
Unfortunately, there is none as of the moment as it lacks authentication capability. Though it is in our roadmap to make it work, we haven't touched upon it yet.

**Comment by sshanzel** [comment]
We had a recent fix to this, if the issue still persists. Feel free to re-open the issue.
