### ISSUE TITLE
🐛 BUG: Squad posts keep showing after leaving squad, and won't open

### ISSUE THREAD

**Issue by yahligitzi** [dailydotdev/daily#945]
### What went wrong? 🤔

Occurs on daily.dev chrome extension. Might be a minor bug but thought I should let you know since I appreciate your work a lot.
I've joined a squad trying the new feature, and then left it. It's posts keep showing in my feed, and on opening one of them it loads for 5 seconds and then crush. Check out the screenshots attached.

I've noticed afterwards the post did disappear (not sure what triggered that), but when joining the same squad again (or a different one), its posts don't appear in my feed again - not sure if this one is a bug or just the expected behavior and I should've been patient xd.

### Expected Behavior

When leaving a squad, its posts are expected to be removed from the personal feed at that moment.

### Steps to Reproduce Issue

```bash
1. Join a squad
2. Leave a squad
3. Open a squad's post from your feed
```
### Screenshots

![loading](https://github.com/dailydotdev/daily/assets/111854403/99662584-a21b-4afa-bf7a-f3ca8701b8a4)
![crush](https://github.com/dailydotdev/daily/assets/111854403/c4b40b59-3e46-4861-9a86-dc85fc0986ef)

### Environment

Windows 11, Chrome 114

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

latest

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @yahligitzi,

Thanks for reporting! We'll work on fixing it

**Comment by Utkarshn10** [comment]
Hey @idoshamun can i work on this issue?

**Comment by sshanzel** [comment]
Hi @Utkarshn10, thank you for your interest, unfortunately, this matter is to be handled by the internal team.

We have a few open issues but some are already assigned. We have reached out to those ones and see if the users are still interested, if not, we will free it up and send you the items here. In the meantime, the item below is the only available unassigned one.

https://github.com/dailydotdev/daily/issues/711

**Comment by Utkarshn10** [comment]
No issues. I can work on issue #711
