### ISSUE TITLE
🐛 BUG: List View in "Popular" not shown as expected

### ISSUE THREAD

**Issue by Utkarshn10** [dailydotdev/daily#947]
### What went wrong? 🤔

The list View on Popular section contains missing posts. The posts are loaded after minutes of scrolling through. 

### Expected Behavior

The posts should be shown after they are loaded. 

### Steps to Reproduce Issue

```bash
1. Go to 'Popular section'
2. Scroll down
4. See the error
```

### Screenshots

```
https://user-images.githubusercontent.com/58587256/258313745-c66d942e-ad81-48f0-ac64-94e486a05b4c.png

https://user-images.githubusercontent.com/58587256/258313740-09fd34c7-5a00-4b88-a948-39b192d0a04c.png

https://user-images.githubusercontent.com/58587256/258313732-e4fbda61-8f4f-49ae-8873-93e33035c841.png
```

### Environment

Windows 11

### Browsers

Firefox, Microsoft Edge

### OS

Windows

### Code of Conduct

- [x] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Utkarshn10,

This is our ads that take more time to load recently. It should be ok in a few days.
Thanks for reporting!
