### ISSUE TITLE
Footer Column is not in center 🐛 BUG: 

### ISSUE THREAD

**Issue by avinashji1302** [dailydotdev/daily#950]
### What went wrong? 🤔

Footer's column is not in center , they are alienged more toward left side 

### Expected Behavior

footer's each column should be in center

### Steps to Reproduce Issue

```bash
1. Go to 'https://docs.daily.dev/'
2. Click on '....'
3. Scroll down to 'Footer'
4. See the error
```

## We need to just do

 "footer_link{ 
display:flex ;
text-aliegn-center
}"

## Screenshot

![final](https://github.com/dailydotdev/daily/assets/91355822/f27d386a-c850-48dc-a161-4cc2e2e0ebba)

### Screenshots

```bash
![final](https://github.com/dailydotdev/daily/assets/91355822/f27d386a-c850-48dc-a161-4cc2e2e0ebba)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by avinashji1302** [comment]
Please assign me this  , I want to work on it

**Comment by idoshamun** [comment]
Hi @avinashji1302,

This website is built on Webflow, so unfortunately, only our design team can access it.
Thanks a lot for reporting and being willing to contribute.

**Comment by avinashji1302** [comment]
> Hi @avinashji1302,
> 
> This website is built on Webflow, so unfortunately, only our design team can access it. Thanks a lot for reporting and being willing to contribute.

No problem

I  inspect the web site
And tried this 

 "footer_link{ 
display:flex ;
text-aliegn-center
}"

And it worked....

Hope this is find helpful..

And yes if there is any work for me on open source please let me know

**Comment by idoshamun** [comment]
Will do!

**Comment by rebelchris** [comment]
@avinashji1302 this is fixed with our recent release.
Thanks for logging it
