### ISSUE TITLE
🐛 BUG: Notifications remain on a deleted squad's article

### ISSUE THREAD

**Issue by RibJulien** [dailydotdev/daily#952]
### What went wrong? 🤔

I recently joined a squad, and I noticed that if an article was deleted, the notification for that article didn't disappear.

### Expected Behavior

I think it would be good if, when an article is deleted, the notification counter is recalculated and the article is no longer displayed in the notifications category.

### Steps to Reproduce Issue

```bash
1. Join a squad
2. A member of your squad, post an article, and delete it
3. Your notification counter stay at '1' and the article is visible in notifactions category (you'll get an error if you try to access the article)
```

### Solution Proposed

Recalculate the notification counter and not display an article that has been deleted

### Screenshots

![example, probably with a typing error by Ido Samun](https://github.com/dailydotdev/daily/assets/55736383/401b1295-38d8-4384-a4b8-59dd2b87df31)

### Environment

Chromium : Version 115.0.5790.110 (official build) snap (64 bits)

### Browsers

Chrome

### OS

Linux

### Version of daily.dev

3.26.1

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by YashRajSingh-4799** [comment]
Hey, @RibJulien 
Can u please assign me this issue??

**Comment by sshanzel** [comment]
> Hey, @RibJulien
> Can u please assign me this issue??

As much as we would want this to be opened for the OSS community, the issue has caught many people's attention so we have decided to work on this within the team.

With that, feel free to check our issues tab to see items with `help-wanted` label. One of the available ones is this issue https://github.com/dailydotdev/daily/issues/876

**Comment by YashRajSingh-4799** [comment]
Okay no problem 
And How can I join the internal team or community???

**Comment by sshanzel** [comment]
> Okay no problem
> And How can I join the internal team or community???

Being active in these tabs of GitHub makes you already part of the community! 🚢 

With regard to being part of the internal team, you will have to go through our recruitment process. Feel free to check our careers page for open positions 🚀 

https://daily.dev/careers

**Comment by rebelchris** [comment]
This recently got added
