### ISSUE TITLE
🐛 BUG: The Post button is not fully visible in Squad section

### ISSUE THREAD

**Issue by hankadev** [dailydotdev/daily#956]
### What went wrong? 🤔

When navigating to my squad page the `Post` button is not visible.

![image](https://github.com/dailydotdev/daily/assets/31318129/8a7de265-7cf8-48af-bae6-0593604dce44)

### Expected Behavior

The button is even fully visible or it is hidden and shows after I start writing in the field.
If you tell me what the right behavior is, I would love to try to contribute and fix this :crossed_fingers: 

### Steps to Reproduce Issue

```bash
1. Go to Squad page
3. Look at the input for entering the URL
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Ubuntu 22, Chrome 115.0.5790.110

### Browsers

Chrome

### OS

Linux

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @hankadev,

Thanks for reporting, we will look into it!

**Comment by sshanzel** [comment]
I can't exactly reproduce the issue. Can you provide more info? Like if it is persistent even after a refresh, the resolution of the window, etc.

![Screenshot 2023-08-17 at 7 06 04 PM](https://github.com/dailydotdev/daily/assets/13744167/80596b77-97b3-4bc4-8ec3-d128c5b02dad)

**Comment by hankadev** [comment]
@sshanzel yes, for me it is persistent issue - on laptop and also on desktop. For screens cca 1900px and smaller.

**Comment by sshanzel** [comment]
Do you have anything unique with your setup? Feel free to spin up a PR so we can check whether the fix would still be compatible with those who have it working normally. That way, we can fix cases similar to the issue you encountered.

There should be a `SharePostBar` file that renders this. The expected behavior should be what I shared in the screenshot above. Let me know if you are up for the challenge! 🚀

**Comment by hankadev** [comment]
@sshanzel I will try to run it locally and create a PR. :ok_hand: I will also look in the office if my colleagues are having same issue or not, because I am not aware of any unusual setup - just Ubuntu with latest Chrome.

**Comment by sshanzel** [comment]
We have recently pushed some fixes to this issue. Feel free to re-open if it still persists.
