### ISSUE TITLE
Issue in setting up the local environment for contribution

### ISSUE THREAD

**Issue by kavinkuma6** [dailydotdev/daily#957]
Hi there,

I thought of contributing to the project. But I am facing issue when setting up the local environment.

I need to do login for testing a feature. But I am not sure what to provide for the auth URL in the env variable [here](https://github.com/dailydotdev/apps/blob/main/packages/webapp/.env#L7-L8). Even in gitpod, it is simply localhost [here](https://github.com/dailydotdev/apps/blob/main/.gitpod.yml#L35-L36). 

Can you guys throw some light on how to enable auth in local env?

(Raising an issue here, as I dont see any other better ways to contact for this problem)

**Comment by sshanzel** [comment]
Hello @kavinkuma6, thank you for raising an issue. Unfortunately, we are yet unable to spool up the perfect local environment for people to make contributions that involve authentication or logging in with accounts.

On that note, it is in our roadmap to provide a better experience with setting up the local environment for potential contributors.

**Comment by xnivaxhzne** [comment]
Sure @sshanzel, thanks for responding back. 

Let me try mocking the auth part.

**Comment by kavinkuma6** [comment]
Sure @sshanzel, thanks for the confirmation.

Let me mock the auth part till then.

**Comment by sshanzel** [comment]
This is now fixed with the recent changes of our GitPod setup 🥳
