### ISSUE TITLE
🐛 BUG: Context menu should be hidden on scroll in squad members modal

### ISSUE THREAD

**Issue by kavinkuma6** [dailydotdev/daily#958]
### What went wrong? 🤔

The context menu with option `Report member` opened by clicking three dots in the squad members modal is not getting hidden on scroll. It stays in the screen unless I click somewhere.

But the context menu in other places like the one rendered by clicking three dots in popular posts page is getting hidden on scroll.

### Expected Behavior

For better UX and consistency of a functionality across the app, the context menu should be hidden on scroll in the `Squad members` modal.

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/squads/dailydevworld' or any other squad page.
2. Click on 'members list' in the top right corner
3. It will open up the `Squad members` modal.
4. Click the three dots(more option) icon of any of the users.
3. A context menu with `Report User` option would be visible.
4. Try to scroll in the list.

You can observe that the context menu stays in place, where it is expected to be hidden.
```

### Solution Proposed

After checking [this](https://github.com/fkhadra/react-contexify/issues/161) github issue, I found that its open item from `react-contexify`. So as suggested [here](https://github.com/fkhadra/react-contexify/issues/161#issuecomment-1304643573) we can add the workaround.

### Screenshots

```bash
https://github.com/dailydotdev/daily/assets/24503078/b7b751bd-f4d4-4c0c-9597-118474b21e6b
```

### Environment

Google Chrome: Version 115.0.5790.170 (Official Build) (x86_64)

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @kavinkuma6,

Thanks for reporting! We will look into it and review the PR
