### ISSUE TITLE
🧩 FEATURE REQUEST:  Show more metadata in listview item

### ISSUE THREAD

**Issue by huantt** [dailydotdev/daily#959]
### Concise Description

Show more metadata in listview item

### Description

I would like to request that you display more metadata in the listview item for each article. Currently, the only metadata that is displayed is the title, author, and publication date. I would like to see the following additional metadata displayed:

- Summary
- Thumbnail

I believe that displaying this additional metadata would make it easier for users to find articles that are relevant to their interests and that would also help to improve the discoverability of articles on the platform.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by huantt** [comment]
I have built a custom version locally, this is what I want to show in listview:
![image](https://github.com/dailydotdev/daily/assets/19801770/45f0659e-2c61-412c-a278-600522fa4e63)

**Comment by idoshamun** [comment]
Hi @huantt,

That's one of the most impressive feature requests we received. You went all the way and built it even, marvelous!
We're considering a new feed layout that resembles the one you show here. May take us a while, but we'll get there.

**Comment by huantt** [comment]
> Hi @huantt,
> 
> That's one of the most impressive feature requests we received. You went all the way and built it even, marvelous! We're considering a new feed layout that resembles the one you show here. May take us a while, but we'll get there.

I created a PR here: [[link to PR](https://github.com/dailydotdev/apps/pull/2060)]. Please review and let me know if you have any feedback. I'm happy to make any changes as needed.

**Comment by rebelchris** [comment]
Hi @huantt,

We are currently re-working our feed layout and that change should pretty much address this issue.
We'll let you know once it's ready.

**Comment by huantt** [comment]
> Hi @huantt,
> 
> We are currently re-working our feed layout and that change should pretty much address this issue. We'll let you know once it's ready.

Thanks for the update. I'm pleased to hear that it's still in progress.

**Comment by rebelchris** [comment]
Hi @huantt It's been a while, but we actually introduced a fully rebuild list mode now.
Closing this ticket in favor of that.
