### ISSUE TITLE
🐛 BUG: Unable to replace a Squad's profile picture.

### ISSUE THREAD

**Issue by rvrlx** [dailydotdev/daily#962]
### What went wrong? 🤔

Problem: I am unable to replace and existing squad profile picture.

I uploaded a profile picture for a squad which I created. This initial picture upload was successful, and the picture was set.

I then tried to replace the profile picture with a new picture. But this process did not succeed. The new picture upload completes, I then hit Save in order to save the changes. This Save process then also completes. However, the old picture is still reflected in the side bar afterwards.

### Expected Behavior

I expected the relevant squad's profile image to change. I.e. replaced with the newly uploaded image.

### Steps to Reproduce Issue

```bash
1. Select the relevant Squad from the list of available squads in the side bar (on the left of screen)
2. Click on 'Squad Options'
3. Select 'Squad Settings' in the menu
3. Click on the 'Camera icon' to upload a new image
4. Image upload completes
5. Old image is replaced (displayed on the screen, where the camera icon was)
6. Click on 'Save'
7. A progress bar is displayed, showing the progress
8. A message is displayed 'The Squad has been updated'
9. Leave the current page, by clicking on any other squad or feed in the side bar
10. Select the previously updated squad in the side bar
11. Notice that the old image is still in place
```

### Solution Proposed

NA

### Screenshots

```bash
NA
```

### Environment

Ubuntu Linux 22.04.3 LTS; Brave 1.56.14

### Browsers

Brave

### OS

Linux

### Version of daily.dev

3.26.2

### Additional Context

```bash
NA
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @rvrlx,

We're aware of the problem, thanks for reporting. We'll fix it

**Comment by rebelchris** [comment]
We addressed this recently and fixed this.
@rvrlx thanks for logging, if you see any other issues don't hesitate to let us know.

**Comment by rvrlx** [comment]
Noted. Thanks for the update.
