### ISSUE TITLE
🐛 BUG: Post Comment is not cleared after submit  

### ISSUE THREAD

**Issue by luisfilipegoncalves** [dailydotdev/daily#965]
### What went wrong? 🤔

Tried to place a comment on a post but UX is misleading about the message being saved. 

### Expected Behavior

The comment input is cleared after success submission and there is a visual confirmation about it ( toast message maybe ? )

Related to https://github.com/dailydotdev/apps/issues/2099 

https://github.com/dailydotdev/daily/assets/2605696/d57b8dd0-caed-4b56-91bd-906856207a28

post: https://app.daily.dev/posts/Zad24k11O

### Steps to Reproduce Issue

```bash
1. Open a post
2. Click on "Share your thoughts" input 
3. Type anything for the comment
4. Click "Comment" button
5. Comment is successfully created but there is not visual feedback about that and also the comment text is not cleared. This might make the user create multiple comments with the same text.
```

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Issue has been resolved in latest release 🙏
Thanks for reporting
