### ISSUE TITLE
While commenting, deleting comments, and bookmarking are not updating in the post-modal [extension], and only bookmarking is not updating in the web version.

### ISSUE THREAD

**Issue by anirbanpaulcom** [dailydotdev/daily#972]
In the web version, when clicking on 'Bookmark,' it does not show whether it has been bookmarked or not. 

https://github.com/dailydotdev/apps/assets/130109852/74b494a1-d0ae-4d1a-95b0-7a1fd6a4b55a

In the extension, the comment box doesn't empty after commenting, and even after deleting a comment, it still remains visible. The same issue applies to bookmarks.If I refresh the page ,I can see the updates.

https://github.com/dailydotdev/apps/assets/130109852/0bd8aaac-afcc-4524-927d-0bc42a06f3e1

P.S.: The issue occurs within the modal, if I directly access the post, everything functions properly.

**Comment by idoshamun** [comment]
Hi @anirbanpaulin,

Thanks for reporting. We're aware of this problem and we'll fix it :)

**Comment by Powell-v2** [comment]
Hi @idoshamun, I'd like to take a stab at this one. Should I dive right in or wait for your design team to have a look first?

**Comment by rebelchris** [comment]
This issue has been resolved and will be closed.

@Powell-v2 thanks for the interest, my colleague @sshanzel will be in touch if you are keen to work on something he can help you.

**Comment by sshanzel** [comment]
Hi @Powell-v2, we are glad to hear your enthusiasm in contributing to dailydev! 🥳 

We have a few open issues which you can find through [this link](https://github.com/dailydotdev/daily/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22). Those are the issues with `Status: Accepted` label.

However, most of the items are already assigned to somebody, but today is your lucky day! 😂 

We just recently opened an issue for OSS contribution. More details in [this issue](https://github.com/dailydotdev/daily/issues/1000) 🐛 

Let me know if you would like me to assign the issue above to you.
