### ISSUE TITLE
Require more metadata in listview item

### ISSUE THREAD

**Issue by huantt** [dailydotdev/daily#973]
I would like to request that you display more metadata in the listview item for each article. Currently, the only metadata that is displayed is the title, author, and publication date. I would like to see the following additional metadata displayed:
- Summary
- Thumbnail

I believe that displaying this additional metadata would make it easier for users to find articles that are relevant to their interests and that would also help to improve the discoverability of articles on the platform.

**Comment by rebelchris** [comment]
Closing as duplicate
