### ISSUE TITLE
🐛 BUG:  Remove button navigation

### ISSUE THREAD

**Issue by Noothan-am** [dailydotdev/daily#975]
### What went wrong? 🤔

After I press the remove button on any of the articles in the history page, it opens the page and then removes it from the history

### Expected Behavior

it should just remove the article from history and should not navigate to that page

### Steps to Reproduce Issue

```bash
1. Go to 'Reading History Tab'
2. Click on 'cross button on any article'
3. See the error
```

### Environment

windows 10

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by Noothan-am** [comment]
hey @idoshamun, is this a feature or bug?

**Comment by sarojregmi200** [comment]
Hey, their maintainers.
I have found the problem and am setting up the environment to test the solution out, I tried setting up with gitpod but due to some reason the auth is not working there, Probably some miss configuration. Anyways I am setting up the project locally. Can I work on this issue?

**Comment by idoshamun** [comment]
Hi @Noothan-am,

Definitely a bug, thanks for reporting!

@sarojregmi200, we'll check your contribution. Thanks!

**Comment by sarojregmi200** [comment]
@idoshamun the problem has been solved and this issue can be closed now.
