### ISSUE TITLE
🐛 BUG: Application error: a client-side exception has occurred 

### ISSUE THREAD

**Issue by pholuutomosia** [dailydotdev/daily#977]
### What went wrong? 🤔

When i restart my device and have error
![Screen Shot 2023-09-13 at 14 53 36](https://github.com/dailydotdev/daily/assets/111719622/0c3bc2e3-75fb-4284-8414-0e50d197234a)

### Expected Behavior

Please explain, and find a solution for me

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @pholuutomosia thanks for logging this issue.
On which page does this happen for you?

We are looking into it, and will let you know as soon as we find something.

**Comment by rebelchris** [comment]
@pholuutomosia We solved the issue, thanks so much for logging it 🙇

**Comment by pholuutomosia** [comment]
@rebelchris Thanks a lot 👍 🙏. I appreciate your support
