### ISSUE TITLE
🧩 FEATURE REQUEST:  Add new layout to Squads

### ISSUE THREAD

**Issue by RiteshK-611** [dailydotdev/daily#979]
### Concise Description

Add new layout to squads

## Layout 1
![image](https://github.com/dailydotdev/daily/assets/61982298/ef6373cd-689e-4368-8f5b-5fbd1386ed7a)

## Layout 2
![image](https://github.com/dailydotdev/daily/assets/61982298/edc7310d-adf9-4557-beeb-82e86db1e5a7)

We have 2 different layouts for squads. Layout 1 is the new one and Layout 2 is the old.

### Solution Proposed

Implement the new layout (Layout 1) to all squads

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @RiteshK-611,

Thanks for the suggestion but this is currently out of scope for us.
