### ISSUE TITLE
🧩 FEATURE REQUEST:  Card layout changes

### ISSUE THREAD

**Issue by Crushoverride007** [dailydotdev/daily#986]
### Description

Hello guys, i've been a daily user of this wonderful webapp, i just wanted to put a quick feature request for the people behind, 
![CleanShot 2023-10-05 at 11 36 08@2x](https://github.com/dailydotdev/daily/assets/45631812/b6e514ed-02fd-419b-8f4e-4064e4d51b32)
Here In the card you can see there is only 3 buttons (Upvote, comment or downvote), can we please add the possibility of the bookmark button making it 4 buttons, without clicking through the card. One click better than 3.

Keep up 👍🏻

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Crushoverride007,

Thanks a lot for the suggestion.
We're indeed considering new feed layout to support more actions

**Comment by Vaibhav91one** [comment]
Is this issue open?

**Comment by Crushoverride007** [comment]
@Vaibhav91one i think so, not so sure tho

**Comment by Vaibhav91one** [comment]
hmm..np @Crushoverride007 have some layouts in mind.

**Comment by idoshamun** [comment]
Hi @Crushoverride007,

You should see the bookmarks button now on your cards :)

@Vaibhav91one feel free to open a new discussion
