### ISSUE TITLE
Header hide on scroll on mobiles/tablets.

### ISSUE THREAD

**Issue by amitabh-sahu** [dailydotdev/daily#998]
Currently, the header is only sticky on laptops and not on mobiles/tablets.
It will be nice to also have the header sticky on mobiles/tablets.

If this is intentional then close this issue.
I'm also willing to make changes and create PR if agree.

**Comment by idoshamun** [comment]
Hi @amitabh-sahu,

Thanks for reporting this issue. Let me check with our design team and come back to you.

**Comment by KKaged** [comment]
If this issue is up for grabs, I'd like to take it on.

**Comment by idoshamun** [comment]
We're revamping the mobile experience. So let me check if this still holds

**Comment by idoshamun** [comment]
I checked with the team and this will soon be deprecated. So I'll go ahead and close the ticket
